### ISSUE TITLE
Keystone Crash in Admin UI -> + New Model in Edit View (Heroku)

### ISSUE THREAD

**Issue by diablo2man** [keystonejs/keystone#1133]
My keystone app on Heroku crash after I click "+ New User" in the User view. This only happens in view/edit existing user view (+ New User is right top corner). If I add user in user list view (Create User), it is ok. Other models have same problems.

The weird thing is that I didn't have this problem when run locally. It only causes heroku crash.

This is the link that would crash app

```
keystone/users?new&_csrf=dtMTg2UhR4emLNNeLB/H5OzWGE/Rg+pI9ytmw=
```

This is the log

```
2015-03-02T03:51:36.053396+00:00 app[web.1]: TypeError: /app/node_modules/keystone/lib/core/../../templates/views/list.jade:24
2015-03-02T03:51:36.053402+00:00 app[web.1]:     22| 	script(src='/keystone/js/lib/browserified/querystring.js')
2015-03-02T03:51:36.053404+00:00 app[web.1]:     23| 	script(src='/keystone/js/lib/browserified/queryfilter.js')
2015-03-02T03:51:36.053406+00:00 app[web.1]:   > 24| 	script.
2015-03-02T03:51:36.053408+00:00 app[web.1]:     25| 		Keystone.list = { path: "#{list.path}", label: "#{list.label}", singular: "#{list.singular}", plural: "#{list.plural}", cols: !{JSON.stringify(colPaths)}, perPage: !{ Number(list.perPage) || 50 } };
2015-03-02T03:51:36.053410+00:00 app[web.1]:     26| 		Keystone.wysiwyg = { options: !{JSON.stringify(wysiwygOptions)} };
2015-03-02T03:51:36.053412+00:00 app[web.1]:     27| 		Keystone.items = !{ JSON.stringify(items) };
2015-03-02T03:51:36.053413+00:00 app[web.1]: 
2015-03-02T03:51:36.053415+00:00 app[web.1]: Cannot convert object to primitive value
2015-03-02T03:51:36.053417+00:00 app[web.1]:   at String (native)
2015-03-02T03:51:36.053418+00:00 app[web.1]:   at Object.escape (/app/node_modules/keystone/node_modules/jade/lib/runtime.js:183:16)
2015-03-02T03:51:36.053420+00:00 app[web.1]:   at eval (<anonymous>:5140:40)
2015-03-02T03:51:36.053421+00:00 app[web.1]:   at eval (<anonymous>:5199:22)
2015-03-02T03:51:36.053422+00:00 app[web.1]:   at res (/app/node_modules/keystone/node_modules/jade/lib/index.js:191:38)
2015-03-02T03:51:36.053424+00:00 app[web.1]:   at [object Object].render (/app/node_modules/keystone/lib/core/render.js:118:13)
2015-03-02T03:51:36.053425+00:00 app[web.1]:   at /app/node_modules/keystone/routes/views/list.js:117:14
2015-03-02T03:51:36.053427+00:00 app[web.1]:   at /app/node_modules/async/lib/async.js:157:25
2015-03-02T03:51:36.053428+00:00 app[web.1]:   at relationship.Field.compile (/app/node_modules/keystone/lib/field.js:298:10)
2015-03-02T03:51:36.053430+00:00 app[web.1]:   at compileFields (/app/node_modules/keystone/routes/views/list.js:113:56)
2015-03-02T03:51:36.053431+00:00 app[web.1]:   at iterate (/app/node_modules/async/lib/async.js:149:13)
2015-03-02T03:51:36.053434+00:00 app[web.1]:   at /app/node_modules/async/lib/async.js:160:25
2015-03-02T03:51:36.053435+00:00 app[web.1]:   at password.Field.compile (/app/node_modules/keystone/lib/field.js:298:10)
2015-03-02T03:51:36.053436+00:00 app[web.1]:   at compileFields (/app/node_modules/keystone/routes/views/list.js:113:56)
2015-03-02T03:51:36.053438+00:00 app[web.1]:   at iterate (/app/node_modules/async/lib/async.js:149:13)
2015-03-02T03:51:36.053439+00:00 app[web.1]:   at /app/node_modules/async/lib/async.js:160:25
2015-03-02T03:51:36.053441+00:00 app[web.1]:   at email.Field.compile (/app/node_modules/keystone/lib/field.js:298:10)
2015-03-02T03:51:36.053442+00:00 app[web.1]:   at compileFields (/app/node_modules/keystone/routes/views/list.js:113:56)
2015-03-02T03:51:36.053443+00:00 app[web.1]:   at iterate (/app/node_modules/async/lib/async.js:149:13)
2015-03-02T03:51:36.053445+00:00 app[web.1]:   at Object.async.eachSeries (/app/node_modules/async/lib/async.js:165:9)
2015-03-02T03:51:36.053446+00:00 app[web.1]:   at /app/node_modules/keystone/routes/views/list.js:115:10
2015-03-02T03:51:36.053447+00:00 app[web.1]:   at Promise.<anonymous> (/app/node_modules/keystone/lib/list.js:1187:5)
2015-03-02T03:51:36.053449+00:00 app[web.1]:   at Promise.<anonymous> (/app/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
2015-03-02T03:51:36.053451+00:00 app[web.1]:   at Promise.emit (events.js:107:17)
2015-03-02T03:51:36.053457+00:00 app[web.1]:   at Promise.<anonymous> (/app/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
2015-03-02T03:51:36.053452+00:00 app[web.1]:   at Promise.emit (/app/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
2015-03-02T03:51:36.053458+00:00 app[web.1]:   at Promise.emit (events.js:107:17)
2015-03-02T03:51:36.053455+00:00 app[web.1]:   at Promise.resolve (/app/node_modules/keystone/node_modules/mongoose/lib/promise.js:114:23)
2015-03-02T03:51:36.053454+00:00 app[web.1]:   at Promise.fulfill (/app/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
2015-03-02T03:51:36.053464+00:00 app[web.1]:   at model.Document.init (/app/node_modules/keystone/node_modules/mongoose/lib/document.js:254:11)
2015-03-02T03:51:36.053466+00:00 app[web.1]:   at completeMany (/app/node_modules/keystone/node_modules/mongoose/lib/query.js:1054:12)
2015-03-02T03:51:36.053460+00:00 app[web.1]:   at Promise.emit (/app/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
2015-03-02T03:51:36.053467+00:00 app[web.1]:   at Promise.<anonymous> (/app/node_modules/key
stone/node_modules/mongoose/lib/query.js:1029:11)
2015-03-02T03:51:36.053461+00:00 app[web.1]:   at Promise.fulfill (/app/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
2015-03-02T03:51:36.053463+00:00 app[web.1]:   at /app/node_modules/keystone/node_modules/mongoose/lib/query.js:1056:26
2015-03-02T03:51:36.053469+00:00 app[web.1]:   at Promise.<anonymous> (/app/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
2015-03-02T03:51:36.053473+00:00 app[web.1]:   at Promise.fulfill (/app/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
2015-03-02T03:51:36.053472+00:00 app[web.1]:   at Promise.emit (/app/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
2015-03-02T03:51:36.053475+00:00 app[web.1]:   at Promise.resolve (/app/node_modules/keystone/node_modules/mongoose/lib/promise.js:114:23)
2015-03-02T03:51:36.053471+00:00 app[web.1]:   at Promise.emit (events.js:107:17)
2015-03-02T03:51:36.053476+00:00 app[web.1]:   at /app/node_modules/keystone/node_modules/mongoose/lib/model.js:2051:23
2015-03-02T03:51:36.053479+00:00 app[web.1]: 
2015-03-02T03:51:36.053478+00:00 app[web.1]:   at process._tickCallback (node.js:355:11)
```

**Comment by morenoh149** [comment]
are you sure jade supports jade keywords inside the script tag? http://jade-lang.com/reference/plain-text/

**Comment by diablo2man** [comment]
@morenoh149 thanks for reply. I'm sure if I understand what you are saying. This problem happens in admin UI page so I didn't modify/write any of its jade code

**Comment by morenoh149** [comment]
I'm just reading the error
```
TypeError: /app/node_modules/keystone/lib/core/../../templates/views/list.jade:24
    22|    script(src='/keystone/js/lib/browserified/querystring.js')
    23|    script(src='/keystone/js/lib/browserified/queryfilter.js')
  > 24|    script.
    25|        Keystone.list = { path: "#{list.path}", label: "#{list.label}", singular: "#{list.singular}", plural: "#{list.plural}", cols: !{JSON.stringify(colPaths)}, perPage: !{ Number(list.perPage) || 50 } };
    26|        Keystone.wysiwyg = { options: !{JSON.stringify(wysiwygOptions)} };
    27|        Keystone.items = !{ JSON.stringify(items) };

Cannot convert object to primitive value
```
That's some jade code. Sounds like you didn't write it and it's keystone's jade code.

**Comment by diablo2man** [comment]
@morenoh149 also the problem only occurs on heroku deployment. When I run it locally, it doesn't give this error.

**Comment by dijs** [comment]
I can reproduce this EXACT error when trying to sort a list of items in the Admin UI

**Comment by dijs** [comment]
Update on this: I was able to get around this error by using node v0.10.36 and not v0.12.0 as I was before.

Hopefully that sheds some light on the issue.

**Comment by wangpingsx** [comment]
I got the same issue no heroku now, I haven't fixed it yet.

I think that is caused by heroku updating.

**Comment by wangpingsx** [comment]
Hi, 
I have solved it and I have posted it here:

http://baiduhix.blogspot.co.uk/2015/03/keystone-crash-in-admin-ui-new-model-in.html

Thanks,
Peter

**Comment by diablo2man** [comment]
Thanks @wangpingsx and @dijs 

I will apply same fix temporarily but I think it is still a keystone issue (some codes don't support new version of NodeJS)

**Comment by dijs** [comment]
Agreed. I would rather keystone be able to use current node...

**Comment by morenoh149** [comment]
@diablo2man could you share what sections of keystone's code don't work under which node versions? thanks

**Comment by diablo2man** [comment]
@morenoh149 

My post has error code and @dijs pointed out heroku is now using Node v 0.12.0

Thanks,

**Comment by morenoh149** [comment]
these are useful to narrow down the infringing code ![screen1](http://4.bp.blogspot.com/-efDbIjYsfxQ/VQL44OICHTI/AAAAAAAAVew/87mxeERdwQY/s1600/Snip20150313_2.png)
```bash

     TypeError: /app/node_modules/keystone/lib/core/../../templates/views/list.jade:24 
     22|  script(src='/keystone/js/lib/browserified/querystring.js') 
    23|  script(src='/keystone/js/lib/browserified/queryfilter.js') 
    24|  script. 
    25|   Keystone.list = { path: "#{list.path}", label: "#{list.label}", singular: "#{list.singular}", plural: "#{list.plural}", cols: !{JSON.stringify(colPaths)}, perPage: !{ Number(list.perPage) || 50 } }; 
    26|   Keystone.wysiwyg = { options: !{JSON.stringify(wysiwygOptions)} }; 
    27|   Keystone.items = !{ JSON.stringify(items) }; 
    Cannot convert object to primitive value 
    at String (native) 
    at Object.escape (/app/node_modules/keystone/node_modules/jade/lib/runtime.js:183:16) 
    at eval (<anonymous>:5140:40) 
    at eval (<anonymous>:5199:22) 
    at res (/app/node_modules/keystone/node_modules/jade/lib/index.js:191:38) 
    at [object Object].render (/app/node_modules/keystone/lib/core/render.js:118:13) 
    at /app/node_modules/keystone/routes/views/list.js:117:14 
    at /app/node_modules/async/lib/async.js:157:25 
    at password.Field.compile (/app/node_modules/keystone/lib/field.js:298:10) 
    at compileFields (/app/node_modules/keystone/routes/views/list.js:113:56) 
    at=error code=H13 desc="Connection closed without response" method=GET path="/keystone/users?new&_csrf=Tu3ZatO8QK1L5hdQ0mjWdm8/nI4ipCiIX5JHE=" connect=1ms service=1266ms status=503 bytes=0 
    at iterate (/app/node_modules/async/lib/async.js:149:13) 
    at /app/node_modules/async/lib/async.js:160:25 
    at email.Field.compile (/app/node_modules/keystone/lib/field.js:298:10) 
    at compileFields (/app/node_modules/keystone/routes/views/list.js:113:56) 
    at iterate (/app/node_modules/async/lib/async.js:149:13) 
    at Object.async.eachSeries (/app/node_modules/async/lib/async.js:165:9) 
    at /app/node_modules/keystone/routes/views/list.js:115:10 
    at Promise.<anonymous> (/app/node_modules/keystone/lib/list.js:1187:5) 
    at Promise.<anonymous> (/app/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8) 
    at Promise.emit (events.js:107:17) 
    at Promise.emit (/app/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38) 
    at Promise.fulfill (/app/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20) 
    at Promise.resolve (/app/node_modules/keystone/node_modules/mongoose/lib/promise.js:114:23) 
    at Promise.<anonymous> (/app/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8) 
    at Promise.emit (events.js:107:17) 
```

**Comment by morenoh149** [comment]
perhaps the react stuff isn't liking the inline script? https://github.com/keystonejs/keystone/blob/master/templates/views/list.jade#L10 could you try factoring it out into a separate file and seeing if it runs under the latest node?

**Comment by wangpingsx** [comment]
Hi Guys 0.12.0 should work.
please make sure you have deleted node_models folder.

Thanks,
peter

**Comment by lntutor** [comment]
thanks @dijs , using node v0.10.36 works with me too. Strange bug.
