### ISSUE TITLE
Cannot call apiResponse or initAPI in my routes after updated my keystone 

### ISSUE THREAD

**Issue by arthurtalkgoal** [keystonejs/keystone#1135]
I updated my keystone from ```0.2.40``` to ```0.3.2```

Then I got errors from my routes from ```keystone.initAPI``` or ```apiResponse```
```
app.get('/api/verify_token/:access_token/:id', keystone.initAPI, app.oauth.authorise(),  routes.api.verify_token);

```

got the errors:
```
[railsu@localhost catchtop]$ node keystone.js

/mynode/node_modules/keystone/node_modules/express/lib/router/route.js:170
        throw new Error(msg);
              ^
Error: Route.get() requires callback functions but got a [object Undefined]
    at Route.<anonymous> (/mynode/node_modules/keystone/node_modules/express/lib/router/route.js:170:15)
    at Array.forEach (native)
    at Route.(anonymous function) [as get] (/mynode/node_modules/keystone/node_modules/express/lib/router/route.js:166:15)
    at EventEmitter.app.(anonymous function) [as get] (/mynode/node_modules/keystone/node_modules/express/lib/application.js:465:19)
    at module.exports (/mynode/routes/index.js:90:7)
    at mount (/mynode/node_modules/keystone/lib/core/mount.js:443:21)
    at start (/mynode/node_modules/keystone/lib/core/start.js:232:7)
    at Object.<anonymous> (/mynode/keystone.js:111:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

```

If I ***removed the keystone.initAPI in the routes, the keystone can be run***
But I found the ```apiResponse``` undefined errors when the codes are triggered

```
exports = module.exports = function(req, res) {

	var id = getObjectId(req);
  User.model.findOne({ _id: id }, function(err, user) {
    
      if(err) return res.apiError('database error', err);
      if (user) {
        return res.apiResponse({
          user: {email: user.email, name: {
            "last": user.name.last,
            "first": user.name.first
          }}
        });
      } 
      
  });  

}
```

will trigger the error:

```
TypeError: Object #<ServerResponse> has no method 'apiResponse'
    at Promise.<anonymous> (/mynode/routes/api/me.js:23:20)
    at Promise.<anonymous> (/mynode/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.emit (events.js:95:17)
    at Promise.emit (/mynode/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/mynode/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at /mynode/node_modules/keystone/node_modules/mongoose/lib/query.js:1400:13
    at model.Document.init (/mynode/node_modules/keystone/node_modules/mongoose/lib/document.js:254:11)
    at completeOne (/mynode/node_modules/keystone/node_modules/mongoose/lib/query.js:1398:10)
    at Object.cb (/mynode/node_modules/keystone/node_modules/mongoose/lib/query.js:1155:11)
    at Object._onImmediate (/mynode/node_modules/keystone/node_modules/mongoose/node_modules/mquery/lib/utils.js:137:16)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by arthurtalkgoal** [comment]
Oh, I solved it. 

The new way to access api is:
```
// in routes 
keystone.middleware.api

```

The old way to define api was:

```
keystone.initAPI
```

**Comment by iamjohnlong** [comment]
Wow I just spent an hour debugging this. Is this in the docs anywhere?

**Comment by morenoh149** [comment]
@iamjohnlong add it

**Comment by jjhesk** [comment]
doesnt work.. 

```

var res_success = function (data) {
    return ks.middleware.api.apiResponse(responseData(data));
}
var res_error = function (error_message) {
    return ks.middleware.api.apiResponse(errorEmit(error_message));
}
exports.resError = res_error;
exports.resDataSuccess = res_success;

```

I try to make a wrapper for output json..

**Comment by arthurtalkgoal** [comment]
@jjhesk , in the routes codes, there is no changes::
```
    if (err) {
      return res.apiError('error.track', err);
    } else {
    
      return res.apiResponse({message: "Ok"});
    }
```

The changes only applicable to index.js:
e.g. 
```
app.post('/track/', keystone.middleware.api, routes.api.track);
```

**Comment by MykhailoDzedzei** [comment]
Hi, all!  I make changes but second "controller" still doesn't work...

var routes = {
	views: importRoutes('./views'),
	api: importRoutes('./api')
};
exports = module.exports = function (app) {
	// Views

    app.get('/api/mates/:id', keystone.middleware.api, routes.api.mates);
}
