### ISSUE TITLE
init API on index.js

### ISSUE THREAD

**Issue by jjhesk** [keystonejs/keystone#1154]
when I run the code on ```routes/index.js``` with the new version ^0.3.2

```javascript

var _ = require('underscore'),
    keystone = require('keystone'),
    middleware = require('./middleware'),
    importRoutes = keystone.importer(__dirname);

// Import Route Controllers
var routes = {
    views: importRoutes('./views'),
    download: importRoutes('./download')
};

var api = {
    token: importRoutes('./api/').token,
    call: importRoutes('./api/call'),
    driver: importRoutes('./api/driver'),
    account: importRoutes('./api/me')
};

// Setup Route Bindings
exports = module.exports = function (app) {
    app.get('/', routes.views.index);
    app.all('/api/*', keystone.initAPI);

};
```

the server crashed with the error as listed below. After I have sorted out the location and the cause was that line ```  app.all('/api/*', keystone.initAPI);```

```


/usr/src/node-v0.10.4/var/taxi/node_modules/keystone/node_modules/express/lib/router/route.js:170
        throw new Error(msg);
              ^
Error: Route.get() requires callback functions but got a [object Undefined]
    at Route.<anonymous> (/usr/src/node-v0.10.4/var/taxi/node_modules/keystone/node_modules/express/lib/router/route.js:170:15)
    at Array.forEach (native)
    at Route.(anonymous function) [as get] (/usr/src/node-v0.10.4/var/taxi/node_modules/keystone/node_modules/express/lib/router/route.js:166:15)
    at /usr/src/node-v0.10.4/var/taxi/node_modules/keystone/node_modules/express/lib/application.js:486:19
    at Array.forEach (native)
    at EventEmitter.app.all (/usr/src/node-v0.10.4/var/taxi/node_modules/keystone/node_modules/express/lib/application.js:485:11)
    at module.exports (/usr/src/node-v0.10.4/var/taxi/routes/index.js:52:9)
    at mount (/usr/src/node-v0.10.4/var/taxi/node_modules/keystone/lib/core/mount.js:443:21)
    at start (/usr/src/node-v0.10.4/var/taxi/node_modules/keystone/lib/core/start.js:232:7)
    at Object.<anonymous> (/usr/src/node-v0.10.4/var/taxi/keystone.js:105:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

```

Before install with the new version it was working fine but when I upgraded to the new version then that was happened. Did I do anything wrong?

**Comment by jjhesk** [comment]
I have read the note in [here](https://github.com/keystonejs/keystone/wiki/0.2.x-to-0.3.x-Changes). Thanks
