### ISSUE TITLE
Clicking create button crashes when using Node 0.12

### ISSUE THREAD

**Issue by bobmoff** [keystonejs/keystone#1196]
![Create button](https://dl.dropboxusercontent.com/s/mrnyfb4gnu7rtbe/2015-03-11%20at%2014.52.png)

Stacktrace:
```
TypeError: /PROJECTDIRECTORY/node_modules/keystone/lib/core/../../templates/views/list.jade:24
    22| 	script(src='/keystone/js/lib/browserified/querystring.js')
    23| 	script(src='/keystone/js/lib/browserified/queryfilter.js')
  > 24| 	script.
    25| 		Keystone.list = { path: "#{list.path}", label: "#{list.label}", singular: "#{list.singular}", plural: "#{list.plural}", cols: !{JSON.stringify(colPaths)}, perPage: !{ Number(list.perPage) || 50 } };
    26| 		Keystone.wysiwyg = { options: !{JSON.stringify(wysiwygOptions)} };
    27| 		Keystone.items = !{ JSON.stringify(items) };

Cannot convert object to primitive value
  at String (native)
  at Object.escape (/PROJECTDIRECTORY/node_modules/keystone/node_modules/jade/lib/runtime.js:183:16)
  at eval (<anonymous>:5140:40)
  at eval (<anonymous>:5199:22)
  at res (/PROJECTDIRECTORY/node_modules/keystone/node_modules/jade/lib/index.js:191:38)
  at [object Object].render (/PROJECTDIRECTORY/node_modules/keystone/lib/core/render.js:118:13)
  at /PROJECTDIRECTORY/node_modules/keystone/routes/views/list.js:117:14
  at /PROJECTDIRECTORY/node_modules/async/lib/async.js:157:25
  at text.Field.compile (/PROJECTDIRECTORY/node_modules/keystone/lib/field.js:298:10)
  at compileFields (/PROJECTDIRECTORY/node_modules/keystone/routes/views/list.js:113:56)
  at iterate (/PROJECTDIRECTORY/node_modules/async/lib/async.js:149:13)
  at Object.async.eachSeries (/PROJECTDIRECTORY/node_modules/async/lib/async.js:165:9)
  at /PROJECTDIRECTORY/node_modules/keystone/routes/views/list.js:115:10
  at Promise.<anonymous> (/PROJECTDIRECTORY/node_modules/keystone/lib/list.js:1187:5)
  at Promise.<anonymous> (/PROJECTDIRECTORY/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
  at Promise.emit (events.js:107:17)
  at Promise.emit (/PROJECTDIRECTORY/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
  at Promise.fulfill (/PROJECTDIRECTORY/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
  at Promise.resolve (/PROJECTDIRECTORY/node_modules/keystone/node_modules/mongoose/lib/promise.js:114:23)
  at Promise.<anonymous> (/PROJECTDIRECTORY/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
  at Promise.emit (events.js:107:17)
  at Promise.emit (/PROJECTDIRECTORY/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
  at Promise.fulfill (/PROJECTDIRECTORY/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
  at /PROJECTDIRECTORY/node_modules/keystone/node_modules/mongoose/lib/query.js:1056:26
  at model.Document.init (/PROJECTDIRECTORY/node_modules/keystone/node_modules/mongoose/lib/document.js:254:11)
  at completeMany (/PROJECTDIRECTORY/node_modules/keystone/node_modules/mongoose/lib/query.js:1054:12)
  at Promise.<anonymous> (/PROJECTDIRECTORY/node_modules/keystone/node_modules/mongoose/lib/query.js:1029:11)
  at Promise.<anonymous> (/PROJECTDIRECTORY/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
  at Promise.emit (events.js:107:17)
  at Promise.emit (/PROJECTDIRECTORY/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
  at Promise.fulfill (/PROJECTDIRECTORY/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
  at Promise.resolve (/PROJECTDIRECTORY/node_modules/keystone/node_modules/mongoose/lib/promise.js:114:23)
  at /PROJECTDIRECTORY/node_modules/keystone/node_modules/mongoose/lib/model.js:2051:23
  at process._tickCallback (node.js:355:11)
```

**Comment by bobmoff** [comment]
Sorry. I just realized I was using an old version of Keystone.
