### ISSUE TITLE
Error: no open connections

### ISSUE THREAD

**Issue by leijing7** [keystonejs/keystone#1204]
> I use mongolab's free sandbox as the session store. Usually after running a few days, this error pops up, then I'd have to restart the app manually.
How do I solve this problem?

keystone-4 (err): Error: no open connections
keystone-4 (err):   at Db._executeInsertCommand (/var/www/babyregister/node_modules/mongodb/lib/mongodb/db.js:1999:21)
keystone-4 (err):   at Collection.update (/var/www/babyregister/node_modules/mongodb/lib/mongodb/collection/core.js:712:13)
keystone-4 (err):   at /var/www/babyregister/node_modules/connect-mongo/lib/connect-mongo.js:275:20
keystone-4 (err):   at MongoStore._get_collection (/var/www/babyregister/node_modules/connect-mongo/lib/connect-mongo.js:156:21)
keystone-4 (err):   at MongoStore.set (/var/www/babyregister/node_modules/connect-mongo/lib/connect-mongo.js:274:12)
keystone-4 (err):   at Session.save (/var/www/babyregister/node_modules/keystone/node_modules/express/node_modules/connect/lib/middleware/session/session.js:63:25)
keystone-4 (err):   at ServerResponse.res.end (/var/www/babyregister/node_modules/keystone/node_modules/express/node_modules/connect/lib/middleware/session.js:282:19)
keystone-4 (err):   at ServerResponse.res.send (/var/www/babyregister/node_modules/keystone/node_modules/express/lib/response.js:152:8)
keystone-4 (err):   at fn (/var/www/babyregister/node_modules/keystone/node_modules/express/lib/response.js:756:10)
keystone-4 (err):   at ExpressHandlebars.extend._renderTemplate (/var/www/babyregister/node_modules/express3-handlebars/lib/express-handlebars.js:340:13)
keystone-4 (err):   at ExpressHandlebars.renderTemplate (/var/www/babyregister/node_modules/express3-handlebars/lib/express-handlebars.js:196:18)
keystone-4 (err):   at fn (/var/www/babyregister/node_modules/express3-handlebars/node_modules/async/lib/async.js:582:34)
keystone-4 (err):   at Object._onImmediate (/var/www/babyregister/node_modules/express3-handlebars/node_modules/async/lib/async.js:498:34)
keystone-4 (err):   at processImmediate [as _immediateCallback] (timers.js:354:15)

>if a browser try again, no error but:

keystone-4 (out): Error thrown for request: /
keystone-4 (out): Error: no open connections
keystone-4 (out):   at Db._executeQueryCommand (/var/www/babyregister/node_modules/mongodb/lib/mongodb/db.js:1874:21)
keystone-4 (out):   at Cursor.nextObject (/var/www/babyregister/node_modules/mongodb/lib/mongodb/cursor.js:749:13)
keystone-4 (out):   at Collection.findOne (/var/www/babyregister/node_modules/mongodb/lib/mongodb/collection/query.js:162:10)
keystone-4 (out):   at /var/www/babyregister/node_modules/connect-mongo/lib/connect-mongo.js:223:18
keystone-4 (out):   at MongoStore._get_collection (/var/www/babyregister/node_modules/connect-mongo/lib/connect-mongo.js:156:21)
keystone-4 (out):   at MongoStore.get (/var/www/babyregister/node_modules/connect-mongo/lib/connect-mongo.js:222:10)
keystone-4 (out):   at Object.session [as handle] (/var/www/babyregister/node_modules/keystone/node_modules/express/node_modules/connect/lib/middleware/session.js:308:11)
keystone-4 (out):   at next (/var/www/babyregister/node_modules/keystone/node_modules/express/node_modules/connect/lib/proto.js:190:15)
keystone-4 (out):   at Object.cookieParser [as handle] (/var/www/babyregister/node_modules/keystone/node_modules/express/node_modules/connect/lib/middleware/cookieParser.js:60:5)
keystone-4 (out):   at next (/var/www/babyregister/node_modules/keystone/node_modules/express/node_modules/connect/lib/proto.js:190:15)
keystone-4 (out):   at Object.methodOverride [as handle] (/var/www/babyregister/node_modules/keystone/node_modules/express/node_modules/connect/lib/middleware/methodOverride.js:49:5)
keystone-4 (out):   at next (/var/www/babyregister/node_modules/keystone/node_modules/express/node_modules/connect/lib/proto.js:190:15)
keystone-4 (out):   at multipart (/var/www/babyregister/node_modules/keystone/node_modules/express/node_modules/connect/lib/middleware/multipart.js:64:37)
keystone-4 (out):   at /var/www/babyregister/node_modules/keystone/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:57:9
keystone-4 (out):   at urlencoded (/var/www/babyregister/node_modules/keystone/node_modules/express/node_modules/connect/lib/middleware/urlencoded.js:51:37)
keystone-4 (out):   at /var/www/babyregister/node_modules/keystone/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:55:7
keystone-4 (out):   at json (/var/www/babyregister/node_modules/keystone/node_modules/express/node_modules/connect/lib/middleware/json.js:53:37)
keystone-4 (out):   at Object.bodyParser [as handle] (/var/www/babyregister/node_modules/keystone/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:53:5)
keystone-4 (out):   at next (/var/www/babyregister/node_modules/keystone/node_modules/express/node_modules/connect/lib/proto.js:190:15)
keystone-4 (out):   at Object.logger (/var/www/babyregister/node_modules/keystone/node_modules/express/node_modules/connect/lib/middleware/logger.js:156:5)
keystone-4 (out):   at next (/var/www/babyregister/node_modules/keystone/node_modules/express/node_modules/connect/lib/proto.js:190:15)
keystone-4 (out):   at next (/var/www/babyregister/node_modules/keystone/node_modules/express/node_modules/connect/lib/proto.js:165:78)
keystone-4 (out):   at next (/var/www/babyregister/node_modules/keystone/node_modules/express/node_modules/connect/lib/proto.js:165:78)
keystone-4 (out):   at resume (/var/www/babyregister/node_modules/keystone/node_modules/express/node_modules/connect/lib/middleware/static.js:60:7)
keystone-4 (out):   at SendStream.error (/var/www/babyregister/node_modules/keystone/node_modules/express/node_modules/connect/lib/middleware/static.js:73:37)
keystone-4 (out):   at SendStream.emit (events.js:95:17)
keystone-4 (out):   at SendStream.error (/var/www/babyregister/node_modules/keystone/node_modules/express/node_modules/send/lib/send.js:147:51)
keystone-4 (out):   at SendStream.onStatError (/var/www/babyregister/node_modules/keystone/node_modules/express/node_modules/send/lib/send.js:248:48)
keystone-4 (out):   at /var/www/babyregister/node_modules/keystone/node_modules/express/node_modules/send/lib/send.js:320:26
keystone-4 (out):   at Object.oncomplete (fs.js:108:15)

**Comment by mxstbr** [comment]
Closing due to inactivity and age, if you're still having this issue feel free to comment again!
