### ISSUE TITLE
Post Categories (I think) Error

### ISSUE THREAD

**Issue by gmmeyer** [keystonejs/keystone#1221]
I have an error that I cannot figure out or track down very well. It only happens in production, no matter how I set things up, I cannot get it to duplicate on my development machine.

Does anyone have any idea as to what's wrong?
```bash
CastError: Cast to ObjectId failed for value "null" at path "categories"
at ObjectId.cast (/deploy/marksite/node_modules/keystone/node_modules/mongoose/lib/schema/objectid.js:117:13)
at Array.MongooseArray._cast (/deploy/marksite/node_modules/keystone/node_modules/mongoose/lib/types/array.js:113:30)
at Object.map (native)                                                                                                                          
at Array.MongooseArray.pull (/deploy/marksite/node_modules/keystone/node_modules/mongoose/lib/types/array.js:452:23)
at /deploy/marksite/node_modules/keystone/fields/types/relationship/RelationshipType.js:162:8
at Array.forEach (native)
at relationship.updateItem (/deploy/marksite/node_modules/keystone/fields/types/relationship/RelationshipType.js:161:28)
at UpdateHandler.<anonymous> (/deploy/marksite/node_modules/keystone/lib/updateHandler.js:287:9)
at Array.forEach (native)
at UpdateHandler.process (/deploy/marksite/node_modules/keystone/lib/updateHandler.js:202:17)
at Promise.<anonymous> (/deploy/marksite/node_modules/keystone/routes/views/item.js:175:31)
at Promise.<anonymous> (/deploy/marksite/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
at Promise.emit (events.js:95:17)
at Promise.emit (/deploy/marksite/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
at Promise.fulfill (/deploy/marksite/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
at Promise.resolve (/deploy/marksite/node_modules/keystone/node_modules/mongoose/lib/promise.js:114:23)
```

**Comment by creynders** [comment]
By the looks of it this is thrown when you try to save a post which has `null` as a value for its `categories` field. Since postcategories have an autokey based on `name` I'd guess it tries to reference a category without a name.

**Comment by gmmeyer** [comment]
Yea, that was my thought as well, and it is to some extent accurate. 

I should give a bit more background, I apologize for not giving it before it took me a while to track everything down. I did delete a category and then tried to delete the category from the post that it was attached to. That's the error that I get when I try to save the post after I remove the category from it (it also occurs when I try to save the post as is, without deleting it from it).

However, the same error is occurring if I restore the backup from before I deleted that category, and try to save the post or delete the category from the post, which is quite strange.

In fact, the error only seems to happen with that post, which makes it doubly bizarre--even with the restored database (and it also happens even if I drop the database and recreate every object in it). It's really frustrating.

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
