### ISSUE TITLE
Install using yo generator

### ISSUE THREAD

**Issue by JasoonS** [keystonejs/keystone#1235]
I am trying to install this on a digital ocean droplet and when I run the command "yo keystone" I get the following error. Can someone help me understand what might be the issue? I am root, so running sudo makes no difference. 

Error: EACCES, permission denied '/root/.config/configstore/insight-yo.yml'
You don't have access to this file.

    at Object.fs.openSync (evalmachine.<anonymous>:432:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:286:15)
    at Object.create.all.get (/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/local/lib/node_modules/yo/node_modules/insight/lib/index.js:36:34)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:117:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

I appreciate any help!
Thanks
Jason

**Comment by JasoonS** [comment]
And now I have seen that the /root/.config/ directory doesn't even exist. Does anyone have any idea why? 
The command: 'npm install -g generator-keystone' worked perfectly. So did: 'sudo npm install -g yo'. Am I missing something?

**Comment by JohnnyEstilles** [comment]
@JasoonS, the explanation is kind of long and convoluted. I know this may sound counterintuitive, but can you try login in as a user "other" than root and attempt the install once again.

```bash
sudo npm install -g yo

sudo npm install -g generator-keystone

yo keystone
```

**Comment by emolr** [comment]
Thank you so much @JohnnyEstilles, i had the same issue, and your solution worked perfectly, thank you
