### ISSUE TITLE
Improve error message when database connection fails

### ISSUE THREAD

**Issue by timleslie** [keystonejs/keystone#1243]
At the moment if you fail to connect to the database, you'll get something like this:

```
✖ Connecting to database
Error: Post connection error
    at /Users/stunjiturner/Downloads/Code/keystone-5/demo-projects/blog/node_modules/@keystone-alpha/utils/dist/utils.cjs.dev.js:72:21
    at async executeDefaultServer (/Users/stunjiturner/Downloads/Code/keystone-5/demo-projects/blog/node_modules/@keystone-alpha/keystone/bin/utils.js:108:3) {
  errors: {
    MongooseAdapter: Error: Post connection error
        at MongooseAdapter.connect (/Users/stunjiturner/Downloads/Code/keystone-5/demo-projects/blog/node_modules/@keystone-alpha/keystone/lib/adapters/index.js:31:23)
        at processTicksAndRejections (internal/process/task_queues.js:89:5)
        at async pReflect (/Users/stunjiturner/Downloads/Code/keystone-5/demo-projects/blog/node_modules/p-reflect/index.js:5:17)
        at async Promise.all (index 0)
        at async executeDefaultServer (/Users/stunjiturner/Downloads/Code/keystone-5/demo-projects/blog/node_modules/@keystone-alpha/keystone/bin/utils.js:108:3) {
      errors: [Array]
    }
  }
}
error Command failed with exit code 1.
```

The actual error message which caused the failure is hidden within the line `errors: [Array]`. We need to improve the way we report these errors so that the vital info is not lost.

See #1231

**Comment by stunjiturner** [comment]
what is the error, how can it be fixed.
