### ISSUE TITLE
res.setHeader  failed  Can't set headers after they are sent.

### ISSUE THREAD

**Issue by arthurtalkgoal** [keystonejs/keystone#1371]
Hi ,

I want to generate ***.vcf*** (vcard) file of the company in my database.

However, if I update the ```res.setHeader``` after my grabbing the company, it has error *** Can't set headers after they are sent.***

If I put the setheader to top, I cannot do the ***company not found*** validation.

Also, My failname cannot rely on the company.

Where should I update the set header?  
```
var Company = keystone.list('Company');

exports = module.exports = function(req, res) {
  ...

	// Load the current post
	view.on('init', function(next) {
    Company.model
      .findOne({slug: req.params.id})
        .exec(function(err, company) {
          if (company) {

              locals.company = company;
              email = company.email                    
              
              bizcard = ["BEGIN:VCARD"];
              bizcard.push("VERSION:2.1");
              bizcard.push("N:Arthur;CHAN");  // name
              bizcard.push("FN:Arthur Chan");  // Full Name
              bizcard.push("ORG:" + company.name);
              bizcard.push("TEL;WORK;VOICE:" + company.phone);
              bizcard.push("ADR;WORK:;;" + company.address.serialized);
              bizcard.push("EMAIL;PREF;INTERNET:" + email);
              bizcard.push("BEGIN:VCARD")

              res.send(bizcard.join("\n"));
              

             /*
              * Failed to set Header here!
             **************/
              res.setHeader('Content-Type', 'application/octet-stream');
              res.setHeader('Content-disposition', 'attachment; filename="'+company.slug+'.vcf"');
              


              next(err);

            } else {
              req.flash('error', req.i18n.__("error.company_notfound")) ;
              return res.redirect('/shops' );

            }
          });
	});

  view.render('shops/businesscard');
}
```

**Comment by WingedToaster** [comment]
what happens if you put it before the res.send?

              bizcard = ["BEGIN:VCARD"];
              bizcard.push("VERSION:2.1");
              bizcard.push("N:Arthur;CHAN");  // name
              bizcard.push("FN:Arthur Chan");  // Full Name
              bizcard.push("ORG:" + company.name);
              bizcard.push("TEL;WORK;VOICE:" + company.phone);
              bizcard.push("ADR;WORK:;;" + company.address.serialized);
              bizcard.push("EMAIL;PREF;INTERNET:" + email);
              bizcard.push("BEGIN:VCARD")

              res.setHeader('Content-Type', 'application/octet-stream');
              res.setHeader('Content-disposition', 'attachment; filename="'+company.slug+'.vcf"');

              res.send(bizcard.join("\n"));

**Comment by arthurtalkgoal** [comment]
Hi @WingedToaster  I put it there before, but got the error.

**Comment by creynders** [comment]
They definitely should go before `send`. If the error still remains, I'd try and drop `next(err)` to see what happens

**Comment by WingedToaster** [comment]
OK, there must be another export or other code within this export that is starting to send a response before this code...I doubt this is an issue with keystone. Any more source or github link to share?

**Comment by arthurtalkgoal** [comment]
Hi @WingedToaster ,  

I think it's not particular issue for keystone. 
How to export a text file, vCalenar in my case in keystone or express is my main concern. 

The particular issue here is I need checking the instance existence before finish the body or go redirection.

**Comment by creynders** [comment]
@arthurtalkgoal Have you tried my suggestion?

**Comment by arthurtalkgoal** [comment]
Hi @creynders,

Thanks for the suggestion, fact, it still get the same can't send header error.

my code now becomes:

```
// res.setHeader('Content-Type', 'application/octet-stream');
//res.setHeader('Content-disposition', 'attachment; filename="'+company.slug+'.vcf"');
...

                  bizcard.push("END:VCARD")

                    res.setHeader('Content-Type', 'application/octet-stream');
                    res.setHeader('Content-disposition', 'attachment; filename="'+company.slug+'.vcf"');

                    res.send(bizcard.join("\n"));

     
                    //next(err);

       } else {
	   req.flash('error', req.i18n.__("error.company_notfound")) ;
           return res.redirect('/shops' );

}
```
The error is:
```
Error thrown for request: /shops/home-chef/calendar/event.vcs
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:691:11)
    at ServerResponse.header (/mykeystone/node_modules/keystone/node_modules/express/lib/response.js:700:10)
    at ServerResponse.send (/mykeystone/node_modules/keystone/node_modules/express/lib/response.js:154:12)
    at fn (/mykeystone/node_modules/keystone/node_modules/express/lib/response.js:934:10)
    at View.exports.renderFile [as engine] (/mykeystone/node_modules/keystone/node_modules/jade/lib/index.js:374:12)
    at View.render (/mykeystone/node_modules/keystone/node_modules/express/lib/view.js:93:8)
    at EventEmitter.app.render (/mykeystone/node_modules/keystone/node_modules/express/lib/application.js:566:10)
    at ServerResponse.res.render (/mykeystone/node_modules/keystone/node_modules/express/lib/response.js:938:7)
    at View.<anonymous> (/mykeystone/node_modules/keystone/lib/view.js:336:13)
    at /mykeystone/node_modules/keystone/lib/view.js:372:3
    at /mykeystone/node_modules/async/lib/async.js:157:25
    at /mykeystone/node_modules/async/lib/async.js:254:17
    at async.each (/mykeystone/node_modules/async/lib/async.js:121:20)
    at _asyncMap (/mykeystone/node_modules/async/lib/async.js:248:13)
    at Object.map (/mykeystone/node_modules/async/lib/async.js:219:23)
    at _parallel (/mykeystone/node_modules/async/lib/async.js:568:20)
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:691:11)
    at ServerResponse.header (/mykeystone/node_modules/keystone/node_modules/express/lib/response.js:700:10)
    at ServerResponse.send (/mykeystone/node_modules/keystone/node_modules/express/lib/response.js:154:12)
    at default500Handler (/mykeystone/node_modules/keystone/lib/core/mount.js:526:20)
    at /mykeystone/node_modules/keystone/lib/core/mount.js:555:5
    at Layer.handle_error (/mykeystone/node_modules/keystone/node_modules/express/lib/router/layer.js:58:5)
    at trim_prefix (/mykeystone/node_modules/keystone/node_modules/express/lib/router/index.js:300:13)
    at /mykeystone/node_modules/keystone/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/mykeystone/node_modules/keystone/node_modules/express/lib/router/index.js:321:12)
    at next (/mykeystone/node_modules/keystone/node_modules/express/lib/router/index.js:261:10)
    at Layer.handle_error (/mykeystone/node_modules/keystone/node_modules/express/lib/router/layer.js:54:12)
    at trim_prefix (/mykeystone/node_modules/keystone/node_modules/express/lib/router/index.js:300:13)
    at /mykeystone/node_modules/keystone/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/mykeystone/node_modules/keystone/node_modules/express/lib/router/index.js:321:12)
    at IncomingMessage.next (/mykeystone/node_modules/keystone/node_modules/express/lib/router/index.js:261:10)
    at fn (/mykeystone/node_modules/keystone/node_modules/express/lib/response.js:933:25)

```

**Comment by creynders** [comment]
Ah, yes of course, it errors on `view.render()`. If you still need the view, you'll have to render conditionally, i.e. sth like:

```js
var bizCardFound=false;
view.on('init', function(next) {
  ...
  bizCardFound = true;
  res.send(bizcard.join("\n"));
  ...
});

if(!bizCardFound){
  view.render();
}
```

**Comment by creynders** [comment]
:facepalm: ah no, it's async of course. That won't work.

**Comment by creynders** [comment]
Just had a look and the way I did was make it a separate API call.

```js
//file: routes/index.js
  app.get( "/api/reports/comparisons", api.reports.comparisons );

//file: routes/api/reports.js
module.exports.comparisons = function(){
  //create csv store in `results`
       res.attachment( "comparisons.csv" );
      res.send( 200, results );
}
```

Then hit the API instead

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
