### ISSUE TITLE
Plugin undefined

### ISSUE THREAD

**Issue by creynders** [keystonejs/keystone#1377]
Oh noes, `keystone` is kaput! :wink: 

When viewing the admin UI (code from `master`) an error is thrown:

```sh
Error thrown for request: /keystone/js/home.js
TypeError: Plugin undefined didn't export a default Transformer instance while parsing file: ~/keystone/admin/src/views/home.js
    at File.addPlugin (~/keystone/node_modules/babelify/node_modules/babel-core/lib/babel/transformation/file/index.js:287:13)
    at File.buildTransformers (~/keystone/node_modules/babelify/node_modules/babel-core/lib/babel/transformation/file/index.js:219:12)
    at new File (~/keystone/node_modules/babelify/node_modules/babel-core/lib/babel/transformation/file/index.js:90:10)
    at Object.transform (~/keystone/node_modules/babelify/node_modules/babel-core/lib/babel/transformation/index.js:18:14)
    at Stream.end (~/keystone/node_modules/babelify/index.js:38:25)
    at _end (~/keystone/node_modules/babelify/node_modules/through/index.js:65:9)
    at Stream.stream.end (~/keystone/node_modules/babelify/node_modules/through/index.js:74:5)
    at Transform.onend (~/keystone/node_modules/browserify-middleware/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at Transform.g (events.js:199:16)
    at Transform.emit (events.js:129:20)
    at ~/keystone/node_modules/browserify-middleware/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickCallback (node.js:355:11)
```

**Comment by JedWatson** [comment]
ugh, looks like a problem with our babel setup. I'll check it out.

**Comment by JedWatson** [comment]
I just updated all the dependencies, did a fresh npm link in a project and can't replicate the issue. Try again maybe?

**Comment by creynders** [comment]
@JedWatson :cake: and :beers: !
