### ISSUE TITLE
Need some help - I'm getting this error - am I out of memory?

### ISSUE THREAD

**Issue by didymu5** [keystonejs/keystone#1397]
I have keystone installed on a MEAN stack on DO - but it keeps crashing on me when I access that admin tool. I can't even post.  Any help or suggestions would be much appreciated

2015-04-30 19:53:16: ERROR CAUGHT BY DOMAIN:
Error: spawn ENOMEM
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1155:11)
    at exports.spawn (child_process.js:988:9)
    at Object.exports.execFile (child_process.js:682:15)
    at exports.exec (child_process.js:642:18)
    at getUrl (/usr/local/lib/node_modules/pm2/node_modules/vizion/lib/git.js:17:5)
    at fn (/usr/local/lib/node_modules/pm2/node_modules/async/lib/async.js:641:34)
    at Immediate._onImmediate (/usr/local/lib/node_modules/pm2/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
child_process.js:1155
    throw errnoException(err, 'spawn');
          ^
Error: spawn ENOMEM
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1155:11)
    at exports.spawn (child_process.js:988:9)
    at Object.exports.execFile (child_process.js:682:15)
    at exports.exec (child_process.js:642:18)
    at getUrl (/usr/local/lib/node_modules/pm2/node_modules/vizion/lib/git.js:17:5)
    at fn (/usr/local/lib/node_modules/pm2/node_modules/async/lib/async.js:641:34)
    at Immediate._onImmediate (/usr/local/lib/node_modules/pm2/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:358:17)

**Comment by didymu5** [comment]
BTW, I'm running pm2
It overs around 110mb-220mb use of memory. Is that a little high?

**Comment by ttsirkia** [comment]
In my measurements, an empty Keystone application will use about 80 mb memory. In my own application which is not that large, a typical memory consumption is about 220 mb. However, it seems that Node memory management does not always garbage collect all unused data which may cause high memory usage. The default memory size may be up to 1 gb. I've used `max_old_space_size` parameter which sets maximum memory size for long-persisting objects.

**Comment by medv** [comment]
http://stackoverflow.com/questions/28823202/beginner-memory-usage-on-a-stock-install

**Comment by didymu5** [comment]
Thanks Mikhail!

**Comment by didymu5** [comment]
So what I ended up doing was upgrading DO to the next level, beyond the 512. 
No issues so far, except for one crash. Overall this is still a concern once traffic increases what will happen?

**Comment by medv** [comment]
Yeah, but this will prevent that:
https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
