### ISSUE TITLE
Large values in Number fields crash the server

### ISSUE THREAD

**Issue by mcauser** [keystonejs/keystone#141]
Number fields containing very large numbers such as '999999999999999999999' crash the server with the error:

    Cannot read property 'length' of undefined
    at formatNumber (/Users/mike/Development/keystone/node_modules/numeral/numeral.js:360:36)
    at formatNumeral (/Users/mike/Development/keystone/node_modules/numeral/numeral.js:75:22)
    at Object.numeral.fn.Numeral.format (/Users/mike/Development/keystone/node_modules/numeral/numeral.js:587:20)
    at number.format (/Users/mike/Development/keystone/lib/fieldTypes/number.js:41:82)
    at eval (eval at <anonymous> (/Users/mike/Development/keystone/node_modules/jade/lib/jade.js:160:8), <anonymous>:19:19)
    at res (/Users/mike/Development/keystone/node_modules/jade/lib/jade.js:161:38)
    at number.Field.render (/Users/mike/Development/keystone/lib/field.js:223:9)
    at jade_debug.unshift.lineno (eval at <anonymous> (/Users/mike/Development/keystone/node_modules/jade/lib/jade.js:160:8), <anonymous>:1378:41)
    at eval (eval at <anonymous> (/Users/mike/Development/keystone/node_modules/jade/lib/jade.js:160:8), <anonymous>:1470:4)
    at res (/Users/mike/Development/keystone/node_modules/jade/lib/jade.js:161:38)

**Comment by sebmck** [comment]
Can't seem to replicate this. It's likely been fixed upstream and fixed in keystone when the package has been upgraded. Feel free to reopen or create a new issue if this problem persists. Thanks!
