### ISSUE TITLE
Keystone Enviroment Host Error: listen EADDRNOTAVAIL

### ISSUE THREAD

**Issue by xianlin** [keystonejs/keystone#1491]
I have `.env` with `require('dotenv').load()` to load all the env variables in that file.

`.env`

```
NODE_ENV=development
MONGO_URI=mongodb://localhost/utownrc
PORT=3000
IP=172.29.182.61

```

`keystone.js`

```
keystone.init({
...
        'mongo': process.env.MONGO_URI || "mongodb://localhost/your-db",
        'port': process.env.PORT || 3000,
        'host': process.env.IP || '127.0.0.1'

});

```

When I run `node keystone`, here are the errors:

```
Error: listen EADDRNOTAVAIL
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1139:19)
    at listen (net.js:1182:10)
    at net.js:1280:9
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)

```

if I change IP to `127.0.0.1` in the `.env` file, everything is OK. Why?

**Comment by xianlin** [comment]
it turns on my keystonejs host IP is not the IP I set in the `.env` file, these 2 IPs (host ip and env IP should match).
