### ISSUE TITLE
yo keystone fails ....

### ISSUE THREAD

**Issue by oronoa** [keystonejs/keystone#1528]
> yo keystone ( on node 0.10.28) give me 

Error: EACCES, permission denied '/root/.config/configstore/insight-yo.json'
You don't have access to this file.

    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
    at Object.create.all.get (/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:27:26)
    at Object.Configstore (/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:20:44)
    at new Insight (/usr/local/lib/node_modules/yo/node_modules/insight/lib/index.js:37:34)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:130:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

also where is the best place to char about keystone , IRC seems empty

**Comment by morenoh149** [comment]
https://gitter.im/keystonejs/keystone

**Comment by oronoa** [comment]
thx !

Best Wishes

Oron Ogdan-Adam

Mobile +972 (0) 54 667 1414
email : oronoa@gmail.com


***********************************************

This email and any attachments thereto contain private, confidential, and
privileged material. Any use, review, copying, or disclosure of this email
(or any attachments thereto) by any party other than the intended recipient
is strictly prohibited. If you are not the intended recipient, please
contact the sender immediately and permanently delete the original and any
copies of this email and any attachments thereto.

2015-07-16 0:30 GMT+03:00 Harry Moreno <notifications@github.com>:
