### ISSUE TITLE
Access Control: no longer accepts object as return value from granular function 

### ISSUE THREAD

**Issue by gautamsi** [keystonejs/keystone#1542]
error in meetup demo.

steps to repro:
* go to home page and sign in after running the meetup demo
* go to graphiql and try following query (from `Profile` page in the demo)
```gql
query user {
    authenticatedUser {
      id
      name
      email
      twitterHandle
      image {
        publicUrlTransformed(
          transformation: { quality: "40", width: "90", height: "90", crop: "thumb", page: "1" }
        )
      }
    }
  }
```
observe the error (when signed in already

```gql
{
  "errors": [
    {
      "message": "Must return a Boolean from User.fields.email.access.read(). Got Object",
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ],
      "path": [
        "authenticatedUser",
        "email"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Must return a Boolean from User.fields.email.access.read(). Got Object",
            "    at validateFieldAccessControl (/Volumes/dev/keystone-5/packages/access-control/lib/access-control.js:175:13)",
            "    at fastMemoize (/Volumes/dev/keystone-5/packages/keystone/lib/Keystone/index.js:422:16)",
            "    at variadic (/Volumes/dev/keystone-5/node_modules/fast-memoize/src/index.js:50:24)",
            "    at rest (/Volumes/dev/keystone-5/packages/keystone/lib/List/index.js:515:30)",
            "    at field.resolve (/Volumes/dev/keystone-5/node_modules/apollo-server-core/node_modules/graphql-extensions/src/index.ts:267:18)",
            "    at resolveFieldValueOrError (/Volumes/dev/keystone-5/node_modules/graphql/execution/execute.js:503:18)",
            "    at resolveField (/Volumes/dev/keystone-5/node_modules/graphql/execution/execute.js:470:16)",
            "    at executeFields (/Volumes/dev/keystone-5/node_modules/graphql/execution/execute.js:311:18)",
            "    at collectAndExecuteSubfields (/Volumes/dev/keystone-5/node_modules/graphql/execution/execute.js:747:10)",
            "    at completeObjectValue (/Volumes/dev/keystone-5/node_modules/graphql/execution/execute.js:737:10)",
            "    at completeValue (/Volumes/dev/keystone-5/node_modules/graphql/execution/execute.js:626:12)",
            "    at /Volumes/dev/keystone-5/node_modules/graphql/execution/execute.js:528:16",
            "    at process._tickCallback (internal/process/next_tick.js:68:7)"
          ]
        }
      },
      "uid": "cjztng8ay0009ghg2g0fa0z3a",
      "name": "GraphQLError"
    }
  ],
  "data": {
    "authenticatedUser": {
      "id": "5d64b742f534932b6b7266b3",
      "name": "Admin User",
      "email": null,
      "twitterHandle": null,
      "image": null
    }
  },
  "extensions": {}
}
```

This error is due to schema for User list, 

```js
exports.User = {
  access: {
    update: access.userIsCurrentAuth,
    delete: access.userIsAdmin,
  },
  fields: {
    name: { type: Text },
    email: { type: Text, isUnique: true, access: { read: access.userIsCurrentAuth } },
    //....... other fields
  },
}
```

```js
userIsCurrentAuth: ({ authentication: { item } }) => {
    if (!item) {
      return false;
    }
    return { id: item.id };
  },
```

**Comment by Vultraz** [comment]
That function is the same as what's generated by the `create keystone-app` helper:

```js
const userOwnsItem = ({ authentication: { item: user } }) => {
  if (!user) {
    return false;
  }
  return { id: user.id };
};
```

Can reproduce the bug, but only for fields 🤔 The same function for List access seems to work fine...

**Comment by singhArmani** [comment]
@gautamsi : You are right for the User schema email field returning an **object** instead of **boolean** 👍 . This is indeed the cause of the bug. 
@Vultraz: You are right in your observation regarding list level access control can use `AccessInput => GraphQLWhere` 👍 

@MadeByMike: I am going to create a PR to update the demo. 
Thanks guys ❤️
