### ISSUE TITLE
Installing Keystone's npm dependencies fails.

### ISSUE THREAD

**Issue by yn5** [keystonejs/keystone#1564]
The problem occurs in OSX node v0.12(.2)  as well as in a node:0.12 Docker container.

Since today installing the npm dependencies of a Keystone project generated with Yeoman generator (or causing the npm install by creating a new project with the Yeoman generator) fails on installing  the nodejieba dependency.

This is the npm output of the freshly generated Keystone project by Yeoman:

```
npm WARN peerDependencies The peer dependency browserify@>= 2.3.0 < 12 included from browserify-shim will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

> fsevents@0.3.7 install /Users/yn5/stuff/web/phkstone-temp/node_modules/keystone/node_modules/watchify/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node: Finished
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  SOLINK_MODULE(target) Release/fse.node: Finished

> kerberos@0.0.11 install /Users/yn5/stuff/web/phkstone-temp/node_modules/keystone/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
  CXX(target) Release/obj.target/kerberos/lib/worker.o
  CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
  CC(target) Release/obj.target/kerberos/lib/base64.o
  CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
  SOLINK_MODULE(target) Release/kerberos.node
  SOLINK_MODULE(target) Release/kerberos.node: Finished

> bson@0.2.22 install /Users/yn5/stuff/web/phkstone-temp/node_modules/keystone/node_modules/mongoose/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bson/ext/bson.o
  SOLINK_MODULE(target) Release/bson.node
  SOLINK_MODULE(target) Release/bson.node: Finished
npm WARN engine nodejieba@1.0.3: wanted: {"node":"0.10.x"} (current: {"node":"0.12.2","npm":"2.7.5"})
|
> nodejieba@1.0.3 install /Users/yn5/stuff/web/phkstone-temp/node_modules/keystone/node_modules/keystone-utils/node_modules/limax/node_modules/pinyin/node_modules/nodejieba
> node-gyp rebuild

  CXX(target) Release/obj.target/nodejieba/lib/index.o
In file included from ../lib/index.cpp:1:
In file included from ../lib/nodejieba.h:4:
../lib/utils.h:17:11: error: use of undeclared identifier 'NanIntern'
  array = NanIntern::Factory<v8::Array>::New(ov.size());
          ^
../lib/utils.h:17:39: error: expected '(' for function-style cast or type construction
  array = NanIntern::Factory<v8::Array>::New(ov.size());
                             ~~~~~~~~~^
../lib/utils.h:17:42: error: no member named 'New' in the global namespace
  array = NanIntern::Factory<v8::Array>::New(ov.size());
                                       ~~^
../lib/utils.h:19:21: error: use of undeclared identifier 'NanIntern'
      array->Set(i, NanIntern::Factory<v8::String>::New(ov[i].c_str()));
                    ^
../lib/utils.h:19:50: error: expected '(' for function-style cast or type construction
      array->Set(i, NanIntern::Factory<v8::String>::New(ov[i].c_str()));
                                       ~~~~~~~~~~^
../lib/utils.h:19:53: error: no member named 'New' in the global namespace
      array->Set(i, NanIntern::Factory<v8::String>::New(ov[i].c_str()));
                                                  ~~^
../lib/utils.h:24:11: error: use of undeclared identifier 'NanIntern'
  array = NanIntern::Factory<v8::Array>::New(ov.size());
          ^
../lib/utils.h:24:39: error: expected '(' for function-style cast or type construction
  array = NanIntern::Factory<v8::Array>::New(ov.size());
                             ~~~~~~~~~^
../lib/utils.h:24:42: error: no member named 'New' in the global namespace
  array = NanIntern::Factory<v8::Array>::New(ov.size());
                                       ~~^
../lib/utils.h:30:19: error: use of undeclared identifier 'NanIntern'
    array->Set(i, NanIntern::Factory<v8::String>::New(ss.str().c_str()));
                  ^
../lib/utils.h:30:48: error: expected '(' for function-style cast or type construction
    array->Set(i, NanIntern::Factory<v8::String>::New(ss.str().c_str()));
                                     ~~~~~~~~~~^
../lib/utils.h:30:51: error: no member named 'New' in the global namespace
    array->Set(i, NanIntern::Factory<v8::String>::New(ss.str().c_str()));
                                                ~~^
../lib/utils.h:35:11: error: use of undeclared identifier 'NanIntern'
  array = NanIntern::Factory<v8::Array>::New(ov.size());
          ^
../lib/utils.h:35:39: error: expected '(' for function-style cast or type construction
  array = NanIntern::Factory<v8::Array>::New(ov.size());
                             ~~~~~~~~~^
../lib/utils.h:35:42: error: no member named 'New' in the global namespace
  array = NanIntern::Factory<v8::Array>::New(ov.size());
                                       ~~^
../lib/utils.h:41:19: error: use of undeclared identifier 'NanIntern'
    array->Set(i, NanIntern::Factory<v8::String>::New(ss.str().c_str()));
                  ^
../lib/utils.h:41:48: error: expected '(' for function-style cast or type construction
    array->Set(i, NanIntern::Factory<v8::String>::New(ss.str().c_str()));
                                     ~~~~~~~~~~^
../lib/utils.h:41:51: error: no member named 'New' in the global namespace
    array->Set(i, NanIntern::Factory<v8::String>::New(ss.str().c_str()));
                                                ~~^
18 errors generated.
make: *** [Release/obj.target/nodejieba/lib/index.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/yn5/stuff/web/phkstone-temp/node_modules/keystone/node_modules/keystone-utils/node_modules/limax/node_modules/pinyin/node_modules/nodejieba
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5
npm ERR! code ELIFECYCLE

npm ERR! nodejieba@1.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodejieba@1.0.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the nodejieba package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodejieba
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yn5/stuff/web/phkstone-temp/npm-debug.log

------------------------------------------------

Your KeystoneJS project is ready to go!

For help getting started, visit http://keystonejs.com/guide

To start your new website, run "cd phkstone-temp" then "node keystone".
```

**Comment by bscheibe** [comment]
+1

**Comment by tompatros** [comment]
+1

**Comment by kmattimo** [comment]
I have just hit this when trying to install keystone through the yo generator, the heroku starter pack and by cloning the main repo. this was not happening last night. ubuntu 15.04 x64

I am curious how keystone found its way into trying to native build this obscure package that involves Chinese characters... this is one of several problems I've had with keystone and native built dependencies

**Comment by chriswburke** [comment]
+1

**Comment by macoss** [comment]
Having the same issue with Ubuntu 14.04 on a Digital Ocean droplet.

**Comment by nanymor** [comment]
Progress on this at https://github.com/lovell/limax/issues/7

**Comment by mark-bradshaw** [comment]
The pinyin module was just updated by the author to include a later version of nodejieba.  It's being released.

**Comment by mark-bradshaw** [comment]
It's out now on npm, and this issue is fixed.

**Comment by kmattimo** [comment]
can confirm this fixed it for me! Thanks!

**Comment by yn5** [comment]
Thanks for all the replies! The issue is fixed so I'll close it.

**Comment by dennismayr** [comment]
After doing `npm audit fix` on a KeystoneJS installation, I get the following errors while building *kerberos* modules:

```$ npm audit fix
npm WARN deprecated babyparse@0.4.6: Deprecated in favour of PapaParse, which now supports Node.js
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated letsencrypt-express@2.0.7: letsencrypt-express has been renamed to greenlock-express and will now be maintained as such.
npm WARN deprecated scmp@1.0.2: scmp v2 uses improved core crypto comparison since Node v6.6.0
npm WARN deprecated sprintf@0.1.1: The sprintf package is deprecated in favor of sprintf-js.
npm WARN deprecated letsencrypt@2.1.9: letsencrypt has been renamed to greenlock. Please find it at npm greenlock
npm WARN deprecated localhost.daplie.com-certificates@1.2.5: this package has been deprecated

> kerberos@0.0.23 install /home/dmayr/Documentos/DEV/Web_DEV/sururu-keystonejs/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: se entra en el directorio '/home/dmayr/Documentos/DEV/Web_DEV/sururu-keystonejs/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
  CXX(target) Release/obj.target/kerberos/lib/worker.o
  CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
../lib/kerberosgss.c:36:0: error: ignoring #pragma clang diagnostic [-Werror=unknown-pragmas]
 #pragma clang diagnostic push
 ^
../lib/kerberosgss.c:37:0: error: ignoring #pragma clang diagnostic [-Werror=unknown-pragmas]
 #pragma clang diagnostic ignored "-Wdeprecated-declarations"
 ^
../lib/kerberosgss.c: In function ‘authenticate_gss_client_init’:
../lib/kerberosgss.c:180:34: error: implicit declaration of function ‘strdup’ [-Werror=implicit-function-declaration]
       state->credentials_cache = strdup(credentials_cache);
                                  ^
../lib/kerberosgss.c:180:32: error: assignment makes pointer from integer without a cast [-Werror=int-conversion]
       state->credentials_cache = strdup(credentials_cache);
                                ^
../lib/kerberosgss.c: In function ‘authenticate_gss_client_wrap’:
../lib/kerberosgss.c:446:19: error: variable ‘server_conf_flags’ set but not used [-Werror=unused-but-set-variable]
   char buf[4096], server_conf_flags;
                   ^
../lib/kerberosgss.c: In function ‘authenticate_gss_server_step’:
../lib/kerberosgss.c:716:24: error: assignment makes pointer from integer without a cast [-Werror=int-conversion]
      response->message = strdup("No auth_data value in request from client");
                        ^
../lib/kerberosgss.c: In function ‘create_krb5_ccache’:
../lib/kerberosgss.c:1092:12: error: assignment makes pointer from integer without a cast [-Werror=int-conversion]
     ccname = strdup("FILE:/tmp/krb5cc_nodekerberos_XXXXXX");
            ^
../lib/kerberosgss.c:1095:10: error: implicit declaration of function ‘mkstemp’ [-Werror=implicit-function-declaration]
     fd = mkstemp(ccname + strlen("FILE:"));
          ^
../lib/kerberosgss.c:1115:40: error: assignment makes pointer from integer without a cast [-Werror=int-conversion]
     state->delegated_credentials_cache = strdup(ccname);
                                        ^
../lib/kerberosgss.c: In function ‘krb5_ctx_error’:
../lib/kerberosgss.c:1200:23: error: assignment makes pointer from integer without a cast [-Werror=int-conversion]
     response->message = strdup(error_text);
                       ^
../lib/kerberosgss.c: At top level:
../lib/kerberosgss.c:1236:0: error: ignoring #pragma clang diagnostic [-Werror=unknown-pragmas]
 #pragma clang diagnostic pop
 ^
cc1: all warnings being treated as errors
kerberos.target.mk:108: fallo en las instrucciones para el objetivo 'Release/obj.target/kerberos/lib/kerberosgss.o'
make: *** [Release/obj.target/kerberos/lib/kerberosgss.o] Error 1
make: se sale del directorio '/home/dmayr/Documentos/DEV/Web_DEV/sururu-keystonejs/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-138-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/dmayr/Documentos/DEV/Web_DEV/sururu-keystonejs/node_modules/kerberos
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok```

I tried installing `libkrb5-dev` as suggested somewhere else, and at least that got `clang` to try building the module.
Installation, however, still seems to fail.
