### ISSUE TITLE
False positive test failures in CircleCI

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1576]
We're getting false positives for our integration test runs: https://circleci.com/gh/keystonejs/keystone-5/25315?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

The tests have failures, but CI passes it as green.

Running the tests locally produces the same result:

```
❯ cd test-projects/basic
❯ yarn cypress:run:ci
<snip>
    6 of 15 failed (40%)                        10:35       64       50       13        1        -

npm ERR! code ELIFECYCLE
npm ERR! errno 13
npm ERR! @keystone-alpha/cypress-project-basic@1.3.10 cypress:run:cmd: `TZ=UTC node -r dotenv-safe/config `which cypress` run`
npm ERR! Exit status 13
npm ERR!
npm ERR! Failed at the @keystone-alpha/cypress-project-basic@1.3.10 cypress:run:cmd script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jess/.npm/_logs/2019-09-03T06_35_53_908Z-debug.log
{ Error: Command failed: npm run cypress:run:cmd
    at makeError (/Users/jess/dev/keystone-5/node_modules/start-server-and-test/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/Users/jess/dev/keystone-5/node_modules/start-server-and-test/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 13,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'npm run cypress:run:cmd',
  timedOut: false,
  killed: false }
Error: Command failed with exit code 1 (EPERM): start-server-and-test start http-get://localhost:3000/admin cypress:run:cmd
✨  Done in 872.99s.

~/dev/keystone-5/test-projects/basic master* 14m 34s
❯ echo $?
0
```
ie; the exit code is incorrectly reported as `0` instead of `1`.

Versions:
- `yarn`: `1.15.2`
- `node`: `10.9.0`
- commit: `e586af45`

**Comment by timleslie** [comment]
CI has been running smoothly for ages, so I'm going to close out this issue now 👍
