### ISSUE TITLE
heroku libsass issue w/ node-sass

### ISSUE THREAD

**Issue by waltonryan** [keystonejs/keystone#1704]
I'm getting an error deploying a keystonejs app to heroku (the yo keystone example).

<pre>
Starting process with command `node keystone.js`
2015-10-04T14:30:04.671196+00:00 app[web.1]: { [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
2015-10-04T14:30:08.936809+00:00 app[web.1]: { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
2015-10-04T14:30:08.937503+00:00 app[web.1]: js-bson: Failed to load c++ bson extension, using pure JS version
2015-10-04T14:30:09.452734+00:00 app[web.1]: Warning: connect.session() MemoryStore is not
2015-10-04T14:30:09.452740+00:00 app[web.1]: designed for a production environment, as it will leak
2015-10-04T14:30:09.452742+00:00 app[web.1]: memory, and will not scale past a single process.
2015-10-04T14:30:09.472343+00:00 app[web.1]: /app/node_modules/keystone/lib/core/mount.js:316
2015-10-04T14:30:09.472348+00:00 app[web.1]: 				throw e;
2015-10-04T14:30:09.472349+00:00 app[web.1]: 				^
2015-10-04T14:30:09.472351+00:00 app[web.1]: 
2015-10-04T14:30:09.472353+00:00 app[web.1]: Error: `libsass` bindings not found. Try reinstalling `node-sass`?
2015-10-04T14:30:09.472355+00:00 app[web.1]:     at getBinding (/app/node_modules/node-sass-middleware/node_modules/node-sass/lib/index.js:22:11)
2015-10-04T14:30:09.472356+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/node-sass-middleware/node_modules/node-sass/lib/index.js:188:23)
2015-10-04T14:30:09.472358+00:00 app[web.1]:     at Module._compile (module.js:434:26)
2015-10-04T14:30:09.472359+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:452:10)
2015-10-04T14:30:09.472361+00:00 app[web.1]:     at Module.load (module.js:355:32)
2015-10-04T14:30:09.472362+00:00 app[web.1]:     at Function.Module._load (module.js:310:12)
2015-10-04T14:30:09.472364+00:00 app[web.1]:     at Module.require (module.js:365:17)
2015-10-04T14:30:09.472365+00:00 app[web.1]:     at require (module.js:384:17)
2015-10-04T14:30:09.472367+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/node-sass-middleware/middleware.js:1:74)
2015-10-04T14:30:09.472368+00:00 app[web.1]:     at Module._compile (module.js:434:26)
2015-10-04T14:30:09.472370+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:452:10)
2015-10-04T14:30:09.472371+00:00 app[web.1]:     at Module.load (module.js:355:32)
2015-10-04T14:30:09.472373+00:00 app[web.1]:     at Function.Module._load (module.js:310:12)
2015-10-04T14:30:09.472374+00:00 app[web.1]:     at Module.require (module.js:365:17)
2015-10-04T14:30:09.472375+00:00 app[web.1]:     at require (module.js:384:17)
2015-10-04T14:30:09.472377+00:00 app[web.1]:     at mount (/app/node_modules/keystone/lib/core/mount.js:306:21)
2015-10-04T14:30:09.472378+00:00 app[web.1]:     at start (/app/node_modules/keystone/lib/core/start.js:239:7)
2015-10-04T14:30:09.472379+00:00 app[web.1]:     at Object.<anonymous> (/app/keystone.js:105:10)
2015-10-04T14:30:09.472381+00:00 app[web.1]:     at Module._compile (module.js:434:26)
2015-10-04T14:30:09.472382+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:452:10)
2015-10-04T14:30:09.472383+00:00 app[web.1]:     at Module.load (module.js:355:32)
2015-10-04T14:30:09.472384+00:00 app[web.1]:     at Function.Module._load (module.js:310:12)
2015-10-04T14:30:10.920575+00:00 heroku[web.1]: State changed from starting to crashed
</pre>

Also, at the moment, the keystonejs demo is down. I'm wondering if it might be the same issue?

**Comment by morenoh149** [comment]
What version of node is running on the heroku app? recent versions of node will require a later version of  `node-sass`. The generator was recently updated https://github.com/keystonejs/generator-keystone/commit/c74a13c6898558635083ff9b64b2a8baef1bb926 so make sure you're using the latest version of it.

**Comment by waltonryan** [comment]
Hey, thanks. Yeah, I believe I have been using this latest version. I was able to fix the issue by upgrading <code>node-sass-middleware</code> to the latest version. 
<pre>
  "dependencies": {
   ...
    "gulp-sass": "^2.0.4",
   ...
    "node-sass": "^3.3.3",
    "node-sass-middleware": "^0.9.6",
    ...
  },
...
  },
  "engines": {
    "node": ">=0.10.22",
    "npm": ">=1.3.14"
  },
</pre>

**Comment by jessaimaya** [comment]
Thank you @waltonryan !!!  "node-sass-middleware": "^0.9.6" +1

**Comment by morenoh149** [comment]
should be node-sass-middleware 0.9.7 or above https://github.com/keystonejs/generator-keystone/blob/master/app/templates/_package.json#L17 closing
