### ISSUE TITLE
Unknown keystone list "login"

### ISSUE THREAD

**Issue by steveellis** [keystonejs/keystone#1740]
I'm getting this immediately after submitting the login form. I'm able to navigate to my pages list and the app otherwise functions as expected (the user is authenticated). I'm sure its just some configuration problem, but I'm not sure what to try. Thanks!

I'm running 0.3.14.

POST /keystone/signin?from=/keystone/login 302 3955.846 ms
Error thrown for request: /keystone/login
ReferenceError: Unknown keystone list "login"
    at list (D:\home\site\wwwroot\node_modules\keystone\lib\core\list.js:12:18)
    at D:\home\site\wwwroot\node_modules\keystone\lib\core\routes.js:55:24
    at Layer.handle [as handle_request] (D:\home\site\wwwroot\node_modules\express\lib\router\layer.
js:95:5)
    at next (D:\home\site\wwwroot\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (D:\home\site\wwwroot\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\home\site\wwwroot\node_modules\express\lib\router\layer.
js:95:5)
    at D:\home\site\wwwroot\node_modules\express\lib\router\index.js:277:22
    at param (D:\home\site\wwwroot\node_modules\express\lib\router\index.js:349:14)
    at param (D:\home\site\wwwroot\node_modules\express\lib\router\index.js:365:14)
    at param (D:\home\site\wwwroot\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (D:\home\site\wwwroot\node_modules\express\lib\router\index.js:410:3)

    at next (D:\home\site\wwwroot\node_modules\express\lib\router\index.js:271:10)
    at next (D:\home\site\wwwroot\node_modules\express\lib\router\route.js:121:14)
    at next (D:\home\site\wwwroot\node_modules\express\lib\router\route.js:125:14)
    at next (D:\home\site\wwwroot\node_modules\express\lib\router\route.js:125:14)
    at next (D:\home\site\wwwroot\node_modules\express\lib\router\route.js:125:14)
    at next (D:\home\site\wwwroot\node_modules\express\lib\router\route.js:125:14)
    at next (D:\home\site\wwwroot\node_modules\express\lib\router\route.js:125:14)
    at next (D:\home\site\wwwroot\node_modules\express\lib\router\route.js:125:14)
    at next (D:\home\site\wwwroot\node_modules\express\lib\router\route.js:125:14)
    at next (D:\home\site\wwwroot\node_modules\express\lib\router\route.js:125:14)
    at next (D:\home\site\wwwroot\node_modules\express\lib\router\route.js:125:14)
GET /keystone/login 500 67.765 ms

**Comment by creynders** [comment]
It's thrown because the signin is trying to redirect you to a URL `/keystone/login` which is the URL you tried before, or have set as redirect page in your keystone settings.

**Comment by morenoh149** [comment]
closing as stale
