### ISSUE TITLE
Upgrade (or remove) Mocha 

### ISSUE THREAD

**Issue by MadeByMike** [keystonejs/keystone#1791]
# Bug report

## Describe the bug

Most of our tests use Jest but we need mocha for Cypress. We want to upgrade to the latest version of Mocha but in the last attempt we found Mocha `6.0.2` had issues. This might be because of incompatibility with our cypress version or it might be bugs in our code. 

## Additional context

Cypress already includes Mocha: https://github.com/cypress-io/cypress/blob/develop/package.json#L137 so we might not need it at all! We do have some custom reporters but it's worth checking it everything works without it.

If that doesn't work Cypress has been updated since this was last checked so the next step would be to attempt to upgrade.

Failing that there may be bugs with our test.

**Comment by MadeByMike** [comment]
@timleslie also mentioned some warning in CI that are related to our test config. This may yield more info.

**Comment by singhArmani** [comment]
@MadeByMike: I was able to reproduce this bug by upgrading the mocha version to the latest (which is 7.0.1 at the time of testing). 

And then running `yarn cypress:run` from the workspace root throws the following error: 

```
TypeError: Cannot read property 'passes' of undefined
    at Dot.Base.epilogue (<path>/node_modules/mocha/lib/reporters/base.js:349:30)
    at Runner.<anonymous> (<path>/node_modules/mocha/lib/reporters/dot.js:72:10)
    at Object.onceWrapper (events.js:282:20)
    at Runner.emit (events.js:199:15)
    at Reporter.emit (<path>/Library/Caches/Cypress/3.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/reporter.js:237:55)
    at Object.server.startWebsockets.onMocha (<path>/Library/Caches/Cypress/3.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/project.js:304:22)
    at Socket.<anonymous> (<path>/Library/Caches/Cypress/3.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/socket.js:236:36)
    at Socket.emit (events.js:194:13)
    at <path>Library/Caches/Cypress/3.5.0/Cypress.app/Contents/Resources/app/packages/socket/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:79:9)

TypeError: Cannot read property 'passes' of undefined
    at Dot.Base.epilogue (/<path>/node_modules/mocha/lib/reporters/base.js:349:30)
    at Runner.<anonymous> (/<path>/node_modules/mocha/lib/reporters/dot.js:72:10)
    at Object.onceWrapper (events.js:282:20)
    at Runner.emit (events.js:199:15)
    at Reporter.emit (<path>/Library/Caches/Cypress/3.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/reporter.js:237:55)
    at Object.server.startWebsockets.onMocha (<path>/Library/Caches/Cypress/3.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/project.js:304:22)
    at Socket.<anonymous> (<path>/Library/Caches/Cypress/3.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/socket.js:236:36)
    at Socket.emit (events.js:194:13)
    at <path>/Library/Caches/Cypress/3.5.0/Cypress.app/Contents/Resources/app/packages/socket/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:79:9)
```

After investigating further and following this [issue](https://github.com/cypress-io/cypress/issues/3756), it appears removing [mocha-multi-reporters](https://www.npmjs.com/package/mocha-multi-reporters) from the project, and adding [cypress-multi-reporters](https://www.npmjs.com/package/cypress-multi-reporters) seems to fix the aforementioned issue. 

Consequently, I shall be creating a PR soon to upgrade mocha to latest and replace `mocha-multi-reporters` with `cypress-multi-reporters`. Apparently, both of these packages are doing the same job.
