### ISSUE TITLE
TypeError: res.apiError is not a function

### ISSUE THREAD

**Issue by sgireddy** [keystonejs/keystone#1813]
I have been using keystone api for more than a year, has being using this function for a long time. Not sure what changed but res.apiError has been failing lately.

return res.apiError('Can not validate PIN.');

TypeError: res.apiError is not a function
    at Promise.<anonymous> (D:\iBS\routes\api\profile.js:77:24)
    at Promise.<anonymous> (D:\iBS\node_modules\keystone\node_modules\mongoose\n
ode_modules\mpromise\lib\promise.js:177:8)
    at emitOne (events.js:77:13)
    at Promise.emit (events.js:169:7)
    at Promise.emit (D:\iBS\node_modules\keystone\node_modules\mongoose\node_mod
ules\mpromise\lib\promise.js:84:38)
    at Promise.fulfill (D:\iBS\node_modules\keystone\node_modules\mongoose\node_
modules\mpromise\lib\promise.js:97:20)
    at Promise.resolve (D:\iBS\node_modules\keystone\node_modules\mongoose\lib\p
romise.js:114:23)
    at Promise.<anonymous> (D:\iBS\node_modules\keystone\node_modules\mongoose\n
ode_modules\mpromise\lib\promise.js:177:8)
    at emitOne (events.js:77:13)
    at Promise.emit (events.js:169:7)
    at Promise.emit (D:\iBS\node_modules\keystone\node_modules\mongoose\node_mod
ules\mpromise\lib\promise.js:84:38)
    at Promise.fulfill (D:\iBS\node_modules\keystone\node_modules\mongoose\node_
modules\mpromise\lib\promise.js:97:20)
    at Immediate.cb (D:\iBS\node_modules\keystone\node_modules\mongoose\lib\quer
y.js:1153:30)
    at Immediate._onImmediate (D:\iBS\node_modules\mquery\lib\utils.js:137:16)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
Press any key to continue...

**Comment by sgireddy** [comment]
My bad, my route was missing keystone.middleware.api.
