### ISSUE TITLE
node-sass crash on 'node keystone', Node v5.0.0

### ISSUE THREAD

**Issue by SerbanC** [keystonejs/keystone#1824]
Hi,

I'm trying to run Keystone but after running the generator I get this error:
```
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
/Users/serbancarjan/Workspace/Personal/testcms-keystone/node_modules/keystone/lib/core/mount.js:327
				throw e;
				^

Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/Users/serbancarjan/Workspace/Personal/testcms-keystone/node_modules/node-sass-middleware/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/Users/serbancarjan/Workspace/Personal/testcms-keystone/node_modules/node-sass-middleware/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/serbancarjan/Workspace/Personal/testcms-keystone/node_modules/node-sass-middleware/middleware.js:1:74)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at mount (/Users/serbancarjan/Workspace/Personal/testcms-keystone/node_modules/keystone/lib/core/mount.js:317:21)
    at start (/Users/serbancarjan/Workspace/Personal/testcms-keystone/node_modules/keystone/lib/core/start.js:239:7)
    at Object.<anonymous> (/Users/serbancarjan/Workspace/Personal/testcms-keystone/keystone.js:99:10)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
```

I noticed there is a closed issue about this same error on Node v4 at #1707 but the recommended fixes there don't seem to be working for me: I installed node-sass@3.4.2 (I didn't have it installed) both globally and in the project and I still get the same error.

**Comment by jonathanp** [comment]
Does `npm rebuild node-sass` fix your problem?

**Comment by SerbanC** [comment]
Still failing with `npm requild node-sass`. This is the output:
```
> node-sass@3.4.2 install /Users/serbancarjan/Workspace/Personal/test-keystone/node_modules/node-sass
> node scripts/install.js


> node-sass@3.4.2 postinstall /Users/serbancarjan/Workspace/Personal/test-keystone/node_modules/node-sass
> node scripts/build.js

` /Users/serbancarjan/Workspace/Personal/test-keystone/node_modules/node-sass/vendor/darwin-x64-47/binding.node ` exists.
 testing binary.
Binary is fine; exiting.

> node-sass@2.1.1 install /Users/serbancarjan/Workspace/Personal/test-keystone/node_modules/node-sass-middleware/node_modules/node-sass
> node scripts/install.js


> node-sass@2.1.1 postinstall /Users/serbancarjan/Workspace/Personal/test-keystone/node_modules/node-sass-middleware/node_modules/node-sass
> node scripts/build.js

module.js:339
    throw err;
    ^

Error: Cannot find module '/Users/serbancarjan/Workspace/Personal/test-keystone/node_modules/node-sass-middleware/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
Build failed
node-sass@3.4.2 /Users/serbancarjan/Workspace/Personal/test-keystone/node_modules/node-sass
node-sass@2.1.1 /Users/serbancarjan/Workspace/Personal/test-keystone/node_modules/node-sass-middleware/node_modules/node-sass
```

Here are other warnings/errors from during the install/setup process:

* `Unmet peer dependency` for yo@>=1.0.0 after installing the generator, although I already have Yo@latest, this is my global npm list:

  ```
npm WARN EPEERINVALID generator-keystone@0.3.9 requires a peer of yo@>=1.0.0 but none was installed.
 serbancarjan@Serbans-iMac  ~/Workspace/Personal/test-keystone  npm list -g --depth=0
/usr/local/lib
├── bower@1.6.5
├── browser-sync@2.10.0
├── eslint@1.9.0
├── generator-keystone@0.3.9
├── grunt-cli@0.1.13
├── gulp-cli@0.3.0
├── less@2.5.3
├── npm@3.4.0
├── webpack@1.12.6
└── yo@1.5.0
  ```
* `yo keystone` throws these warnings after creating the file tree:

  ```
npm WARN deprecated pangyp@2.3.3: use node-gyp@3+ instead
npm WARN prefer global coffee-script@1.10.0 should be installed with -g
npm WARN prefer global marked@0.3.5 should be installed with -g
npm WARN prefer global jshint@2.8.0 should be installed with -g
npm WARN prefer global pangyp@2.3.3 should be installed with -g
npm WARN prefer global node-gyp@3.1.0 should be installed with -g
  ```
* a failed build at the end of `yo keystone`:

  ```
> spawn-sync@1.0.14 postinstall /Users/serbancarjan/Workspace/Personal/test-keystone/node_modules/spawn-sync
> node postinstall


> node-sass@2.1.1 postinstall /Users/serbancarjan/Workspace/Personal/test-keystone/node_modules/node-sass-middleware/node_modules/node-sass
> node scripts/build.js

module.js:339
    throw err;
    ^

Error: Cannot find module '/Users/serbancarjan/Workspace/Personal/test-keystone/node_modules/node-sass-middleware/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
Build failed

> node-sass@3.4.2 postinstall /Users/serbancarjan/Workspace/Personal/test-keystone/node_modules/node-sass
> node scripts/build.js

` /Users/serbancarjan/Workspace/Personal/test-keystone/node_modules/node-sass/vendor/darwin-x64-47/binding.node ` exists.
 testing binary.
Binary is fine; exiting.
```
* When first running `node keystone`, I got:
  ```
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
module.js:339
    throw err;
    ^

Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/serbancarjan/Workspace/Personal/test-keystone/routes/views/blog.js:2:13)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /Users/serbancarjan/Workspace/Personal/test-keystone/node_modules/keystone/lib/core/importer.js:42:23
    at Array.forEach (native)
    at importer (/Users/serbancarjan/Workspace/Personal/test-keystone/node_modules/keystone/lib/core/importer.js:32:26)
    at Object.<anonymous> (/Users/serbancarjan/Workspace/Personal/test-keystone/routes/index.js:31:9)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/serbancarjan/Workspace/Personal/test-keystone/keystone.js:47:24)
  ```

  So running `npm list --depth=0` showed:

  ```
testing-the-keystone@0.0.0 /Users/serbancarjan/Workspace/Personal/test-keystone
├── UNMET DEPENDENCY async@^1.4.2
├── dotenv@1.2.0
├── gulp@3.9.0
├── gulp-jshint@1.12.0
├── gulp-sass@2.1.0
├── gulp-shell@0.4.3
├── gulp-watch@0.6.10
├── jshint-stylish@0.1.5
├── keystone@0.3.15
├── node-sass@3.4.2
├── node-sass-middleware@0.5.0
└── underscore@1.8.3
  ```

  I ran `npm install` and it installed `async` this time, after which `node keystone` crashes with the `node-sass` error mentioned originally.

My environment is Node 5.0.0 / NPM 3.4.0 / OSX El Capitan

**Comment by hamishtaplin** [comment]
Exact same problem here, trying to install Keystone a Scotchbox VM.

**Comment by nodkrot** [comment]
Tried installing with yo on node 4.2.2, similar issue with 
`Error: `libsass` bindings not found. Try reinstalling `node-sass`?`

**Comment by mhoffmeyerDC** [comment]
Same issue on OSX yosemite. Saw the error is actually coming from trying to load [node-sass-middleware](https://github.com/sass/node-sass-middleware). Fixed by upgrading:
`npm i node-sass-middleware@0.9.7 --save --no-shrinkwrap`

**Comment by rafaelfernandesnet** [comment]
After I upgraded my nodeJs, I started to get this error.
1. Removed the node_modules folder
2. ```npm install```

> I also was missing to install globally ember_cli for my specific project.

**Comment by nodkrot** [comment]
Is this going to be fixed? or we have to wait until 0.4.0 release?

**Comment by creynders** [comment]
@nodkrot It's a bit hard to discern what exactly and if anything at all goes wrong on our side, after npm _totally_ broke with v3.x
I re-installed npm v2.10.1 and haven't encountered any "module not found"/ENOENT errors anymore. Hope they get their shit together soon.

**Comment by charleslouis** [comment]
I encouter the same issue. Not only with keaystone, but also in some other projects where libsass is involved. For now, as I use NVM, I can `nvm use 0.10` which might not be the best, but works as a temp fix.

**Comment by knotech** [comment]
@mhoffmeyerDC solution worked me on OSX Yosemite with
`node v5.0.0`
`npm v3.3.6`

**Comment by morenoh149** [comment]
If the solution is installing node-sass-middleware 0.9.7 then merging https://github.com/keystonejs/generator-keystone/pull/141 should fix this. Someone please verify that it works.

**Comment by LasTanzen** [comment]
Can confirm `npm i node-sass-middleware@0.9.7 --save --no-shrinkwrap` works on OSX El Capitan
`node v5.0.0` & `npm v3.3.6`
