### ISSUE TITLE
[0.4] Test project not working

### ISSUE THREAD

**Issue by celiao** [keystonejs/keystone#1847]
From Issue #1612:
**Complete Getting Started Guide**
```
git clone https://github.com/keystonejs/keystone.git
cd keystone
npm link
cd ..
git clone https://github.com/keystonejs/keystone-test-project.git
cd keystone-test-project
npm install
npm link keystone
KEYSTONE_DEV=true npm start
```
Results in:
```
> keystone-test@1.0.0 start /Users/Celia/node/keystone-test-project
> node keystone.js

/Users/me/node/keystone-test-project/keystone.js:11
	onMount () { console.log('Application Mounted'); },
	        ^
SyntaxError: Unexpected token (
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! keystone-test@1.0.0 start: `node keystone.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keystone-test@1.0.0 start script 'node keystone.js'.
npm ERR! This is most likely a problem with the keystone-test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node keystone.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls keystone-test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Celia/node/keystone-test-project/npm-debug.log
```

**Comment by creynders** [comment]
You have to run it with node>= v4 and the `--harmony` flag

**Comment by creynders** [comment]
Closing this, since it's answered and in the wrong repo. If you have any more questions/troubles let us know @celiao !

**Comment by JedWatson** [comment]
For reference here, `--harmony` isn't needed, just Node.js `>=4.0.0`
