### ISSUE TITLE
Quick Start won't Start

### ISSUE THREAD

**Issue by cawoodm** [keystonejs/keystone#1863]
Just ran `npm init keystone-app my-app` (Windows, Node 12) and it happily created a project. I chose MongoDB (mongoose). There were no errors but the resulting project will not run - which is not surprising since it has no idea where my DB server is and never asked. So it eventually crashes:

```
√ Validated project entry file ./index.js
√ Keystone server listening on port 3000
√ Initialised Keystone instance
× Connecting to database
Error: Server selection timed out after 30000 ms
    at D:\services\keystone\my-app\node_modules\@keystonejs\utils\dist\utils.cjs.dev.js:56:21
    at async executeDefaultServer (D:\services\keystone\my-app\node_modules\@keystonejs\keystone\bin\utils.js:109:3) {
  errors: {
    MongooseAdapter: MongoTimeoutError: Server selection timed out after 30000 ms
        at Timeout.<anonymous> (D:\services\keystone\my-app\node_modules\mongodb\lib\core\sdam\topology.js:878:9)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      name: 'MongoTimeoutError',
      reason: [MongoNetworkError],
      [Symbol(mongoErrorContextSymbol)]: {}
    }
  }
}
```

I can find no configuration file so what's a boy to do??

**Comment by cawoodm** [comment]
OK, some googling revealed the secret:
```
set MONGO_URI=mongodb://mydbserver
```
Use `export` instead of `set` for Linux/MacOS.

**Comment by stunjiturner** [comment]
@cawoodm I just ran export MONGO_URI=mongodb://localhost:27017 at the command line on  Mac, i still get the Timed out error
