### ISSUE TITLE
Cannot run blog demo on Windows

### ISSUE THREAD

**Issue by Vultraz** [keystonejs/keystone#1886]
# Bug report

## Describe the bug

When running `yarn demo blog dev`, this happens:

```sh
C:\Users\exodi\Documents\keystone-5>yarn demo blog dev
yarn run v1.19.1
$ yarn --cwd ./demo-projects blog dev
$ yarn --cwd blog dev
$ cross-env NODE_ENV=development DISABLE_LOGGING=true node -r dotenv-safe/config `yarn bin`/keystone dev
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'C:\Users\exodi\Documents\keystone-5\demo-projects\blog\`yarn'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Presumably this is because the backtick command insertion ( ``` `yarn bin`/keystone dev```) doesn't work in cmd.exe (which I'm using). ☹️ 

Even if I replace it with the proper path manually, this still happens:
```sh
C:\Users\exodi\Documents\keystone-5>yarn demo blog dev
yarn run v1.19.1
$ yarn --cwd ./demo-projects blog dev
$ yarn --cwd blog dev
$ cross-env NODE_ENV=development DISABLE_LOGGING=true node -r dotenv-safe/config ../../node_modules/.bin/keystone dev
C:\Users\exodi\Documents\keystone-5\node_modules\.bin\keystone:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
```

## System information

- OS: Windows 10 1903

**Comment by jualoppaz** [comment]
I gets the same error in Microsoft Windows [Version 10.0.18362.356]

**Comment by gautamsi** [comment]
after #1892 keystone in general works on windows now. #1917 fixes this startup issue
