### ISSUE TITLE
keystone api (not admin api) not accessible anymore in V4

### ISSUE THREAD

**Issue by sgireddy** [keystonejs/keystone#2042]
wanted to convert the demo app to support custom api. I borrowed some code from working version of keystone 3.

Added following routes to index.js
```js
app.all('/api*', keystone.middleware.api);
app.post('/api/login', [keystone.middleware.api, keystone.middleware.cors], routes.api.members.login);
app.post('/api/signup', [keystone.middleware.api, keystone.middleware.cors], routes.api.members.signup);
```

added middleware.js for few additional tasks but I don't think I am reaching there yet (didn't even login or sign up yet)

Here is what I got:

```sh
OPTIONS /api/signup 500 2.557 ms
Error thrown for request: /api/signup
TypeError: Cannot read property 'length' of undefined
    at async.eachSeries.asyncFinished (/Users/reactivedev/code/keystone/node_modules/grappling-hook/index.js:226:19)
    at async.eachSeries.iterate (/Users/reactivedev/code/keystone/node_modules/grappling-hook/node_modules/async/lib/async.js:146:13)
    at Object.async.eachSeries (/Users/reactivedev/code/keystone/node_modules/grappling-hook/node_modules/async/lib/async.js:162:9)
    at iterateAsyncMiddleware (/Users/reactivedev/code/keystone/node_modules/grappling-hook/index.js:225:8)
    at /Users/reactivedev/code/keystone/node_modules/grappling-hook/index.js:585:5
    at dezalgofy (/Users/reactivedev/code/keystone/node_modules/grappling-hook/index.js:192:2)
    at methods.callHook (/Users/reactivedev/code/keystone/node_modules/grappling-hook/index.js:584:4)
    at /Users/reactivedev/code/keystone/server/createApp.js:87:12
    at Layer.handle [as handle_request] (/Users/reactivedev/code/keystone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/reactivedev/code/keystone/node_modules/express/lib/router/index.js:312:13)
    at /Users/reactivedev/code/keystone/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/reactivedev/code/keystone/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/reactivedev/code/keystone/node_modules/express/lib/router/index.js:271:10)
    at frameGuard (/Users/reactivedev/code/keystone/lib/security/frameGuard.js:20:3)
    at Layer.handle [as handle_request] (/Users/reactivedev/code/keystone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/reactivedev/code/keystone/node_modules/express/lib/router/index.js:312:13)
    at /Users/reactivedev/code/keystone/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/reactivedev/code/keystone/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/reactivedev/code/keystone/node_modules/express/lib/router/index.js:271:10)
    at methodOverride (/Users/reactivedev/code/keystone/node_modules/method-override/index.js:65:14)
    at Layer.handle [as handle_request] (/Users/reactivedev/code/keystone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/reactivedev/code/keystone/node_modules/express/lib/router/index.js:312:13)
    at /Users/reactivedev/code/keystone/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/reactivedev/code/keystone/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/reactivedev/code/keystone/node_modules/express/lib/router/index.js:271:10)
    at module.exports (/Users/reactivedev/code/keystone/node_modules/multer/index.js:218:19)
    at Layer.handle [as handle_request] (/Users/reactivedev/code/keystone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/reactivedev/code/keystone/node_modules/express/lib/router/index.js:312:13)
OPTIONS /api/signup 500 21772.449 ms
```
Looks like the following function is the culprit:

```js
Layer.prototype.handle_request = function handle(req, res, next) {
  var fn = this.handle;
  if (fn.length > 3) {
    // not a standard request handler
    return next();
  }
  try {
    fn(req, res, next);
  } catch (err) {
    next(err);
  }
};
```

Really appreciate any help, thanks in advance.

**Comment by dscdac** [comment]
Check if you have moved the ```app.use(...)``` calls to the correct place:
https://github.com/strongloop/express/wiki/Migrating-from-3.x-to-4.x#approuter

**Comment by mxstbr** [comment]
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!
