### ISSUE TITLE
Figure out why the build / tests are failing with 0.12

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#2151]
In the past, build tests have been intermittently failing on 0.12 (possibly due to timeouts) and recently they have been failing 100% of the time.

We still want to target node 0.12 if it's feasible but I'm disabling the tests for that version until this can be resolved, hopefully before the final release of keystone 0.4 - let's fix it locally then re-enable the 0.12 tests, rather than having every commit & PR fail.

If anyone has a chance to dig into this, I'd appreciate it.

**Comment by erg0dic** [comment]
There are five failures:
```
  1) Test dependsOn and required Ignore required if evalDependsOn is not `true` by setting `state` to `draft`:
     Uncaught TypeError: undefined is not a function
      at new ExMatch (node_modules/expression-match/ExMatch.js:68:26)
      at new module.exports (node_modules/expression-match/ExMatch.js:24:9)
      at evalDependsOn (fields/utils/evalDependsOn.js:12:14)
      at model.Field.options.required (fields/types/Type.js:73:41)
      at model.requiredValidator (node_modules/mongoose/lib/schematype.js:531:59)
      at node_modules/mongoose/lib/schematype.js:709:28
      at Array.forEach (native)
      at SchemaDate.SchemaType.doValidate (node_modules/mongoose/lib/schematype.js:683:19)
      at node_modules/mongoose/lib/document.js:1194:9

  2) Test dependsOn and required Save will fail if `state` set to `published` and `publishedDate` is not defined:
     Uncaught TypeError: undefined is not a function
      at new ExMatch (node_modules/expression-match/ExMatch.js:68:26)
      at new module.exports (node_modules/expression-match/ExMatch.js:24:9)
      at evalDependsOn (fields/utils/evalDependsOn.js:12:14)
      at model.Field.options.required (fields/types/Type.js:73:41)
      at model.requiredValidator (node_modules/mongoose/lib/schematype.js:531:59)
      at node_modules/mongoose/lib/schematype.js:709:28
      at Array.forEach (native)
      at SchemaDate.SchemaType.doValidate (node_modules/mongoose/lib/schematype.js:683:19)
      at node_modules/mongoose/lib/document.js:1194:9

  3) Test dependsOn and required Save will succeed if `state` set to `published` and `publishedDate` is defined:
     Uncaught TypeError: undefined is not a function
      at new ExMatch (node_modules/expression-match/ExMatch.js:68:26)
      at new module.exports (node_modules/expression-match/ExMatch.js:24:9)
      at evalDependsOn (fields/utils/evalDependsOn.js:12:14)
      at model.Field.options.required (fields/types/Type.js:73:41)
      at model.requiredValidator (node_modules/mongoose/lib/schematype.js:531:59)
      at node_modules/mongoose/lib/schematype.js:709:28
      at Array.forEach (native)
      at SchemaDate.SchemaType.doValidate (node_modules/mongoose/lib/schematype.js:683:19)
      at node_modules/mongoose/lib/document.js:1194:9

  4) When paginating results without an optional expression should return results plus pagination metadata:
     Uncaught TypeError: undefined is not a function
      at test/lib/list/pagination.js:83:13
      at lib/list/paginate.js:79:5
      at Query.<anonymous> (node_modules/mongoose/lib/query.js:2149:28)
      at node_modules/mongoose/node_modules/kareem/index.js:177:19
      at node_modules/mongoose/node_modules/kareem/index.js:109:16

  5) When paginating results with an optional expression should return results plus query metadata and pagination metadata:
     Uncaught TypeError: undefined is not a function
      at test/lib/list/pagination.js:155:13
      at lib/list/paginate.js:79:5
      at Query.<anonymous> (node_modules/mongoose/lib/query.js:2149:28)
      at node_modules/mongoose/node_modules/kareem/index.js:177:19
      at node_modules/mongoose/node_modules/kareem/index.js:109:16
```

The first three are because Object.assign is not polyfilled in expression-match. I have created an issue there.

The last two are because the assert module in 0.12.9 does not define deepStrictEqual:
https://nodejs.org/docs/v0.12.9/api/assert.html

This will either need to be polyfilled or abandoned.

**Comment by erg0dic** [comment]
We can use this module to polyfill:
https://github.com/sindresorhus/core-assert

PR shortly

**Comment by JedWatson** [comment]
Brilliant, thanks @erg0dic! Merging those PRs and updating now :)

**Comment by mxstbr** [comment]
This is highly likely fixed, so I'll close this issue.
