### ISSUE TITLE
[0.3] BUG: fails bootstrap with `npm install --production` due to missing 'browserify'

### ISSUE THREAD

**Issue by creynders** [keystonejs/keystone#2163]
See subject. This is the output:

```sh
staging-30 Error: Cannot find module 'browserify'
staging-30     at Function.Module._resolveFilename (module.js:337:15)
staging-30     at Function.Module._load (module.js:287:25)
staging-30     at Module.require (module.js:366:17)
staging-30     at require (module.js:385:17)
staging-30     at Object.<anonymous> (/home/dpac/staging/cms/node_modules/keystone/admin/app/browserify.js:2:18)
staging-30     at Module._compile (module.js:435:26)
staging-30     at Object.Module._extensions..js (module.js:442:10)
staging-30     at Module.load (module.js:356:32)
staging-30     at Function.Module._load (module.js:311:12)
staging-30     at Module.require (module.js:366:17)
staging-30     at require (module.js:385:17)
staging-30     at Object.<anonymous> (/home/dpac/staging/cms/node_modules/keystone/admin/app/static.js:9:18)
staging-30     at Module._compile (module.js:435:26)
staging-30     at Object.Module._extensions..js (module.js:442:10)
staging-30     at Module.load (module.js:356:32)
staging-30     at Function.Module._load (module.js:311:12)
```

Should browserify be listed under keystone's 'dependencies' instead of 'devDependencies'?

**Comment by morenoh149** [comment]
yes I think so. Doesn't the adminUI dynamically generate the js bundle? to avoid delivering large deps like codemirror for users that use fieldtypes that don't need that.

**Comment by mxstbr** [comment]
I think this is fixed, let me know if this is still affecting you!
