### ISSUE TITLE
[0.4] eslint fails

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#2213]
See error below...but doing `npm install eslint-config-standard --save-dev` fixes it.  Is that package supposed to be installed?

ERROR:
```
> keystone@0.4.0-alpha lint C:\Users\Carlos\git\prs\keystonejs\keystone
> eslint .

C:\Users\Carlos\git\prs\keystonejs\keystone\node_modules\eslint\lib\config\config-file.js:332
            throw e;
            ^

Error: Cannot read config package: eslint-config-standard
Error: Cannot find module 'eslint-config-standard'
Referenced from: C:\Users\Carlos\git\prs\keystonejs\keystone\node_modulesX\browserify\node_modules\crypto-browserify\node_modules\browserify-cipher\node_m                                            odules\browserify-aes\node_modules\cipher-base\.eslintrc
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at loadPackage (C:\Users\Carlos\git\prs\keystonejs\keystone\node_modules\eslint\lib\config\config-file.js:168:16)
    at loadConfigFile (C:\Users\Carlos\git\prs\keystonejs\keystone\node_modules\eslint\lib\config\config-file.js:212:18)
    at load (C:\Users\Carlos\git\prs\keystonejs\keystone\node_modules\eslint\lib\config\config-file.js:385:18)
    at C:\Users\Carlos\git\prs\keystonejs\keystone\node_modules\eslint\lib\config\config-file.js:326:36
    at Array.reduceRight (native)
    at applyExtends (C:\Users\Carlos\git\prs\keystonejs\keystone\node_modules\eslint\lib\config\config-file.js:309:28)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\avp\\nodejs\\node.exe" "C:\\avp\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "lint"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! keystone@0.4.0-alpha lint: `eslint .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keystone@0.4.0-alpha lint script 'eslint .'.
npm ERR! This is most likely a problem with the keystone package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint .
npm ERR! You can get their info via:
npm ERR!     npm owner ls keystone
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Carlos\git\prs\keystonejs\keystone\npm-debug.log
```

OS:  Windows 10

**Comment by JedWatson** [comment]
@webteckie we're not using the `standard` eslint config... you're hitting this issue because your node modules are in a `node_modulesX` directory, which eslint is **not** ignoring, and then it's trying to use the `standard` preset because the `crypto-browserify` package uses it.

(typical @dcousens :P)

If you get rid of `node_modulesX` it should lint Keystone just fine.

**Comment by webteckie** [comment]
Hmm...yes, I had a temporary backup node_modulesX directory but I removed it and I think I tried again and got the same issue.  Will confirm though and get back.

**Comment by dcousens** [comment]
:smiley: mean while,  I'm think I might perform a covert operation into your office @JedWatson and plant a few of these: https://github.com/feross/standard/issues/398#issuecomment-178956045

**Comment by JedWatson** [comment]
@dcousens **yes please**

**Comment by webteckie** [comment]
@JedWatson my bad...that was the issue...will never do that again :-)
