### ISSUE TITLE
When I try to run meetup up demo project I get cloudinary error

### ISSUE THREAD

**Issue by arrrrny** [keystonejs/keystone#2254]
When I run yarn demo meetup dev I get below error:

/Users/arrrrny/Developer/keystone-5/packages/file-adapters/lib/cloudinary.js:19
      throw new Error('CloudinaryAdapter requires cloudName, apiKey, and apiSecret');
            ^
Error: CloudinaryAdapter requires cloudName, apiKey, and apiSecret
    at new CloudinaryAdapter (/Users/arrrrny/Developer/keystone-5/packages/file-adapters/lib/cloudinary.js:19:13)
    at Object.<anonymous> (/Users/arrrrny/Developer/keystone-5/demo-projects/meetup/schema.js:18:27)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/arrrrny/Developer/keystone-5/demo-projects/meetup/index.js:10:81)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

**Comment by gautamsi** [comment]
you have to have a cloudinary account and provide those variables in `.env` file. see `.env.example` for how to provide them

**Comment by arrrrny** [comment]
@gautamsi I added the cloudinary account and project launched. But now when I create a sponsor and upload a file I get below error:

(node:13275) [DEP0135] DeprecationWarning: ReadStream.prototype.open() is deprecated
RangeError: Maximum call stack size exceeded
    at ReadStream.deprecated [as open] (internal/util.js:74:22)
    at ReadStream.open (/Users/arrrrny/Developer/keystone-5/node_modules/fs-capacitor/lib/index.js:90:11)
    at _openReadFs (internal/fs/streams.js:154:12)
    at ReadStream.<anonymous> (internal/fs/streams.js:147:3)
    at ReadStream.deprecated [as open] (internal/util.js:89:15)
    at ReadStream.open (/Users/arrrrny/Developer/keystone-5/node_modules/fs-capacitor/lib/index.js:90:11)
    at _openReadFs (internal/fs/streams.js:154:12)
    at ReadStream.<anonymous> (internal/fs/streams.js:147:3)
    at ReadStream.deprecated [as open] (internal/util.js:89:15)
    at ReadStream.open (/Users/arrrrny/Developer/keystone-5/node_modules/fs-capacitor/lib/index.js:90:11)
    at _openReadFs (internal/fs/streams.js:154:12)
    at ReadStream.<anonymous> (internal/fs/streams.js:147:3)
    at ReadStream.deprecated [as open] (internal/util.js:89:15)
    at ReadStream.open (/Users/arrrrny/Developer/keystone-5/node_modules/fs-capacitor/lib/index.js:90:11)
    at _openReadFs (internal/fs/streams.js:154:12)
    at ReadStream.<anonymous> (internal/fs/streams.js:147:3)
    at ReadStream.deprecated [as open] (internal/util.js:89:15)
    at ReadStream.open (/Users/arrrrny/Developer/keystone-5/node_modules/fs-capacitor/lib/index.js:90:11)
    at _openReadFs (internal/fs/streams.js:154:12)
    at ReadStream.<anonymous> (internal/fs/streams.js:147:3)
    at ReadStream.deprecated [as open] (internal/util.js:89:15)
    at ReadStream.open (/Users/arrrrny/Developer/keystone-5/node_modules/fs-capacitor/lib/index.js:90:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
