### ISSUE TITLE
Installation error: Cannot find module 'node_modules\@keystonejs\keystone\bin\cli.js'

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [keystonejs/keystone#2333]
- Windows 10
- **node** v13.7.0
-  **npm:** 6.13.7
-  **mongodb** v4.2.3

**I am new to Keystone  (Maybe I missing something).**

Step 1 (works fine):
`npm init keystone-app my-app`

![image](https://user-images.githubusercontent.com/16711871/73744594-c8845a80-4759-11ea-867d-a831b34405f6.png)

```
cd my-app
npm run dev
```

Step 2 (Throw error):
![image](https://user-images.githubusercontent.com/16711871/73745478-c8855a00-475b-11ea-99c8-4f010207c9fa.png)

```javascript
> @keystonejs/example-projects-blank@5.0.0 dev C:\Users\Siton\my-app
> cross-env NODE_ENV=development DISABLE_LOGGING=true keystone dev

internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'C:\Users\Siton\my-app\node_modules\@keystonejs\keystone\bin\cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @keystonejs/example-projects-blank@5.0.0 dev: `cross-env NODE_ENV=development DISABLE_LOGGING=true keystone dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @keystonejs/example-projects-blank@5.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Siton\AppData\Roaming\npm-cache\_logs\2020-02-04T12_35_16_800Z-debug.log
```

# complete log
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Users\\Siton\\AppData\\Roaming\\npm\\node_modules\\node\\bin\\node.exe',
1 verbose cli   'C:\\Users\\Siton\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.13.7
3 info using node@v13.7.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @keystonejs/example-projects-blank@5.0.0~predev: @keystonejs/example-projects-blank@5.0.0
6 info lifecycle @keystonejs/example-projects-blank@5.0.0~dev: @keystonejs/example-projects-blank@5.0.0
7 verbose lifecycle @keystonejs/example-projects-blank@5.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle @keystonejs/example-projects-blank@5.0.0~dev: PATH: C:\Users\Siton\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Siton\my-app\node_modules\.bin;C:\Users\Siton\AppData\Roaming\npm\node_modules\node\bin;C:\Users\Siton\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\Siton\AppData\Local\Microsoft\WindowsApps;C:\Users\Siton\AppData\Roaming\npm;C:\Users\Siton\AppData\Local\atom\bin;C:\Users\Siton\AppData\Local\GitHubDesktop\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\MongoDB\Server\4.2\bin;C:\Users\Siton\AppData\Local\Microsoft\WindowsApps;C:\Users\Siton\AppData\Local\atom\bin;C:\Users\Siton\AppData\Local\GitHubDesktop\bin;C:\Users\Siton\AppData\Local\Microsoft\WindowsApps;C:\Users\Siton\AppData\Roaming\npm;
9 verbose lifecycle @keystonejs/example-projects-blank@5.0.0~dev: CWD: C:\Users\Siton\my-app
10 silly lifecycle @keystonejs/example-projects-blank@5.0.0~dev: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'cross-env NODE_ENV=development DISABLE_LOGGING=true keystone dev'
10 silly lifecycle ]
11 silly lifecycle @keystonejs/example-projects-blank@5.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle @keystonejs/example-projects-blank@5.0.0~dev: Failed to exec dev script
13 verbose stack Error: @keystonejs/example-projects-blank@5.0.0 dev: `cross-env NODE_ENV=development DISABLE_LOGGING=true keystone dev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Siton\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:321:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Siton\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:321:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid @keystonejs/example-projects-blank@5.0.0
15 verbose cwd C:\Users\Siton\my-app
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Users\\Siton\\AppData\\Roaming\\npm\\node_modules\\node\\bin\\node.exe" "C:\\Users\\Siton\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v13.7.0
19 verbose npm  v6.13.7
20 error code ELIFECYCLE
21 error errno 1
22 error @keystonejs/example-projects-blank@5.0.0 dev: `cross-env NODE_ENV=development DISABLE_LOGGING=true keystone dev`
22 error Exit status 1
23 error Failed at the @keystonejs/example-projects-blank@5.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by MadeByMike** [comment]
Sorry about this! Can I get you to check that '@keystonjs/keystone' is in the project's dependencies?

**Comment by Ezra-Siton-UIX** [comment]
I run
`
npm i
`
And the problem solved. 
Anyway this idea missing in the docs (when you only run `npm init keystone-app my-app`)
