### ISSUE TITLE
createItems throws Error when using Lists Back References

### ISSUE THREAD

**Issue by bertez** [keystonejs/keystone#2360]
# Bug report

## Describe the bug

`keystone.createItems` works fine when adding items to lists with relationships when no [back references are enabled](https://www.keystonejs.com/guides/relationships#enabling-back-reference-between-users-and-todos) but crashes when they are defined.

## To Reproduce

When using lists with back references, p.ex.:

```js
const Tag = {
  fields: {
    title: { type: Text, isUnique: true, isRequired: true },
    posts: { type: Relationship, ref: 'Post.tags', many: true }
  }
};

const Post = {
  fields: {
    title: { type: Text, isRequired: true },
    tags: { type: Relationship, ref: 'Tag.posts', many: true },
  }
};
```

Adding items using `createItems`:

```js
keystone.createItems({
 Tag: [
    {
      title: 'media',
      slug: 'media',
      posts: [{ where: { title: 'This is a test post' } }] //it also crashes without this line
    }
  ],
  Post: [
    {
      title: 'This is a test post',
      tags: [{ where: { title: 'media' } }], //same as above
    }
  ]
});
```

I tried all the possible combinations but I always get an error like this:

```
app_1  | Error: Cannot read property 'adapter' of undefined
app_1  |     at /usr/src/app/node_modules/@keystonejs/utils/dist/utils.cjs.dev.js:57:21
app_1  |     at processTicksAndRejections (internal/process/task_queues.js:94:5)
app_1  |     at async Keystone.createItems (/usr/src/app/node_modules/@keystonejs/keystone/lib/Keystone/index.js:703:30)
app_1  |     at async Object.module.exports [as onConnect] (/usr/src/app/initialData.js:25:5)
app_1  |     at async executeDefaultServer (/usr/src/app/node_modules/@keystonejs/keystone/bin/utils.js:114:3) {
app_1  |   errors: {
app_1  |     Tag: Error: Cannot read property 'adapter' of undefined
app_1  |         at /usr/src/app/node_modules/@keystonejs/utils/dist/utils.cjs.dev.js:57:21
app_1  |         at processTicksAndRejections (internal/process/task_queues.js:94:5)
app_1  |         at async pReflect (/usr/src/app/node_modules/p-reflect/index.js:5:17)
app_1  |         at async Promise.all (index 0)
app_1  |         at async Keystone.createItems (/usr/src/app/node_modules/@keystonejs/keystone/lib/Keystone/index.js:703:30)
app_1  |         at async Object.module.exports [as onConnect] (/usr/src/app/initialData.js:25:5)
app_1  |         at async executeDefaultServer (/usr/src/app/node_modules/@keystonejs/keystone/bin/utils.js:114:3) {
app_1  |       errors: [Object]
app_1  |     },
app_1  |     Post: Error: Cannot read property 'adapter' of undefined
app_1  |         at /usr/src/app/node_modules/@keystonejs/utils/dist/utils.cjs.dev.js:57:21
app_1  |         at processTicksAndRejections (internal/process/task_queues.js:94:5)
app_1  |         at async pReflect (/usr/src/app/node_modules/p-reflect/index.js:5:17)
app_1  |         at async Promise.all (index 1)
app_1  |         at async Keystone.createItems (/usr/src/app/node_modules/@keystonejs/keystone/lib/Keystone/index.js:703:30)
app_1  |         at async Object.module.exports [as onConnect] (/usr/src/app/initialData.js:25:5)
app_1  |         at async executeDefaultServer (/usr/src/app/node_modules/@keystonejs/keystone/bin/utils.js:114:3) {
app_1  |       errors: [Object]
app_1  |     }
app_1  |   }
app_1  | }
```

## Expected behaviour

If everything I'm trying is correct it should work fine.

## System information

- OS: docker on macOS

Package versions:
```
    "@keystonejs/adapter-mongoose": "^5.1.5",
    "@keystonejs/app-admin-ui": "^5.7.2",
    "@keystonejs/app-graphql": "^5.0.3",
    "@keystonejs/app-next": "^5.0.2",
    "@keystonejs/app-static": "^5.0.0",
    "@keystonejs/auth-password": "^5.0.2",
    "@keystonejs/fields": "^6.2.2",
    "@keystonejs/fields-markdown": "^5.0.4",
    "@keystonejs/file-adapters": "^5.4.0",
    "@keystonejs/keystone": "^5.4.3",
```

**Comment by ralexrdz** [comment]
I'm using keystone v. 5.3.0 and still seeing this error happening. Was this issue fixed for this version o I should wait for next release?

**Comment by ralexrdz** [comment]
When [this pull](https://github.com/keystonejs/keystone/pull/2394) (5.6.0) gets aproved will be fixed, right? 

I'm testing on 5.5.0 and still happens
