### ISSUE TITLE
Unable to query File fields

### ISSUE THREAD

**Issue by LiamAttClarke** [keystonejs/keystone#2365]
# Bug report

Querying a file field using operators defined in the schema docs produces an "unknown operator" error. 

Furthermore the available operators for file fields don't allow you to query the fields of the stored json object such as  `id`, `filename`, 'publicUrl'. If we can retrieve those specific values we should also be able to query against them.

## To Reproduce

**Query:**
```
query {
  # interactiveSource - a file field
  allLayouts(where: {interactiveSource_contains: ""}) {
    interactiveSource {
      id
    }
}
```

**Error message:**
```
{
  "errors": [
    {
      "message": "select \"t0\".* from \"public\".\"Layout\" as \"t0\" where true and (\"t0\".\"interactiveSource\" ~ $1) - operator does not exist: jsonb ~ unknown",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "allLayouts"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "name": "error",
          "length": 200,
          "severity": "ERROR",
          "code": "42883",
          "hint": "No operator matches the given name and argument types. You might need to add explicit type casts.",
          "position": "87",
          "file": "parse_oper.c",
          "line": "731",
          "routine": "op_error",
          "stacktrace": [
            "error: operator does not exist: jsonb ~ unknown",
            "    at Connection.parseE (/Users/liam/projects/maps/venue-map-service/node_modules/pg/lib/connection.js:614:13)",
            "    at Connection.parseMessage (/Users/liam/projects/maps/venue-map-service/node_modules/pg/lib/connection.js:413:19)",
            "    at Socket.<anonymous> (/Users/liam/projects/maps/venue-map-service/node_modules/pg/lib/connection.js:129:22)",
            "    at Socket.emit (events.js:182:13)",
            "    at Socket.EventEmitter.emit (domain.js:442:20)",
            "    at addChunk (_stream_readable.js:283:12)",
            "    at readableAddChunk (_stream_readable.js:264:11)",
            "    at Socket.Readable.push (_stream_readable.js:219:10)",
            "    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)",
            "From previous event:",
            "    at Client_PG._query (/Users/liam/projects/maps/venue-map-service/node_modules/knex/lib/dialects/postgres/index.js:236:12)",
            "    at Client_PG.query (/Users/liam/projects/maps/venue-map-service/node_modules/knex/lib/client.js:168:17)",
            "    at Runner.query (/Users/liam/projects/maps/venue-map-service/node_modules/knex/lib/runner.js:133:36)",
            "    at /Users/liam/projects/maps/venue-map-service/node_modules/knex/lib/runner.js:39:23",
            "    at client.acquireConnection.catch.then (/Users/liam/projects/maps/venue-map-service/node_modules/knex/lib/runner.js:253:24)",
            "    at runCallback (timers.js:705:18)",
            "    at tryOnImmediate (timers.js:676:5)",
            "    at processImmediate (timers.js:658:5)",
            "    at process.topLevelDomainCallback (domain.js:121:23)",
            "From previous event:",
            "    at Runner.ensureConnection (/Users/liam/projects/maps/venue-map-service/node_modules/knex/lib/runner.js:251:8)",
            "    at Runner.run (/Users/liam/projects/maps/venue-map-service/node_modules/knex/lib/runner.js:25:12)",
            "    at Builder.Target.then (/Users/liam/projects/maps/venue-map-service/node_modules/knex/lib/interface.js:15:43)",
            "    at process._tickCallback (internal/process/next_tick.js:68:7)"
          ]
        }
      },
      "uid": "ck6mn661w0004k4ko7psp11i5",
      "name": "GraphQLError"
    }
  ],
  "data": {
    "allLayouts": null
  }
}
```

## Expected behaviour

Users should be able to write queries that are conditional on the subfields of the stored json file object (id, filename, originalFilename, publicUrl, encoding, mimetype, path).

## System information

- OS: macOS
- Database: Postgres

**Comment by Vultraz** [comment]
I was trying to reproduce this in the GraphiQL console with the TODO demo but I couldn't. Could you offer some more info?

**Comment by MadeByMike** [comment]
Closing this issue pending more info
