### ISSUE TITLE
ReferenceError: Unknown keystone list "js"

### ISSUE THREAD

**Issue by PoluosmakAndrew** [keystonejs/keystone#2370]
Page: /keystone/*
Problem only with Heroku. 
On local machine - working

Keystone Version: 0.3.16

Can you help me?

**Server console output:**
2016-03-04T19:09:29.301229+00:00 app[web.1]: GET /keystone/js/common/ui-sortable.js 404 5.687 ms
2016-03-04T19:09:29.374188+00:00 app[web.1]: Error thrown for request: /keystone/js/packages.js
2016-03-04T19:09:29.374860+00:00 app[web.1]: ReferenceError: Unknown keystone list "js"
2016-03-04T19:09:29.374869+00:00 app[web.1]:     at list (/app/node_modules/keystone/lib/core/list.js:12:18)
2016-03-04T19:09:29.374869+00:00 app[web.1]:     at /app/node_modules/keystone/lib/core/routes.js:55:24
2016-03-04T19:09:29.374870+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-03-04T19:09:29.374871+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:131:13)

**Browser console:**
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (select2-3.3.2.css, line 0)
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (packages.js, line 0)
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (keystone.min.css, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (async.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (pikaday-1.1.0.css, line 0)

**Comment by PoluosmakAndrew** [comment]
its a problem with node version.
Closed
