### ISSUE TITLE
ReferenceError: Unknown keystone list "js"

### ISSUE THREAD

**Issue by shi11** [keystonejs/keystone#2374]
Something busted on my staging server and I have no idea what caused it. Any guidance would be much appreciated. Thnx in advance.

This is a snippet of the error:

Error thrown for request: /keystone/js/packages.js
2016-03-05T03:04:52.328846+00:00 app[web.1]: ReferenceError: Unknown keystone list "js"
2016-03-05T03:04:52.328852+00:00 app[web.1]:     at list (/app/node_modules/keystone/lib/core/list.js:12:18)
2016-03-05T03:04:52.328857+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:131:13)
2016-03-05T03:04:52.328856+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-03-05T03:04:52.328853+00:00 app[web.1]:     at /app/node_modules/keystone/lib/core/routes.js:55:24
2016-03-05T03:04:52.328858+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:125:14)
...

**Comment by creynders** [comment]
Is this node v5? It's a known issue. I suggest downgrading to node v4

**Comment by shi11** [comment]
Thanks! Yeah downgrading from node 5.7 to 5.6 worked.

**Comment by JedWatson** [comment]
@creynders is there an issue open for the incompatibility with node@5.7?

**Comment by creynders** [comment]
@JedWatson not specifically AFAIK, a bunch of possibly related ones are though
