### ISSUE TITLE
Error: List.expandColumns: column definition must contain a path, when opening a new model edit page 

### ISSUE THREAD

**Issue by yao23** [keystonejs/keystone#2513]
I created a new model (TestPost) and can feed data and show successfully without login. But it complains 

    Error thrown for request: /keystone/test-posts
    Error: List.expandColumns: column definition must contain a path.
    at List.expandColumns (/Users/xx/projects/oo/NodeJS_Keystone/node_modules/keystone/lib/list/expandColumns.js:82:10)
    at List.Object.defineProperty.get (/Users/xx/projects/oo/NodeJS_Keystone/node_modules/keystone/lib/list.js:140:32)
    at /Users/xx/projects/oo/NodeJS_Keystone/node_modules/keystone/admin/routes/views/item.js:44:27
    at /Users/xx/projects/oo/NodeJS_Keystone/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/Users/xx/projects/oo/NodeJS_Keystone/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/Users/xx/projects/oo/NodeJS_Keystone/node_modules/async/lib/async.js:209:22)
    at renderView (/Users/xx/projects/oo/NodeJS_Keystone/node_modules/keystone/admin/routes/views/item.js:32:10)
    at Promise.<anonymous> (/Users/xx/projects/oo/NodeJS_Keystone/node_modules/keystone/admin/routes/views/item.js:94:4)
    at Promise.<anonymous> (/Users/xx/projects/oo/NodeJS_Keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at emitOne (events.js:77:13)
    at Promise.emit (events.js:169:7)
    at Promise.emit (/Users/xx/projects/oo/NodeJS_Keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/Users/xx/projects/oo/NodeJS_Keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at Promise.resolve (/Users/xx/projects/oo/NodeJS_Keystone/node_modules/mongoose/lib/promise.js:114:23)
    at Promise.<anonymous> (/Users/xx/projects/oo/NodeJS_Keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at emitOne (events.js:77:13)
    at Promise.emit (events.js:169:7)
    at Promise.emit (/Users/xx/projects/oo/NodeJS_Keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/Users/xx/projects/oo/NodeJS_Keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at /Users/xx/projects/oo/NodeJS_Keystone/node_modules/mongoose/lib/query.js:1406:13
    at model.Document.init (/Users/xx/projects/oo/NodeJS_Keystone/node_modules/mongoose/lib/document.js:254:11)
    at completeOne (/Users/xx/projects/oo/NodeJS_Keystone/node_modules/mongoose/lib/query.js:1404:10)

when I click a row and want to edit attribute after login as admin, I tried editing original post and user data, they all work well. Is there any routing configuration or something else I can do to make the new model editing page work?

Thanks in advance.

**Comment by yao23** [comment]
It's due to model definition error about defaultColumns

    TestPost.defaultColumns = 'name|15%, type|10%,' +
      ' description|30%, ';

The last comma after percentage caused the error, delete it and the edit page works.
