### ISSUE TITLE
numeric uid/gid fails with pki/fernet commands

### ISSUE THREAD

**Issue by bjne** [keystonejs/keystone#2564]
keystone-manage fernet_rotate --keystone-user 1000 --keystone-group 1000

2016-04-01 20:09:16.799 9 ERROR keystone Traceback (most recent call last):
2016-04-01 20:09:16.799 9 ERROR keystone   File "/opt/openstack/keystone/bin/keystone-manage", line 11, in <module>
2016-04-01 20:09:16.799 9 ERROR keystone     sys.exit(main())
2016-04-01 20:09:16.799 9 ERROR keystone   File "/opt/openstack/keystone/lib/python3.5/site-packages/keystone/cmd/manage.py", line 47, in main
2016-04-01 20:09:16.799 9 ERROR keystone     cli.main(argv=sys.argv, config_files=config_files)
2016-04-01 20:09:16.799 9 ERROR keystone   File "/opt/openstack/keystone/lib/python3.5/site-packages/keystone/cmd/cli.py", line 992, in main
2016-04-01 20:09:16.799 9 ERROR keystone     CONF.command.cmd_class.main()
2016-04-01 20:09:16.799 9 ERROR keystone   File "/opt/openstack/keystone/lib/python3.5/site-packages/keystone/cmd/cli.py", line 531, in main
2016-04-01 20:09:16.799 9 ERROR keystone     keystone_user_id, keystone_group_id = cls.get_user_group()
2016-04-01 20:09:16.799 9 ERROR keystone   File "/opt/openstack/keystone/lib/python3.5/site-packages/keystone/cmd/cli.py", line 416, in get_user_group
2016-04-01 20:09:16.799 9 ERROR keystone     raise ValueError("Unknown user '%s' in --keystone-user" % a)
2016-04-01 20:09:16.799 9 ERROR keystone ValueError: Unknown user '1000' in --keystone-user

**Comment by erg0dic** [comment]
Hi,

I think you have the wrong number, try calling here:
https://github.com/openstack/keystone

Best,
Rob
