### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by raduchiriac** [keystonejs/keystone#2581]
Everything worked great until a day or two and I am guessing this is caused by upgrading to `"async": "^2.0.0-rc.2"` and `"keystone": "^0.3.17"` but my website is showing a 500 error and I get this log (server is running Node.js v0.12.12)
```
Error thrown for request: /
TypeError: Cannot read property 'length' of undefined
    at eval (eval at <anonymous> (/srv/data/web/vhosts/default/node_modules/keystone/node_modules/jade/lib/index.js:218:8), <anonymous>:161:31)
    at eval (eval at <anonymous> (/srv/data/web/vhosts/default/node_modules/keystone/node_modules/jade/lib/index.js:218:8), <anonymous>:178:4)
    at eval (eval at <anonymous> (/srv/data/web/vhosts/default/node_modules/keystone/node_modules/jade/lib/index.js:218:8), <anonymous>:300:77)
    at res (/srv/data/web/vhosts/default/node_modules/keystone/node_modules/jade/lib/index.js:219:38)
    at Object.exports.renderFile (/srv/data/web/vhosts/default/node_modules/keystone/node_modules/jade/lib/index.js:380:38)
    at Object.exports.renderFile (/srv/data/web/vhosts/default/node_modules/keystone/node_modules/jade/lib/index.js:370:21)
    at View.exports.__express [as engine] (/srv/data/web/vhosts/default/node_modules/keystone/node_modules/jade/lib/index.js:417:11)
    at View.render (/srv/data/web/vhosts/default/node_modules/keystone/node_modules/express/lib/view.js:126:8)
    at tryRender (/srv/data/web/vhosts/default/node_modules/keystone/node_modules/express/lib/application.js:639:10)
    at EventEmitter.render (/srv/data/web/vhosts/default/node_modules/keystone/node_modules/express/lib/application.js:591:3)
    at ServerResponse.render (/srv/data/web/vhosts/default/node_modules/keystone/node_modules/express/lib/response.js:961:7)
    at View.<anonymous> (/srv/data/web/vhosts/default/node_modules/keystone/lib/view.js:337:13)
    at /srv/data/web/vhosts/default/node_modules/keystone/lib/view.js:372:3
    at /srv/data/web/vhosts/default/node_modules/keystone/node_modules/async/lib/async.js:52:16
    at /srv/data/web/vhosts/default/node_modules/keystone/node_modules/async/lib/async.js:269:32
    at /srv/data/web/vhosts/default/node_modules/keystone/node_modules/async/lib/async.js:44:16
    at /srv/data/web/vhosts/default/node_modules/keystone/node_modules/async/lib/async.js:726:13
    at /srv/data/web/vhosts/default/node_modules/keystone/node_modules/async/lib/async.js:52:16
    at async.forEachOf.async.eachOf (/srv/data/web/vhosts/default/node_modules/keystone/node_modules/async/lib/async.js:236:30)
    at _parallel (/srv/data/web/vhosts/default/node_modules/keystone/node_modules/async/lib/async.js:717:9)
    at Object.async.parallel (/srv/data/web/vhosts/default/node_modules/keystone/node_modules/async/lib/async.js:731:9)
    at /srv/data/web/vhosts/default/node_modules/keystone/lib/view.js:364:10
```

**Comment by mxstbr** [comment]
I'm 99% sure this is due to the upgrade to `async@2.0.0`. Looking at the [changelog](https://github.com/caolan/async/blob/master/CHANGELOG.md), they broke basically everything, meaning all the keystone internals don't work correctly anymore.

The only option I see here is downgrading back to `async@<2`, sorry!
