### ISSUE TITLE
Cannot run meetup exemple.

### ISSUE THREAD

**Issue by efleurine** [keystonejs/keystone#2591]
# Bug report
Cannot run `meetup exemple` with a fresh clone repo on my Ubuntu

## Describe the bug

With a fresh clone repo, I am trying to run the meetup exemple and it is failling with the message below

```
yarn run v1.22.4
$ cross-env NODE_ENV=development DISABLE_LOGGING=true keystone dev
ℹ Command: keystone dev
✔ Validated project entry file ./index.js
✔ Keystone server listening on port 3000
✖ Initialising Keystone instance
{ Error: Cannot find module '@keystonejs/utils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/emma/repo/keystone/packages/access-control/lib/access-control.js:1:53)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

So I went and install `"@keystonejs/utils": "^5.4.0",` and it did not change anything about the error

## To Reproduce

Clone Keystone repo and try to run the meetup exemple

## Expected behaviour

It just run.

## System information

- OS: Ubuntu

**Comment by efleurine** [comment]
I was finally able to run it, by moving the folder out of the subfolder exemples. It seems with so many package.json there are some conflits of which one is being used.

**Comment by Vultraz** [comment]
Did you try `yarn demo meetup dev` from the toplevel (not `demo-projects/meetup`) dir?

**Comment by MadeByMike** [comment]
I suspect this was a case of not running `yarn` in the root directory first.
