### ISSUE TITLE
Heroku Deploy doesnt work

### ISSUE THREAD

**Issue by DonHansDampf** [keystonejs/keystone#2629]
I tried the Heroku deploy but get the following error:

```
 Apr 14 09:37:53 keystonereact heroku/web.1: Starting process with command `node keystone.js` 
Apr 14 09:37:56 keystonereact app/web.1: { [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' } 
Apr 14 09:37:58 keystonereact app/web.1: { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' } 
Apr 14 09:37:58 keystonereact app/web.1: js-bson: Failed to load c++ bson extension, using pure JS version 
Apr 14 09:37:58 keystonereact app/web.1: ------------------------------------------------ 
Apr 14 09:37:58 keystonereact app/web.1: Mongo Error: 
Apr 14 09:37:58 keystonereact app/web.1: [Error: failed to connect to [localhost:27017]] 
Apr 14 09:37:58 keystonereact app/web.1: /app/node_modules/keystone/lib/core/mount.js:627 
Apr 14 09:37:58 keystonereact app/web.1: 			throw new Error('KeystoneJS (' + keystone.get('name') + ') failed to start'); 
Apr 14 09:37:58 keystonereact app/web.1: 			^ 
Apr 14 09:37:58 keystonereact app/web.1: Error: KeystoneJS (KeystoneJS) failed to start 
Apr 14 09:37:58 keystonereact app/web.1:     at NativeConnection.<anonymous> (/app/node_modules/keystone/lib/core/mount.js:627:10) 
Apr 14 09:37:58 keystonereact app/web.1:     at emitOne (events.js:90:13) 
Apr 14 09:37:58 keystonereact app/web.1:     at NativeConnection.emit (events.js:182:7) 
Apr 14 09:37:58 keystonereact app/web.1:     at NativeConnection.Connection.error (/app/node_modules/mongoose/lib/connection.js:389:8) 
Apr 14 09:37:58 keystonereact app/web.1:     at /app/node_modules/mongoose/lib/connection.js:416:14 
Apr 14 09:37:58 keystonereact app/web.1:     at /app/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:57:21 
Apr 14 09:37:58 keystonereact app/web.1:     at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:286:18 
Apr 14 09:37:58 keystonereact app/web.1:     at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:365:7 
Apr 14 09:37:58 keystonereact app/web.1:     at _combinedTickCallback (internal/process/next_tick.js:67:7) 
Apr 14 09:37:58 keystonereact app/web.1:     at process._tickCallback (internal/process/next_tick.js:98:9) 
Apr 14 09:37:59 keystonereact heroku/web.1: Process exited with status 1 
Apr 14 09:37:59 keystonereact heroku/web.1: State changed from starting to crashed 
Apr 14 09:38:00 keystonereact heroku/router: at=error code=H10 desc="App crashed" method=GET path="/" host=keystonereact.herokuapp.com request_id=7fde97fb-6ca8-4952-8cfa-b9631c6355f8 fwd="62.245.160.245" dyno= connect= service= status=503 bytes= 
Apr 14 09:38:25 keystonereact heroku/router: at=error code=H10 desc="App crashed" method=GET path="/" host=keystonereact.herokuapp.com request_id=ece8d5da-0a97-4988-8a58-03c217cc461b fwd="62.245.160.245" dyno= connect= service= status=503 bytes= 
```
How can i fix this?

**Comment by mxstbr** [comment]
This is highly likely a problem related to MongoDB, not to Keystone. See [this google search](https://www.google.at/search?q=%5BError%3A+failed+to+connect+to+%5Blocalhost%3A27017%5D%5D&oq=%5BError%3A+failed+to+connect+to+%5Blocalhost%3A27017%5D%5D&aqs=chrome..69i57.197j0j7&sourceid=chrome&ie=UTF-8) for a few hints what it might be.

I'll close this issue for now, if this does turn out to not be solvable by any of the approaches suggested above and is related to Keystone please let me know in this issue!
