### ISSUE TITLE
Allow discriminatorKey to be set to existing field

### ISSUE THREAD

**Issue by geloescht** [keystonejs/keystone#2649]
Right now, list inheritance is kind of a second-class citizen in keystone. It works ok, as long as you use it in it's most basic form, but could be more useful if it was more configurable.
A first step would be to make it possible to set the discriminator field to one that is already defined in the schema.
This is impossible currently, because mongoose throws `Error: Discriminator "Derived" cannot have field with name "discriminatorKey"`. The underlying reason is, that keystone adds fields from the base list to the schema for derived lists. IMO this is both unnecessary and harmful.
The corresponding setting is `schema.discriminatorKey`, but should possibly be replaced by a proper list option instead of a schema option to make it interceptable by keystone.

**Comment by geloescht** [comment]
Investigated this a bit:
We would need to disable the invocation of addToSchema in fields/type/Type.js inside the constructor of Field for all parent fields. Unfortunately the call stack is quite deep at this point:
at boolean.
```
Field (--snip--/node_modules/keystone/fields/types/Type.js:85:14) <-- point where addToSchema is called
    at new boolean (--snip--/node_modules/keystone/fields/types/boolean/BooleanType.js:15:17)
    at List.field (--snip--/node_modules/keystone/lib/list/field.js:46:14)
    at List.<anonymous> (--snip--/node_modules/keystone/lib/list/add.js:41:16)
    at List.<anonymous> (--snip--/node_modules/keystone/lib/list/add.js:30:5)
    at --snip--/node_modules/keystone/lib/list/add.js:74:5
    at arrayEach (--snip--/node_modules/keystone/node_modules/lodash/lodash.js:483:11)
    at Function.forEach (--snip--/node_modules/keystone/node_modules/lodash/lodash.js:7827:11)
    at List.add (--snip--/node_modules/keystone/lib/list/add.js:48:4)
    at new List (--snip--/node_modules/keystone/lib/list.js:114:12) <-- point where parent fields get added
```
Passing a boolean to disable addToSchema down this call stack is quite impractical. Maybe a new method should be devised to add parent fields or the call to addToSchema be moved out of the field Type constructor.

**Comment by Noviny** [comment]
Inheritance functionality is not something we are looking at extending going forward. Closing this as an issue.
