### ISSUE TITLE
Cannot boot in existing project: "TypeError: Cannot read property 'prepare' of undefined"

### ISSUE THREAD

**Issue by ra-external** [keystonejs/keystone#2651]
This is a two-part issue.  The first was when -- in an almost two month old project -- I attempted to add some additional relationships, writing the additional Lists and putting the correct Relationship fields into one of my Lists.  At that point that List into which I added the new relationships could not see any of the relationships it had -- neither the new ones, nor the old ones, _even after I edited the file and removed all new code_.  I had to download from the repo to solve the problem.

I tried it again with the newly downloaded repo, step by step, just adding one file to the project.  At the point it blew up again -- _an existing relationship__ no longer worked, even though I hadn't added any new ones, just added one file.  

I deleted the new file and attempted to boot and now I am getting

```
✔ Initialised Keystone instance
✖ Connecting to database
TypeError: Cannot read property 'prepare' of undefined
    at executeDefaultServer (/Users/ranthony/Documents/projects/yaa-cms2/node_modules/@keystonejs/keystone/bin/utils.js:112:42)
error Command failed with exit code 1.
```
Even though I've correctly initialised the Keystone instance.  It booted fine until I added a new file to the project.  I dropped the Mongo DB, just to see if that helped, but it did not. 

Any idea what the above error might indicate?

**Comment by ra-external** [comment]
To be clearer about the first error, since I've just now reproduced it:

1. Start with a working KS project written in TypeScript.  A list -- in this case 'Article' -- contains several tags that are relationships, one of which is:
```

			tag: {
				type: Relationship,
				ref: 'Tag',
				many: true
			},
```

  All works fine and the app boots correctly.

2.  Add the following file to the project

```
// Category.ts
import log from '../util/log';

export default keystone => {
	log('setting up category list');
	keystone.createList('Category', {
		schemaDoc: 'Category for Article',

		fields: {
			articleCategory: { type: Text }
		}
	});
};


```

3.  Run project again.  Now this error is produced
```

✔ Initialised Keystone instance
✖ Connecting to database
Error: Unable to resolve related list 'Tag' from Article.tag
    at Relationship.tryResolveRefList (/Users/ranthony/Documents/projects/yaa-cms2/node_modules/@keystonejs/fields/dist/fields.cjs.js:1566:13)
    at Relationship.getGqlAuxTypes (/Users/ranthony/Documents/projects/yaa-cms2/node_modules/@keystonejs/fields/dist/fields.cjs.js:1837:14)
    at /Users/ranthony/Documents/projects/yaa-cms2/node_modules/@keystonejs/keystone/lib/List/index.js:381:51
    at Array.map (<anonymous>)
    at List.getGqlTypes (/Users/ranthony/Documents/projects/yaa-cms2/node_modules/@keystonejs/keystone/lib/List/index.js:381:32)
    at /Users/ranthony/Documents/projects/yaa-cms2/node_modules/@keystonejs/keystone/lib/Keystone/index.js:419:58
    at Array.map (<anonymous>)
    at Keystone.getTypeDefs (/Users/ranthony/Documents/projects/yaa-cms2/node_modules/@keystonejs/keystone/lib/Keystone/index.js:419:41)
    at Keystone.getAdminSchema (/Users/ranthony/Documents/projects/yaa-cms2/node_modules/@keystonejs/keystone/lib/Keystone/index.js:520:27)
    at createApolloServer (/Users/ranthony/Documents/projects/yaa-cms2/node_modules/@keystonejs/app-graphql/lib/apolloServer.js:147:17)
    at GraphQLApp.prepareMiddleware (/Users/ranthony/Documents/projects/yaa-cms2/node_modules/@keystonejs/app-graphql/index.js:24:20)
    at /Users/ranthony/Documents/projects/yaa-cms2/node_modules/@keystonejs/keystone/lib/Keystone/index.js:759:17
    at Array.map (<anonymous>)
    at Keystone.prepare (/Users/ranthony/Documents/projects/yaa-cms2/node_modules/@keystonejs/keystone/lib/Keystone/index.js:758:12)
    at executeDefaultServer (/Users/ranthony/Documents/projects/yaa-cms2/node_modules/@keystonejs/keystone/bin/utils.js:112:42)

```

**Comment by ahmedjahmi** [comment]
@ra-external i noticed you closed this issue, did you find a solution to this? i'm experiencing the same issue now.

**Comment by ldonjibson** [comment]
This issue needs to be address, i am trying to create custom server and i am stocked at that ... 
the v5 has no sample project for the custom server.

**Comment by wesbos** [comment]
Got this too, make sure you export keystone from your index.js:

`module.exports.keystone = keystone;`

**Comment by abhijithvijayan** [comment]
> Got this too, make sure you export keystone from your index.js:
> 
> `module.exports.keystone = keystone;`

OMG, thank you :)

**Comment by Nikodermus** [comment]
Just got that one, also, if you are using ESM

```javascript
export const keystone = new Keystone({ ... })
export default { keystone, apps: [ ... ]}
```
