### ISSUE TITLE
Unable to connect to a mongodb instance with an authentication strategy

### ISSUE THREAD

**Issue by loconluis** [keystonejs/keystone#2713]
# Bug report

## Describe the bug

Unable to connect to a mongodb instance with an authentication strategy; Suppose this connection string: ```mongodb://user:pass@localhost:27017/blog```

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

1. Change connection string [.env] 'MONGODB_URI="mongodb://user:pass@localhost:27017/blog"
2. Run ```$ yarn dev```
3. Wait 

````
Error: Authentication failed.
    at /Users/luislocon/Documents/Projects/github/xxxxxx/node_modules/@keystonejs/utils/dist/utils.cjs.dev.js:57:21
    at async executeDefaultServer (/Users/luislocon/Documents/Projects/github/xxxxxx/node_modules/@keystonejs/keystone/bin/utils.js:114:3) {
  errors: {
    MongooseAdapter: MongooseError [MongooseServerSelectionError]: Authentication failed.
        at new MongooseServerSelectionError (/Users/luislocon/Documents/Projects/github/xxxxxx/node_modules/mongoose/lib/error/serverSelection.js:22:11)
        at NativeConnection.Connection.openUri (/Users/luislocon/Documents/Projects/github/xxxxxx/node_modules/mongoose/lib/connection.js:808:32)
        at Mongoose.connect (/Users/luislocon/Documents/Projects/github/xxxxxx/node_modules/mongoose/lib/index.js:333:15)
        at MongooseAdapter._connect (/Users/luislocon/Documents/Projects/github/xxxxxx/node_modules/@keystonejs/adapter-mongoose/lib/adapter-mongoose.js:55:25)
        at MongooseAdapter.connect (/Users/luislocon/Documents/Projects/github/xxxxxx/node_modules/@keystonejs/keystone/lib/adapters/index.js:22:16)
        at /Users/luislocon/Documents/Projects/github/xxxxxx/node_modules/@keystonejs/keystone/lib/Keystone/index.js:360:64
        at /Users/luislocon/Documents/Projects/github/xxxxxx/node_modules/@keystonejs/utils/dist/utils.cjs.dev.js:24:12
        at Array.reduce (<anonymous>)
        at mapKeys (/Users/luislocon/Documents/Projects/github/xxxxxx/node_modules/@keystonejs/utils/dist/utils.cjs.dev.js:21:52)
        at Keystone.connect (/Users/luislocon/Documents/Projects/github/xxxxxx/node_modules/@keystonejs/keystone/lib/Keystone/index.js:360:27)
        at executeDefaultServer (/Users/luislocon/Documents/Projects/github/xxxxxx/node_modules/@keystonejs/keystone/bin/utils.js:114:18) {
      message: 'Authentication failed.',
      name: 'MongooseServerSelectionError',
      reason: [TopologyDescription],
      [Symbol(mongoErrorContextSymbol)]: {}
    }
  }
````
## Expected behaviour

````
✔ Connected to database
✔ Keystone instance is ready at http://localhost:3000 🚀
🔗 Keystone Admin UI:   http://localhost:3000/admin
🔗 GraphQL Playground:  http://localhost:3000/admin/graphiql
🔗 GraphQL API:         http://localhost:3000/admin/api
````

## System information

- OS: MacOs

## Additional context
- Yarn 1.22.4
- Also tried with npm 6.14.2

**Comment by gautamsi** [comment]
try use this connection string `mongodb://user:pass@localhost:27017/blog?authSource=admin`
change `admin` as configure on your mongodb

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
