### ISSUE TITLE
Node 6 support

### ISSUE THREAD

**Issue by jacqueslareau** [keystonejs/keystone#2759]
Hi,

I know it's related to https://github.com/dodo/node-unicodetable/issues/24 but since keystone depends on it, installation on Node 6.0 doesn't work.

**Comment by mxstbr** [comment]
That's very possible. I'll investigate it, please use a Node version `< 6` until we've ironed out all the dependency problems! (which could take a while)

**Comment by JedWatson** [comment]
I've just updated `keystone-utils` to depend on [mollusc](https://www.npmjs.com/package/mollusc) instead of `slug` (which wanted `node-unicodetable`) so that should be resolved now. @jacqueslareau anything else you can see blocking Node 6 support?

**Comment by jacqueslareau** [comment]
Can confirm that it's resolved. Thanks for the quick follow up! 

As of now, it seems it was the only issue related to 6.0.

**Comment by mxstbr** [comment]
Awesome, I'll close this issue then! :tada:

**Comment by leolweb** [comment]
I have issues after this update (v0.3.19) using Types.Key
```
TypeError: Cannot read property 'c' of undefined
    at slug (node_modules/mollusc/slug.js:71:25)
    at Object.slug (node_modules/keystone-utils/lib/index.js:364:10)
    at key.generateKey (node_modules/keystone/fields/types/key/KeyType.js:26:15)
    at key.validateInput (node_modules/keystone/fields/types/key/KeyType.js:37:15)
    at UpdateHandler.<anonymous> (node_modules/keystone/lib/updateHandler.js:271:30)
    at Array.forEach (native)
    at UpdateHandler.process (node_modules/keystone/lib/updateHandler.js:210:17)
    at Promise.<anonymous> (node_modules/keystone/admin/routes/views/item.js:84:31)
    at Promise.<anonymous> (node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at emitOne (events.js:96:13)
    at Promise.emit (events.js:188:7)
    at Promise.emit (node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at Promise.resolve (node_modules/keystone/node_modules/mongoose/lib/promise.js:114:23)
    at Promise.<anonymous> (node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at emitOne (events.js:96:13)
    at Promise.emit (events.js:188:7)
    at Promise.emit (node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at node_modules/keystone/node_modules/mongoose/lib/query.js:1406:13
    at model.Document.init (node_modules/keystone/node_modules/mongoose/lib/document.js:254:11)
    at completeOne (node_modules/keystone/node_modules/mongoose/lib/query.js:1404:10)
```

**Comment by JedWatson** [comment]
@leolweb that should be fixed with our most recent update to keystone-utils
