### ISSUE TITLE
Blog demo project doesn't work

### ISSUE THREAD

**Issue by pahaz** [keystonejs/keystone#2761]
# Bug report

## Describe the bug

If you try to follow a README: https://github.com/keystonejs/keystone/tree/master/demo-projects/blog
You'll get an error.

```
git clone https://github.com/keystonejs/keystone
cd keystone/demo-projects/todo
rm -rf node_modules
git pull
yarn
yarn dev
```

## Screenshots

![image](https://user-images.githubusercontent.com/1394025/79501485-c894b680-8036-11ea-9548-eae5e641943f.png)

```
$ cross-env NODE_ENV=development DISABLE_LOGGING=true keystone dev
internal/modules/cjs/loader.js:327
      throw err;
      ^

Error: Cannot find module '/Users/pahaz/Code/node-docker-compose-dev/keystone/node_modules/@keystonejs/utils/dist/utils.cjs.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:319:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:703:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:967:27)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/pahaz/Code/node-docker-compose-dev/keystone/packages/keystone/bin/commands/create-tables.js:5:26)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/pahaz/Code/node-docker-compose-dev/keystone/node_modules/@keystonejs/utils/package.json',
  requestPath: '@keystonejs/utils'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by pahaz** [comment]
Workaround: you need to copy `blog` to a directory outside the keystone git.
```
cp -r keystone/demo-projects/blog my-blog-app
cd my-blog-app
yarn
yarn dev
```

**Comment by pahaz** [comment]
But have a problem with the production environment ...

![image](https://user-images.githubusercontent.com/1394025/79558363-b0f81500-80ac-11ea-85eb-0c3b627063ad.png)

```
pahaz@PahazMac16 keystone-blog % yarn build
yarn run v1.22.4
$ cross-env NODE_ENV=production keystone build
ℹ Command: keystone build
✔ Validated project entry file ./index.js
✔ Initialised Keystone instance
Creating an optimized production build  

Compiled successfully.

Automatically optimizing pages  

Page                            Size     First Load JS
┌ ○ /                           1.08 kB         118 kB
├ ○ /404                        2.59 kB        60.9 kB
├ λ /post/[slug]                2.73 kB         119 kB
├ ○ /post/new                   5.44 kB         114 kB
└ ○ /signin                     5.2 kB          114 kB
+ First Load JS shared by all   58.3 kB
  ├ static/pages/_app.js        959 B
  ├ chunks/commons.5aae38.js    10.5 kB
  ├ chunks/framework.970a96.js  40.3 kB
  ├ runtime/main.cb8470.js      5.82 kB
  └ runtime/webpack.b65cab.js   746 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)

✔ Exported Keystone build to ./dist
✨  Done in 18.72s.
pahaz@PahazMac16 keystone-blog % yarn start
yarn run v1.22.4
$ cross-env NODE_ENV=production keystone start
ℹ Command: keystone start
✔ Validated project entry file ./index.js
✔ Keystone server listening on port 3000
✔ Initialised Keystone instance
⠋ Connecting to databaseWarning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
✔ Connected to database
✔ Keystone instance is ready at http://localhost:3000 🚀
🔗 Keystone Admin UI: http://localhost:3000/admin
🔗 GraphQL API:       http://localhost:3000/admin/api
```

**Comment by MadeByMike** [comment]
@pahaz this is because of the yarn workspace set-up. Deleting `node_modules` in the project directory and running yarn only in the project directory could cause issues. You need to run yarn in the root directory to correctly link monorepo packages:

"To run this project, open your terminal and run yarn **within the Keystone project root** to install all required packages, then run yarn start blog to begin running Keystone."
