### ISSUE TITLE
limit() doesn't work on single CloudinaryImage type

### ISSUE THREAD

**Issue by brundonsmith** [keystonejs/keystone#2762]
I have a model that has both a main image and a list of images:

```
mainImage: { type: Types.CloudinaryImage },
images: { type: Types.CloudinaryImages },
```

It has a method that returns the main image if it's populated, or the first image in the list otherwise:

```
Instrument.schema.methods.getMainImage = function getMainImage() {
  if(this.mainImage.exists) {
    return this.mainImage;
  } else {
    return this.images[0];
  }
};
```

In my Swig template, I have the following:

```
<a 
class="instrument-item shadowed" 
href="/instrument/{{ instrument.id }}" 
style="background-image:url('{{ (instrument.getMainImage()).limit(300,300) }}')">
```

This works just fine when the main image doesn't exist and `images[0]` is returned, but when the singular `CloudinaryImage` is returned I get the following error:

```
TypeError: ((intermediate value)(intermediate value)(intermediate value) || _fn).call(...).limit is not a function
    at eval (eval at <anonymous> (/Users/brundon/git/fiddlers-green/node_modules/swig/lib/swig.js:498:13), <anonymous>:194:1661)
    at Object.exports.each (/Users/brundon/git/fiddlers-green/node_modules/swig/lib/utils.js:45:11)
    at eval (eval at <anonymous> (/Users/brundon/git/fiddlers-green/node_modules/swig/lib/swig.js:498:13), <anonymous>:185:10)
    at Object.eval [as tpl] (eval at <anonymous> (/Users/brundon/git/fiddlers-green/node_modules/swig/lib/swig.js:498:13), <anonymous>:206:3)
    at compiled (/Users/brundon/git/fiddlers-green/node_modules/swig/lib/swig.js:619:18)
    at /Users/brundon/git/fiddlers-green/node_modules/swig/lib/swig.js:559:20
    at /Users/brundon/git/fiddlers-green/node_modules/swig/lib/swig.js:690:9
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```

Also of note, if I replace `.limit(300,300)` with `.url`, it works fine in both cases. But I'd really rather avoid sending the full-sized image, and `.limit(...)` is listed in the docs for `CloudinaryImage`, so I don't see why it wouldn't be found here. I'm on Keystone version 0.3.17.

**Comment by Noviny** [comment]
Closing as a keystone 0.3 issue, as we are no longer supporting 0.3

Options for this have been added in 4.
