### ISSUE TITLE
Yarn dev is giving mongodb connection error

### ISSUE THREAD

**Issue by stardev24** [keystonejs/keystone#2777]
# Bug report
Yarn dev is giving mongodb connection error
## Describe the bug

A clear and concise description of the bug.
Even after having mongodb latest version the Keystone dev is not starting.The logs are given here.
✖ Connecting to database
{ Error: MongoDB version 3.6.14 is incompatible. Version 4.0.0 or later is required.
    at Promise.all.then.results (/home/sai/Desktop/cms/nerchuko/node_modules/@keystonejs/utils/dist/utils.cjs.dev.js:48:21)
  errors:
   { MongooseAdapter:
      Error: MongoDB version 3.6.14 is incompatible. Version 4.0.0 or later is required.
          at MongooseAdapter.checkDatabaseVersion (/home/sai/Desktop/cms/nerchuko/node_modules/@keystonejs/adapter-mongoose/lib/adapter-mongoose.js:147:13)
          at process._tickCallback (internal/process/next_tick.js:68:7) } }
error Command failed with exit code 1.

## To Reproduce
yarn create keystone-app test
yarn dev

## Expected behaviour
Dev server should start with yarn dev.

**Comment by Vultraz** [comment]
Are you sure you're running MongoDB > 4.0?

**Comment by MadeByMike** [comment]
@stardev24 unfortunately we only support Mongo v4 and later.
