### ISSUE TITLE
Create Keystone Unexpected token error.

### ISSUE THREAD

**Issue by luvmex** [keystonejs/keystone#2820]
```
/usr/local/lib/node_modules/generator-keystone/node_modules/yeoman-generator/node_modules/lodash/dist/lodash.js:6309
        throw e;
        ^

SyntaxError: Unexpected token =
    at Function (native)
    at Function.template (/usr/local/lib/node_modules/generator-keystone/node_modules/yeoman-generator/node_modules/lodash/dist/lodash.js:6306:22)
    at KeystoneGenerator.underscore [as _engine] (/usr/local/lib/node_modules/generator-keystone/node_modules/yeoman-generator/lib/util/engines.js:31:14)
    at KeystoneGenerator.engine (/usr/local/lib/node_modules/generator-keystone/node_modules/yeoman-generator/lib/actions/actions.js:314:10)
    at KeystoneGenerator.template (/usr/local/lib/node_modules/generator-keystone/node_modules/yeoman-generator/lib/actions/actions.js:289:15)
    at KeystoneGenerator.project (/usr/local/lib/node_modules/generator-keystone/app/index.js:289:7)
    at /usr/local/lib/node_modules/generator-keystone/node_modules/yeoman-generator/lib/base.js:395:14
    at processImmediate [as _immediateCallback] (timers.js:371:17)
```

When create the project in the last step, will get the error " Unexpected token = " #6309.
I reinstall Keystone again using sudo, the problem are the same.

**Comment by mxstbr** [comment]
Which version of the generator is this? (`npm list -g generator-keystone`)

**Comment by r3wt** [comment]
I can confirm in `generator-keystone@0.3.15`

**Comment by r3wt** [comment]
`/app/templates/_package.json` seems to be all screwed up

**Comment by mxstbr** [comment]
Can you try updating to `0.3.19` and seeing if it still happens?

**Comment by mxstbr** [comment]
Thanks, will close in favor of https://github.com/keystonejs/generator-keystone/issues/189!
