### ISSUE TITLE
keystone.createItems() call doesn't use fields defaultValue

### ISSUE THREAD

**Issue by pahaz** [keystonejs/keystone#2852]
# Bug report

## Describe the bug

I have code:
```
        const users = await keystone.lists.User.adapter.findAll();
        if (!users.length) {
            const initialData = require('./initial-data');
            await keystone.createItems(initialData);
        }
```

And I have a field `settings` with default value in my `User` model.
My `initial-data` also don't have `settings`.

```
$ cross-env NODE_ENV=development DISABLE_LOGGING=true keystone dev
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
Error: insert into "public"."User" ("dob", "email", "isActive", "isAdmin", "name", "password") values ($1, $2, $3, $4, $5, $6) returning * - null value in column "settings" violates not-null constraint
    at /home/runner/work/nodejs-hackathon-boilerplate-starter-kit/nodejs-hackathon-boilerplate-starter-kit/node_modules/@keystonejs/utils/dist/utils.cjs.dev.js:48:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Keystone.createItems (/home/runner/work/nodejs-hackathon-boilerplate-starter-kit/nodejs-hackathon-boilerplate-starter-kit/node_modules/@keystonejs/keystone/lib/Keystone/index.js:562:26)
    at async Object.onConnect (/home/runner/work/nodejs-hackathon-boilerplate-starter-kit/nodejs-hackathon-boilerplate-starter-kit/index.js:24:13)
    at async executeDefaultServer (/home/runner/work/nodejs-hackathon-boilerplate-starter-kit/nodejs-hackathon-boilerplate-starter-kit/node_modules/@keystonejs/keystone/bin/utils.js:114:3) {
  errors: {
    User: error: insert into "public"."User" ("dob", "email", "isActive", "isAdmin", "name", "password") values ($1, $2, $3, $4, $5, $6) returning * - null value in column "settings" violates not-null constraint
        at Connection.parseE (/home/runner/work/nodejs-hackathon-boilerplate-starter-kit/nodejs-hackathon-boilerplate-starter-kit/node_modules/pg/lib/connection.js:614:13)
        at Connection.parseMessage (/home/runner/work/nodejs-hackathon-boilerplate-starter-kit/nodejs-hackathon-boilerplate-starter-kit/node_modules/pg/lib/connection.js:413:19)
        at Socket.<anonymous> (/home/runner/work/nodejs-hackathon-boilerplate-starter-kit/nodejs-hackathon-boilerplate-starter-kit/node_modules/pg/lib/connection.js:129:22)
        at Socket.emit (events.js:310:20)
        at Socket.EventEmitter.emit (domain.js:482:12)
        at addChunk (_stream_readable.js:286:12)
        at readableAddChunk (_stream_readable.js:268:9)
        at Socket.Readable.push (_stream_readable.js:209:10)
        at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
      length: 342,
      severity: 'ERROR',
      code: '23502',
      detail: 'Failing row contains (1, JustUser, user@example.com, f, t, $2a$10$4FG6V7YDYXbuX.Jozk9pSO7EVuSs7HuY0OYKUbDsBwKBG8q6lBHai, null, null, null, null, 1995-06-09, null, null, null, null, null, null).',
      hint: undefined,
      position: undefined,
      internalPosition: undefined,
      internalQuery: undefined,
      where: undefined,
      schema: 'public',
      table: 'User',
      column: 'settings',
      dataType: undefined,
      constraint: undefined,
      file: 'execMain.c',
      line: '1965',
      routine: 'ExecConstraints'
    }
  }
}
```

## Expected behaviour

The Keystone should use `defaultValue` from a field list.

This issue may be related to https://github.com/keystonejs/keystone/issues/2851

**Comment by MadeByMike** [comment]
We'd probably encourage most people to use `executeQuery` over `createItems` now and there are even plans to depreciate it: #1091 

We probably will not be fixing this bug anytime soon. The suggested work around is to use `executeQuery` or always provide data.
