### ISSUE TITLE
npm start doesn't work

### ISSUE THREAD

**Issue by nfatah** [keystonejs/keystone#2889]
running npm start after `yo keystone` is done, outputs the following error 
## npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.9.0
3 info using node@v6.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle my-site@0.0.0~prestart: my-site@0.0.0
6 silly lifecycle my-site@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle my-site@0.0.0~start: my-site@0.0.0
8 verbose lifecycle my-site@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle my-site@0.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/negus/Desktop/lultech/y/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle my-site@0.0.0~start: CWD: /home/negus/Desktop/lultech/y
11 silly lifecycle my-site@0.0.0~start: Args: [ '-c', 'none' ]
12 info lifecycle my-site@0.0.0~start: Failed to exec start script
13 verbose stack Error: my-site@0.0.0 start: `none`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:850:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
14 verbose pkgid my-site@0.0.0
15 verbose cwd /home/negus/Desktop/lultech/y
16 error Linux 4.4.0-22-generic
17 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 error node v6.0.0
19 error npm  v3.9.0
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error my-site@0.0.0 start: `none`
24 error spawn ENOENT
25 error Failed at the my-site@0.0.0 start script 'none'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the my-site package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     none
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs my-site
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls my-site
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]
```

**Comment by jstockwin** [comment]
@nfatah Try `node keystone` instead of `npm start`. There is no `start` script in package.json for you to be able to run `npm start`.

**Comment by mxstbr** [comment]
What @jstockwin said should fix your problem!

We're trying to keep this issue tracker solely for real issues, please ask your next question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead! Thanks!
