### ISSUE TITLE
Crash on fresh install

### ISSUE THREAD

**Issue by ddaddy** [keystonejs/keystone#3004]
I copied my project to a new AWS server and ran `npm install` and am getting this crash after visiting a page.
```GET /aboutus 304 84.333 ms
Error: watch node_modules/express/lib/express.js ENOSPC
    at exports._errnoException (util.js:870:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at createFsWatchInstance (/home/ubuntu/sololet/node_modules/nunjucks/node_modules/chokidar/lib/nodefs-handler.js:24:15)
    at setFsWatchListener (/home/ubuntu/sololet/node_modules/nunjucks/node_modules/chokidar/lib/nodefs-handler.js:47:19)
    at EventEmitter.NodeFsHandler._watchWithNodeFs (/home/ubuntu/sololet/node_modules/nunjucks/node_modules/chokidar/lib/nodefs-handler.js:177:15)
    at EventEmitter.NodeFsHandler._handleFile (/home/ubuntu/sololet/node_modules/nunjucks/node_modules/chokidar/lib/nodefs-handler.js:201:8)
    at EventEmitter.<anonymous> (/home/ubuntu/sololet/node_modules/nunjucks/node_modules/chokidar/lib/nodefs-handler.js:353:12)
    at FSReqWrap.oncomplete (fs.js:82:15)```

I wondering if it could be a problem with an pm package being updated?

**Comment by morenoh149** [comment]
please use the search feature https://github.com/keystonejs/keystone/search?q=+ENOSPC+&type=Issues&utf8=%E2%9C%93 if those issues do not provide answers please detail your environment.
