### ISSUE TITLE
TypeError: Cannot supply flags when constructing one RegExp from another

### ISSUE THREAD

**Issue by jannispl** [keystonejs/keystone#3207]
```
TypeError: Cannot supply flags when constructing one RegExp from another
    at new RegExp (native)
    at /app/node_modules/keystone/lib/core/mount.js:228:44
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:131:13)
    at next (/app/node_modules/express/lib/router/route.js:125:14)
    at next (/app/node_modules/express/lib/router/route.js:125:14)
    at next (/app/node_modules/express/lib/router/route.js:125:14)
    at next (/app/node_modules/express/lib/router/route.js:125:14)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:277:22
    at param (/app/node_modules/express/lib/router/index.js:349:14)
    at param (/app/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/app/node_modules/express/lib/router/index.js:410:3)
    at next (/app/node_modules/express/lib/router/index.js:271:10)
    at expressInit (/app/node_modules/express/lib/middleware/init.js:33:5)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:312:13)
    at /app/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)
    at next (/app/node_modules/express/lib/router/index.js:271:10)
    at query (/app/node_modules/express/lib/middleware/query.js:44:5)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:312:13)
    at /app/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)
    at next (/app/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/app/node_modules/express/lib/router/index.js:176:3)
```

relevant change was made here: #2970 

`new RegExp(/\/\//, 'g')` should just be `/\/\//g`

**Comment by wmertens** [comment]
@jannispl could you do a quick PR?

**Comment by jannispl** [comment]
@wmertens Done #3211

**Comment by JedWatson** [comment]
Thanks, merged!
