### ISSUE TITLE
CustomField inconsistent knex/mongoose logic

### ISSUE THREAD

**Issue by pahaz** [keystonejs/keystone#3207]
# Bug report

## Describe the bug

I have an `Options` field based on the MuliCheck field example. [Options field source](https://github.com/8iq/nodejs-hackathon-boilerplate-starter-kit/tree/b019c713cb4673aa151f5c2259e6876b99378b45/apps/_back02keystone/custom-fields/Options) 

I have a `User` list like so:
```
const { Stars, Options } = require('../custom-fields')
...

keystone.createList('User', {
    ...
    fields: {
        settings: { type: Options, options: ['Feature1', 'Feature2'] },
        ...
    }
})
```

I have a test which filters the User list by settings field. [source](https://github.com/8iq/nodejs-hackathon-boilerplate-starter-kit/blob/b019c713cb4673aa151f5c2259e6876b99378b45/apps/_back02keystone/_api_tests/user.settings.test.js#L149-L172)

At the moment this test work as expected for `knex`. 
`mongoose` fail by an error:
```
    [
      {
        message: "'User' Mongo List Adapter failed to determine field responsible for the query condition 'settings'. 'settings' was seen by following the query 'settings'.",
        locations: [ { line: 2, column: 3 } ],
        path: [ 'users' ],
        extensions: { code: 'INTERNAL_SERVER_ERROR' },
        uid: 'ckbxrvoxy0000e55l4i2aecuk',
        name: 'GraphQLError'
      }
    ]
```
Traceback:
```
"Error: 'User' Mongo List Adapter failed to determine field responsible for the query condition 'settings'. 'settings' was seen by following the query 'settings'.
    at getRelatedListAdapterFromQueryPath (/nodejs-hackathon-boilerplate-starter-kit/node_modules/@keystonejs/mongo-join-builder/lib/tokenizers.js:31:13)
    at simpleTokenizer (/nodejs-hackathon-boilerplate-starter-kit/node_modules/@keystonejs/mongo-join-builder/lib/tokenizers.js:98:26)
    at /nodejs-hackathon-boilerplate-starter-kit/node_modules/@keystonejs/mongo-join-builder/lib/query-parser.js:55:27
    at Array.map (<anonymous>)
    at queryParser (/nodejs-hackathon-boilerplate-starter-kit/node_modules/@keystonejs/mongo-join-builder/lib/query-parser.js:27:47)
    at /nodejs-hackathon-boilerplate-starter-kit/node_modules/@keystonejs/mongo-join-builder/lib/query-parser.js:51:48
    at Array.map (<anonymous>)
    at queryParser (/nodejs-hackathon-boilerplate-starter-kit/node_modules/@keystonejs/mongo-join-builder/lib/query-parser.js:27:47)
    at MongooseListAdapter._itemsQuery (/nodejs-hackathon-boilerplate-starter-kit/node_modules/@keystonejs/adapter-mongoose/lib/adapter-mongoose.js:553:23)
    at MongooseListAdapter.itemsQuery (/nodejs-hackathon-boilerplate-starter-kit/node_modules/@keystonejs/keystone/lib/adapters/index.js:139:32)
    at List._itemsQuery (/nodejs-hackathon-boilerplate-starter-kit/node_modules/@keystonejs/keystone/lib/ListTypes/list.js:670:40)
    at List.listQuery (/nodejs-hackathon-boilerplate-starter-kit/node_modules/@keystonejs/keystone/lib/ListTypes/list.js:584:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

At the moment the problem is inside `mongo-join-builder/lib/query-parser.js:queryParse:44` [code](https://github.com/keystonejs/keystone/blob/master/packages/mongo-join-builder/lib/query-parser.js#L44-L53):

![image](https://user-images.githubusercontent.com/1394025/85925388-8fd45180-b8b1-11ea-88aa-5d67c9bcb3e2.png)

The `queryParse` logic doesn't expect custom query objects. 

# The key #

The key difference between `knex-adapter` and `mongoose-adapter` is the `knex-adapter` uses `listAdapter.fieldAdaptersByPath` [here](https://github.com/keystonejs/keystone/blob/master/packages/adapter-knex/lib/adapter-knex.js#L740)
which desn't used by `mongoose-adapter` [here](https://github.com/keystonejs/keystone/blob/master/packages/adapter-mongoose/lib/adapter-mongoose.js)

# additional #

I think it's probably the same problem inside the `File` field. If anyone tries to filter by file field on Mongo. (I don't test it yet)

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
