### ISSUE TITLE
Naming a list "Upload" results in `Error: There can be only one type named "Upload"`

### ISSUE THREAD

**Issue by mwcz** [keystonejs/keystone#3214]
# Bug report

## Describe the bug

When I name a list "Upload" and run `npm run dev`, I see the error:

```
Error: There can be only one type named "Upload".                              
    at assertValidSDL (/home/mwcz/projects/keystone-test/node_modules/graphql/validation/validate.js:108:11)
    at Object.buildASTSchema (/home/mwcz/projects/keystone-test/node_modules/graphql/utilities/buildASTSchema.js:71:34)
    at Object.buildSchemaFromTypeDefinitions (/home/mwcz/projects/keystone-test/node_modules/graphql-tools/dist/generate/buildSchemaFromTypeDefinitions.
js:25:28)                              
    at Object.makeExecutableSchema (/home/mwcz/projects/keystone-test/node_modules/graphql-tools/dist/makeExecutableSchema.js:26:29)
    at ApolloServer.initSchema (/home/mwcz/projects/keystone-test/node_modules/apollo-server-core/dist/ApolloServer.js:272:49)
    at new ApolloServerBase (/home/mwcz/projects/keystone-test/node_modules/apollo-server-core/dist/ApolloServer.js:194:30)
    at new ApolloServer (/home/mwcz/projects/keystone-test/node_modules/apollo-server-express/dist/ApolloServer.js:60:9)
    at createApolloServer (/home/mwcz/projects/keystone-test/node_modules/@keystonejs/app-graphql/lib/apolloServer.js:144:18)
    at GraphQLApp.prepareMiddleware (/home/mwcz/projects/keystone-test/node_modules/@keystonejs/app-graphql/index.js:23:20)
    at /home/mwcz/projects/keystone-test/node_modules/@keystonejs/keystone/lib/Keystone/index.js:697:17
    at Array.map (<anonymous>)
    at Keystone._prepareMiddlewares (/home/mwcz/projects/keystone-test/node_modules/@keystonejs/keystone/lib/Keystone/index.js:696:12)
    at Keystone.prepare (/home/mwcz/projects/keystone-test/node_modules/@keystonejs/keystone/lib/Keystone/index.js:714:36)
    at executeDefaultServer (/home/mwcz/projects/keystone-test/node_modules/@keystonejs/keystone/bin/utils.js:149:42)
```

## To Reproduce

1. `npm init keystone-app my-app`
2. Name: `my-app`
3. Choose "Starter (Users + Authentication)"
4. Mongo (test connection Yes)
5. Dependencies are installed with npm
6. cd my-app
7. Edit `index.js`, add the following createList call just below the existing createList call for Users.
```
keystone.createList("Upload", {
  fields: {
    name: {
      type: Text
    }
  }
});
```

Then run `npm run dev`.  The "there can only be one" error (see above) appears.

## Expected behaviour

Keystone server launches.

## System information

- OS: Fedora 30
- Node versions:
```
{
  '@keystonejs/example-projects-starter': '5.0.11',
  npm: '6.10.2',
  node: '12.9.1'
}
```

## Additional context

Changing the list name to anything besides "Upload" fixes the issue.

**Comment by MadeByMike** [comment]
Ooooh! Interesting. I wonder if we should re-name the default upload type something less... "clashy"

**Comment by mwcz** [comment]
`__Keystone_Internal_Upload_NO_COLLISION_SRSLY_NOT_EVEN_ONE__`

**Comment by gautamsi** [comment]
I would say `FileUploadType`

**Comment by mwcz** [comment]
I was totally joking about my last suggestion, any name seems fine to me, even keeping "Upload".  Whether the name is changed or not, it would be great if the error message could clarify that the conflict is with an internal type.  Something like `"Cannot create list, 'Upload' is a reserved name"`.
