### ISSUE TITLE
Running 'build' script intermittently throws error " Error: No executable schema named 'public' is available."

### ISSUE THREAD

**Issue by ra-external** [keystonejs/keystone#3216]
NOTE: This happens only intermittently.  Usually if I run `yarn build` a second time, it does not happen.

NOTE 2: I notice in my 'build' script that I'm using `NODE_ENV= development`.  This can't be right.   Should it be `NODE_ENV=production`?  Or does it matter?  I can't find any documentation on `keystone build`

When I run `yarn build`, which calls this script

```
    "build": "tsc && cross-env NODE_ENV=development NODE_OPTIONS=\"-r dotenv/config\"   keystone --entry=tsout/index.js build ",
```

I get the following error

```
 yarn build
yarn run v1.22.1
$ tsc && cross-env NODE_ENV=development NODE_OPTIONS="-r dotenv/config"   keystone --entry=tsout/index.js build 
ℹ Command: keystone build --entry=tsout/index.js
✔ Validated project entry file ./tsout/index.js
✔ Initialised Keystone instance
⠹ Exporting Keystone build to ./dist(node:96678) UnhandledPromiseRejectionWarning: Error: No executable schema named 'public' is available. Have you setup '@keystonejs/app-graphql'?
    at Keystone.executeGraphQL (/Users/ranthony/Documents/projects/yaa-cms-new/node_modules/@keystonejs/keystone/lib/Keystone/index.js:259:13)
    at Object.<anonymous> (/Users/ranthony/Documents/projects/yaa-cms-new/tsout/jobs/checkArticlePublishDates.js:44:53)
    at Generator.next (<anonymous>)
    at /Users/ranthony/Documents/projects/yaa-cms-new/tsout/jobs/checkArticlePublishDates.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/ranthony/Documents/projects/yaa-cms-new/tsout/jobs/checkArticlePublishDates.js:4:12)
    at CronJob.<anonymous> (/Users/ranthony/Documents/projects/yaa-cms-new/tsout/jobs/checkArticlePublishDates.js:24:54)
    at CronJob.fireOnTick (/Users/ranthony/Documents/projects/yaa-cms-new/node_modules/cron/lib/cron.js:600:23)
    at Timeout.callbackWrapper [as _onTimeout] (/Users/ranthony/Documents/projects/yaa-cms-new/node_modules/cron/lib/cron.js:667:10)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:96678) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:96678) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

My GraphQLApp setup in `/index.ts` is 

```
	new GraphQLApp({
			apollo: {
				introspection: true,
				validationRules: [validation.depthLimit(KEYSTONE_DEPTH_LIMIT), validation.fieldLimit(KEYSTONE_FIELD_LIMIT)]
			}
		}),
```

My Keystone versions are

```
  "@keystonejs/adapter-mongoose": "^8.1.3",
    "@keystonejs/app-admin-ui": "^7.0.4",
    "@keystonejs/app-graphql": "^5.1.8",
    "@keystonejs/app-next": "^5.2.0",
    "@keystonejs/app-static": "^5.1.2",
    "@keystonejs/auth-password": "^5.1.10",
    "@keystonejs/field-content": "^7.0.1",
    "@keystonejs/fields": "^13.0.1",
    "@keystonejs/fields-markdown": "^5.2.1",
    "@keystonejs/fields-wysiwyg-tinymce": "^5.3.1",
    "@keystonejs/file-adapters": "^7.0.0",
    "@keystonejs/keystone": "^11.1.1",
    "@keystonejs/list-plugins": "^7.0.2",
    "@keystonejs/oembed-adapters": "^5.1.4",
```
and I'm running NodeJS 12.14.0

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
