### ISSUE TITLE
w

### ISSUE THREAD

**Issue by wmertens** [keystonejs/keystone#3221]

**Comment by wmertens** [comment]
@JedWatson @jossmac I'm stumped here, this is very weird. Is there any way that json return (400) can be called by anything before the callback in create.js?

**Comment by wmertens** [comment]
I added a backtrace and the json object to the json call debug. There is a mongoose error that goes uncaught but sent as json and then the add itself.

```
  express:router <anonymous>  : /keystone/api/inline-relationships/create +1ms
validate
  mquery findOne +4ms users { _id: 5797ba8e66be184f5dbb61f6 } { fields: undefined }
validate 1
update
  express:response json +15ms Error: json
    at ServerResponse.json (/Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/express/lib/response.js:226:15)
    at /Users/wmertens/Documents/AeroFS/Projects/keystone/admin/server/api/item/update.js:9:35
    at /Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/mongoose/lib/model.js:3331:16
    at /Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/kareem/index.js:207:48
    at /Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/kareem/index.js:127:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9) { err: 'database error',
  detail: 
   { CastError: Cast to ObjectId failed for value "create" at path "_id"
       at MongooseError.CastError (/Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/mongoose/lib/error/cast.js:19:11)
       at ObjectId.cast (/Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/mongoose/lib/schema/objectid.js:147:13)
       at ObjectId.castForQuery (/Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/mongoose/lib/schema/objectid.js:187:15)
       at cast (/Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/mongoose/lib/cast.js:182:32)
       at Query.cast (/Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/mongoose/lib/query.js:2638:10)
       at Query.findOne (/Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/mongoose/lib/query.js:1281:10)
       at Function.findOne (/Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/mongoose/lib/model.js:1315:13)
       at Function.findById (/Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/mongoose/lib/model.js:1247:15)
       at module.exports (/Users/wmertens/Documents/AeroFS/Projects/keystone/admin/server/api/item/update.js:8:17)
       at Layer.handle [as handle_request] (/Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/express/lib/router/layer.js:95:5)
       at next (/Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/express/lib/router/route.js:131:13)
       at initList (/Users/wmertens/Documents/AeroFS/Projects/keystone/admin/server/middleware/initList.js:11:2)
       at Layer.handle [as handle_request] (/Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/express/lib/router/layer.js:95:5)
       at next (/Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/express/lib/router/route.js:131:13)
       at Route.dispatch (/Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/express/lib/router/route.js:112:3)
       at Layer.handle [as handle_request] (/Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/express/lib/router/layer.js:95:5)
     message: 'Cast to ObjectId failed for value "create" at path "_id"',
     name: 'CastError',
     kind: 'ObjectId',
     value: 'create',
     path: '_id',
     reason: undefined } }
  express:response header/set +3ms
  express:response send +0ms
  express:response header/set +0ms
  express:response header/set +0ms
  express:response header/set +1ms
  express-session touching +0ms
  express-session split response +0ms
  compression no compression: size below threshold +0ms
update 2
return
  express:response json +13ms Error: json
    at ServerResponse.json (/Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/express/lib/response.js:226:15)
    at /Users/wmertens/Documents/AeroFS/Projects/keystone/admin/server/api/list/create.js:20:8
    at /Users/wmertens/Documents/AeroFS/Projects/keystone/lib/list/updateItem.js:36:11
    at model.<anonymous> (/Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/mongoose/lib/document.js:1920:20)
    at next_ (/Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/hooks-fixed/hooks.js:89:34)
    at fnWrapper (/Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/hooks-fixed/hooks.js:186:18)
    at /Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/mongoose/lib/model.js:3331:16
    at /Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/mongoose/lib/model.js:228:5
    at /Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/mongoose/lib/model.js:135:7
    at /Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/mongodb/lib/collection.js:504:5
    at /Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/mongodb/lib/collection.js:666:5
    at handleCallback (/Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/mongodb/lib/utils.js:96:12)
    at /Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/mongodb/lib/bulk/unordered.js:473:9
    at handleCallback (/Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/mongodb/lib/utils.js:96:12)
    at resultHandler (/Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/mongodb/lib/bulk/unordered.js:420:5)
    at commandCallback (/Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/mongodb-core/lib/topologies/server.js:1194:9) { id: '5797bc6666be184f5dbb61fa',
  name: '5797bc6666be184f5dbb61fa',
  fields: { fieldA: undefined } }
  express:response send +7ms
  express:response header/set +0ms
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at ServerResponse.header (/Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/express/lib/response.js:728:10)
    at ServerResponse.send (/Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/express/lib/response.js:166:12)
    at ServerResponse.json (/Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/express/lib/response.js:253:15)
    at /Users/wmertens/Documents/AeroFS/Projects/keystone/admin/server/api/list/create.js:20:8
    at /Users/wmertens/Documents/AeroFS/Projects/keystone/lib/list/updateItem.js:36:11
    at model.<anonymous> (/Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/mongoose/lib/document.js:1920:20)
    at next_ (/Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/hooks-fixed/hooks.js:89:34)
    at fnWrapper (/Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/hooks-fixed/hooks.js:186:18)
    at /Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/mongoose/lib/model.js:3331:16
    at /Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/mongoose/lib/model.js:228:5
    at /Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/mongoose/lib/model.js:135:7
    at /Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/mongodb/lib/collection.js:504:5
    at /Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/mongodb/lib/collection.js:666:5
    at handleCallback (/Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/mongodb/lib/utils.js:96:12)
    at /Users/wmertens/Documents/AeroFS/Projects/keystone/node_modules/mongodb/lib/bulk/unordered.js:473:9

```

**Comment by wmertens** [comment]
This means that https://github.com/keystonejs/keystone/blob/master/admin/server/app/createDynamicRouter.js#L90 is being matched, instead of only https://github.com/keystonejs/keystone/blob/master/admin/server/app/createDynamicRouter.js#L85

I don't understand :(

**Comment by JedWatson** [comment]
@wmertens can you try reproducing this in `keystonejs/keystone-test-project`? I've been doing a lot of work in that and haven't seen this issue, so I wonder if it's somehow related to the way the e2e test app is running.
