### ISSUE TITLE
Error on signin

### ISSUE THREAD

**Issue by sylvainlap** [keystonejs/keystone#3222]
### Steps to reproduce the behavior
Clone keystone-test-project, and npm start it.
A click on "Got it, let's begin" throws a 500 error.

### Expected behavior
No 500 error ;)

### Actual behavior
```
Error thrown for request: /keystone/signin
TypeError: Cannot read property 'id' of undefined
    at SigninRoute (D:\DEV\WORKSPACE\keystone-test-project\node_modules\keystone\admin\server\routes\signin.js:17:16)
    at Layer.handle [as handle_request] (D:\DEV\WORKSPACE\keystone-test-project\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\DEV\WORKSPACE\keystone-test-project\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (D:\DEV\WORKSPACE\keystone-test-project\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\DEV\WORKSPACE\keystone-test-project\node_modules\express\lib\router\layer.js:95:5)
    at D:\DEV\WORKSPACE\keystone-test-project\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (D:\DEV\WORKSPACE\keystone-test-project\node_modules\express\lib\router\index.js:330:12)
    at next (D:\DEV\WORKSPACE\keystone-test-project\node_modules\express\lib\router\index.js:271:10)
    at next (D:\DEV\WORKSPACE\keystone-test-project\node_modules\express\lib\router\route.js:121:14)
    at exports.persist (D:\DEV\WORKSPACE\keystone-test-project\node_modules\keystone\lib\session.js:210:3)
    at Layer.handle [as handle_request] (D:\DEV\WORKSPACE\keystone-test-project\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\DEV\WORKSPACE\keystone-test-project\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (D:\DEV\WORKSPACE\keystone-test-project\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\DEV\WORKSPACE\keystone-test-project\node_modules\express\lib\router\layer.js:95:5)
    at D:\DEV\WORKSPACE\keystone-test-project\node_modules\express\lib\router\index.js:277:22
    at param (D:\DEV\WORKSPACE\keystone-test-project\node_modules\express\lib\router\index.js:349:14)
GET /keystone/signin 500 0.651 ms
```

The error comes from here:
https://github.com/keystonejs/keystone/blob/master/admin/server/routes/signin.js#L17

**Comment by mxstbr** [comment]
Are you using the `master` version or the `npm` version? The test project is currently up to date with the changes in master and won't work with the currently installable version on `npm`!

**Comment by sylvainlap** [comment]
I'm using the `master` version.
Here's my entry in `package.json`: `"keystone": "https://github.com/keystonejs/keystone.git",`.

**Comment by JedWatson** [comment]
Sorry about that - I fixed it almost immediately after it was introduced, but just realised my net failed while I was syncing the change up. It's working again.

**Comment by rturk** [comment]
I'm having this error after upgrading to beta4.3

/keystone/admin/server/routes/index.js:39:16)
