### ISSUE TITLE
`rels` may be undefined in postConnect but is not handled

### ISSUE THREAD

**Issue by Noviny** [keystonejs/keystone#3338]
# Bug report

## Describe the bug

When starting keystone with no relationships, the knex adapter throws an error in postConnect - it tries to run `rels.find` but in this instance `rels` is undefined.

```
✖ Connecting to database
Error: Cannot read property 'find' of undefined
    at resolveAllKeys (/Users/noviny/Development/40k-app/node_modules/@keystonejs/utils/dist/utils.cjs.dev.js:48:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async executeDefaultServer (/Users/noviny/Development/40k-app/node_modules/@keystonejs/keystone/bin/utils.js:114:3) {
  errors: {
    KnexAdapter: TypeError: Cannot read property 'find' of undefined
        at /Users/noviny/Development/40k-app/node_modules/@keystonejs/adapter-knex/lib/adapter-knex.js:278:31
        at Array.forEach (<anonymous>)
        at KnexListAdapter._postConnect (/Users/noviny/Development/40k-app/node_modules/@keystonejs/adapter-knex/lib/adapter-knex.js:277:24)
        at /Users/noviny/Development/40k-app/node_modules/@keystonejs/adapter-knex/lib/adapter-knex.js:69:19
        at Array.forEach (<anonymous>)
        at KnexAdapter.postConnect (/Users/noviny/Development/40k-app/node_modules/@keystonejs/adapter-knex/lib/adapter-knex.js:67:38)
        at KnexAdapter.connect (/Users/noviny/Development/40k-app/node_modules/@keystonejs/adapter-knex/node_modules/@keystonejs/keystone/lib/adapters/index.js:29:38)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async pReflect (/Users/noviny/Development/40k-app/node_modules/p-reflect/index.js:5:17)
        at async Promise.all (index 0)
        at async resolveAllKeys (/Users/noviny/Development/40k-app/node_modules/@keystonejs/utils/dist/utils.cjs.dev.js:40:19)
        at async executeDefaultServer (/Users/noviny/Development/40k-app/node_modules/@keystonejs/keystone/bin/utils.js:114:3)
  }
}
```

## To Reproduce

1. Run the keystone app starter
2. Select the first option for project type (Users + Authentication)
3. after npm install, run the `dev` command.
4. You should see the above error

## Expected behaviour

App is able to launch, even if there are no relationships

**Comment by timleslie** [comment]
This error was the result of a locally cached collection of `keystone` packages being used.
