### ISSUE TITLE
TinyMCE throws when navigating away from item

### ISSUE THREAD

**Issue by mxstbr** [keystonejs/keystone#3379]
When navigating away from an item that has something happening with TinyMCE (not 100% which field that is), TinyMCE throws this error and the admin interface breaks:

<details>
  <summary><code>tinymce.min.js:8 Uncaught TypeError: Cannot read property 'setAttribute' of undefined</code></summary>
  <pre>
    <code>
    tinymce.min.js:8 Uncaught TypeError: Cannot read property 'setAttribute' of undefined
    at t.aria (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:8:21429)
    at t.postRender (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:8:23245)
    at t.postRender (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:9:15953)
    at t.postRender (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:8:3514)
    at t.<anonymous> (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:8:11517)
    at Object.n [as each] (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:3:808)
    at t.each (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:8:11040)
    at t.exec (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:8:11489)
    at t.postRender (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:8:29788)
    at t.postRender (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:8:3514)
    at t.<anonymous> (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:8:11517)
    at Object.n [as each] (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:3:808)
    at t.each (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:8:11040)
    at t.exec (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:8:11489)
    at t.postRender (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:8:29788)
    at t.postRender (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:8:3514)
    at t.postRender (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:8:3514)
    at t.<anonymous> (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:8:11517)
    at Object.n [as each] (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:3:808)
    at t.each (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:8:11040)
    at t.exec (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:8:11489)
    at t.postRender (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:8:29788)
    at t.postRender (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:8:3514)
    at t.<anonymous> (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:8:11517)
    at Object.n [as each] (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:3:808)
    at t.each (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:8:11040)
    at t.exec (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:8:11489)
    at t.postRender (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:8:29788)
    at t.postRender (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:8:3514)
    at t.renderBefore (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:8:22352)
    at c (http://localhost:3000/keystone/js/lib/tinymce/themes/modern/theme.min.js:1:7811)
    at Object.u.renderUI (http://localhost:3000/keystone/js/lib/tinymce/themes/modern/theme.min.js:1:9125)
    at A.init (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:11:2208)
    at n.<anonymous> (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:10:31890)
    at Array.<anonymous> (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:4:10176)
    at n (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:3:808)
    at p (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:4:10153)
    at http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:4:10139
    at HTMLScriptElement.i (http://localhost:3000/keystone/js/lib/tinymce/tinymce.min.js:4:9165)
    </code>
  </pre>
</details>

*(click for full stack trace)*

**Comment by mxstbr** [comment]
Cannot replicate anymore, will close for now until I have a properly reproducible test case.
