### ISSUE TITLE
Unable to render list plugin view

### ISSUE THREAD

**Issue by devskope** [keystonejs/keystone#3396]
# Bug report

## Describe the bug

Getting an _"**Unable to render view**"_ error when using the `byTracking` plugins (byTracking / createdBy / createdAt):

```javascript
const { atTracking, createdBy } = require('@keystonejs/list-plugins');

module.exports = {
  ... // list config
  plugins: [
    atTracking({ format: 'MM/DD/YYYY' }), 
    createdBy()          // Unable to render view    
  ],
```

## Expected behaviour
`Created By` Field should be rendered on the Admin UI

### Expected:
![image](https://user-images.githubusercontent.com/40476712/90297045-3043fc80-de85-11ea-9bbd-d4ced2d2b523.png)

### Actual:
![image](https://user-images.githubusercontent.com/40476712/90295828-dee63e00-de81-11ea-8e72-028438ed6c8a.png)

## System information

- Browser chrome

Error:

```
Uncaught Invariant Violation: Could not find "client" in the context or passed in as an option. Wrap the root component in an <ApolloProvider>, or pass an ApolloClient instance in via options.
    at new InvariantError (http://localhost:3000/super/js/main.ce050558be2d30d55779.bundle.js:77887:28)
    at invariant (http://localhost:3000/super/js/main.ce050558be2d30d55779.bundle.js:77899:15)
    at QueryData.push.../../../@apollo/react-hooks/lib/react-hooks.esm.js.OperationData.refreshClient (http://localhost:3000/super/js/4.ce050558be2d30d55779.bundle.js:199:92)
    at QueryData.push.../../../@apollo/react-hooks/lib/react-hooks.esm.js.QueryData.execute (http://localhost:3000/super/js/4.ce050558be2d30d55779.bundle.js:262:14)
    at http://localhost:3000/super/js/4.ce050558be2d30d55779.bundle.js:548:95
    at useDeepMemo (http://localhost:3000/super/js/4.ce050558be2d30d55779.bundle.js:514:42)
    at useBaseQuery (http://localhost:3000/super/js/4.ce050558be2d30d55779.bundle.js:548:18)
    at useQuery (http://localhost:3000/super/js/4.ce050558be2d30d55779.bundle.js:568:12)
    at RelationshipSelect (http://localhost:3000/super/js/4.ce050558be2d30d55779.bundle.js:4657:75)
    at renderWithHooks (http://localhost:3000/super/js/main.ce050558be2d30d55779.bundle.js:48566:18)
InvariantError @ invariant.esm.js:12
invariant @ invariant.esm.js:24
push.../../../@apollo/react-hooks/lib/react-hooks.esm.js.OperationData.refreshClient @ react-hooks.esm.js:34
push.../../../@apollo/react-hooks/lib/react-hooks.esm.js.QueryData.execute @ react-hooks.esm.js:97
(anonymous) @ react-hooks.esm.js:383
useDeepMemo @ react-hooks.esm.js:349
useBaseQuery @ react-hooks.esm.js:383
useQuery @ react-hooks.esm.js:403
RelationshipSelect @ RelationshipSelect-bf12150c.esm.js:210
renderWithHooks @ react-dom.development.js:14803



The above error occurred in the <SetAsCurrentUser> component:
    in SetAsCurrentUser (created by RelationshipField)
    in div (created by Context.Consumer)
    in EmotionCssPropInternal (created by FieldInput)
    in FieldInput (created by RelationshipField)
    in div (created by Context.Consumer)
    in EmotionCssPropInternal (created by FieldContainer)
    in FieldContainer (created by RelationshipField)
    in RelationshipField (at Item/index.js:278)
    in ErrorBoundary (at Item/index.js:277)
    in Render (at Item/index.js:248)
    in form (created by Context.Consumer)
    in EmotionCssPropInternal (at Item/index.js:43)
    in Form (at Item/index.js:245)
    in ApolloProvider (at client/index.js:99)
    in HooksProvider (at client/index.js:98)
    in KeystoneAdminUI (at client/index.js:120)
    in AdminMetaProvider (at client/index.js:119)
    in Suspense (at client/index.js:118)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

**Comment by devskope** [comment]
Updating all keystone packages to latest versions solved this for me.
