### ISSUE TITLE
v4.0.0-beta Cannot find module underscore on fresh npm install

### ISSUE THREAD

**Issue by jstockwin** [keystonejs/keystone#3432]
### Steps to reproduce the behavior

I've just upgraded to keystone v4.0.0-beta, but my app is not starting. I've run npm install, and have also tried completely clearing node_modules and then running npm install again. 

### Expected behavior

Keystone should start.

### Actual behavior

```
> node keystone.js

module.js:457
    throw err;
    ^

Error: Cannot find module 'underscore'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Documents\Development\GitHub\robin-thompson\templates\views\helpers\index.js:2:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Documents\Development\GitHub\robin-thompson\keystone.js:27:12)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "start"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! robin-thompson@0.0.0 start: `node keystone.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the robin-thompson@0.0.0 start script 'node keystone.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the robin-thompson package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node keystone.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs robin-thompson
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls robin-thompson
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Documents\Development\GitHub\robin-thompson\npm-debug.log

Process finished with exit code 1
```

**Comment by JedWatson** [comment]
@jstockwin the way I'm reading this, your app (not keystone itself) is requiring `underscore` in this file:

```
robin-thompson\templates\views\helpers\index.js
```

It may be the case that Keystone 3 or one of its dependencies included underscore in a way that made it available to your project, coincidentally?

You should be able to fix this by running `npm install --save underscore`

You may also want to consider replacing `underscore` with `lodash`.

Let me know if this fixes it for you!

**Comment by jstockwin** [comment]
@JedWatson I guess so, however this app was generated by generator-keystone... I've not actually created that file. 

I've installed underscore for now, so happy for you to close this. I feel like lots of people may have this issue though.

**Comment by JedWatson** [comment]
I'll add a note to the upgrade guide, sounds like this is a longstanding bug in the generator that wasn't noticed until now.
