### ISSUE TITLE
GraphQLError [Object]: Syntax Error: Expected ":", found "(".

### ISSUE THREAD

**Issue by chtonal** [keystonejs/keystone#3437]
# Bug report

```i Command: keystone dev
√ Validated project entry file ./index.js
√ Keystone server listening on port 3000
√ Initialised Keystone instance
× Initialising Keystone instance
GraphQLError [Object]: Syntax Error: Expected ":", found "(".
    at syntaxError (D:\Projects\development\Protrans\node_modules\graphql\error\syntaxError.js:15:10)
    at Parser.expectToken (D:\Projects\development\Protrans\node_modules\graphql\language\parser.js:1423:40)
    at Parser.parseInputValueDef (D:\Projects\development\Protrans\node_modules\graphql\language\parser.js:902:10)
    at Parser.optionalMany (D:\Projects\development\Protrans\node_modules\graphql\language\parser.js:1516:28)
    at Parser.parseInputFieldsDefinition (D:\Projects\development\Protrans\node_modules\graphql\language\parser.js:1066:17)
    at Parser.parseInputObjectTypeDefinition (D:\Projects\development\Protrans\node_modules\graphql\language\parser.js:1050:23)
    at Parser.parseTypeSystemDefinition (D:\Projects\development\Protrans\node_modules\graphql\language\parser.js:714:23)
    at Parser.parseDefinition (D:\Projects\development\Protrans\node_modules\graphql\language\parser.js:144:23)
    at Parser.many (D:\Projects\development\Protrans\node_modules\graphql\language\parser.js:1537:26)
    at Parser.parseDocument (D:\Projects\development\Protrans\node_modules\graphql\language\parser.js:109:25)
    at parse (D:\Projects\development\Protrans\node_modules\graphql\language\parser.js:36:17)
    at parseDocument (D:\Projects\development\Protrans\node_modules\graphql-tag\lib\graphql-tag.umd.js:135:16)
    at gql (D:\Projects\development\Protrans\node_modules\graphql-tag\lib\graphql-tag.umd.js:176:10)
    at D:\Projects\development\Protrans\node_modules\@keystonejs\keystone\lib\Keystone\index.js:533:17
    at Array.map (<anonymous>)
    at Keystone.getTypeDefs (D:\Projects\development\Protrans\node_modules\@keystonejs\keystone\lib\Keystone\index.js:533:8) {
  message: 'Syntax Error: Expected ":", found "(".',
  locations: [ { line: 13, column: 21 } ]
}```
## Describe the bug

```
"dependencies": {
		"@apollo/react-hooks": "^3.1.5",
		"@apollo/react-ssr": "^3.1.5",
		"@hapi/joi": "^17.1.1",
		"@keystonejs/adapter-mongoose": "^9.0.3",
		"@keystonejs/app-admin-ui": "^7.3.2",
		"@keystonejs/app-graphql": "^6.1.0",
		"@keystonejs/app-graphql-playground": "^5.1.5",
		"@keystonejs/app-next": "^5.2.1",
		"@keystonejs/app-schema-router": "^5.1.1",
		"@keystonejs/app-static": "^5.1.2",
		"@keystonejs/auth-password": "^5.1.14",
		"@keystonejs/field-content": "^7.0.3",
		"@keystonejs/fields": "^15.0.0",
		"@keystonejs/fields-authed-relationship": "^1.0.11",
		"@keystonejs/fields-datetime-utc": "^6.0.4",
		"@keystonejs/fields-markdown": "^5.2.5",
		"@keystonejs/fields-wysiwyg-tinymce": "^5.3.6",
		"@keystonejs/file-adapters": "^7.0.3",
		"@keystonejs/keystone": "^13.1.1",
		"@keystonejs/list-plugins": "^7.1.0",
		"@keystonejs/server-side-graphql-client": "^1.1.1",
		"@material-ui/core": "^4.11.0",
		"@material-ui/icons": "^4.9.1",
		"apollo-cache-inmemory": "^1.6.6",
		"apollo-client": "^2.6.10",
		"apollo-server-express": "^2.16.1",
		"apollo-upload-client": "^13.0.0",
		"bootstrap": "^4.5.0",
		"classnames": "^2.2.6",
		"connect-mongo": "^3.2.0",
		"cross-env": "^7.0.2",
		"crypt": "^0.0.2",
		"date-fns": "^2.14.0",
		"framer-motion": "^2.3.0",
		"graphql": "^15.3.0",
		"graphql-tag": "^2.10.4",
		"isomorphic-unfetch": "^3.0.0",
		"jquery": "^3.5.1",
		"lodash": "^4.17.19",
		"mdbreact": "^4.27.0",
		"moment": "^2.27.0",
		"next": "^9.5.1",
		"nextjs-redirect": "^4.0.2",
		"node-sass": "^4.14.1",
		"nouislider": "^14.6.0",
		"path": "^0.12.7",
		"popper.js": "^1.16.1",
		"prop-types": "^15.7.2",
		"range_check": "^2.0.3",
		"react": "^16.13.1",
		"react-datetime": "^2.16.3",
		"react-datocms": "^1.2.5",
		"react-dom": "^16.13.1",
		"react-image-lightbox": "^5.1.1",
		"react-markdown": "^4.3.1",
		"react-slick": "^0.26.1",
		"react-swipeable-views": "^0.13.9",
		"react-toast-notifications": "^2.4.0",
		"react-use-form-state": "^0.13.1",
		"remark": "^12.0.0",
		"remark-html": "^11.0.2",
		"sitemap": "^6.2.0",
		"slugify": "^1.4.4",
		"styled-components": "^5.1.1",
		"transliteration": "^2.1.11"
	}
```

Today i bumped keystone and all its packages to latest versions. However before upgrading to latest versions my project was working. After upgrading i am getting such an error. I did not understand wher does it come from. I had not made any changes on the project files.

Does anybody explain where its is coming from? Thanks

**Comment by chtonal** [comment]
I made a fresh install and it has gone
