### ISSUE TITLE
Unable to rename User model

### ISSUE THREAD

**Issue by zapbuild** [keystonejs/keystone#3445]
Hi,
For some reason I have to rename my User model to Member model. I have already defined this in 

```js
keystone.init({
    'name': 'Airbots',
    'brand': 'Airbots',
    'less': 'public',
    'static': 'public',
    'favicon': 'public/favicon.ico',
    'views': 'templates/views',
    'view engine': 'jade',
    'emails': 'templates/emails',
    'auto update': true,
    'session': true,
    'auth': true,
    **'user model': 'Member',**
    'cookie secret': 'ASDsdfasdfASDfEWrWEQgSfdgFSDgghSdfGSD23',
    'session store': 'mongo'
});
```

But its not working. When I start keystone it show the following error stack:

```
/var/www/html/airbots/node_modules/keystone/lib/core/list.js:12
	if (!ret) throw new ReferenceError('Unknown keystone list ' + JSON.stringify(arg));
	          ^

ReferenceError: Unknown keystone list "User"
    at list (/var/www/html/airbots/node_modules/keystone/lib/core/list.js:12:18)
    at Object.<anonymous> (/var/www/html/airbots/routes/views/auth/forgotpassword.js:1:115)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /var/www/html/airbots/node_modules/keystone/lib/core/importer.js:42:23
    at Array.forEach (native)
    at importer (/var/www/html/airbots/node_modules/keystone/lib/core/importer.js:32:26)
    at /var/www/html/airbots/node_modules/keystone/lib/core/importer.js:36:22
    at Array.forEach (native)
    at importer (/var/www/html/airbots/node_modules/keystone/lib/core/importer.js:32:26)
    at Object.<anonymous> (/var/www/html/airbots/keystone.js:94:12)
    at Module._compile (module.js:409:26)
```

Please help.
Thanks!

**Comment by creynders** [comment]
AFAIK there's no `forgotpassword.js` in keystone or generator-keystone. I.e. it should be a file you've created (or copied) from somewhere. Probably it has a hard-coded reference to the "User" model.

**Comment by reachdevelopers** [comment]
Same issue here, I rename the "Y" model to proper name "User" and got the same error above.

**Comment by reachdevelopers** [comment]
well now I know what happen "yo keystone" is run you are confirming most of the time and when it gets to the part where it ask you if you want to create a users model you type Y instead of typing User.
