### ISSUE TITLE
Issue upgrading project to Keystone 4.0

### ISSUE THREAD

**Issue by briviere** [keystonejs/keystone#3454]
Hello

The npm 4.0 upgrade worked fine for me. Just that I'm getting the follow error at startup.  The file image is there on cloudinary. 

Error: ENOENT: no such file or directory, stat '/home/brian/keystone-realestate-template/http:confused:res.cloudinary.com/homnj3fqa/image/upload/c_scale,w_213/v1458418951/logo_rwc3z8.ico'
at Error (native)
at Object.fs.statSync (fs.js:981:18)
at favicon (/home/brian/keystone-realestate-template/node_modules/serve-favicon/index.js:64:15)

**Comment by briviere** [comment]
I deleted the favicon entry from keystone.js and that resolved my issue.

thanks

Brian
