### ISSUE TITLE
Broken moduleRoot in index.js

### ISSUE THREAD

**Issue by promethe42** [keystonejs/keystone#3564]
### Steps to reproduce the behavior

```
npm install --save-dev jest
```

```
/src # your KeystoneJS nodejs code 
/test
  /index.test.js
```

```javascript
// index.test.js
var keystone = require('keystone');
```

Run the tests with `jest`.

### Expected behavior

The `keystone` JS is properly imported.

### Actual behavior

```
TypeError: Cannot read property '0' of undefined
      at Object.<anonymous> (../../node_modules/keystone/index.js:18:39)
      at Object.<anonymous> (test/index.test.js:2:16)
      at process._tickCallback (node.js:369:9)
```

### Fix

```javascript
var moduleRoot = (function (_rootPath) {
	var parts = _rootPath.split(path.sep);
	parts.pop(); // get rid of /node_modules from the end of the path
	return parts.join(path.sep);
})(module.parent ? module.parent.paths[0] : module.paths[0]);
```

should be:

```javascript
var moduleRoot = (function (_rootPath) {
	var parts = _rootPath.split(path.sep);
	parts.pop(); // get rid of /node_modules from the end of the path
	return parts.join(path.sep);
})(module.parent && module.parent.path ? module.parent.paths[0] : module.paths[0]);
```

### Workaround

```javascript
// index.test.js
delete module.parent; // ouch...
var keystone = require('keystone');
```

**Comment by jstockwin** [comment]
@promethe42 Would you mind submitting a PR for this?

**Comment by aoc** [comment]
@promethe42 did you find any workaround to this issue?
Any reason not to apply your fix?

**Comment by ChrisWphoto** [comment]
Jest doesn't seem to play nice with Keystone even after fixing this. I am having trouble loading models via keystone.list() when I run the test using Jest.
