### ISSUE TITLE
LocationGoogle field error on startup

### ISSUE THREAD

**Issue by LiamAttClarke** [keystonejs/keystone#3575]
# Bug report

## Describe the bug

After adding a LocationGoogle field the application crashes on startup with the following error:
```
✖ Initialising Keystone instance
admin_1           | GraphQLError [Object]: Syntax Error: Expected ":", found "(".
admin_1           |     at syntaxError (/usr/src/node_modules/graphql/error/syntaxError.js:15:10)
admin_1           |     at Parser.expectToken (/usr/src/node_modules/graphql/language/parser.js:1423:40)
admin_1           |     at Parser.parseInputValueDef (/usr/src/node_modules/graphql/language/parser.js:902:10)
admin_1           |     at Parser.optionalMany (/usr/src/node_modules/graphql/language/parser.js:1516:28)
admin_1           |     at Parser.parseInputFieldsDefinition (/usr/src/node_modules/graphql/language/parser.js:1066:17)
admin_1           |     at Parser.parseInputObjectTypeDefinition (/usr/src/node_modules/graphql/language/parser.js:1050:23)
admin_1           |     at Parser.parseTypeSystemDefinition (/usr/src/node_modules/graphql/language/parser.js:714:23)
admin_1           |     at Parser.parseDefinition (/usr/src/node_modules/graphql/language/parser.js:144:23)
admin_1           |     at Parser.many (/usr/src/node_modules/graphql/language/parser.js:1537:26)
admin_1           |     at Parser.parseDocument (/usr/src/node_modules/graphql/language/parser.js:109:25)
admin_1           |     at parse (/usr/src/node_modules/graphql/language/parser.js:36:17)
admin_1           |     at parseDocument (/usr/src/node_modules/apollo-server-core/node_modules/graphql-tag/lib/graphql-tag.umd.js:135:16)
admin_1           |     at gql (/usr/src/node_modules/apollo-server-core/node_modules/graphql-tag/lib/graphql-tag.umd.js:176:10)
admin_1           |     at /usr/src/node_modules/@keystonejs/keystone/lib/Keystone/index.js:533:17
admin_1           |     at Array.map (<anonymous>)
admin_1           |     at Keystone.getTypeDefs (/usr/src/node_modules/@keystonejs/keystone/lib/Keystone/index.js:533:8) {
admin_1           |   message: 'Syntax Error: Expected ":", found "(".',
admin_1           |   locations: [ { line: 5, column: 21 } ]
admin_1           | }
admin_1           | [nodemon] app crashed - waiting for file changes before starting...
```

## To Reproduce

My list:
```
import { Text } from '@keystonejs/fields';
import { LocationGoogle } from '@keystonejs/fields-location-google';

export default {
  adminConfig: {
    defaultColumns: 'name',
  },
  fields: {
    name: { type: Text, isRequired: true },
    location: { type: LocationGoogle, googleMapsKey: 'SUPER_SECRET_KEY' },
  },
};

``` 

## Expected behaviour

Following the documentation for LocationGoogle field should work :).

## System information

- OS: Pop!_OS (https://pop.system76.com/)

**Comment by Vultraz** [comment]
I can't reproduce this 🤔

**Comment by LiamAttClarke** [comment]
I have resolved the issue. It appears to have been a `graphql` version mismatch.
