### ISSUE TITLE
version 4.0.0-beta.1  does not work in heroku

### ISSUE THREAD

**Issue by jiangfeng0103** [keystonejs/keystone#3593]
**heroku log**

2016-10-12T11:21:09.294317+00:00 app[web.1]: Error thrown for request: /
2016-10-12T11:21:09.294652+00:00 app[web.1]: Error: Cannot find module 'jade'
2016-10-12T11:21:09.294654+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:339:15)
2016-10-12T11:21:09.294655+00:00 app[web.1]:     at Function.Module._load (module.js:290:25)
2016-10-12T11:21:09.294655+00:00 app[web.1]:     at Module.require (module.js:367:17)
2016-10-12T11:21:09.294656+00:00 app[web.1]:     at require (internal/module.js:20:19)
2016-10-12T11:21:09.294657+00:00 app[web.1]:     at new View (/app/node_modules/express/lib/view.js:78:30)
2016-10-12T11:21:09.294658+00:00 app[web.1]:     at EventEmitter.render (/app/node_modules/express/lib/application.js:569:12)
2016-10-12T11:21:09.294659+00:00 app[web.1]:     at ServerResponse.render (/app/node_modules/express/lib/response.js:960:7)
2016-10-12T11:21:09.294660+00:00 app[web.1]:     at View.<anonymous> (/app/node_modules/keystone/lib/view.js:330:13)
2016-10-12T11:21:09.294661+00:00 app[web.1]:     at /app/node_modules/keystone/lib/view.js:365:3
2016-10-12T11:21:09.294661+00:00 app[web.1]:     at /app/node_modules/keystone/node_modules/async/dist/async.js:486:20
2016-10-12T11:21:09.294662+00:00 app[web.1]:     at replenish (/app/node_modules/keystone/node_modules/async/dist/async.js:879:29)
2016-10-12T11:21:09.294663+00:00 app[web.1]:     at iterateeCallback (/app/node_modules/keystone/node_modules/async/dist/async.js:869:21)
2016-10-12T11:21:09.294663+00:00 app[web.1]:     at /app/node_modules/keystone/node_modules/async/dist/async.js:847:20
2016-10-12T11:21:09.294664+00:00 app[web.1]:     at /app/node_modules/keystone/node_modules/async/dist/async.js:3679:13
2016-10-12T11:21:09.294665+00:00 app[web.1]:     at /app/node_modules/keystone/node_modules/async/dist/async.js:952:25
2016-10-12T11:21:09.294666+00:00 app[web.1]:     at eachOfArrayLike (/app/node_modules/keystone/node_modules/async/dist/async.js:990:13)
2016-10-12T11:21:09.295910+00:00 app[web.1]: GET / 500 1.678 ms

**Comment by laurenskling** [comment]
4.0.0-beta.1 works fine for me on Heroku.
It seems to me you haven't put `jade` in your package.json
