### ISSUE TITLE
Initial project setup error

### ISSUE THREAD

**Issue by rahul606** [keystonejs/keystone#3830]
### Steps to reproduce 
Just following the steps from keystonejs.com to setup default project by running KeystoneJS generator on macOS Sierra 10.12.2

### Expected behavior
node keystone should run

### Actual behavior
{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/rahultomar/Documents/pronteo-keystone/node_modules/mongodb/node_modules/bson/ext/index.js:15:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/rahultomar/Documents/pronteo-keystone/node_modules/mongodb/node_modules/bson/lib/bson/index.js:3:24)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version

**Comment by bassjacob** [comment]
Hi Rahul, thanks for reporting this. When I've seen this error in the past, the node process still ran, it just reported this as an error.

Can you please confirm that the node process actually crashes on this error? Can you also please include the output of;
```
node -v
npm ls mongoose
npm ls keystone
```

Thanks :smile:

**Comment by rahul606** [comment]
Hi @bassjacob thx for the reply. I have solved the problem yesterday only and forgot to close the issue. I figured out that problem was because of latest version of nodejs instead of LTS version.
