### ISSUE TITLE
500 error on 4.0 beta4

### ISSUE THREAD

**Issue by freew01f** [keystonejs/keystone#3861]
every time I restart keystone, when I access /keystone/xxx  first time
I get 500 error, but when I refresh it, it will be ok~
```
Error thrown for request: /keystone/projects
ReferenceError: Unknown keystone list undefined
    at Keystone.list (/Users/freewolf/Documents/Project/free_project/node_modules/.4.0.0-beta.4@keystone/lib/core/list.js:7:21)
    at relationship.isValid (/Users/freewolf/Documents/Project/free_project/node_modules/.4.0.0-beta.4@keystone/fields/types/relationship/RelationshipType.js:249:19)
    at relationship.<anonymous> (/Users/freewolf/Documents/Project/free_project/node_modules/.4.0.0-beta.4@keystone/fields/types/Type.js:109:12)
    at Array.forEach (native)
    at relationship.Field.getOptions (/Users/freewolf/Documents/Project/free_project/node_modules/.4.0.0-beta.4@keystone/fields/types/Type.js:108:14)
    at /Users/freewolf/Documents/Project/free_project/node_modules/.4.0.0-beta.4@keystone/lib/list/getOptions.js:42:42
    at arrayEach (/Users/freewolf/Documents/Project/free_project/node_modules/.4.16.5@lodash/lodash.js:530:11)
    at Function.forEach (/Users/freewolf/Documents/Project/free_project/node_modules/.4.16.5@lodash/lodash.js:9320:14)
    at List.getOptions (/Users/freewolf/Documents/Project/free_project/node_modules/.4.0.0-beta.4@keystone/lib/list/getOptions.js:37:4)
    at /Users/freewolf/Documents/Project/free_project/node_modules/.4.0.0-beta.4@keystone/admin/server/routes/index.js:11:21
    at /Users/freewolf/Documents/Project/free_project/node_modules/.4.16.5@lodash/lodash.js:4939:15
    at baseForOwn (/Users/freewolf/Documents/Project/free_project/node_modules/.4.16.5@lodash/lodash.js:2988:24)
    at /Users/freewolf/Documents/Project/free_project/node_modules/.4.16.5@lodash/lodash.js:4908:18
    at Function.forEach (/Users/freewolf/Documents/Project/free_project/node_modules/.4.16.5@lodash/lodash.js:9320:14)
    at IndexRoute (/Users/freewolf/Documents/Project/free_project/node_modules/.4.0.0-beta.4@keystone/admin/server/routes/index.js:10:4)
    at Layer.handle [as handle_request] (/Users/freewolf/Documents/Project/free_project/node_modules/.4.14.0@express/lib/router/layer.js:95:5)
```

**Comment by FOLLGAD** [comment]
having the same problem

**Comment by bassjacob** [comment]
Is the project available as a repository somewhere? Or can you post the file where you initialise keystone (likely keystone.js)?

**Comment by IgorKhromov** [comment]
I had received this error after add track: true option to any already existing schemas.
const Service = new keystone.List('Service', {
  track: true
});
version 4.0.0-beta.5

**Comment by JedWatson** [comment]
@gwyneplaine can you please try and reproduce this in the test project? it may be a blocker for 4.0

**Comment by gwyneplaine** [comment]
Hey @freew01f @IgorKhromov, trying to replicate this issue. 
Would appreciate it greatly if you could let me know the following: 
- Which version of node are you using?
- Which version of npm are you using? 
- What were the exact steps leading up to the failure case? 

Thanks :)!

**Comment by jumasheff** [comment]
@gwyneplaine I think this is related: http://demo.keystonejs.com/blog/post/hello-world (Error 500)

**Comment by langovoi** [comment]
I think problem is `browserify`. When set `DEBUG=*` you can see that on first request `babel` doing much work.

I found poor resolution - `KEYSTONE_PREBUILD_ADMIN=true`
https://github.com/keystonejs/keystone/blob/375c0a5db475bce63ca07c85cf0def10ffdf31c2/admin/server/app/createStaticRouter.js#L63

**Comment by Noviny** [comment]
Closing this issue as not reproduced. Please reopen if it is still a problem/still needs addressing.
