### ISSUE TITLE
Keystone doesn't start after Node update

### ISSUE THREAD

**Issue by kimasendorf** [keystonejs/keystone#3925]
I am running keystone 0.3.19 and I just installed Node 7.4.0 after previously using 6.9.0.
Now I am no longer able to start the server. The terminal output just shows the bson error:

```
{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/HDD/Users/kimasendorf/Development/Node/bromer-kunst/node_modules/bson/ext/index.js:15:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/HDD/Users/kimasendorf/Development/Node/bromer-kunst/node_modules/bson/lib/bson/index.js:3:24)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
```

And stops there..

Any ideas how I could find the bug?

**Comment by Lurk** [comment]
Have same issue

**Comment by Lurk** [comment]
@kimasendorf #3798

**Comment by kimasendorf** [comment]
so you have manually installed the latest mongoose version via npm?

**Comment by Lurk** [comment]
@kimasendorf I update mongoose version in 
```
node_modules/keystone/package.json +110
```

to 4.7.7  
and then:

```
npm i
```

I am not sure yet if it not add some new bugs :)

**Comment by jhamPac** [comment]
@Lurk your solution worked for me too

mongoose need to be updated in keystone/package.json

**Comment by jaehoo** [comment]
Thanks! I have the same problem and now the webapp run without errors.

**Comment by troystarwalt** [comment]
@jaehoo I was able to fix this error by changing the version of Node to 6.9.5.

**Comment by kimasendorf** [comment]
@troystarwalt down grading node is not a fix

**Comment by thejameskyle** [comment]
If all that needs to happen is a mongoose update we should do that. Anyone want to open a PR?

**Comment by kraigh** [comment]
I'm experiencing this same issue and am considering updating Mongoose to 4.x, has anyone had any issues running Keystone 0.3x with Mongoose 4.x?

**Comment by tylerFowler** [comment]
+1 on moving back down to node `6.11.2` from 8.x. Should probably add to documentation somewhere that node 8.x isn't supported.

**Comment by Noviny** [comment]
Closing this as a known keystone 0.3 problem. We are no longer actively developing for 0.3. Updating mongoose yourself is the recommended fix if anyone else runs into this problem.

We recommend upgrading to 4 if you can (the upgrade is quite small, and upgrade docs can be found [here](http://keystonejs.netlify.com/guides/v-0-3-to-v-4-0-upgrade-guide).
