### ISSUE TITLE
KnexAdapter: TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by karimkawambwa** [keystonejs/keystone#3994]
# Bug report

## Describe the bug

Starting a new project and running `keystone dev` results in the error `Error: Cannot read property 'find' of undefined`. Looks like the passed down `refs` is undefined at times. 

The changes was here -> https://github.com/keystonejs/keystone/commit/ca28681ca23c74bc57041fa36c20b93a4520e762

## To Reproduce

Create a project using create-keystone-app with the knex adapter.
Run dev mode `keystone dev`

## Expected behaviour

The app to start.

## System information

node 14.14.0

## Additional context

```
backend_1   | 
backend_1   | > research-backend@5.0.3 dev /src
backend_1   | > keystone dev
backend_1   | 
backend_1   | - Initialising Keystone CLI
backend_1   | ℹ Command: keystone dev
backend_1   | -  
backend_1   | ✔ Validated project entry file ./index.js
backend_1   | -  
backend_1   | ✔ Keystone server listening on port 3000
backend_1   | ✔ Initialised Keystone instance
backend_1   | - Connecting to database
backend_1   | ✖ Connecting to database
backend_1   | Error: Cannot read property 'find' of undefined
backend_1   |     at resolveAllKeys (/src/node_modules/@keystonejs/utils/dist/utils.cjs.dev.js:54:19)
backend_1   |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
backend_1   |     at async executeDefaultServer (/src/node_modules/@keystonejs/keystone/bin/utils.js:114:3) {
backend_1   |   errors: {
backend_1   |     KnexAdapter: TypeError: Cannot read property 'find' of undefined
backend_1   |         at /src/node_modules/@keystonejs/adapter-knex/lib/adapter-knex.js:276:31
backend_1   |         at Array.forEach (<anonymous>)
backend_1   |         at KnexListAdapter._postConnect (/src/node_modules/@keystonejs/adapter-knex/lib/adapter-knex.js:275:24)
backend_1   |         at /src/node_modules/@keystonejs/adapter-knex/lib/adapter-knex.js:68:19
backend_1   |         at Array.forEach (<anonymous>)
backend_1   |         at KnexAdapter.postConnect (/src/node_modules/@keystonejs/adapter-knex/lib/adapter-knex.js:67:38)
backend_1   |         at KnexAdapter.connect (/src/node_modules/@keystonejs/adapter-knex/node_modules/@keystonejs/keystone/lib/adapters/index.js:29:38)
backend_1   |         at processTicksAndRejections (internal/process/task_queues.js:93:5)
backend_1   |         at async Object.pReflect [as default] (/src/node_modules/p-reflect/index.js:5:17)
backend_1   |         at async Promise.all (index 0)
backend_1   |         at async resolveAllKeys (/src/node_modules/@keystonejs/utils/dist/utils.cjs.dev.js:46:19)
backend_1   |         at async executeDefaultServer (/src/node_modules/@keystonejs/keystone/bin/utils.js:114:3)
backend_1   |   }
backend_1   | }
backend_1   | npm ERR! code ELIFECYCLE
backend_1   | npm ERR! errno 1
backend_1   | npm ERR! research-backend@5.0.3 dev: `keystone dev`
backend_1   | npm ERR! Exit status 1
backend_1   | npm ERR! 
backend_1   | npm ERR! Failed at the research-backend@5.0.3 dev script.
backend_1   | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
backend_1   | 
backend_1   | npm ERR! A complete log of this run can be found in:
backend_1   | npm ERR!     /root/.npm/_logs/2020-10-20T02_09_51_836Z-debug.log
```

https://github.com/keystonejs/keystone/issues/2588
https://github.com/keystonejs/keystone/issues/3338

**Comment by karimkawambwa** [comment]
🤦🏾‍♂️  I was using older versions
