### ISSUE TITLE
Error AdminUI on Heroku Cannot read property 'content' of undefined

### ISSUE THREAD

**Issue by jbmarflo** [keystonejs/keystone#4017]
I deployed "@keystonejs/keystone": "^17.0.0",

When I log on, then appear error 500
I think the problem is that it dont find the files to show Admin UI.

`const APP = [
	new GraphQLApp(),
	new AdminUIApp({
		name: 'Revista',
        adminPath: '/admin',
		enableDefaultRoute: false, authStrategy }),

]`

`2020-10-22T19:06:08.635102+00:00 app[web.1]: at asyncData (src/pages/_article/index.vue:398:0)
2020-10-22T19:06:08.635103+00:00 app[web.1]: at runMicrotasks (<anonymous>)
2020-10-22T19:06:08.635104+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-10-22T19:06:08.635104+00:00 app[web.1]: 
2020-10-22T19:06:08.635689+00:00 app[web.1]: (node:30) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'content' of undefined
2020-10-22T19:06:08.635689+00:00 app[web.1]: at asyncData (src/pages/_article/index.vue:398:0)
2020-10-22T19:06:08.635690+00:00 app[web.1]: at runMicrotasks (<anonymous>)
2020-10-22T19:06:08.635690+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-10-22T19:06:08.635749+00:00 app[web.1]: (node:30) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise 
`

**Comment by bladey** [comment]
**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old issues such as this one. If you feel this issue is still relevant for **Keystone Next**, please let us know.
