### ISSUE TITLE
Server is running But still get an error when starting

### ISSUE THREAD

**Issue by FernandoBoza** [keystonejs/keystone#4062]
Build Mac OS Sierra 10.12.3
Node -v 6.9.5
mongoose@3.8.40
keystone@0.3.22 
Mongo 3.4.2

### Steps to reproduce the behavior
Node Keystone
### Expected behavior
Running Smoothly
### Actual behavior

{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/fernandoboza/Desktop/KeyStone_Site/snapsite/node_modules/bson/ext/index.js:15:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/fernandoboza/Desktop/KeyStone_Site/snapsite/node_modules/bson/lib/bson/index.js:3:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version

KeystoneJS Started:
SnapSite is ready on port 3000

**Comment by juangl** [comment]
Same problem.

I think it's mongoose-related. When I run `npm install` I get the next warning:
```
warning keystone > mongoose > mongodb@1.4.38: Please upgrade to 2.2.19 or higher
```

And mongodb is who use Bson.

**Comment by Noviny** [comment]
@JedWatson talked about this on #1752. Unfortunately this isn't solvable for keystone 3.

Closing this. Feel free to ask any more questions about this.

**Comment by sdutta5264** [comment]
### 

> 

> [`_****_`](

- 

- [ ] @1. url

)
