### ISSUE TITLE
Error R10 - (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch

### ISSUE THREAD

**Issue by SiriMhM** [keystonejs/keystone#4282]
Hey, 

I am trying to get keystonejs git project run as a new App in my heroku free account.

I have used the keystonejs deploy button on github and keystonejs has been deployed.
It did not start so I found out that I had to change a config variable in Heroku.
So I went to "Settings" -> Config Variables and deleted the old "MONGO_URI" variable and replaced it with "MONGOLAB_URL" with the copied value. This seems to be the first fix for that.

But now I am having trouble with the port binding.

If I take a look at the log I can see the following:

```
2017-05-11T04:20:30.237787+00:00 app[web.1]:     at Module.require (module.js:498:17)
2017-05-11T04:20:30.237787+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-05-11T04:20:30.237788+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/mongoose/node_modules/bson/lib/bson/index.js:3:24)
2017-05-11T04:20:30.237788+00:00 app[web.1]:     at Module._compile (module.js:571:32)
2017-05-11T04:20:30.237790+00:00 app[web.1]:     at Module.load (module.js:488:32) code: 'MODULE_NOT_FOUND' }
2017-05-11T04:20:30.237789+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:580:10)
2017-05-11T04:20:30.237936+00:00 app[web.1]: js-bson: Failed to load c++ bson extension, using pure JS version
2017-05-11T04:21:25.354872+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2017-05-11T04:21:25.355090+00:00 heroku[web.1]: Stopping process with SIGKILL
2017-05-11T04:21:25.494038+00:00 heroku[web.1]: Process exited with status 137
2017-05-11T04:21:25.505588+00:00 heroku[web.1]: State changed from starting to crashed

```
I did a lot of research and found many "fixes" for this problem, but they are all very old and do not seem to work.
As I found out, Heroku sets a port for the app dynamically, so it is not possible to use another one.
But what I actually understood is, that keystonejs already reads out this port dynamically in the code, via process.env.PORT.

What Is the correct way to fix it? Is this a startup problem (booting takes to long) ? Or do I have to change some keystonejs code, to get it work? I really don't have any idea any more.

**Comment by export-mike** [comment]
hi what does your keystone.js file look like?

**Comment by SiriMhM** [comment]
@export-mike 
```
// Simulate config options from your production environment by
// customising the .env file in your project's root folder.
require('dotenv').load();

// Require keystone
var keystone = require('keystone');

// Initialise Keystone with your project's configuration.
// See http://keystonejs.com/guide/config for available options
// and documentation.

keystone.init({

	'name': 'KeystoneJS',
	'brand': 'KeystoneJS',

	'less': 'public',
	
	'static': 'public',
	'favicon': 'public/favicon.ico',
	'views': 'templates/views',
	'view engine': 'jade',
	
	'emails': 'templates/emails',
	
	'auto update': true,
	'session': true,
	'session store': 'mongo',
	'auth': true,
	'user model': 'User'
	
});

// Load your project's Models

keystone.import('models');

// Your cookie secret is used to secure session cookies. This environment
// variable was added to your Heroku config for you if you used the "Deploy to
// Heroku" button. The secret below will be used for development.
// You may want to set it to something private and secure.

if (!keystone.get('cookie secret')) {
	keystone.set('cookie secret', '----change-me-to-something-secret----');
}

// Setup common locals for your templates. The following are required for the
// bundled templates and layouts. Any runtime locals (that should be set uniquely
// for each request) should be added to ./routes/middleware.js

keystone.set('locals', {
	_: require('underscore'),
	env: keystone.get('env'),
	utils: keystone.utils,
	editable: keystone.content.editable
});

// Load your project's Routes

keystone.set('routes', require('./routes'));

// Setup common locals for your emails. The following are required by Keystone's
// default email templates, you may remove them if you're using your own.

// You should ensure you have the EMAIL_HOSTNAME environment variable set on
// your production / staging servers, or images and links in your emails will 
// default to http://localhost:3000.

var email_hostname = process.env.EMAIL_HOSTNAME || 'localhost:3000';

keystone.set('email locals', {
	server: 'http://' + email_hostname,
	logo_src: 'http://' + email_hostname + '/images/logo-email.gif',
	logo_width: 194,
	logo_height: 76,
	theme: {
		email_bg: '#f9f9f9',
		link_color: '#2697de',
		buttons: {
			color: '#fff',
			background_color: '#2697de',
			border_color: '#1a7cb7'
		}
	}
});

// Load your project's email test routes

keystone.set('email tests', require('./routes/emails'));

// Configure the navigation bar in Keystone's Admin UI

keystone.set('nav', {
	'posts': ['posts', 'post-categories'],
	'galleries': 'galleries',
	'enquiries': 'enquiries',
	'users': 'users'
});

// Start Keystone to connect to your database and initialise the web server

keystone.start();
```

It is this one:

https://github.com/keystonejs/keystone-starter/blob/master/keystone.js

**Comment by export-mike** [comment]
set your port on init:

``` js
	'port': process.env.PORT || 4000,
```

**Comment by mradambeck** [comment]
I'm having the same issue, frustratingly, my app was working on Heroku and I updated a PDF file, and now after trying to push it back up it can't seem to do anything but crash. I've defined the port as suggested, but am still getting the same error.

`2018-02-11T23:47:49.515768+00:00 heroku[router]: at=error code=H20 desc="App boot timeout" method=GET path="/" host=housesofheaven.com request_id=4e6432a3-aabb-49e0-aedd-1d66369d88cb fwd="69.181.190.89" dyno= connect= service= status=503 bytes= protocol=http
2018-02-11T23:47:54.374348+00:00 heroku[web.1]: Starting process with command `node keystone.js`
2018-02-11T23:47:59.670483+00:00 app[web.1]: { Error: Cannot find module '../build/Release/bson'
2018-02-11T23:47:59.670497+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:538:15)
2018-02-11T23:47:59.670503+00:00 app[web.1]:     at Function.Module._load (module.js:468:25)
2018-02-11T23:47:59.670504+00:00 app[web.1]:     at Module.require (module.js:587:17)
2018-02-11T23:47:59.670506+00:00 app[web.1]:     at require (internal/module.js:11:18)
2018-02-11T23:47:59.670511+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/bson/ext/index.js:15:10)
2018-02-11T23:47:59.670512+00:00 app[web.1]:     at Module._compile (module.js:643:30)
2018-02-11T23:47:59.670514+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:654:10)
2018-02-11T23:47:59.670515+00:00 app[web.1]:     at Module.load (module.js:556:32)
2018-02-11T23:47:59.670534+00:00 app[web.1]:     at tryModuleLoad (module.js:499:12)
2018-02-11T23:47:59.670535+00:00 app[web.1]:     at Function.Module._load (module.js:491:3)
2018-02-11T23:47:59.670536+00:00 app[web.1]:     at Module.require (module.js:587:17)
2018-02-11T23:47:59.670537+00:00 app[web.1]:     at require (internal/module.js:11:18)
2018-02-11T23:47:59.670539+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/bson/lib/bson/index.js:3:24)
2018-02-11T23:47:59.670540+00:00 app[web.1]:     at Module._compile (module.js:643:30)
2018-02-11T23:47:59.670541+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:654:10)
2018-02-11T23:47:59.670543+00:00 app[web.1]:     at Module.load (module.js:556:32) code: 'MODULE_NOT_FOUND' }
2018-02-11T23:47:59.671739+00:00 app[web.1]: js-bson: Failed to load c++ bson extension, using pure JS version
2018-02-11T23:47:59.966558+00:00 app[web.1]: Warning: connect.session() MemoryStore is not
2018-02-11T23:47:59.966636+00:00 app[web.1]: designed for a production environment, as it will leak
2018-02-11T23:47:59.966638+00:00 app[web.1]: memory, and will not scale past a single process.
2018-02-11T23:48:54.713454+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2018-02-11T23:48:54.713454+00:00 heroku[web.1]: Stopping process with SIGKILL
2018-02-11T23:48:54.829550+00:00 heroku[web.1]: Process exited with status 137
2018-02-11T23:48:54.845609+00:00 heroku[web.1]: State changed from starting to crashed
2018-02-11T23:48:55.504359+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=housesofheaven.com request_id=c03f92c6-fde9-494b-9be0-5fd1546b51cc fwd="69.181.190.89" dyno= connect= service= status=503 bytes= protocol=http
2018-02-11T23:48:56.065778+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=housesofheaven.com request_id=cbebc375-f6c0-4d41-bef8-56504290583e fwd="69.181.190.89" dyno= connect= service= status=503 bytes= protocol=http
2018-02-11T23:48:56.597929+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=housesofheaven.com request_id=ba53178c-e57f-4ff2-9c76-9de8de00b3d8 fwd="69.181.190.89" dyno= connect= service= status=503 bytes= protocol=http`
