### ISSUE TITLE
TypeError: mime is not a function

### ISSUE THREAD

**Issue by mahnunchik** [keystonejs/keystone#4291]
```
TypeError: mime is not a function
    at normalizeFile (/home/node_modules/keystone/lib/storage/index.js:120:57)
    at Storage.uploadFile (/home/node_modules/keystone/lib/storage/index.js:149:2)
    at file.upload (/home/node_modules/keystone/fields/types/file/FileType.js:50:15)
```

It seems something wrong with this module: https://github.com/keystonejs/keystone/blob/master/lib/storage/index.js#L4

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         |  4.0.0-beta.5
| Node             |  v6.10.2

**Comment by mahnunchik** [comment]
https://github.com/keystonejs/keystone/blob/master/lib/storage/index.js#L120 should be `mime.lookup`

**Comment by mahnunchik** [comment]
Hi @JedWatson
Any news?

**Comment by UnGast** [comment]
#4017

**Comment by stennie** [comment]
Closing as duplicate of #4017.
