### ISSUE TITLE
Error: Can't set headers after they are sent

### ISSUE THREAD

**Issue by yao23** [keystonejs/keystone#4334]
### Expected behavior

No errors complain.

### Actual/Current behavior

10:24:15.000
Error: Can't set headers after they are sent. at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:357:11) at ServerResponse.header (/app/node_modules/express/lib/response.js:730:10) at ServerResponse.send (/app/node_modules/express/lib/response.js:170:12) at default500Handler (/app/node_modules/keystone/lib/core/mount.js:550:20) at /app/node_modules/keystone/lib/core/mount.js:579:5 at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5) at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13) at /app/node_modules/express/lib/router/index.js:284:7 at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12) at next (/app/node_modules/express/lib/router/index.js:275:10) at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:67:12) at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13) at /app/node_modules/express/lib/router/index.js:284:7 at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12) at next (/app/node_modules/express/lib/router/index.js:275:10) at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:67:12) at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13) at /app/node_modules/express/lib/router/index.js:284:7 at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12) at Immediate.next (/app/node_modules/express/lib/router/index.js:275:10) at runCallback (timers.js:674:20) at tryOnImmediate (timers.js:645:5) at processImmediate [as _immediateCallback] (timers.js:617:5)

### Steps to reproduce the actual/current behavior

visit the web app

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | keystone@4.0.0-beta.5
| Node             | v4.4.0

**Comment by yao23** [comment]
Error happened in keystone 500 error handler which is in [keystone start page](http://keystonejs.com/docs/getting-started/): 

/app/routes/middleware.js:97:21
```
/**
    Inits the error handler functions into `res`
*/
exports.initErrorHandlers = function(req, res, next) {
    
    res.err = function(err, title, message) {
        res.status(500).render('errors/500', { // line 97:21 as error in stack track
            err: err,
            errorTitle: title,
            errorMsg: message
        });
    }
    
    res.notfound = function(title, message) {
        res.status(404).render('errors/404', {
            errorTitle: title,
            errorMsg: message
        });
    }
    
    next();
    
};
```

/app/routes/index.js:49:7
```
// Handle other errors
keystone.set('500', function(err, req, res, next) {
    var title, message;
    if (err instanceof Error) {
        message = err.message;
        err = err.stack;
    }
    res.err(err, title, message);  // line 49:7 as error in stack track
});
```

original log:

```
Error: Can't set headers after they are sent. 
at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:357:11) 
at ServerResponse.header (/app/node_modules/express/lib/response.js:730:10) 
at ServerResponse.send (/app/node_modules/express/lib/response.js:170:12) 
at done (/app/node_modules/express/lib/response.js:967:10) 
at Object.exports.renderFile (/app/node_modules/jade/lib/index.js:374:12) 
at View.exports.__express [as engine] (/app/node_modules/jade/lib/index.js:417:11) 
at View.render (/app/node_modules/express/lib/view.js:128:8) 
at tryRender (/app/node_modules/express/lib/application.js:640:10) 
at EventEmitter.render (/app/node_modules/express/lib/application.js:592:3) 
at ServerResponse.render (/app/node_modules/express/lib/response.js:971:7) 
at ServerResponse.res.serverError (/app/routes/middleware.js:97:21) 
at /app/routes/index.js:49:7 
at /app/node_modules/keystone/lib/core/mount.js:560:7 
at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13) 
at /app/node_modules/express/lib/router/index.js:284:7 
at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12) 
at next (/app/node_modules/express/lib/router/index.js:275:10) 
at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:67:12) 
at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13) 
at /app/node_modules/express/lib/router/index.js:284:7 
at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12) 
at next (/app/node_modules/express/lib/router/index.js:275:10) 
at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:67:12) 
at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13) 
at /app/node_modules/express/lib/router/index.js:284:7 
at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12) 
at Immediate.next (/app/node_modules/express/lib/router/index.js:275:10) 
at runCallback (timers.js:674:20) at tryOnImmediate (timers.js:645:5) 
at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by yao23** [comment]
I cannot login admin panel now, logs:

```
16:47:22.402 GET 302 138B 36ms Chrome 58 /keystone/giftcard-brands
 
16:47:22.402 GET 200 740B 308ms Chrome 58 /keystone/signin?from=/keystone/giftcard-brands
 
16:47:23.000 Error: Can't set headers after they are sent. 
at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:357:11) 
at ServerResponse.header (/app/node_modules/express/lib/response.js:730:10) 
 
….. (many lines of same error as above)
 
16:47:23.000 POST /keystone/signin?from=/keystone/giftcard-brands 500 394.171 ms
 
16:47:27.000 Error: Can't set headers after they are sent. 
at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:357:11) 
at ServerResponse.header (/app/node_modules/express/lib/response.js:730:10)
 
….. (many lines of same error as above)
 
16:47:27.115 POST 200 830B 402ms Chrome 58 /keystone/signin?from=/keystone/giftcard-brands
```

**Comment by laurenskling** [comment]
This message happens when you send out something with express two times, like sending out an error and the rest of your code still runs and wants to send out the page.
make sure to stop your code when sending out something.

**Comment by yao23** [comment]
I comment out the above error (400/500) handler and it uses default one, but it still complained for keystone default500Handler as following log:

```
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:357:11)
    at ServerResponse.header (/app/node_modules/keystone/node_modules/express/lib/response.js:719:10)
    at ServerResponse.send (/app/node_modules/keystone/node_modules/express/lib/response.js:164:12)
    at default500Handler (/app/node_modules/keystone/server/bindErrorHandlers.js:72:26)
    at /app/node_modules/keystone/server/bindErrorHandlers.js:102:11
    at Layer.handle_error (/app/node_modules/keystone/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/app/node_modules/keystone/node_modules/express/lib/router/index.js:310:13)
    at /app/node_modules/keystone/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/app/node_modules/keystone/node_modules/express/lib/router/index.js:330:12)
    at next (/app/node_modules/keystone/node_modules/express/lib/router/index.js:271:10)
    at Layer.handle_error (/app/node_modules/keystone/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/app/node_modules/keystone/node_modules/express/lib/router/index.js:310:13)
    at /app/node_modules/keystone/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/app/node_modules/keystone/node_modules/express/lib/router/index.js:330:12)
    at next (/app/node_modules/keystone/node_modules/express/lib/router/index.js:271:10)
    at Layer.handle_error (/app/node_modules/keystone/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/app/node_modules/keystone/node_modules/express/lib/router/index.js:310:13)
    at /app/node_modules/keystone/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/app/node_modules/keystone/node_modules/express/lib/router/index.js:330:12)
    at next (/app/node_modules/keystone/node_modules/express/lib/router/index.js:271:10)
    at Layer.handle_error (/app/node_modules/keystone/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/app/node_modules/keystone/node_modules/express/lib/router/index.js:310:13)
    at /app/node_modules/keystone/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/app/node_modules/keystone/node_modules/express/lib/router/index.js:330:12)
    at Immediate.next (/app/node_modules/keystone/node_modules/express/lib/router/index.js:271:10)
    at runCallback (timers.js:674:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

@laurenskling @beppu @stonean @kumo @stennie do you have any idea?

**Comment by export-mike** [comment]
Hi what does your keystone.js and user model
Look like?

**Comment by yao23** [comment]
Keystone.js is similar as [keystone-demo](https://github.com/keystonejs/keystone-demo/blob/master/keystone.js)
```
require('dotenv').load();

var keystone = require('keystone');

keystone.init({

	'name': 'MyProject',
	'brand': 'MyProject',
	
	'less': 'public',
	'static': 'public',
	'favicon': 'public/favicon.ico',
	'views': 'templates/views',
	'view engine': 'jade',
	
	'emails': 'templates/emails',
	
	'auto update': true,
	'session': true,
	'auth': true,
	'user model': 'User',
	'session store': 'mongo'
});

keystone.import('models');

// Setup common locals for your templates. The following are required for the
// bundled templates and layouts. Any runtime locals (that should be set uniquely
// for each request) should be added to ./routes/middleware.js

keystone.set('locals', {
	_: require('underscore'),
	env: keystone.get('env'),
	utils: keystone.utils,
	editable: keystone.content.editable
});

// Load your project's Routes
keystone.set('routes', require('./routes'));

// Force cloudinary to serve images over https
keystone.set('cloudinary secure', true);

// Setup common locals for your emails. The following are required by Keystone's
// default email templates, you may remove them if you're using your own.

keystone.set('email locals', {
	logo_src: '/images/logo-email.gif',
	logo_width: 194,
	logo_height: 76,
	theme: {
		email_bg: '#f9f9f9',
		link_color: '#2697de',
		buttons: {
			color: '#fff',
			background_color: '#2697de',
			border_color: '#1a7cb7'
		}
	}
});

// Load your project's email test routes
keystone.set('email tests', require('./routes/emails'));

keystone.set('nav', {
	'posts': ['posts', 'post-comments', 'post-categories'],
	'galleries': 'galleries',
	'enquiries': 'enquiries',
	'users': 'users',
	'field-tests': 'things'
});

keystone.start();

```

User model is similar as [keystone-demo](https://github.com/keystonejs/keystone-demo/blob/master/models/User.js)

```
var keystone = require('keystone');
var Types = keystone.Field.Types;

/**
 * User Model
 * ==========
 */

var User = new keystone.List('User');

User.add({
	name: { type: Types.Name, required: true, index: true },
	email: { type: Types.Email, initial: true, required: true, index: true },
	password: { type: Types.Password, initial: true, required: true }
}, 'Permissions', {
	isAdmin: { type: Boolean, label: 'Can access Keystone', index: true }
});

// Provide access to Keystone
User.schema.virtual('canAccessKeystone').get(function() {
	return this.isAdmin;
});


/**
 * Relationships
 */

User.relationship({ ref: 'Post', path: 'posts', refPath: 'author' });


/**
 * Registration
 */

User.defaultColumns = 'name, email, isAdmin';
User.register();
```

**Comment by laurenskling** [comment]
i'm pretty sure your problem is in your route. I'm pretty sure you are sending out a response after an error. Show me the route.

**Comment by yao23** [comment]
```
var keystone = require('keystone');
var middleware = require('./middleware');
var sitemap = require('keystone-express-sitemap');
var robots = require('express-robots');
var importRoutes = keystone.importer(__dirname);

// Common Middleware
keystone.pre('routes', middleware.redirectToFullDomainName);
keystone.pre('routes', middleware.initErrorHandlers);
keystone.pre('routes', middleware.initLocals);
keystone.pre('render', middleware.flashMessages);
keystone.pre('routes', middleware.redirectToNewURL);

// Handle 404 errors
keystone.set('404', function(req, res, next) {
  res.notfound();
});

// Handle other errors
keystone.set('500', function(err, req, res, next) {
  var title, message;
  if (err instanceof Error) {
      message = err.message;
      err = err.stack;
  } else {
      message = '';
      title = '';
  }
  res.serverError(err, title, message);
});

// Import Route Controllers
var routes = {
	views: importRoutes('./views')
};

// Setup Route Bindings
exports = module.exports = function(app) {

	// Views
	app.get('/blogs', routes.views.blog);
	app.get('/blog/:post', routes.views.post);
        app.post('/post_related_posts_fetch', keystone.middleware.api, routes.views.post_related_posts_fetch);
	app.get('/gallery', routes.views.gallery);
	app.all('/contact', routes.views.contact);
	app.get('/privacy-policy', routes.views.privacy_policy);
	app.get('/term-of-use', routes.views.term_of_use);
	app.get('/out/:id', routes.views.redirect_out);
	// NOTE: To protect a route so that only admins can see it, use the requireUser middleware:
	// app.get('/protected', middleware.requireUser, routes.views.protected);

	// GAE health check
        app.get('/_ah/health', routes.views.gcloud_health_check);

	// sitemap
	app.get('/sitemap.xml', function(req, res) {
		sitemap.create(keystone, req, res);
	});

        app.use(robots(__dirname + '/../robots.txt'));
};
```

**Comment by laurenskling** [comment]
Any of these could be the problem:
```
keystone.pre('routes', middleware.redirectToFullDomainName);
keystone.pre('routes', middleware.initErrorHandlers);
keystone.pre('routes', middleware.initLocals);
keystone.pre('render', middleware.flashMessages);
keystone.pre('routes', middleware.redirectToNewURL);
```
if any of them `send` out something and call `next` and you send out something again, your error appears.
So I also would need these functions and the view that is crashing to confirm.

**Comment by yao23** [comment]
I implemented redirectToFullDomainName() and redirectToNewURL(), other parts of code are from [keystone example](http://keystonejs.com/docs/getting-started/)

```
exports.initLocals = function(req, res, next) {
	var locals = res.locals;
	locals.navLinks = [
		{ label: 'Home',		key: 'home',		href: '/' },
		{ label: 'Blog',		key: 'blog',		href: '/blog' },
		{ label: 'Gallery',		key: 'gallery',		href: '/gallery' },
		{ label: 'Contact',		key: 'contact',		href: '/contact' }
	];
	locals.user = req.user;
	next();
};

exports.flashMessages = function(req, res, next) {
	var flashMessages = {
		info: req.flash('info'),
		success: req.flash('success'),
		warning: req.flash('warning'),
		error: req.flash('error')
	};
	res.locals.messages = _.any(flashMessages, function(msgs) { return msgs.length; }) ? flashMessages : false;
	
	next();	
};


exports.requireUser = function(req, res, next) {	
	if (!req.user) {
		req.flash('error', 'Please sign in to access this page.');
		res.redirect('/keystone/signin');
	} else {
		next();
	}	
};

exports.redirectToFullDomainName = function(req, res, next) {
	if(req.headers.host === 'myproject.com') {
		return res.redirect('https://www.myproject.com'+req.url);
	}
	next();

};

exports.initErrorHandlers = function(req, res, next) {

  res.serverError = function(err, title, message) {
    res.status(500).render('errors/500', {
      err: err,
      errorTitle: title,
      errorMsg: message
    });
  };

  res.notfound = function(title, message) {
    res.status(404).render('errors/404', {
      errorTitle: title,
      errorMsg: message
    });
  };

  next();

};

exports.redirectToNewURL = function(req, res, next) {
  if(req.url === '/post/ABC%20DEF%20GHI') {
    return res.redirect('/post/abc-def-ghi');
  }
  next();

};
```

**Comment by laurenskling** [comment]
This is all correct. What does the actual route code look like?

**Comment by yao23** [comment]
There is a route handling Google Cloud health check and it goes to my custom 400/500 error page and status is 200, then it pops a lot of errors (Can't set headers after they are sent ) after the health check requests, it seems trigger the 500 error setting.

the route:
```
app.get('/_ah/health', routes.views.gcloud_health_check);
```

500 setting:
```
// Handle other errors, /app/routes/index.js:49:7
keystone.set('500', function(err, req, res, next) {
    var title, message;
    if (err instanceof Error) {
        message = err.message;
        err = err.stack;
    }
    res.err(err, title, message);  // line 49:7 as error in stack track
});
```

After I commented out the about route, 90% of errors disappeared. (Errors still happened seldomly, but seems not related to health check

**Comment by laurenskling** [comment]
I will give you an example:
```
someFunction = (req, res) => {
    if (true) {
        res.error('send out this error');
    }
    res.render('page');
}
```

this will result in Express sending out the error. JS keeps running the rest of the code and will render the `page` and send it out. Now we have a conflict, because we cannot send twice. This will result in the `Can't set headers after they are sent.` you are getting.

**solution**
make sure that when you send out errors you stop the code.
```
someFunction = (req, res) => {
    if (true) {
        return res.error('send out this error');
    }
    res.render('page');
}
```
