### ISSUE TITLE
tinymce cloudinary 'insert an image from your computer' not work on https.

### ISSUE THREAD

**Issue by Seunghunsh** [keystonejs/keystone#4368]
### Steps to reproduce the actual/current behavior
**Issue:**
In keystone.js admin tinyMCE editor, it says no file chosen when I choose an image inside the ’insert an image from your computer’ button. It doesn't load the image. I'm just trying to load the image from the computer on my keystone.js hosted on https domain. This feature works over http , localhost but not on https domain.

**console says:**
```
serialize @ tinymce.min.js:5
593667c59ccc8a21f1f113c9:1 Refused to display 'https://lifeartlee.us/keystone/api/cloudinary/upload' in a frame because it set 'X-Frame-Options' to 'deny'.
/keystone/api/cloudinary/upload Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE
plugin.min.js:1 Uncaught DOMException: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "https://lifeartlee.us" from accessing a cross-origin frame.
    at HTMLIFrameElement.j (https://lifeartlee.us/keystone/js/lib/tinymce/plugins/uploadimage/plugin.min.js:1:2041)
593667c59ccc8a21f1f113c9:1 Refused to display 'https://lifeartlee.us/keystone/api/cloudinary/upload' in a frame because it set 'X-Frame-Options' to 'deny'.
/keystone/api/cloudinary/upload Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE
plugin.min.js:1 Uncaught DOMException: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "https://lifeartlee.us" from accessing a cross-origin frame.
    at HTMLIFrameElement.j (https://lifeartlee.us/keystone/js/lib/tinymce/plugins/uploadimage/plugin.min.js:1:2041)

```
**Guessing:**
Probably tinyMCE is receiving cloudinary image over http, which may be blocked from my https domain,

**Please help me solve the issue. thank you!**

### Environment

| Software         | Version
| ---------------- | 4.0.0-beta.5
| Keystone         | 
| Node             |

**Comment by icyretribution** [comment]
Have you set your cloudinary api key in your .env configuration?
