### ISSUE TITLE
cookie secret and heroku unexpected string via heroku logs

### ISSUE THREAD

**Issue by Elemino** [keystonejs/keystone#4392]
Hello, 

I am trying to store a secret cookie via Heroku. (Both via env and manually) 

Heroku logs show the following:

/app/keystone.js:28
2017-07-25T04:13:28.003002+00:00 app[web.1]: 	'cookie secret': process.env.COOKIE_SECRET
2017-07-25T04:13:28.003003+00:00 app[web.1]: 	^^^^^^^^^^^^^^^
2017-07-25T04:13:28.003004+00:00 app[web.1]: SyntaxError: Unexpected string
2017-07-25T04:13:28.003005+00:00 app[web.1]:     at createScript (vm.js:56:10)
2017-07-25T04:13:28.003005+00:00 app[web.1]:     at Object.runInThisContext (vm.js:97:10)
2017-07-25T04:13:28.003006+00:00 app[web.1]:     at Module._compile (module.js:542:28)
2017-07-25T04:13:28.003007+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-07-25T04:13:28.003007+00:00 app[web.1]:     at Module.load (module.js:487:32)
2017-07-25T04:13:28.003008+00:00 app[web.1]:     at tryModuleLoad (module.js:446:12)
2017-07-25T04:13:28.003009+00:00 app[web.1]:     at Function.Module._load (module.js:438:3)
2017-07-25T04:13:28.003009+00:00 app[web.1]:     at Module.runMain (module.js:604:10)
2017-07-25T04:13:28.003010+00:00 app[web.1]:     at run (bootstrap_node.js:389:7)
2017-07-25T04:13:28.003011+00:00 app[web.1]:     at startup (bootstrap_node.js:149:9)
2017-07-25T04:13:28.063328+00:00 heroku[web.1]: State changed from starting to crashed

This happens in the following repository: 

https://github.com/Elemino/keystone-from-scratch

When I run cat .env in project directory: 

cat .env          
COOKIE_SECRET=43618074ca7e7779a715f4210abc3c691e09e4ff353c34b9bb704e84a0a40c1757fc13c3b86bc403d7f8196d90d451ed59280ee3fc1a623b949721c9ad53b1bb
CLOUDINARY_URL=cloudinary://333779167276662:_8jbSi9FB3sWYrfimcl8VKh34rI@keystone-demo

I've executed the following: 

heroku config:set COOKIE_SECRET=43618074ca7e7779a715f4210abc3c691e09e4ff353c34b9bb704e84a0a40c1757fc13c3b86bc403d7f8196d90d451ed59280ee3fc1a623b949721c9ad53b1bb

I have completed some pretty complicated architecture for this app and I have been stuck with this for a while now. I feel like I am very close to successfully deploy but this seemingly basic syntax error is driving me crazy.  It seems like a very simple problem, however, I'm at a loss for ideas. 

I feel like I have two options now: Either to learn dotenv from scratch and try to set the secret cookie via the module which I don't have much experience or revert back to the local environment and continue working on the backend/frontend. However, I feel like it would be much more motivating to learn about Keystone in prod under a deployed app.  

I have posted the above both on StackOverflow and Gitter. I would very much appreciate some guidelines. I thank you enormously in advance! Cheers!

**Comment by larsha** [comment]
On line 27 in your `keystone.js` you're missing a ,

That's probably why you get this unexpected string error.

**Comment by Elemino** [comment]
Thanks! Guess I needed another pair of eyes. Such a cliche incident haha.
