### ISSUE TITLE
node 8.9.1 support

### ISSUE THREAD

**Issue by sarkistlt** [keystonejs/keystone#4511]
Any updates on this one? It just hanging the process.
Below is the log from `DEBUG=keystone:* node dist/server/keystone`

```cli
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option dist/server/app/index.js:56:48
  keystone:core:init initializing app +0ms
  keystone:core:options settings options +1ms
  keystone:core:options setting session for auth +0ms
{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/sarkisarutiunian/Projects/Coda/hum/store-front/node_modules/bson/ext/index.js:15:10)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/sarkisarutiunian/Projects/Coda/hum/store-front/node_modules/bson/lib/bson/index.js:3:24)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/sarkisarutiunian/Projects/Coda/hum/store-front/node_modules/mongodb/lib/mongodb/index.js:2:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/sarkisarutiunian/Projects/Coda/hum/store-front/node_modules/mongoose/lib/utils.js:5:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/sarkisarutiunian/Projects/Coda/hum/store-front/node_modules/mongoose/lib/schema.js:7:13)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/sarkisarutiunian/Projects/Coda/hum/store-front/node_modules/mongoose/lib/index.js:7:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/sarkisarutiunian/Projects/Coda/hum/store-front/node_modules/mongoose/index.js:7:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Keystone.init (/Users/sarkisarutiunian/Projects/Coda/hum/store-front/node_modules/keystone/lib/core/init.js:27:24)
    at Object.<anonymous> (/Users/sarkisarutiunian/Projects/Coda/hum/store-front/dist/server/keystone.js:45:20)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3 code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
  keystone:core:options setting nav +126ms
  keystone:core:initNav init nav +0ms
  keystone:core:importer importing  ./views +1ms
  keystone:core:importer recur +1ms
  keystone:core:importer importing  ./views/account +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +1ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +1ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +1ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer importing  ./views/checkout +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +1ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +1ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer importing  ./views/general +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +1ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +1ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +1ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer importing  ./views/partials +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +1ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +1ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer importing  ./views/popups +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +1ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer importing  ./controllers +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer importing  ./controllers/account +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +2ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +1ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +1ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer importing  ./controllers/cart +0ms
  keystone:core:importer recur +1ms
  keystone:core:importer recur +1ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +1ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer importing  ./controllers/checkout +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +1ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +1ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +1ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +1ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer importing  ./controllers/partials +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +1ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer importing  ./controllers/popups +1ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer importing  ./controllers/quiz +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +1ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +1ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +1ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer recur +0ms
  keystone:core:importer cannot require  .map +0ms
  keystone:core:start mount the express app +12ms
  keystone:core:mount mounting +1ms
  keystone:core:mount adding request logger +1ms
  keystone:core:mount enabling frame guard +2ms
  keystone:core:mount adding keystone routes to express app +1ms
  keystone:core:routes setting keystone Admin Route +13ms
  keystone:core:routes setting cloudinary api +1ms
  keystone:core:mount configuring app routes +10ms
  keystone:core:mount connecting to mongo +5ms

```

**Comment by sarkistlt** [comment]
have just found quick work around #3798, updating mongoose to 4.7.7, and everything works, even annoying bson logs disappears.
