### ISSUE TITLE
After creating corporate page this kind of error was showing while rest of the pages was fine.  

### ISSUE THREAD

**Issue by Shashank908** [keystonejs/keystone#4552]
Error thrown for request: `/corporate`
```
TypeError: Cannot read property 'length' of undefined
    at async.eachSeries.asyncFinished (C:\Users\Shashank Shekhar\Desktop\keystone\node_modules\grappling-hook\index.js:226:19)
    at iterate (C:\Users\Shashank Shekhar\Desktop\keystone\node_modules\grappling-hook\node_modules\async\lib\async.js:146:13)
    at Object.async.eachSeries (C:\Users\Shashank Shekhar\Desktop\keystone\node_modules\grappling-hook\node_modules\async\lib\async.js:162:9)
    at iterateAsyncMiddleware (C:\Users\Shashank Shekhar\Desktop\keystone\node_modules\grappling-hook\index.js:225:8)
    at C:\Users\Shashank Shekhar\Desktop\keystone\node_modules\grappling-hook\index.js:585:5
    at dezalgofy (C:\Users\Shashank Shekhar\Desktop\keystone\node_modules\grappling-hook\index.js:192:2)
    at Keystone.callHook (C:\Users\Shashank Shekhar\Desktop\keystone\node_modules\grappling-hook\index.js:584:4)
    at C:\Users\Shashank Shekhar\Desktop\keystone\node_modules\keystone\server\createApp.js:122:12
    at Layer.handle [as handle_request] (C:\Users\Shashank Shekhar\Desktop\keystone\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Shashank Shekhar\Desktop\keystone\node_modules\express\lib\router\index.js:312:13)
    at C:\Users\Shashank Shekhar\Desktop\keystone\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Users\Shashank Shekhar\Desktop\keystone\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\Shashank Shekhar\Desktop\keystone\node_modules\express\lib\router\index.js:271:10)
    at frameGuard (C:\Users\Shashank Shekhar\Desktop\keystone\node_modules\keystone\lib\security\frameGuard.js:20:3)
    at Layer.handle [as handle_request] (C:\Users\Shashank Shekhar\Desktop\keystone\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Shashank Shekhar\Desktop\keystone\node_modules\express\lib\router\index.js:312:13)
```

**Comment by morenoh149** [comment]
Please share the code you wrote.

**Comment by Shashank908** [comment]
@morenoh149 
Please have a look.
[doc.zip](https://github.com/keystonejs/keystone/files/1648961/doc.zip)

**Comment by morenoh149** [comment]
I don't feel comfortable opening that. If it's a large project please upload it to a repo on github and share the link, if you just have small scripts you can share them in this thread inline.
