### ISSUE TITLE
node-gyp rebuild error during Yeoman on Win10 - LINK : fatal error LNK1181

### ISSUE THREAD

**Issue by kchou94** [keystonejs/keystone#4640]
### Expected behavior
Ran `yo keystone` in  as admin and expected it to run without error

### Actual/Current behavior
Error occured:

 ```
> ursa@0.9.4 install C:\Users\[_path to workspace_]\node_modules\ursa
> node-gyp rebuild

C:\Users\[_path to workspace_]\node_modules\ursa>if not defined npm_config_node_gyp (node "C:\Users\[_user_]\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\[_user_]\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  ursaNative.cc
  win_delay_load_hook.cc
..\src\ursaNative.cc(157): warning C4244: 'argument': conversion from 'ssize_t' to 'int', possible loss of data [C:\Users\[_path to workspace_]\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(172): warning C4244: 'argument': conversion from 'ssize_t' to 'int', possible loss of data [C:\Users\[_path to workspace_]\node_modules\ursa\build\ursaNative.vcxproj]
LINK : fatal error LNK1181: cannot open input file 'C:\OpenSSL-Win64\lib\libeay32.lib' [C:\Users\[_path to  workspace_]\node_modules\ursa\build\ursaNative.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\[_user_]\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\[_user_]\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\[_path to workspace_]\node_modules\ursa
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

### Steps to reproduce the actual/current behavior
- Open Powershell as admin
- `npm i -g generator-keystone`
- `npm i -g --production windows-build-tools`
- `cd` to workspace directory
- `yo keystone`

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | 0.5.1
| Node             | 8.11.2
| Windows       | 10
| windows-build-tools | 2.3.0

**Comment by kchou94** [comment]
Turns out I just had to install OpenSSL (see the Windows instructions for URSA [here](https://github.com/JoshKaufman/ursa#testing)).
