### ISSUE TITLE
yo keystone fails

### ISSUE THREAD

**Issue by bakovkin** [keystonejs/keystone#4851]
### Expected behavior
The "yo keystone" process should have gone without errors.

### Actual/Current behavior
**First error:**

make: вход в каталог «/home/and/project/test/my-site/node_modules/kerberos/build»
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../../nan/nan.h:190:0,
                 from ../lib/kerberos.h:9,
                 from ../lib/kerberos.cc:1:
../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../../nan/nan_maybe_43_inl.h:88:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
   return obj->ForceSet(GetCurrentContext(), key, value, attribs);

**Next errors:**
In file included from /home/and/.node-gyp/10.13.0/include/node/node.h:63:0,
                 from ../lib/kerberos.h:4,
                 from ../lib/kerberos.cc:1:
/home/and/.node-gyp/10.13.0/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^
kerberos.target.mk:105: ошибка выполнения рецепта для цели «Release/obj.target/kerberos/lib/kerberos.o»

make: *** [Release/obj.target/kerberos/lib/kerberos.o] Ошибка 1
make: выход из каталога «/home/and/project/test/my-site/node_modules/kerberos/build»
gyp ERR! build error 
gyp ERR! stack Error: "make" failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/and/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.10.0-38-generic
gyp ERR! command "/home/and/.nvm/versions/node/v10.13.0/bin/node" "/home/and/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/and/project/test/my-site/node_modules/kerberos
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

**Full log:**
[log.txt](https://github.com/keystonejs/keystone/files/2585143/log.txt)

### Steps to reproduce the actual/current behavior
yo keystone

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | 4.0.0-beta.5
| Node.js          | v10.13.0

**Comment by jrichardsz** [comment]
June 2019.
The "yo keystone" process has the same kerberos error.

**Comment by autoboxer** [comment]
@bakovkin, I'm closing this issue as the fix (#4888) was merged into Keystone 4.1.0.  If you try again with Keystone 4.1.0 and run into the same issue, post a comment and I'll reopen it.

**Comment by laurenskling** [comment]
looks like a conflict in node versions to me. Probably installed modules on an older (or newer) node version.

`rm -rf node_modules && npm i` and try to run it on another node version
