### ISSUE TITLE
Error when using text or integer idField: refId.adapter.addToForeignTableSchema is not a function

### ISSUE THREAD

**Issue by MurzNN** [keystonejs/keystone#4897]
# Bug report

When I change the `idField` type of List from `autoIncrement` to `integer` or `text` - using "knex" adapter the List is created successfully and works well without any problems (even with Admin UI). 

But when in other List I try to add the relationship field to this List item, I got the error on startup:
```
TypeError: refId.adapter.addToForeignTableSchema is not a function
    at KnexRelationshipInterface.addToTableSchema (keystone/packages/fields/src/types/Relationship/Implementation.js:420:21)
    at keystone/packages/adapter-knex/lib/adapter-knex.js:303:53
    at Array.forEach (<anonymous>)
    at TableBuilder._fn (keystone/packages/adapter-knex/lib/adapter-knex.js:303:26)
    at TableBuilder.toSQL (keystone/node_modules/knex/lib/schema/tablebuilder.js:43:12)
    at SchemaCompiler_PG.createTable (keystone/node_modules/knex/lib/schema/compiler.js:89:25)
    at SchemaCompiler_PG.toSQL (keystone/node_modules/knex/lib/schema/compiler.js:72:26)
    at SchemaBuilder.toSQL (keystone/node_modules/knex/lib/schema/builder.js:79:43)
    at keystone/node_modules/knex/lib/runner.js:31:36
    at keystone/node_modules/knex/lib/runner.js:277:24
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at KnexListAdapter.createTable (keystone/packages/adapter-knex/lib/adapter-knex.js:302:5)
    at pReflect (keystone/node_modules/p-reflect/index.js:5:17)
    at async Promise.all (index 1)
    at KnexAdapter._createTables (keystone/packages/adapter-knex/lib/adapter-knex.js:98:26)
    at KnexAdapter.connect (keystone/packages/keystone/lib/adapters/index.js:28:27)
```

If I revert the `idField` type back to `autoIncrement` - all works well.

So seems the problem is because of missing addToForeignTableSchema function for text and integer field types?

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

1. Use the examples-next/todo example for reproduce the problem
2. Change id field type of "Todo" list item from `autoIncrement` to `integer` via something like this:
```js
  Todo: list({
    ui: {
      listView: {
        initialColumns: ['label', 'isComplete', 'createdAt', 'createdBy', 'updatedAt', 'updatedBy'],
      },
    },
    fields: {
      label: text({ isRequired: true }),
      isComplete: checkbox(),
      assignedTo: relationship({ ref: 'User.tasks' }),
      finishBy: timestamp(),
      ...trackingFields,
    },
    idField: integer({
      access: {
        create: true,
      },
      ui: {
        createView: { fieldMode: 'edit' },
        itemView: { fieldMode: 'read' },
      },
    }),
  }),
```
3. Add the new "TodoComment" list with relationship field to "Todo" list:
```js
  TodoComment: list({
    fields: {
      todo: relationship({ ref: 'Todo'}),
      text: text({ isRequired: true }),
    },
  }),
```
4. Try to start via `yarn dev` and see the error:
```
TypeError: refId.adapter.addToForeignTableSchema is not a function
```
5. Same error with `text` field type.

## Expected behaviour

Keystone-next should treat the `integer` field types for idField in relations exactly like `autoIncrement`, because there is same format of field in database table. Also we need to have support for `text` fields as id too.

**Comment by MurzNN** [comment]
Seems this issue can be solved via simple porting `addToForeignTableSchema()` function from `autoIncrement` field to that fields, here is my PR #4897 to fix this.

**Comment by timleslie** [comment]
Closing as the `knex` adapter no longer exists.
