### ISSUE TITLE
There was an error initialising Keystone field.getGqlAuxMutations is not a function

### ISSUE THREAD

**Issue by acoreyj** [keystonejs/keystone#5128]
# Bug report

## Describe the bug

🚨 There was an error initialising Keystone
TypeError: field.getGqlAuxMutations is not a function
    at /home/corey/workspace/genie-keystone-next-cms/node_modules/@keystone-next/keystone/node_modules/@keystone-next/keystone-legacy/lib/ListTypes/list.js:1094:98
    at Array.map (<anonymous>)
    at List.getGqlMutations (/home/corey/workspace/genie-keystone-next-cms/node_modules/@keystone-next/keystone/node_modules/@keystone-next/keystone-legacy/lib/ListTypes/list.js:1094:43)
    at /home/corey/workspace/genie-keystone-next-cms/node_modules/@keystone-next/keystone/node_modules/@keystone-next/keystone-legacy/lib/providers/listCRUD.js:35:53
    at Array.map (<anonymous>)
    at ListCRUDProvider.getMutations (/home/corey/workspace/genie-keystone-next-cms/node_modules/@keystone-next/keystone/node_modules/@keystone-next/keystone-legacy/lib/providers/listCRUD.js:35:36)
    at /home/corey/workspace/genie-keystone-next-cms/node_modules/@keystone-next/keystone/node_modules/@keystone-next/keystone-legacy/lib/Keystone/index.js:531:65
    at Array.map (<anonymous>)
    at Keystone.getTypeDefs (/home/corey/workspace/genie-keystone-next-cms/node_modules/@keystone-next/keystone/node_modules/@keystone-next/keystone-legacy/lib/Keystone/index.js:531:54)
    at createGraphQLSchema (/home/corey/workspace/genie-keystone-next-cms/node_modules/@keystone-next/keystone/dist/initConfig-1f8193fc.cjs.dev.js:33:24)
    at Object.createSystem (/home/corey/workspace/genie-keystone-next-cms/node_modules/@keystone-next/keystone/dist/initConfig-1f8193fc.cjs.dev.js:668:25)
    at initKeystone (/home/corey/workspace/genie-keystone-next-cms/node_modules/@keystone-next/keystone/scripts/dist/keystone.cjs.dev.js:310:20)
    at Server.<anonymous> (/home/corey/workspace/genie-keystone-next-cms/node_modules/@keystone-next/keystone/scripts/dist/keystone.cjs.dev.js:345:5)

## To Reproduce

`yarn create keystone-next-app`
`npm run start`

## System information

- OS: [WSL2]

**Comment by acoreyj** [comment]
This seems fixed in `"@keystone-next/keystone": "^12.0.0",` so may just be a matter of updating `keystone-next-app`

**Comment by JedWatson** [comment]
Thanks for the bug report and investigation @acoreyj 

Can confirm this was being caused by a bad combination of dependencies that `create-keystone-next-app` was including when you opened this 12 days ago, we've fixed that and updated our process for releases of `create-keystone-next-app` so we hopefully won't get into that situation again 🤞
