### ISSUE TITLE
Error querying the database: db error: ERROR: no such database: postgres

### ISSUE THREAD

**Issue by Temkit** [keystonejs/keystone#5583]
when starting yarn dev sometims it works and sometimes i have the error above

Error: Database error
Error querying the database: db error: ERROR: no such database: postgres
   0: sql_migration_connector::flavour::postgres::create_database
           with self=PostgresFlavour { features: BitFlags<MigrationFeature>(0b0), url: "<REDACTED>" }
             at migration-engine/connectors/sql-migration-connector/src/flavour/postgres.rs:117
   0: sql_migration_connector::flavour::postgres::create_database
           with self=PostgresFlavour { features: BitFlags<MigrationFeature>(0b0), url: "<REDACTED>" }
             at migration-engine/connectors/sql-migration-connector/src/flavour/postgres.rs:117
    at Object.createDatabase (/Users/sidalitemkit/work/web/yet/wirxe/wirxe-app/node_modules/@prisma/sdk/src/migrateEngineCommands.ts:131:13)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at ensureDatabaseExists (/Users/sidalitemkit/work/web/yet/wirxe/wirxe-app/node_modules/@keystone-next/keystone/dist/migrations-108d2571.cjs.dev.js:267:18)
    at withMigrate (/Users/sidalitemkit/work/web/yet/wirxe/wirxe-app/node_modules/@keystone-next/keystone/dist/migrations-108d2571.cjs.dev.js:40:3)
    at Object.pushPrismaSchemaToDatabase (/Users/sidalitemkit/work/web/yet/wirxe/wirxe-app/node_modules/@keystone-next/keystone/dist/migrations-108d2571.cjs.dev.js:52:19)
    at initKeystone (/Users/sidalitemkit/work/web/yet/wirxe/wirxe-app/node_modules/@keystone-next/keystone/scripts/dist/keystone.cjs.dev.js:190:9)
error Command failed with exit code 1.

**Comment by Temkit** [comment]
i am using digitalocean managed database postgres, i changed the Pool Mode to session and it's working now ! 
wired ....

<img width="729" alt="Screen Shot 2021-05-02 at 8 12 50 AM" src="https://user-images.githubusercontent.com/13275723/116805419-5e09c800-ab1e-11eb-849a-b8cff46d29e6.png">

**Comment by timleslie** [comment]
This sounds like a DigitalOcean configuration issue, rather than a Keystone issue per-se. I'm going to close this for now. Please reopen it if you feel like there is something else that needs fixing 👍
