### ISSUE TITLE
Uploading image gets 400 error

### ISSUE THREAD

**Issue by theskillwithin** [keystonejs/keystone#6457]
# Bug report

Uploading images from frontend or backend causes 400 response.   (unless is done via seed-data)

Keystone v24
db: postgres

tried deleting .keystone, doing fresh npm i and running again. same result

## code
keystone.ts: https://gist.github.com/theskillwithin/3a730a28a595d57360a9c9298bf4782a
Product.ts: https://gist.github.com/theskillwithin/74f8b27e98e866f8780063f4deed01c9
ProductImage.ts: https://gist.github.com/theskillwithin/398f457a341e95274a2d4ef377f920e9
package.json: https://gist.github.com/theskillwithin/80819d0e2b429df9d90cc780ab1d0491

## backend error

```
{"errors":[{"message":"Variable \"$data\" got invalid value { resolve: [function], reject: [function], promise: {}, file: { filename: \"download.jpeg\", mimetype: \"image/jpeg\", encoding: \"7bit\", createReadStream: [function createReadStream] } } at \"data.image.upload\"; Upload value invalid.","locations":[{"line":1,"column":11}],"extensions":{"code":"BAD_USER_INPUT","exception":{"stacktrace":["GraphQLError: Variable \"$data\" got invalid value { resolve: [function], reject: [function], promise: {}, file: { filename: \"download.jpeg\", mimetype: \"image/jpeg\", encoding: \"7bit\", createReadStream: [function createReadStream] } } at \"data.image.upload\"; Upload value invalid.","    at /Users/Austin/Projects/ColdBlooded/cold-blooded/backend/node_modules/graphql/execution/values.js:116:15","    at coerceInputValueImpl (/Users/Austin/Projects/ColdBlooded/cold-blooded/backend/node_modules/graphql/utilities/coerceInputValue.js:131:9)","    at coerceInputValueImpl (/Users/Austin/Projects/ColdBlooded/cold-blooded/backend/node_modules/graphql/utilities/coerceInputValue.js:105:34)","    at coerceInputValueImpl (/Users/Austin/Projects/ColdBlooded/cold-blooded/backend/node_modules/graphql/utilities/coerceInputValue.js:105:34)","    at coerceInputValueImpl (/Users/Austin/Projects/ColdBlooded/cold-blooded/backend/node_modules/graphql/utilities/coerceInputValue.js:54:14)","    at coerceInputValue (/Users/Austin/Projects/ColdBlooded/cold-blooded/backend/node_modules/graphql/utilities/coerceInputValue.js:37:10)","    at _loop (/Users/Austin/Projects/ColdBlooded/cold-blooded/backend/node_modules/graphql/execution/values.js:109:69)","    at coerceVariableValues (/Users/Austin/Projects/ColdBlooded/cold-blooded/backend/node_modules/graphql/execution/values.js:121:16)","    at getVariableValues (/Users/Austin/Projects/ColdBlooded/cold-blooded/backend/node_modules/graphql/execution/values.js:50:19)","    at buildExecutionContext (/Users/Austin/Projects/ColdBlooded/cold-blooded/backend/node_modules/graphql/execution/execute.js:203:61)","    at executeImpl (/Users/Austin/Projects/ColdBlooded/cold-blooded/backend/node_modules/graphql/execution/execute.js:101:20)","    at Object.execute (/Users/Austin/Projects/ColdBlooded/cold-blooded/backend/node_modules/graphql/execution/execute.js:60:35)","    at /Users/Austin/Projects/ColdBlooded/cold-blooded/backend/node_modules/apollo-server-core/src/requestPipeline.ts:571:22","    at Generator.next (<anonymous>)","    at /Users/Austin/Projects/ColdBlooded/cold-blooded/backend/node_modules/apollo-server-core/dist/requestPipeline.js:8:71","    at new Promise (<anonymous>)"]}}}]}
```

![image](https://user-images.githubusercontent.com/8095506/131924135-4f310ad1-7f5c-4de1-ac6e-a7e8449b6303.png)

## frontend error

code: https://gist.github.com/theskillwithin/785acaf28bfb8e67d277bb32a40159fc

```Shoot!Variable "$image" got invalid value { resolve: [function], reject: [function], promise: {}, file: { filename: "download.jpeg", mimetype: "image/jpeg", encoding: "7bit", createReadStream: [function createReadStream] } }; Upload value invalid.```

**Comment by theskillwithin** [comment]
also when creating a product with an image also produces an error
![image](https://user-images.githubusercontent.com/8095506/131924721-942fd68b-8cb4-456f-a8d7-270185ee6bef.png)

**Comment by bladey** [comment]
Currently debugging in the Keystone Community Slack - https://keystonejs.slack.com/archives/C01STDMEW3S/p1630622236172600

**Comment by theskillwithin** [comment]
not sure why but switching to yarn instead of using npm fixed this for me  🎉

**Comment by bladey** [comment]
Seems to be a project specific bug with `npm`. New projects are with files are working all OK with `npm` and `yarn`.
