### ISSUE TITLE
TypeError: client.gql is not a function

### ISSUE THREAD

**Issue by Temkit** [keystonejs/keystone#6598]
# Bug report
```

$ keystone-next build
✨ Building Keystone
✨ Generating Admin UI code
✨ Generating Keystone config code
✨ Building Admin UI
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Skipping validation of types  
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data ..TypeError: client.gql is not a function
    at Object.<anonymous> (/Users/sidalitemkit/work/web/ysana/kysana-pql/node_modules/@keystone-next/keystone/dist/admin-meta-graphql-1e30b380.cjs.dev.js:5:40)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/sidalitemkit/work/web/ysana/kysana-pql/node_modules/@keystone-next/keystone/admin-ui/context/dist/keystone.cjs.dev.js:17:24)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Describe the bug

When building error !

## To Reproduce
```

"@babel/runtime": "^7.15.4",
    "@emotion/core": "^11.0.0",
    "@graphql-tools/merge": "^8.1.2",
    "@keystone-next/admin-ui": "^15.0.0",
    "@keystone-next/document-renderer": "^4.0.0",
    "@keystone-next/types": "^25.0.0",
    "@types/react": "^17.0.21",
    "apollo-server-micro": "^3.3.0",
    "graphql": "^15.5.3",
    "graphql-tag": "^2.12.5",
    "next": "11.1.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "@keystone-ui/core": "^3.2.0",
    "@keystone-ui/fields": "^4.1.3",
    "@keystone-ui/icons": "^4.0.1",
    "@keystone-ui/tooltip": "^4.0.2",
    "@preconstruct/next": "^3.0.0",
    "@keystone-next/auth": "^32.0.0",
    "@keystone-next/cloudinary": "^7.0.0",
    "@keystone-next/fields-document": "^9.0.0",
    "@keystone-next/keystone": "^25.0.3"

```

**Comment by peelar** [comment]
I am experiencing the same issue.

**Comment by timleslie** [comment]
I suspect this is related to an updated version of the package `@apollo/client`. Could you please confirm what version you have installed, and see what happens if you use a yarn resolution to force this to be `3.4.11`?

**Comment by timleslie** [comment]
I can reproduce this here: https://github.com/keystonejs/keystone/runs/3648771113?check_suite_focus=true when updating to `3.4.12`. I'll keep y'all posted on any progress on this as I find it. For now I suspect a yarn resolution pinning to `3.4.11` will be your best bet.

**Comment by timleslie** [comment]
This is now fixed in `@apollo/client` version `3.4.13` 👍

**Comment by dcousens** [comment]
@dbehmoaras could you please post steps to reproduce the problem?

**Comment by dbehmoaras** [comment]
> @dbehmoaras could you please post steps to reproduce the problem?

At the moment I can't provide a detailed reproduction - we are quite slammed at the moment. When I have time after our next release I will try. What I can share is that this only occurs for us in unit tests and thankfully not in our dev environment.

That said, after digging in further it's very likely an issue with Apollo and not Keystone. For the moment we are skipping those unit tests and covering them in integration tests.

**Comment by karthikRaiker** [comment]
its not fixed

**Comment by dcousens** [comment]
@vorlov, @karthikRaiker could you please provide reproduction steps
