### ISSUE TITLE
Generating GraphQL and Prisma schemas Error: Could not find prisma-fmt binary

### ISSUE THREAD

**Issue by HitsiLent** [keystonejs/keystone#6780]
# Bug report

Generating GraphQL and Prisma schemas Error: Could not find prisma-fmt binary

## Describe the bug

Generating GraphQL and Prisma schemas Error: Could not find prisma-fmt binary when you run yarn dev

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

1. After yarn install version Release - 5th October 2021
2. throw error while run yarn dev on blog example project 

## Expected behaviour

run server with without error

## Screenshots

![1634053773815](https://user-images.githubusercontent.com/3459741/136988663-3dd4ea70-2b9e-451f-9110-7453ac3674a4.jpg)

## System information

- OS: macOS

**Comment by timleslie** [comment]
Hi @HitsiLent, let's make sure you have a clean and correct install. Please run the following commands and see if it fixes things.

```
rm -rf .keystone
rm -rf node_modules
yarn
yarn dev
```

**Comment by HitsiLent** [comment]
same error, i think it cuz upgrade to prisma 3.X cause the problem

**Comment by Zegnat** [comment]
I just ran into the exact same issue just now, with a completely clean install. Putting a copy of the error here as text, rather than just a screenshot. Ran `npm init keystone-app`, then `cd`ed into the new folder, and then `npm run dev`:

```
> keystone-app@3.0.1 dev /Users/zegnat/keystone
> keystone-next dev

✨ Starting Keystone
⭐️ Dev Server Starting on http://localhost:3000
⭐️ GraphQL API Starting on http://localhost:3000/api/graphql
✨ Generating GraphQL and Prisma schemas
Error: Could not find prisma-fmt binary. Searched in /Users/zegnat/keystone/node_modules/@prisma/sdk/prisma-fmt-darwin and /Users/zegnat/keystone/node_modules/@prisma/prisma-fmt-darwin
    at resolveBinary (/Users/zegnat/keystone/node_modules/@prisma/sdk/dist/resolveBinary.js:87:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Object.formatSchema (/Users/zegnat/keystone/node_modules/@prisma/sdk/dist/engine-commands/formatSchema.js:41:25)
    at getCommittedArtifacts (/Users/zegnat/keystone/node_modules/@keystone-next/keystone/artifacts/dist/keystone-next-keystone-artifacts.cjs.dev.js:427:13)
    at Object.generateCommittedArtifacts (/Users/zegnat/keystone/node_modules/@keystone-next/keystone/artifacts/dist/keystone-next-keystone-artifacts.cjs.dev.js:490:21)
    at initKeystone (/Users/zegnat/keystone/node_modules/@keystone-next/keystone/scripts/dist/keystone-next-keystone-scripts.cjs.dev.js:308:27)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keystone-app@3.0.1 dev: `keystone-next dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keystone-app@3.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zegnat/.npm/_logs/2021-11-01T07_49_44_476Z-debug.log
```

Bit of system info, incase that is important:

```fish
system_profiler SPSoftwareDataType
# Software:
# 
#     System Software Overview:
# 
#       System Version: macOS 11.6 (20G165)
#       Kernel Version: Darwin 20.6.0
#       Boot Volume: Macintosh HD
#       Boot Mode: Normal
#       Computer Name: Zegnat’s MacBook Air
#       User Name: Martijn (zegnat)
#       Secure Virtual Memory: Enabled
#       System Integrity Protection: Enabled
#       Time since boot: 25 days 3:07

node --version
# v14.17.6

npm --version
# 6.14.15
```

**Comment by Zegnat** [comment]
My own comment actually showed me the way. Switching to the newer LTS Node (v16) made it run correctly. I am guessing there is some soft requirement between depencendies and node version and what not. @HitsiLent what version of node/yarn were you using?

**Comment by sladg** [comment]
For me, the issue was including `--ignore-scripts` in my Docker file during `yarn install`.
```
# This is using node 16.13
FROM node:gallium-bullseye-slim
```

**Comment by vonba** [comment]
I am seeing the same issue after upgrading to keystone-6 from keystone-next
Using Node 16.13

**Comment by remygendron** [comment]
Same issue when deploying KS 6 to AWS Elastic Beanstalk. Runs fin on Node 14 on MacOS, but fails with the following on same Node 14 version on Amazon Linux 2 images under Elastic Beanstalk.

Error: Could not find prisma-fmt binary. Searched in /var/app/current/node_modules/@prisma/sdk/prisma-fmt-rhel-openssl-1.0.x and /var/app/current/node_modules/@prisma/prisma-fmt-rhel-openssl-1.0.x
Feb  9 01:28:52 ip-10-0-69-95 web: at resolveBinary (/var/app/current/node_modules/@prisma/sdk/dist/resolveBinary.js:92:9)
Feb  9 01:28:52 ip-10-0-69-95 web: at Object.formatSchema (/var/app/current/node_modules/@prisma/sdk/dist/engine-commands/formatSchema.js:41:25)
Feb  9 01:28:52 ip-10-0-69-95 web: at getCommittedArtifacts (/var/app/current/node_modules/@keystone-6/core/dist/artifacts-7f46986c.cjs.dev.js:398:13)
Feb  9 01:28:52 ip-10-0-69-95 web: at Object.generateCommittedArtifacts (/var/app/current/node_modules/@keystone-6/core/dist/artifacts-7f46986c.cjs.dev.js:461:21)
Feb  9 01:28:52 ip-10-0-69-95 web: at setupInitialKeystone (/var/app/current/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.dev.js:402:25)
Feb  9 01:28:52 ip-10-0-69-95 web: at initKeystone (/var/app/current/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.dev.js:165:35)

**Comment by remygendron** [comment]
Additional info from my Elastic Beanstalk deployment.

Looked at the code for resolveBinary.js. And looked on the ec2 instance where that code is looking for the binary. The paths and binary are simply not there. Looked at all the eb logs at deployment time, no visible errors when installing npm dependencies. 

On my mac, the binary is at : node_modules/@prisma/engines/prisma-fmt-darwin

On the ec2 instance, prisma-fmt-* cannot be found under node_modules/@prisma with find . -name "prisma-fmt*"

I conclude that the binary was simply not built on the AWS Linux 2 AMI.

**Comment by remygendron** [comment]
Other ideas:

As AWS EB installs a Node app in production mode (npm install --production), the package-lock.jon file generated on my Mac may incite npm install to consider installing some MacOS version of packages. Not sure about that, but just in case.

I rm -rf the node_modules folder, and deleted package-lock.json and did a plain npm install.

Same error at launch.

Running out of ideas.

**Comment by molomby** [comment]
Digging though the `prisma@3.6.0` package, it depends on `@prisma/engines@3.6.0-24.dc520b92b1ebb2d28dc3161f9f82e875bd35d727`. That package has a `postinstall` script that downloads the appropriate engine binary.

Could your build environment be blocking this request? You must be allowing requests to `npmjs.org` or you wouldn't be able to install the package itself, but maybe the binary comes from `binaries.prisma.sh`.

In fact, looking at https://binaries.prisma.sh, it's a publicly listable S3 bucket. You could probably manually pull the binaries you need and incorporate them into your project some how.

**Comment by remygendron** [comment]
Thank you for the repry molomby. The ec2 instance runs on a public subnet and I verified that it has a security group that allows all traffic outbound. This is standard and is a sg that is configured by Elastic Beanstalk at deploy time. The IAM role also has AdministratorAccess.

I would building a deploy recipe for a low code backend and wanted to keep things simple. As such, I was deploying directly to an EB Node Platform. I am in the process off containerizing the deployment and will use EB Docker platform. This will also allow me to upgrade to Node 16 (eb only support node 14 natively).

Thank you for your input.

**Comment by mwcz** [comment]
I'm also running into this error.  Not in a build environment, but on my regular workstation.  DNS for `binaries.prisma.sh` resolves.  I've tried with node 14, 16, and 17, with yarn 1.22 and 3.2, and with npm versions 6.14, 8.5, and 8.5.5.

<details>
<summary>yarn install  log</summary>
<pre><code>
$ yarn
yarn install v1.22.17
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning @keystone-6/core > @prisma/sdk > temp-write > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @keystone-6/core > supertest > superagent@7.1.2: Deprecated due to bug in CI build https://github.com/visionmedia/superagent/pull/1677\#issuecomment-1081361876
warning @keystone-6/fields-document > @braintree/sanitize-url@5.0.2: Potential XSS vulnerability patched in v6.0.0.
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > @keystone-6/auth@1.0.2" has unmet peer dependency "react@^17.0.2".
warning "@keystone-6/auth > @keystone-ui/core@4.0.0" has unmet peer dependency "react@^17.0.2".
warning "@keystone-6/auth > @keystone-ui/core@4.0.0" has unmet peer dependency "react-dom@^17.0.2".
warning "@keystone-6/auth > @keystone-ui/core > @emotion/react@11.8.2" has unmet peer dependency "react@>=16.8.0".
warning "@keystone-6/auth > @keystone-ui/core > @emotion/react > @emotion/babel-plugin@11.7.2" has unmet peer dependency "@babel/core@^7.0.0".
warning "@keystone-6/auth > @keystone-ui/core > @emotion/react > @emotion/babel-plugin > @babel/plugin-syntax-jsx@7.16.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@keystone-6/auth > @keystone-ui/fields > react-select@5.2.2" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@keystone-6/core > @prisma/migrate@3.11.0" has unmet peer dependency "@prisma/generator-helper@*".
warning "@keystone-6/fields-document > slate-react@0.69.0" has unmet peer dependency "react-dom@>=16.8.0".
[5/5] Building fresh packages...
success Saved lockfile.
$ keystone postinstall
Error: Could not find prisma-fmt binary. Searched in /home/user/projects/keystone-test/node_modules/@prisma/sdk/prisma-fmt-rhel-openssl-3.0.x and /home/user/projects/keystone-test/node_modules/@prisma/prisma-fmt-rhel-openssl-3.0.x
    at resolveBinary (/home/user/projects/keystone-test/node_modules/@prisma/sdk/dist/resolveBinary.js:92:9)
    at Object.formatSchema (/home/user/projects/keystone-test/node_modules/@prisma/sdk/dist/engine-commands/formatSchema.js:41:25)
    at getCommittedArtifacts (/home/user/projects/keystone-test/node_modules/@keystone-6/core/dist/artifacts-61fd8d1d.cjs.dev.js:398:13)
    at Object.validateCommittedArtifacts (/home/user/projects/keystone-test/node_modules/@keystone-6/core/dist/artifacts-61fd8d1d.cjs.dev.js:417:21)
    at postinstall (/home/user/projects/keystone-test/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.dev.js:619:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
</code></pre>
</details>
