### ISSUE TITLE
Duplicate GraphQL instance crashes the installation

### ISSUE THREAD

**Issue by azzazkhan** [keystonejs/keystone#6803]
# Bug report

Please use this form for bug reports only. If you have a question, feature request or want to chat with us, please select the appropriate option here - https://github.com/keystonejs/keystone/issues/new/choose

## Describe the bug

Throws an error while creating a new keystone app with `yarn create keystone-app` command.

```
[4/4] Building fresh packages...
$ keystone-next postinstall
Error: Cannot use GraphQLObjectType "Post" from another module or realm.   

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at instanceOf (C:\Users\stude\Documents\development\keystone-blog\node_modules\graphql\jsutils\instanceOf.js:35:13)     
    at isObjectType (C:\Users\stude\Documents\development\keystone-blog\node_modules\graphql\type\definition.js:122:34)     
    at isType (C:\Users\stude\Documents\development\keystone-blog\node_modules\graphql\type\definition.js:92:32)
    at isNullableType (C:\Users\stude\Documents\development\keystone-blog\node_modules\graphql\type\definition.js:422:10)   
    at assertNullableType (C:\Users\stude\Documents\development\keystone-blog\node_modules\graphql\type\definition.js:426:8)    at new GraphQLNonNull (C:\Users\stude\Documents\development\keystone-blog\node_modules\graphql\type\definition.js:379:19)
    at Object.nonNull (C:\Users\stude\Documents\development\keystone-blog\node_modules\@graphql-ts\schema\dist\list-and-non-null-8696cd4e.cjs.dev.js:445:18)
    at C:\Users\stude\Documents\development\keystone-blog\node_modules\@keystone-next\keystone\fields\dist\keystone-next-keystone-fields.cjs.dev.js:1277:58
    at C:\Users\stude\Documents\Development\keystone-blog\node_modules\@keystone-next\keystone\dist\types-for-lists-99088921.cjs.dev.js:1722:15
    at Array.map (<anonymous>)
error Command failed with exit code 1.
```

## To Reproduce

Just create a new project using `yarn create keystone-app` command provided on the official KeystoneJS's website.

## Expected behaviour

Should create a new Keystone app without any errors.

## System information

- OS: Windows 10 Pro
- Browser Chrome

## Additional context

I read about Keystone JS from an NPM package and found it appealing but I could not set it up.

**Comment by azzazkhan** [comment]
The project failed to build so I deleted the `node_modules` directory and `yarn.lock` file and ran `yarn install` again but it threw this error.

**Comment by bladey** [comment]
Hi @azzazkhan, could you please confirm what versions of Node.JS, npm, and Yarn you are using?
