### ISSUE TITLE
Url with % course Bad Request

### ISSUE THREAD

**Issue by Yinear** [keystonejs/keystone#683]
Any url with % will course a internal error.  

eg. /covergirl/pic_b/11%BA%C5%20%CF%F4%BC%D1%C7%D9.JPG

Also happened in the sydjs project.  Seems like it's problem with express?

**Comment by morenoh149** [comment]
stale

**Comment by Yinear** [comment]
@morenoh149 
If you deploy keystone on localhost:3000
You can try visit http://localhost:3000/11%BA%C5%20%CF%F4%BC%D1%C7%D9.jpg

Is there a 500 error?

**Comment by morenoh149** [comment]
I see
```
TypeError: /Users/harrymoreno/programming/r3dm/shpesfba/templates/layouts/default.jade:48
   46|           button.navbar-toggle.collapsed(type='button', data-toggle='collapse', data-target='#navbar-collapsable')
   47|             span.sr-only Toggle navigation
 > 48|             span.icon-bar
   49|             span.icon-bar
   50|             span.icon-bar
   51|           a.navbar-brand(href="/")

Cannot read property 'length' of undefined
   at jade_debug.unshift.lineno (eval at <anonymous> (/Users/harrymoreno/programming/r3dm/shpesfba/node_modules/keystone/node_modules/jade/lib/index.js:190:8), <anonymous>:502:31)
   at eval (eval at <anonymous> (/Users/harrymoreno/programming/r3dm/shpesfba/node_modules/keystone/node_modules/jade/lib/index.js:190:8), <anonymous>:545:4)
   at eval (eval at <anonymous> (/Users/harrymoreno/programming/r3dm/shpesfba/node_modules/keystone/node_modules/jade/lib/index.js:190:8), <anonymous>:1070:22)
   at res (/Users/harrymoreno/programming/r3dm/shpesfba/node_modules/keystone/node_modules/jade/lib/index.js:191:38)
   at Object.exports.render (/Users/harrymoreno/programming/r3dm/shpesfba/node_modules/keystone/node_modules/jade/lib/index.js:316:10)
   at Object.exports.renderFile (/Users/harrymoreno/programming/r3dm/shpesfba/node_modules/keystone/node_modules/jade/lib/index.js:352:18)
   at View.exports.renderFile [as engine] (/Users/harrymoreno/programming/r3dm/shpesfba/node_modules/keystone/node_modules/jade/lib/index.js:337:21)
   at View.render (/Users/harrymoreno/programming/r3dm/shpesfba/node_modules/keystone/node_modules/express/lib/view.js:93:8)
   at EventEmitter.app.render (/Users/harrymoreno/programming/r3dm/shpesfba/node_modules/keystone/node_modules/express/lib/application.js:530:10)
   at ServerResponse.res.render (/Users/harrymoreno/programming/r3dm/shpesfba/node_modules/keystone/node_modules/express/lib/response.js:904:7) 
```

**Comment by morenoh149** [comment]
@Yinear see these issues https://github.com/strongloop/express/search?q=percent&type=Issues&utf8=%E2%9C%93 Sounds like express is doing exactly what it should - error out like apache does. You either need to properly encode your url @Yinear 

Or, @keystonejs/contributors is there a way for keystone to add a middleware to the express instance that would catch this edge-case as well?

**Comment by Yinear** [comment]
@morenoh149 
I don't use % in my project,  It's OK with me.
So It's not a issue of keystone.  I close it.

**Comment by morenoh149** [comment]
oh okay. My issue was that my jade template depended on a variable being initialized by `initLocals` https://github.com/r3dm/shpe-sfba/blob/master/routes/index.js#L12 so when the jade template tried to reference this undefined variable it would error out. Short-circuiting in the jade template solves this issue and displays a 500 error. https://github.com/r3dm/shpe-sfba/commit/14c93107bf439ee554cf81dea0ca95dedf46224e
