### ISSUE TITLE
Keystone 6 does not work with next 12

### ISSUE THREAD

**Issue by rburgst** [keystonejs/keystone#6848]
# Bug report

Please use this form for bug reports only. If you have a question, feature request or want to chat with us, please select the appropriate option here - https://github.com/keystonejs/keystone/issues/new/choose

## Describe the bug

Upgrading to next 12 produces errors

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

1. create a new keystone app 
   ```
   yarn create keystone-app
   ```
2. add next.js to package 
   ```
   yarn add next
   ```
3. run the server and try to access http://localhost:3000

```
yarn dev

yarn dev
yarn run v1.22.17
$ keystone-next dev
✨ Starting Keystone
⭐️ Dev Server Starting on http://localhost:3000
⭐️ GraphQL API Starting on http://localhost:3000/api/graphql
✨ Generating GraphQL and Prisma schemas
✨ sqlite database "keystone.db" created at file:./keystone.db
✨ Your database is now in sync with your schema. Done in 693ms
✨ Connecting to the database
✨ Creating server
✅ GraphQL API ready
✨ Generating Admin UI code
✨ Preparing Admin UI app
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
event - compiled successfully

...
event - compiled successfully
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
TypeError: Cannot destructure property 'inAmpMode' of '(0 , _react).useContext(...)' as it is null.
    at Html (webpack-internal:///../../node_modules/@keystone-next/keystone/node_modules/next/dist/pages/_document.js:215:5)
    at processChild (/Users/rainer/git/private/turnen/turnen-ks-empty/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/Users/rainer/git/private/turnen/turnen-ks-empty/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/Users/rainer/git/private/turnen/turnen-ks-empty/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/Users/rainer/git/private/turnen/turnen-ks-empty/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (/Users/rainer/git/private/turnen/turnen-ks-empty/node_modules/react-dom/cjs/react-dom-server.node.development.js:4314:27)
    at Object.renderToHTML (/Users/rainer/git/private/turnen/turnen-ks-empty/node_modules/@keystone-next/keystone/node_modules/next/server/render.tsx:1101:39)
    at doRender (/Users/rainer/git/private/turnen/turnen-ks-empty/node_modules/@keystone-next/keystone/node_modules/next/server/next-server.ts:1669:27)
    at /Users/rainer/git/private/turnen/turnen-ks-empty/node_modules/@keystone-next/keystone/node_modules/next/server/next-server.ts:1783:21
    at /Users/rainer/git/private/turnen/turnen-ks-empty/node_modules/@keystone-next/keystone/node_modules/next/server/response-cache.ts:94:25
TypeError: Cannot destructure property 'inAmpMode' of '(0 , _react).useContext(...)' as it is null.
    at Html (webpack-internal:///../../node_modules/@keystone-next/keystone/node_modules/next/dist/pages/_document.js:215:5)
    at processChild (/Users/rainer/git/private/turnen/turnen-ks-empty/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/Users/rainer/git/private/turnen/turnen-ks-empty/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/Users/rainer/git/private/turnen/turnen-ks-empty/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/Users/rainer/git/private/turnen/turnen-ks-empty/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (/Users/rainer/git/private/turnen/turnen-ks-empty/node_modules/react-dom/cjs/react-dom-server.node.development.js:4314:27)
    at Object.renderToHTML (/Users/rainer/git/private/turnen/turnen-ks-empty/node_modules/@keystone-next/keystone/node_modules/next/server/render.tsx:1101:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at doRender (/Users/rainer/git/private/turnen/turnen-ks-empty/node_modules/@keystone-next/keystone/node_modules/next/server/next-server.ts:1669:27)
error Command failed with exit code 1.
```

## Expected behaviour

Server should boot up fine.

## System information

- OS: macOS

**Comment by bladey** [comment]
Hey @rburgst, we're aware of this, Next 12 won't work until we upgrade Keystone to Next 11, I'll let you know once this is done, hopefully in the next release - #6835

**Comment by JedWatson** [comment]
We just released keystone-next/keystone@27.0.0 which includes Next 12

**Comment by rburgst** [comment]
wow, thanks a lot for the fast turn around!

**Comment by JedWatson** [comment]
You're welcome @rburgst 🙂 

Heads up we found an issue with `keystone-next build` in `27.0.0`, will have a patch release out in the morning that fixes it just in case you hit that.

**Comment by alvaaz** [comment]
Also, you will have to upgrade to next@12.0.2 to make it work. next@12.0.1 doesn't work and show the same error.

**Comment by rburgst** [comment]
Problem appears again when upgrading to next 12.0.3

**Comment by bladey** [comment]
Thanks @rburgst, we'll take a look as soon as possible.

**Comment by rburgst** [comment]
just fyi I found this: https://github.com/vercel/next.js/discussions/30602#discussioncomment-1674147. I am using yarn with pnp. Maybe thats the reason?

**Comment by mzaien** [comment]
Hello again, it seems this issues happens for every new next.js new version, i updated next to 12.0.5 and it happened to me (i'm embedding keystone with next project)

**Comment by rburgst** [comment]
@mzaien check the associated patch to the docs, the next version MUST match to the next version used in keystone. https://github.com/keystonejs/keystone/pull/7003

**Comment by mzaien** [comment]
> @mzaien check the associated patch to the docs, the next version MUST match to the next version used in keystone. https://github.com/keystonejs/keystone/pull/7003

Thank you 👍, can this issue be resolved in the future 🧐 we should not force the user from updating until keystone is Updated
