### ISSUE TITLE
create keystone-app fails on fresh install of Node 16

### ISSUE THREAD

**Issue by jayhale** [keystonejs/keystone#7242]
# Steps to reproduce
```
$ nvm use 16.13
$ npm install -g yarn
$ yarn create keystone-app
...
✔ What directory should create-keystone-app generate your app into? · test-app
...
```

# Expected
A successful install.

# Result
```
$ nvm use 16.13
Now using node v16.13.2 (npm v8.1.2)

$ which yarn
/Users/james/.nvm/versions/node/v16.13.2/bin/yarn

$ yarn create keystone-app
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 966ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed
➤ YN0000: Done with warnings in 1s 230ms


✨ You're about to generate a project using Keystone 6 packages.

✔ What directory should create-keystone-app generate your app into? · test-app

⠏ Installing dependencies with yarn. This may take a few minutes.
⚠ Failed to install with yarn.
✖ Failed to install with npm.
Error: Command failed with exit code 1: npm install
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
/private/var/folders/g9/22skwg094pqcrp8_8ndfp8kh0000gn/T/xfs-a07bae1f/dlx-43491/.pnp.cjs:11310
    throw firstError;
    ^

Error: Your application tried to access meow, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: meow
Required by: /Users/james/Projects/test-app/node_modules/@keystone-6/core/scripts/dist/

Require stack:
- /Users/james/Projects/test-app/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.dev.js
- /Users/james/Projects/test-app/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.js
- /Users/james/Projects/test-app/node_modules/@keystone-6/core/bin/cli.js
    at Function.external_module_.Module._resolveFilename (/private/var/folders/g9/22skwg094pqcrp8_8ndfp8kh0000gn/T/xfs-a07bae1f/dlx-43491/.pnp.cjs:11309:55)
    at Function.external_module_.Module._load (/private/var/folders/g9/22skwg094pqcrp8_8ndfp8kh0000gn/T/xfs-a07bae1f/dlx-43491/.pnp.cjs:11108:48)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/james/Projects/test-app/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.dev.js:3:12)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.external_module_.Module._load (/private/var/folders/g9/22skwg094pqcrp8_8ndfp8kh0000gn/T/xfs-a07bae1f/dlx-43491/.pnp.cjs:11158:14)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
npm ERR! code 1
npm ERR! path /Users/james/Projects/test-app
npm ERR! command failed
npm ERR! command sh -c keystone postinstall

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/james/.npm/_logs/2022-01-30T03_29_54_273Z-debug.log

> keystone-app@1.0.0 postinstall
> keystone postinstall

    at makeError (/Users/james/.yarn/berry/cache/execa-npm-5.1.1-191347acf5-8.zip/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/james/.yarn/berry/cache/execa-npm-5.1.1-191347acf5-8.zip/node_modules/execa/index.js:118:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async installDeps (/Users/james/.yarn/berry/cache/create-keystone-app-npm-6.0.1-a7d955f8db-8.zip/node_modules/create-keystone-app/dist/create-keystone-app.cjs.dev.js:142:9)
    at async /Users/james/.yarn/berry/cache/create-keystone-app-npm-6.0.1-a7d955f8db-8.zip/node_modules/create-keystone-app/dist/create-keystone-app.cjs.dev.js:165:26 {
  shortMessage: 'Command failed with exit code 1: npm install',
  command: 'npm install',
  escapedCommand: 'npm install',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '\n> keystone-app@1.0.0 postinstall\n> keystone postinstall\n',
  stderr: 'npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.\n' +
    '/private/var/folders/g9/22skwg094pqcrp8_8ndfp8kh0000gn/T/xfs-a07bae1f/dlx-43491/.pnp.cjs:11310\n' +
    '    throw firstError;\n' +
    '    ^\n' +
    '\n' +
    "Error: Your application tried to access meow, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.\n" +
    '\n' +
    'Required package: meow\n' +
    'Required by: /Users/james/Projects/test-app/node_modules/@keystone-6/core/scripts/dist/\n' +
    '\n' +
    'Require stack:\n' +
    '- /Users/james/Projects/test-app/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.dev.js\n' +
    '- /Users/james/Projects/test-app/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.js\n' +
    '- /Users/james/Projects/test-app/node_modules/@keystone-6/core/bin/cli.js\n' +
    '    at Function.external_module_.Module._resolveFilename (/private/var/folders/g9/22skwg094pqcrp8_8ndfp8kh0000gn/T/xfs-a07bae1f/dlx-43491/.pnp.cjs:11309:55)\n' +
    '    at Function.external_module_.Module._load (/private/var/folders/g9/22skwg094pqcrp8_8ndfp8kh0000gn/T/xfs-a07bae1f/dlx-43491/.pnp.cjs:11108:48)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1005:19)\n' +
    '    at require (node:internal/modules/cjs/helpers:102:18)\n' +
    '    at Object.<anonymous> (/Users/james/Projects/test-app/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.dev.js:3:12)\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1101:14)\n' +
    '    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)\n' +
    '    at Module.load (node:internal/modules/cjs/loader:981:32)\n' +
    '    at Function.external_module_.Module._load (/private/var/folders/g9/22skwg094pqcrp8_8ndfp8kh0000gn/T/xfs-a07bae1f/dlx-43491/.pnp.cjs:11158:14)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1005:19)\n' +
    'npm ERR! code 1\n' +
    'npm ERR! path /Users/james/Projects/test-app\n' +
    'npm ERR! command failed\n' +
    'npm ERR! command sh -c keystone postinstall\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     /Users/james/.npm/_logs/2022-01-30T03_29_54_273Z-debug.log',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

# Context
```
$ node -v
v16.13.2

$ yarn -v
3.1.1

$ npm -v
8.1.2

$ npm info create-keystone-app

create-keystone-app@6.0.1 | MIT | deps: 10 | versions: 75

bin: create-keystone-app

dist
.tarball: https://registry.npmjs.org/create-keystone-app/-/create-keystone-app-6.0.1.tgz
.shasum: a4f8e4c4fc3b1a02f75f4ef664731b5a19054ab5
.integrity: sha512-A9IDC0EDHZ3ju0RqsWEvkmobdK2l9YQJPz0Ar7rks81n35DwMHH3xYRxhc+trKqctSjPTZdD4JvuDqDoJ6GtzQ==
.unpackedSize: 133.0 MB

dependencies:
@babel/runtime: ^7.16.5 execa: ^5.1.1           ora: ^5.4.1             terminal-link: ^2.1.1   
chalk: ^4.1.2           fs-extra: ^10.0.0       package-json: ^6.5.0    
enquirer: ^2.3.6        meow: ^9.0.0            semver: ^7.3.5          

maintainers:
- bladey <bladey@me.com>
- jedwatson <jed.watson@me.com>
- jesstelford <jess+npmjs@jes.st>
- dominikwilkowski <hi@dominik-wilkowski.com>
- molomby <john@molomby.com>
- timl <tim.leslie@thinkmill.com.au>

dist-tags:
buttress: 3.3.4  entasis: 3.3.6   hyphen: 3.4.0    latest: 6.0.1    nave: 3.4.1      quoin: 3.4.2     
cornice: 3.3.5   facade: 3.3.6    ionic: 3.4.1     lintel: 3.4.1    oculus: 3.4.1    rotunda: 3.4.3   
dormer: 3.3.5    gable: 3.4.0     jagati: 3.4.1    minaret: 3.4.1   parapet: 3.4.1   scroll: 3.4.3    

published a month ago by bladey <bladey@me.com>

```

**Comment by bladey** [comment]
Hey @jayhale, that's odd, here is what I get --

```
➜  temp nvm use 16.13
Now using node v16.13.2 (npm v8.1.2)
➜  temp which yarn
/Users/bladey/.nvm/versions/node/v16.13.2/bin/yarn
➜  temp yarn create keystone-app
yarn create v1.22.17
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Installed "create-keystone-app@6.0.1" with binaries:
      - create-keystone-app
[#######################################################################################################################] 160/160
✨ You're about to generate a project using Keystone 6 packages.

✔ What directory should create-keystone-app generate your app into? · test-app

✔ Installed dependencies with yarn.

🎉  Keystone created a starter project in: test-app

  To launch your app, run:

  - cd test-app
  - yarn dev

  Next steps:

  - Read test-app/README.md for additional getting started details.
  - Edit test-app/keystone.ts to customize your app.
  - Open the Admin UI
  - Open the Graphql API
  - Read the docs
  - Star Keystone on GitHub

✨  Done in 36.84s.
➜  temp cd test-app
➜  test-app yarn postinstall
yarn run v1.22.17
$ keystone postinstall
✨ GraphQL and Prisma schemas are up to date
✨  Done in 1.63s.
```

I'm on an Apple MacBook Pro M1 with macOS 12.2.

I'll run this by the team and see if they have any ideas.

**Comment by jayhale** [comment]
Resolved with a clean out of requirements and starting over - must have been a rogue cached dependency.
