### ISSUE TITLE
BABEL_TRANSFORM_ERROR related to unicode regular expressions

### ISSUE THREAD

**Issue by pahaz** [keystonejs/keystone#7261]
Hi, I've some common js packages. And I want to import it.

I've added the line inside a ks6 example:
```
import { Message } from '../condo/apps/condo/domains/notification/schema'
```

And then I've got an error:
```
pahaz@PahazMac16 ks6-condo % yarn dev
yarn run v1.22.17
$ keystone dev
✨ Starting Keystone
Error: /Users/pahaz/Code/pahaz/condo/apps/condo/domains/common/constants/regexps.js: Unknown property: L
    at matchProperty (/Users/pahaz/Code/pahaz/ks6-condo/node_modules/next/dist/compiled/babel-packages/packages-bundle.js:320:32929)
    at handleLoneUnicodePropertyNameOrValue (/Users/pahaz/Code/pahaz/ks6-condo/node_modules/next/dist/compiled/babel-packages/packages-bundle.js:315:46664)
    at getUnicodePropertyEscapeSet (/Users/pahaz/Code/pahaz/ks6-condo/node_modules/next/dist/compiled/babel-packages/packages-bundle.js:315:46807)
    at processCharacterClass (/Users/pahaz/Code/pahaz/ks6-condo/node_modules/next/dist/compiled/babel-packages/packages-bundle.js:315:47864)
    at processTerm (/Users/pahaz/Code/pahaz/ks6-condo/node_modules/next/dist/compiled/babel-packages/packages-bundle.js:315:48494)
    at rewritePattern (/Users/pahaz/Code/pahaz/ks6-condo/node_modules/next/dist/compiled/babel-packages/packages-bundle.js:315:50577)
    at PluginPass.RegExpLiteral (/Users/pahaz/Code/pahaz/ks6-condo/node_modules/next/dist/compiled/babel-packages/packages-bundle.js:74:17966)
    at newFn (/Users/pahaz/Code/pahaz/ks6-condo/node_modules/@babel/traverse/lib/visitors.js:177:21)
    at NodePath._call (/Users/pahaz/Code/pahaz/ks6-condo/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/pahaz/Code/pahaz/ks6-condo/node_modules/@babel/traverse/lib/path/context.js:40:17) {
  code: 'BABEL_TRANSFORM_ERROR'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This error is related to the line:
```
const LETTERS_AND_NUMBERS = /[\p{L}\p{N}]/gu
```

It looks like a `babel` problem. But there is no way to configure internal keystone6 babel logic.

Any idea what to do with that error?

**Comment by dcousens** [comment]
Marked as stale, if anyone can reproduce this problem, please comment or open a new issue
