### ISSUE TITLE
@keystone-6/session-store-redis 'setEx' type Error

### ISSUE THREAD

**Issue by kyoungduck** [keystonejs/keystone#7351]
This is my code, but there was an error.
**code**
```
import { createAuth } from "@keystone-6/auth";

import { storedSessions } from "@keystone-6/core/session";
import { redisSessionStore } from "@keystone-6/session-store-redis";
import { createClient } from "redis";
import { getAppConfig } from "./app-config";

let sessionSecret = process.env.SESSION_SECRET;

if (!sessionSecret) {
  if (process.env.NODE_ENV === "production") {
    throw new Error(
      "The SESSION_SECRET environment variable must be set in production"
    );
  } else {
    sessionSecret = "dev secret dev secret dev secret dev secret dev secret";
  }
}

const { withAuth } = createAuth({
  listKey: "User",
  identityField: "email",
  sessionData: "name isAdmin",
  secretField: "password",
  initFirstItem: {
    fields: ["name", "email", "password"],
  },
});

let sessionMaxAge = 60 * 60 * 24 * 30; // 30 days

const session = storedSessions({
  maxAge: sessionMaxAge,
  secret: sessionSecret!,
  store: redisSessionStore({ //error in here
    client: createClient({ url: getAppConfig().REDIS_URL }),
  }),
});

export { withAuth, session };

```

**Error**
```
TypeError: The "original" argument must be of type function. Received undefined
    at Object.promisify (node:internal/util:329:3)
    at redisSessionStore (/Users/peter/Documents/project/team-bridge/maskque-app/node_modules/@keystone-6/session-store-redis/dist/keystone-6-session-store-redis.cjs.dev.js:12:31)
    at Object.<anonymous> (/Users/peter/Documents/project/team-bridge/maskque-app/auth.ts:35:10)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._compile (/Users/peter/Documents/project/team-bridge/maskque-app/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.newLoader [as .ts] (/Users/peter/Documents/project/team-bridge/maskque-app/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

I trace the error and I found error occured in [here](https://github.com/keystonejs/keystone/blob/main/packages/session-store-redis/src/index.ts#L11) 

When I fix the code like this, it works well.
```
let promisifiedSetex = promisify(client.setex).bind(client);
```

I think this is redis version problem, and I saw keystone package redis version is low(https://github.com/keystonejs/keystone/blob/main/packages/session-store-redis/package.json#L12).

How about upgrade redis version?

**My Environment**
- node version: v16.13.2
- redis(node package) version: redis@4.0.4
- @keystone-6/session-store-redis version: @keystone-6/session-store-redis@1.0.0

**Comment by dcousens** [comment]
Fixed in #7051,  see that for progress
