### ISSUE TITLE
Postinstall hook throws Prisma error when using pnpm: Command failed with exit code 1: npm install -D prisma@latest

### ISSUE THREAD

**Issue by isla-nye** [keystonejs/keystone#7625]
- Use pnpm for dependency management.
- Run `keystone postinstall`

Expected behaviour:
Postinstall completes

Actual:
Error thrown when trying to install Prisma, see below screenshot (it's for `postinstall --fix` but the same thing happens with `postinstall`):
![image](https://user-images.githubusercontent.com/87641417/173436674-3b100596-f719-445c-a91d-a661195fe6b1.png)

This seems like it's probably an issue with the dependency file structure of pnpm. No such error happens with npm, or when forcing a flat node_modules structure by using `pnpm i --shamefully-hoist`. 

It's not clear to me whether this is an issue on the Prisma side or on the Keystone side. Please let me know if it needs to be reported elsewhere.

Node version 18.3

**Comment by borisno2** [comment]
Hi @isla-nye 
Thanks for posting, we are exploring how we might better support `pnpm` for package management, currently you can list `prisma` and `@prisma/client` in your dependencies OR as you suggest use `pnpm i --shamefully-hoist`. 
Thanks

**Comment by fkrauthan** [comment]
For me I see a lot more errors. Like I have to specify `react` and tons of other libraries in my `package.json` when trying to use `pnpm` out of the box.

**Comment by fkrauthan** [comment]
To be more specific I had to list:

* `react`
* `@babel/runtime`
* `@prisma/client`
* `prisma`
* `@types/react`
* `@types/node`

That at least makes all keystone commands succeed and the GraphQL API works as expected. BUT when trying to access the keystone admin UI I am stuck with the error:

```
Error: Cannot find module 'next/dist/shared/lib/constants.js'
Require stack:
- C:\Users\fkrauthan\WebstormProjects\xxx\backend\.keystone\admin\.next\server\pages\_document.js
```

**Comment by isla-nye** [comment]
@fkrauthan We use pnpm workspaces too. --shamefully-hoist for just the package using KeystoneJS seems to work fine as a temporary workaround without having to add other dependencies, though I understand if you don't want to use it as a long-term solution.

**Comment by fkrauthan** [comment]
@isla-nye how do I enable the `--shamefully-hoist` just for the backend? Or do I always need to remember to call `pnpm i --shamefully-hoist`?

**Comment by isla-nye** [comment]
@fkrauthan you just have to remember `pnpm i --shamefully-hoist` (for the package containing your Keystone app only - no need to have it for the other packages in your workspace), and also remember to put it in whenever you run `pnpm i` in your CI scripts.

**Comment by fkrauthan** [comment]
But how does that work if I run `pnpm i` from the root of my project? It would loose the `--shamefully-hoist` install method for the backend subpackage wouldn't?

**Comment by mmachatschek** [comment]
I ran into some problems today with `@prisma/client` not having access to the generated client located in `.prisma/client` as `pnpm keystone postinstall --fix` and `pnpm keystone prisma generate` wouldn't put it into the appropriate folder. This issue came up when I tried to upgrade pnpm from version 6.x to 7.x

**Comment by xenobytezero** [comment]
I'm also seeing this issue as described by @fkrauthan when accessing the Admin UI

```
Error: Cannot find module 'next/dist/shared/lib/router/utils/remove-trailing-slash.js'
```

Im trying to avoid `--shamefully-hoist` as I have a different package in my monorepo which also uses NextJS that I'd like to have the versions kept sepearately.

**Comment by xenobytezero** [comment]
Also I can't add Next as a direct dependency like I normally do, as Keystone throws the usual "you have multiple Reacts" error

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following 
reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app        
See https://reactjs.org/link/invalid-hook-call for tips about how to 
debug and fix this problem.
```

**Comment by mmachatschek** [comment]
So I hit this error again with pnpm and after some debugging I found out, that the main issue is that `execa` doesn't know in which `.bin` folder it should look to use the `prisma` binary.

The `process.env.PATH` only contains the `node_modules/.bin` folder. In that folder (if you didn't explicitly install prisma) the binary for prisma is missing, as its only linked in the `node_modules/@keystone-6/core/node_modules/.bin` folder.

What I don't know is, if this is an issue on keystone, execa (executes the prisma command) or pnpm side.

At least keystone would fix this if the `node_modules/@keystone6-core/node_modules/.bin` path would be added to the command here I guess:

https://github.com/keystonejs/keystone/blob/6c60565c940a9e27b8bb9b3e3e61260f22ee1e1a/packages/core/src/scripts/prisma.ts#L15

**Comment by rburgst** [comment]
I have a similar problem as @mmachatschek when running `pnpm install --shamefully-hoist` it fails since its trying to resolve all lists where one of them does rely on the prisma client
```
> keystone postinstall

Error: Cannot find module '.prisma/client/index'
Require stack:
- /Users/user/git/keystone-project/node_modules/.pnpm/@prisma+client@4.4.0_prisma@4.4.0/node_modules/@prisma/client/index.js
- /Users/user/git/keystone-project/ks/services/athlete-result-service.ts
- /Users/user/git/keystone-project/ks/schema/Athlete.ts
- /Users/user/git/keystone-project/schema.ts
- /Users/user/git/keystone-project/keystone.ts
- /Users/user/git/keystone-project/node_modules/.pnpm/@keystone-6+core@2.3.0/node_modules/@keystone-6/core/dist/requireSource-ff4e29c3.cjs.dev.js
- /Users/user/git/keystone-project/node_modules/.pnpm/@keystone-6+core@2.3.0/node_modules/@keystone-6/core/scripts/cli/dist/keystone-6-core-scripts-cli.cjs.dev.js
- /Users/user/git/keystone-project/node_modules/.pnpm/@keystone-6+core@2.3.0/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.dev.js
- /Users/user/git/keystone-project/node_modules/.pnpm/@keystone-6+core@2.3.0/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.js
- /Users/user/git/keystone-project/node_modules/.pnpm/@keystone-6+core@2.3.0/node_modules/@keystone-6/core/bin/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/user/git/keystone-project/node_modules/.pnpm/@prisma+client@4.4.0_prisma@4.4.0/node_modules/@prisma/client/index.js:2:6)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.newLoader [as .js] (/Users/user/git/keystone-project/node_modules/.pnpm/pirates@4.0.4/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/user/git/keystone-project/ks/services/athlete-result-service.ts:13:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._compile (/Users/user/git/keystone-project/node_modules/.pnpm/pirates@4.0.4/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.newLoader [as .ts] (/Users/user/git/keystone-project/node_modules/.pnpm/pirates@4.0.4/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/user/git/keystone-project/ks/schema/Athlete.ts:26:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._compile (/Users/user/git/keystone-project/node_modules/.pnpm/pirates@4.0.4/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.newLoader [as .ts] (/Users/user/git/keystone-project/node_modules/.pnpm/pirates@4.0.4/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/user/git/keystone-project/schema.ts:26:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._compile (/Users/user/git/keystone-project/node_modules/.pnpm/pirates@4.0.4/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.newLoader [as .ts] (/Users/user/git/keystone-project/node_modules/.pnpm/pirates@4.0.4/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/user/git/keystone-project/keystone.ts:13:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._compile (/Users/user/git/keystone-project/node_modules/.pnpm/pirates@4.0.4/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.newLoader [as .ts] (/Users/user/git/keystone-project/node_modules/.pnpm/pirates@4.0.4/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.requireSource (/Users/user/git/keystone-project/node_modules/.pnpm/@keystone-6+core@2.3.0/node_modules/@keystone-6/core/dist/requireSource-ff4e29c3.cjs.dev.js:93:18)
    at postinstall (/Users/user/git/keystone-project/node_modules/.pnpm/@keystone-6+core@2.3.0/node_modules/@keystone-6/core/scripts/cli/dist/keystone-6-core-scripts-cli.cjs.dev.js:684:54) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/user/git/keystone-project/node_modules/.pnpm/@prisma+client@4.4.0_prisma@4.4.0/node_modules/@prisma/client/index.js',
    '/Users/user/git/keystone-project/ks/services/athlete-result-service.ts',
    '/Users/user/git/keystone-project/ks/schema/Athlete.ts',
    '/Users/user/git/keystone-project/schema.ts',
    '/Users/user/git/keystone-project/keystone.ts',
    '/Users/user/git/keystone-project/node_modules/.pnpm/@keystone-6+core@2.3.0/node_modules/@keystone-6/core/dist/requireSource-ff4e29c3.cjs.dev.js',
    '/Users/user/git/keystone-project/node_modules/.pnpm/@keystone-6+core@2.3.0/node_modules/@keystone-6/core/scripts/cli/dist/keystone-6-core-scripts-cli.cjs.dev.js',
    '/Users/user/git/keystone-project/node_modules/.pnpm/@keystone-6+core@2.3.0/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.dev.js',
    '/Users/user/git/keystone-project/node_modules/.pnpm/@keystone-6+core@2.3.0/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.js',
    '/Users/user/git/keystone-project/node_modules/.pnpm/@keystone-6+core@2.3.0/node_modules/@keystone-6/core/bin/cli.js'
  ]
}
```
I fixed that by changing my package.json like so

```
    "postinstall": "prisma generate && keystone postinstall",
```

The install then runs through, however, now when I run `pnpm dev` I get endless recompiles:
```
event - compiled client and server successfully in 3.3s (1248 modules)
✅ Admin UI ready
wait  - compiling /api/__keystone_api_build (client and server)...
event - compiled successfully in 675 ms (248 modules)
wait  - compiling...
event - compiled client and server successfully in 113 ms (1341 modules)
wait  - compiling...
event - compiled client and server successfully in 86 ms (1341 modules)
wait  - compiling...
event - compiled client and server successfully in 88 ms (1341 modules)
wait  - compiling...
event - compiled client and server successfully in 70 ms (1341 modules)
wait  - compiling...
event - compiled client and server successfully in 69 ms (1341 modules)
wait  - compiling...
event - compiled client and server successfully in 64 ms (1341 modules)
wait  - compiling...
event - compiled client and server successfully in 62 ms (1341 modules)
wait  - compiling...
event - compiled client and server successfully in 64 ms (1341 modules)
wait  - compiling...
event - compiled client and server successfully in 61 ms (1341 modules)
wait  - compiling...
event - compiled client and server successfully in 65 ms (1341 modules)
```

**Comment by rburgst** [comment]
ok, the issue with the constant recompiling seems to be #7902

**Comment by rburgst** [comment]
Actually I was too fast, now after getting the install fixed, keystone wont run properly, I am now seeing this issue: https://github.com/keystonejs/keystone/issues/6848

**Comment by TheRealFlyingCoder** [comment]
> Actually I was too fast, now after getting the install fixed, keystone wont run properly, I am now seeing this issue: #6848

I also just had this same issue come up ^

**Comment by dcousens** [comment]
Cannot reproduce with https://github.com/keystonejs/keystone/releases/tag/2023-02-23

**Comment by TheRealFlyingCoder** [comment]
Woohoo!!!
