### ISSUE TITLE
Create new from details screen - Cannot convert object to primitive value

### ISSUE THREAD

**Issue by trentmillar** [keystonejs/keystone#808]
Using keystone 0.2.36.

I have a model,

```
var OrderItem = new keystone.List('OrderItem', {
    track: true
});

OrderItem.add({
    order: { type: Types.Relationship, ref: 'Order', required: true, initial: true },
    photos: { type: Types.CloudinaryImages },
    type: {
        type: Types.Select,
        options: 'shirt, suit, blouse, coat',
        default: 'shirt',
        initial: true,
        required: true
    },
    notes: {type: Types.Html, wysiwyg: true}
});

OrderItem.defaultColumns = 'order, type|15%, updatedAt|30%';
OrderItem.defaultSort = '-updatedAt';
OrderItem.register();
```

I have no issues view or creating new Order Items through the AdminUI unless I select the *+ New Order Item* from within the details screen. When I try to create a new item from here I get the following keystone error dump,

```
TypeError: /home/tmillar/repo/oasis-web/node_modules/oasis-db/node_modules/keyst
one/templates/views/list.jade:24
    22|         script(src='/keystone/js/lib/browserified/querystring.js')
    23|         script(src='/keystone/js/lib/browserified/queryfilter.js')
  > 24|         script.
    25|                 Keystone.list = { path: "#{list.path}", label: "#{list.l
abel}", singular: "#{list.singular}", plural: "#{list.plural}", cols: !{JSON.str
ingify(colPaths)}, perPage: !{ Number(list.perPage) || 50 } };
    26|                 Keystone.wysiwyg = { options: !{JSON.stringify(wysiwygOp
tions)} };
    27|                 Keystone.items = !{ JSON.stringify(items) };

Cannot convert object to primitive value
  at String (native)
  at Object.escape (/home/tmillar/repo/oasis-web/node_modules/oasis-db/node_modu
les/keystone/node_modules/jade/lib/runtime.js:183:16)
  at eval (<anonymous>:5023:40)
  at eval (<anonymous>:5081:22)
  at res (/home/tmillar/repo/oasis-web/node_modules/oasis-db/node_modules/keysto
ne/node_modules/jade/lib/index.js:191:38)
  at [object Object].Keystone.render (/home/tmillar/repo/oasis-web/node_modules/
oasis-db/node_modules/keystone/index.js:344:13)
  at /home/tmillar/repo/oasis-web/node_modules/oasis-db/node_modules/keystone/ro
utes/views/list.js:117:14
  at /home/tmillar/repo/oasis-web/node_modules/oasis-db/node_modules/keystone/no
de_modules/async/lib/async.js:157:25
  at select.Field.compile (/home/tmillar/repo/oasis-web/node_modules/oasis-db/no
de_modules/keystone/lib/field.js:334:10)
  at compileFields (/home/tmillar/repo/oasis-web/node_modules/oasis-db/node_modu
les/keystone/routes/views/list.js:113:56)
  at iterate (/home/tmillar/repo/oasis-web/node_modules/oasis-db/node_modules/ke
ystone/node_modules/async/lib/async.js:149:13)
  at /home/tmillar/repo/oasis-web/node_modules/oasis-db/node_modules/keystone/no
de_modules/async/lib/async.js:160:25
  at relationship.Field.compile (/home/tmillar/repo/oasis-web/node_modules/oasis
-db/node_modules/keystone/lib/field.js:334:10)
  at compileFields (/home/tmillar/repo/oasis-web/node_modules/oasis-db/node_modu
les/keystone/routes/views/list.js:113:56)
  at iterate (/home/tmillar/repo/oasis-web/node_modules/oasis-db/node_modules/ke
ystone/node_modules/async/lib/async.js:149:13)
  at Object.async.eachSeries (/home/tmillar/repo/oasis-web/node_modules/oasis-db
/node_modules/keystone/node_modules/async/lib/async.js:165:9)
  at /home/tmillar/repo/oasis-web/node_modules/oasis-db/node_modules/keystone/ro
utes/views/list.js:115:10
  at Promise.<anonymous> (/home/tmillar/repo/oasis-web/node_modules/oasis-db/nod
e_modules/keystone/lib/list.js:1187:5)
  at Promise.<anonymous> (/home/tmillar/repo/oasis-web/node_modules/mongoose/nod
e_modules/mpromise/lib/promise.js:177:8)
  at Promise.emit (events.js:107:17)
  at Promise.emit (/home/tmillar/repo/oasis-web/node_modules/mongoose/node_modul
es/mpromise/lib/promise.js:84:38)
  at Promise.fulfill (/home/tmillar/repo/oasis-web/node_modules/mongoose/node_mo
dules/mpromise/lib/promise.js:97:20)
  at Promise.resolve (/home/tmillar/repo/oasis-web/node_modules/mongoose/lib/pro
mise.js:114:23)
  at Promise.<anonymous> (/home/tmillar/repo/oasis-web/node_modules/mongoose/nod
e_modules/mpromise/lib/promise.js:177:8)
  at Promise.emit (events.js:107:17)
  at Promise.emit (/home/tmillar/repo/oasis-web/node_modules/mongoose/node_modul
es/mpromise/lib/promise.js:84:38)
  at Promise.fulfill (/home/tmillar/repo/oasis-web/node_modules/mongoose/node_mo
dules/mpromise/lib/promise.js:97:20)
  at /home/tmillar/repo/oasis-web/node_modules/mongoose/lib/query.js:1052:26
  at model.Document.init (/home/tmillar/repo/oasis-web/node_modules/mongoose/lib
/document.js:250:11)
  at completeMany (/home/tmillar/repo/oasis-web/node_modules/mongoose/lib/query.
js:1050:12)
  at Promise.<anonymous> (/home/tmillar/repo/oasis-web/node_modules/mongoose/lib
/query.js:1025:11)
  at Promise.<anonymous> (/home/tmillar/repo/oasis-web/node_modules/mongoose/nod
e_modules/mpromise/lib/promise.js:177:8)
  at Promise.emit (events.js:107:17)
  at Promise.emit (/home/tmillar/repo/oasis-web/node_modules/mongoose/node_modul
es/mpromise/lib/promise.js:84:38)
  at Promise.fulfill (/home/tmillar/repo/oasis-web/node_modules/mongoose/node_mo
dules/mpromise/lib/promise.js:97:20)
  at Promise.resolve (/home/tmillar/repo/oasis-web/node_modules/mongoose/lib/pro
mise.js:114:23)
  at /home/tmillar/repo/oasis-web/node_modules/mongoose/lib/model.js:2040:23
  at process._tickCallback (node.js:372:11)
```

**Comment by JedWatson** [comment]
This should now be fixed in master, @trentmillar please let me know if you encounter it in the future.
