### ISSUE TITLE
Cannot find module 'next/dist/shared/lib/constants.js'

### ISSUE THREAD

**Issue by beccauwu** [keystonejs/keystone#8181]
To reproduce, run Keystone inside a docker container in dev mode with the following Dockerfile:

```yml
FROM node:14.21.1

RUN npm install -g pnpm

WORKDIR /backend

COPY package.json pnpm-lock.yaml ./

COPY . .

RUN pnpm install --frozen-lockfile

CMD [ "pnpm", "run", "dev" ]
```

The app works without any issues locally, however when running it in Docker, the following error happens:

```sh
Server Error
Error: Cannot find module 'next/dist/shared/lib/constants.js'
Require stack:
- /backend/.keystone/admin/.next/server/pages/_document.js
- /backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/require.js
- /backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/next-server.js
- /backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/dev/next-dev-server.js
- /backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/next.js
- /backend/node_modules/.pnpm/@keystone-6+core@4.0.1_b4eyluiibtzggrslc7q5mbsxbu/node_modules/@keystone-6/core/dist/createAdminUIMiddleware-c41a0fb3.cjs.dev.js
- /backend/node_modules/.pnpm/@keystone-6+core@4.0.1_b4eyluiibtzggrslc7q5mbsxbu/node_modules/@keystone-6/core/scripts/cli/dist/keystone-6-core-scripts-cli.cjs.dev.js
- /backend/node_modules/.pnpm/@keystone-6+core@4.0.1_b4eyluiibtzggrslc7q5mbsxbu/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.dev.js
- /backend/node_modules/.pnpm/@keystone-6+core@4.0.1_b4eyluiibtzggrslc7q5mbsxbu/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.js
- /backend/node_modules/.pnpm/@keystone-6+core@4.0.1_b4eyluiibtzggrslc7q5mbsxbu/node_modules/@keystone-6/core/bin/cli.js

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
Function.Module._resolveFilename
internal/modules/cjs/loader.js (902:15)
Function.mod._resolveFilename
file:///backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/build/webpack/require-hook.js (23:32)
Function.Module._load
internal/modules/cjs/loader.js (746:27)
Module.require
internal/modules/cjs/loader.js (974:19)
require
internal/modules/cjs/helpers.js (101:18)
Object.../shared/lib/constants
file:///backend/.keystone/admin/.next/server/pages/_document.js (82:18)
__webpack_require__
file:///backend/.keystone/admin/.next/server/webpack-runtime.js (33:42)
require
../node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/pages/_document.js (9:17)
Object.../../node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/pages/_document.js
file:///backend/.keystone/admin/.next/server/pages/_document.js (22:1)
__webpack_require__
file:///backend/.keystone/admin/.next/server/webpack-runtime.js (33:42)
__webpack_exec__
file:///backend/.keystone/admin/.next/server/pages/_document.js (122:39)
<unknown>
file:///backend/.keystone/admin/.next/server/pages/_document.js (123:28)
Object.<anonymous>
file:///backend/.keystone/admin/.next/server/pages/_document.js (126:3)
Module._compile
internal/modules/cjs/loader.js (1085:14)
Object.Module._extensions..js
internal/modules/cjs/loader.js (1114:10)
Module.load
internal/modules/cjs/loader.js (950:32)
Function.Module._load
internal/modules/cjs/loader.js (790:12)
Module.require
internal/modules/cjs/loader.js (974:19)
require
internal/modules/cjs/helpers.js (101:18)
Object.requirePage
file:///backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/require.js (88:12)
<unknown>
file:///backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/load-components.js (33:54)
processTicksAndRejections
internal/process/task_queues.js (95:5)
async Object.loadComponents
file:///backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/load-components.js (32:33)
async DevServer.findPageComponents
file:///backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/next-server.js (561:36)
```

I've tried deleting the .keystone directory as I figured it may have been a cache issue, it didn't resolve it. I haven't tried building the app and running it that way yet, and it would probably work. I just wanted to have it in docker to easily develop as i'll be having a frontend connected to this later.

This is my package.json:

```json
{
  "name": "keystone-app",
  "version": "1.0.2",
  "private": true,
  "scripts": {
    "dev": "keystone dev",
    "start": "keystone start",
    "build": "keystone build",
    "postinstall": "keystone postinstall"
  },
  "dependencies": {
    "@aws-sdk/abort-controller": "^3.226.0",
    "@babel/core": "^7.20.5",
    "@keystone-6/auth": "^6.0.0",
    "@keystone-6/core": "^4.0.1",
    "@keystone-6/fields-document": "^6.0.0",
    "@prisma/client": "4.3.1",
    "@prisma/generator-helper": "^4.7.1",
    "body-parser": "1.20.1",
    "dotenv": "^16.0.3",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "typescript": "^4.8.0",
    "ws": "^8.11.0"
  },
  "devDependencies": {
    "@types/body-parser": "^1.19.2",
    "@types/node": "18.11.17",
    "@types/react": "18.0.26",
    "@types/ws": "^8.5.3",
    "prisma": "4.3.1"
  }
}
```

and this is my config:

```typescript
export default withAuth(
  config({
    db: {
      // we're using sqlite for the fastest startup experience
      //   for more information on what database might be appropriate for you
      //   see https://keystonejs.com/docs/guides/choosing-a-database#title
      provider: 'sqlite',
      url: databaseUrl,
    },
    lists,
    session,
    server: {
      port: serverPort(),
      extendExpressApp: (app, ctx) => {
        app.use(json( { limit: '50mb' } ));
        // rest stuff
        app.get("/api/users", async (req, res) => {
          const context = await ctx.withRequest(req, res);
          const users = await context.query.User.findMany({query: 'id name email posts { id title }'});
          res.json(users);
        });
        //other endpoints for crud
      },
    },
    graphql: {
      path: '/graphql',
      playground: true,
      apolloConfig: {
        introspection: true,
        allowBatchedHttpRequests: true,
      },
    },
  })
);
```

Only thing I could find with a similar error is in issue #6583, however, from what I know, the only copy of next I have installed is in the keystone modules and the only time it's referenced inside pnpm-lock is in @keystone/core dependencies. I could have completely misunderstood that issue though.

E: Forgot to add logs from the container:

```
error - Error: Cannot find module 'next/dist/shared/lib/constants.js'
Require stack:
- /backend/.keystone/admin/.next/server/pages/_document.js
- /backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/require.js
- /backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/next-server.js
- /backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/dev/next-dev-server.js
- /backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/next.js
- /backend/node_modules/.pnpm/@keystone-6+core@4.0.1_b4eyluiibtzggrslc7q5mbsxbu/node_modules/@keystone-6/core/dist/createAdminUIMiddleware-c41a0fb3.cjs.dev.js
- /backend/node_modules/.pnpm/@keystone-6+core@4.0.1_b4eyluiibtzggrslc7q5mbsxbu/node_modules/@keystone-6/core/scripts/cli/dist/keystone-6-core-scripts-cli.cjs.dev.js
- /backend/node_modules/.pnpm/@keystone-6+core@4.0.1_b4eyluiibtzggrslc7q5mbsxbu/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.dev.js
- /backend/node_modules/.pnpm/@keystone-6+core@4.0.1_b4eyluiibtzggrslc7q5mbsxbu/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.js
- /backend/node_modules/.pnpm/@keystone-6+core@4.0.1_b4eyluiibtzggrslc7q5mbsxbu/node_modules/@keystone-6/core/bin/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.mod._resolveFilename (/backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/build/webpack/require-hook.js:23:32)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.../shared/lib/constants (/backend/.keystone/admin/.next/server/pages/_document.js:82:18)
    at __webpack_require__ (/backend/.keystone/admin/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///../../node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/pages/_document.js:9:18)
    at Object.../../node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/pages/_document.js (/backend/.keystone/admin/.next/server/pages/_document.js:22:1)
    at __webpack_require__ (/backend/.keystone/admin/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/backend/.keystone/admin/.next/server/pages/_document.js:122:39)
    at /backend/.keystone/admin/.next/server/pages/_document.js:123:28
    at Object.<anonymous> (/backend/.keystone/admin/.next/server/pages/_document.js:126:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.requirePage (/backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/require.js:88:12)
    at /backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/load-components.js:33:54
    at async Promise.all (index 0)
    at async Object.loadComponents (/backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/load-components.js:32:33)
    at async DevServer.findPageComponents (/backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/next-server.js:561:36) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/backend/.keystone/admin/.next/server/pages/_document.js',
    '/backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/require.js',
    '/backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/next-server.js',
    '/backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/dev/next-dev-server.js',
    '/backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/next.js',
    '/backend/node_modules/.pnpm/@keystone-6+core@4.0.1_b4eyluiibtzggrslc7q5mbsxbu/node_modules/@keystone-6/core/dist/createAdminUIMiddleware-c41a0fb3.cjs.dev.js',
    '/backend/node_modules/.pnpm/@keystone-6+core@4.0.1_b4eyluiibtzggrslc7q5mbsxbu/node_modules/@keystone-6/core/scripts/cli/dist/keystone-6-core-scripts-cli.cjs.dev.js',
    '/backend/node_modules/.pnpm/@keystone-6+core@4.0.1_b4eyluiibtzggrslc7q5mbsxbu/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.dev.js',
    '/backend/node_modules/.pnpm/@keystone-6+core@4.0.1_b4eyluiibtzggrslc7q5mbsxbu/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.js',
    '/backend/node_modules/.pnpm/@keystone-6+core@4.0.1_b4eyluiibtzggrslc7q5mbsxbu/node_modules/@keystone-6/core/bin/cli.js'
  ],
  page: '/signin'
}
Error: Cannot find module 'next/dist/shared/lib/constants.js'
Require stack:
- /backend/.keystone/admin/.next/server/pages/_document.js
- /backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/require.js
- /backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/next-server.js
- /backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/dev/next-dev-server.js
- /backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/next.js
- /backend/node_modules/.pnpm/@keystone-6+core@4.0.1_b4eyluiibtzggrslc7q5mbsxbu/node_modules/@keystone-6/core/dist/createAdminUIMiddleware-c41a0fb3.cjs.dev.js
- /backend/node_modules/.pnpm/@keystone-6+core@4.0.1_b4eyluiibtzggrslc7q5mbsxbu/node_modules/@keystone-6/core/scripts/cli/dist/keystone-6-core-scripts-cli.cjs.dev.js
- /backend/node_modules/.pnpm/@keystone-6+core@4.0.1_b4eyluiibtzggrslc7q5mbsxbu/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.dev.js
- /backend/node_modules/.pnpm/@keystone-6+core@4.0.1_b4eyluiibtzggrslc7q5mbsxbu/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.js
- /backend/node_modules/.pnpm/@keystone-6+core@4.0.1_b4eyluiibtzggrslc7q5mbsxbu/node_modules/@keystone-6/core/bin/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.mod._resolveFilename (/backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/build/webpack/require-hook.js:23:32)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.../shared/lib/constants (/backend/.keystone/admin/.next/server/pages/_document.js:82:18)
    at __webpack_require__ (/backend/.keystone/admin/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///../../node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/pages/_document.js:9:18)
    at Object.../../node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/pages/_document.js (/backend/.keystone/admin/.next/server/pages/_document.js:22:1)
    at __webpack_require__ (/backend/.keystone/admin/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/backend/.keystone/admin/.next/server/pages/_document.js:122:39)
    at /backend/.keystone/admin/.next/server/pages/_document.js:123:28
    at Object.<anonymous> (/backend/.keystone/admin/.next/server/pages/_document.js:126:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.requirePage (/backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/require.js:88:12)
    at /backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/load-components.js:33:54
    at async Promise.all (index 0)
    at async Object.loadComponents (/backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/load-components.js:32:33)
    at async DevServer.findPageComponents (/backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/next-server.js:561:36) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/backend/.keystone/admin/.next/server/pages/_document.js',
    '/backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/require.js',
    '/backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/next-server.js',
    '/backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/dev/next-dev-server.js',
    '/backend/node_modules/.pnpm/next@13.0.7_672uxklweod7ene3nqtsh262ca/node_modules/next/dist/server/next.js',
    '/backend/node_modules/.pnpm/@keystone-6+core@4.0.1_b4eyluiibtzggrslc7q5mbsxbu/node_modules/@keystone-6/core/dist/createAdminUIMiddleware-c41a0fb3.cjs.dev.js',
    '/backend/node_modules/.pnpm/@keystone-6+core@4.0.1_b4eyluiibtzggrslc7q5mbsxbu/node_modules/@keystone-6/core/scripts/cli/dist/keystone-6-core-scripts-cli.cjs.dev.js',
    '/backend/node_modules/.pnpm/@keystone-6+core@4.0.1_b4eyluiibtzggrslc7q5mbsxbu/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.dev.js',
    '/backend/node_modules/.pnpm/@keystone-6+core@4.0.1_b4eyluiibtzggrslc7q5mbsxbu/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.js',
    '/backend/node_modules/.pnpm/@keystone-6+core@4.0.1_b4eyluiibtzggrslc7q5mbsxbu/node_modules/@keystone-6/core/bin/cli.js'
  ]
}
```

**Comment by borisno2** [comment]
Hi @beccauwu Thanks for posting, I haven't been able to replicate this issue. make sure you have deleted both the `.keystone` and `node_modules` folders before running the `docker build` ideally add these folders to your `.dockerignore`

**Comment by borisno2** [comment]
Hey @beccauwu I am going to close this issue now, feel free to reopen it if there is still an issue - it also might be worth updating to node 18 or at least 16 on your docker container.
