### ISSUE TITLE
Dataloader error when querying to-one relationship to which there is no access

### ISSUE THREAD

**Issue by marekryb** [keystonejs/keystone#8191]
## Steps to Reproduce
1. Run 'blog' example and seed database (`yarn dev --seed-data`)
2. Run keystone (`yarn dev`)
3. Change 'Author' access to denyAll like https://github.com/marekryb/keystone/commit/29fcc9b6ba2bbd3a44b376ff47db9fef3e48c46b
4. Run following query
```graphql
query {
  posts {
   author {
    name
   }
  }
}
```
5. Observe that the output (data) is correct, but for each item returned there is also following error
```graphql
{
  "errors": [
    {
      "message": "DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array of the same length as the Array of keys.\n\nKeys:\nclbwzx1jo00028txkgnyek5yb,clbwzx1k300118txkkms5ey04,clbwzx1ki00208txksj6om4pm,clbwzx1ki00208txksj6om4pm,clbwzx1lf00318txk68x8t7kv,clbwzx1lf00318txk68x8t7kv,clbwzx1m100428txkotvccn9l,clbwzx1mg00518txk2jjpjhpl\n\nValues:\n",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "posts",
        0,
        "author"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
```

<details><summary>Full output</summary>

```graphql
{
  "errors": [
    {
      "message": "DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array of the same length as the Array of keys.\n\nKeys:\nclbwzx1jo00028txkgnyek5yb,clbwzx1k300118txkkms5ey04,clbwzx1ki00208txksj6om4pm,clbwzx1ki00208txksj6om4pm,clbwzx1lf00318txk68x8t7kv,clbwzx1lf00318txk68x8t7kv,clbwzx1m100428txkotvccn9l,clbwzx1mg00518txk2jjpjhpl\n\nValues:\n",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "posts",
        0,
        "author"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array of the same length as the Array of keys.",
            "",
            "Keys:",
            "clbwzx1jo00028txkgnyek5yb,clbwzx1k300118txkkms5ey04,clbwzx1ki00208txksj6om4pm,clbwzx1ki00208txksj6om4pm,clbwzx1lf00318txk68x8t7kv,clbwzx1lf00318txk68x8t7kv,clbwzx1m100428txkotvccn9l,clbwzx1mg00518txk2jjpjhpl",
            "",
            "Values:",
            "",
            "    at /home/exar/os/my_keystone/node_modules/dataloader/index.js:294:13",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
          ]
        }
      }
    },
    {
      "message": "DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array of the same length as the Array of keys.\n\nKeys:\nclbwzx1jo00028txkgnyek5yb,clbwzx1k300118txkkms5ey04,clbwzx1ki00208txksj6om4pm,clbwzx1ki00208txksj6om4pm,clbwzx1lf00318txk68x8t7kv,clbwzx1lf00318txk68x8t7kv,clbwzx1m100428txkotvccn9l,clbwzx1mg00518txk2jjpjhpl\n\nValues:\n",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "posts",
        1,
        "author"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array of the same length as the Array of keys.",
            "",
            "Keys:",
            "clbwzx1jo00028txkgnyek5yb,clbwzx1k300118txkkms5ey04,clbwzx1ki00208txksj6om4pm,clbwzx1ki00208txksj6om4pm,clbwzx1lf00318txk68x8t7kv,clbwzx1lf00318txk68x8t7kv,clbwzx1m100428txkotvccn9l,clbwzx1mg00518txk2jjpjhpl",
            "",
            "Values:",
            "",
            "    at /home/exar/os/my_keystone/node_modules/dataloader/index.js:294:13",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
          ]
        }
      }
    },
    {
      "message": "DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array of the same length as the Array of keys.\n\nKeys:\nclbwzx1jo00028txkgnyek5yb,clbwzx1k300118txkkms5ey04,clbwzx1ki00208txksj6om4pm,clbwzx1ki00208txksj6om4pm,clbwzx1lf00318txk68x8t7kv,clbwzx1lf00318txk68x8t7kv,clbwzx1m100428txkotvccn9l,clbwzx1mg00518txk2jjpjhpl\n\nValues:\n",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "posts",
        2,
        "author"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array of the same length as the Array of keys.",
            "",
            "Keys:",
            "clbwzx1jo00028txkgnyek5yb,clbwzx1k300118txkkms5ey04,clbwzx1ki00208txksj6om4pm,clbwzx1ki00208txksj6om4pm,clbwzx1lf00318txk68x8t7kv,clbwzx1lf00318txk68x8t7kv,clbwzx1m100428txkotvccn9l,clbwzx1mg00518txk2jjpjhpl",
            "",
            "Values:",
            "",
            "    at /home/exar/os/my_keystone/node_modules/dataloader/index.js:294:13",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
          ]
        }
      }
    },
    {
      "message": "DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array of the same length as the Array of keys.\n\nKeys:\nclbwzx1jo00028txkgnyek5yb,clbwzx1k300118txkkms5ey04,clbwzx1ki00208txksj6om4pm,clbwzx1ki00208txksj6om4pm,clbwzx1lf00318txk68x8t7kv,clbwzx1lf00318txk68x8t7kv,clbwzx1m100428txkotvccn9l,clbwzx1mg00518txk2jjpjhpl\n\nValues:\n",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "posts",
        3,
        "author"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array of the same length as the Array of keys.",
            "",
            "Keys:",
            "clbwzx1jo00028txkgnyek5yb,clbwzx1k300118txkkms5ey04,clbwzx1ki00208txksj6om4pm,clbwzx1ki00208txksj6om4pm,clbwzx1lf00318txk68x8t7kv,clbwzx1lf00318txk68x8t7kv,clbwzx1m100428txkotvccn9l,clbwzx1mg00518txk2jjpjhpl",
            "",
            "Values:",
            "",
            "    at /home/exar/os/my_keystone/node_modules/dataloader/index.js:294:13",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
          ]
        }
      }
    },
    {
      "message": "DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array of the same length as the Array of keys.\n\nKeys:\nclbwzx1jo00028txkgnyek5yb,clbwzx1k300118txkkms5ey04,clbwzx1ki00208txksj6om4pm,clbwzx1ki00208txksj6om4pm,clbwzx1lf00318txk68x8t7kv,clbwzx1lf00318txk68x8t7kv,clbwzx1m100428txkotvccn9l,clbwzx1mg00518txk2jjpjhpl\n\nValues:\n",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "posts",
        4,
        "author"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array of the same length as the Array of keys.",
            "",
            "Keys:",
            "clbwzx1jo00028txkgnyek5yb,clbwzx1k300118txkkms5ey04,clbwzx1ki00208txksj6om4pm,clbwzx1ki00208txksj6om4pm,clbwzx1lf00318txk68x8t7kv,clbwzx1lf00318txk68x8t7kv,clbwzx1m100428txkotvccn9l,clbwzx1mg00518txk2jjpjhpl",
            "",
            "Values:",
            "",
            "    at /home/exar/os/my_keystone/node_modules/dataloader/index.js:294:13",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
          ]
        }
      }
    },
    {
      "message": "DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array of the same length as the Array of keys.\n\nKeys:\nclbwzx1jo00028txkgnyek5yb,clbwzx1k300118txkkms5ey04,clbwzx1ki00208txksj6om4pm,clbwzx1ki00208txksj6om4pm,clbwzx1lf00318txk68x8t7kv,clbwzx1lf00318txk68x8t7kv,clbwzx1m100428txkotvccn9l,clbwzx1mg00518txk2jjpjhpl\n\nValues:\n",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "posts",
        5,
        "author"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array of the same length as the Array of keys.",
            "",
            "Keys:",
            "clbwzx1jo00028txkgnyek5yb,clbwzx1k300118txkkms5ey04,clbwzx1ki00208txksj6om4pm,clbwzx1ki00208txksj6om4pm,clbwzx1lf00318txk68x8t7kv,clbwzx1lf00318txk68x8t7kv,clbwzx1m100428txkotvccn9l,clbwzx1mg00518txk2jjpjhpl",
            "",
            "Values:",
            "",
            "    at /home/exar/os/my_keystone/node_modules/dataloader/index.js:294:13",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
          ]
        }
      }
    },
    {
      "message": "DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array of the same length as the Array of keys.\n\nKeys:\nclbwzx1jo00028txkgnyek5yb,clbwzx1k300118txkkms5ey04,clbwzx1ki00208txksj6om4pm,clbwzx1ki00208txksj6om4pm,clbwzx1lf00318txk68x8t7kv,clbwzx1lf00318txk68x8t7kv,clbwzx1m100428txkotvccn9l,clbwzx1mg00518txk2jjpjhpl\n\nValues:\n",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "posts",
        6,
        "author"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array of the same length as the Array of keys.",
            "",
            "Keys:",
            "clbwzx1jo00028txkgnyek5yb,clbwzx1k300118txkkms5ey04,clbwzx1ki00208txksj6om4pm,clbwzx1ki00208txksj6om4pm,clbwzx1lf00318txk68x8t7kv,clbwzx1lf00318txk68x8t7kv,clbwzx1m100428txkotvccn9l,clbwzx1mg00518txk2jjpjhpl",
            "",
            "Values:",
            "",
            "    at /home/exar/os/my_keystone/node_modules/dataloader/index.js:294:13",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
          ]
        }
      }
    },
    {
      "message": "DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array of the same length as the Array of keys.\n\nKeys:\nclbwzx1jo00028txkgnyek5yb,clbwzx1k300118txkkms5ey04,clbwzx1ki00208txksj6om4pm,clbwzx1ki00208txksj6om4pm,clbwzx1lf00318txk68x8t7kv,clbwzx1lf00318txk68x8t7kv,clbwzx1m100428txkotvccn9l,clbwzx1mg00518txk2jjpjhpl\n\nValues:\n",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "posts",
        7,
        "author"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array of the same length as the Array of keys.",
            "",
            "Keys:",
            "clbwzx1jo00028txkgnyek5yb,clbwzx1k300118txkkms5ey04,clbwzx1ki00208txksj6om4pm,clbwzx1ki00208txksj6om4pm,clbwzx1lf00318txk68x8t7kv,clbwzx1lf00318txk68x8t7kv,clbwzx1m100428txkotvccn9l,clbwzx1mg00518txk2jjpjhpl",
            "",
            "Values:",
            "",
            "    at /home/exar/os/my_keystone/node_modules/dataloader/index.js:294:13",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
          ]
        }
      }
    }
  ],
  "data": {
    "posts": [
      {
        "author": null
      },
      {
        "author": null
      },
      {
        "author": null
      },
      {
        "author": null
      },
      {
        "author": null
      },
      {
        "author": null
      },
      {
        "author": null
      },
      {
        "author": null
      }
    ]
  }
}
```
</details>

## Expected Behavior
No errors are thrown

## Additional information
- Issue does not happen if relation is to-many (many: true)
- As a workaround, adding access restriction to relationship field like:
`author: relationship({ ref: 'Author.posts', many: false, access: denyAll }),`
makes the error go away. However such duplication of access restrictions seems 'no-no'.

**Comment by borisno2** [comment]
Hi @marekryb thanks for spotting this one and letting us know
