### ISSUE TITLE
Warning log: validateDOMNesting(...): <head> cannot appear as a child of <div>

### ISSUE THREAD

**Issue by devmor-j** [keystonejs/keystone#8211]
1. Create a keystone app and run `npm run dev` (same as `keystone dev`)
2. Open dev server on your browser
3. Create a user and restart dev server
4. Open browser again and refresh
5. Open devtools and head to console tab
6. Warning with an error log is shown

No error

![Screenshot_20221231_164452](https://user-images.githubusercontent.com/88786674/210138028-e11da792-4f16-441b-8d19-46f1f99be5ef.png)

**Package.json**
```json
{
  "name": "keystone-app",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "keystone dev",
    "start": "keystone start",
    "build": "keystone build",
    "postinstall": "keystone postinstall",
  },
  "dependencies": {
    "@keystone-6/auth": "^6.0.0",
    "@keystone-6/core": "^4.0.1",
    "@keystone-6/fields-document": "^6.0.0",
    "typescript": "^4.9.4"
  }
}
```

**Error log**

```js
next-dev.js?36dd:20 Warning: validateDOMNesting(...): <head> cannot appear as a child of <div>.
    at head
    at div
    at SigninContainer (webpack-internal:///../../node_modules/@keystone-6/auth/dist/useFromRedirect-048776a2.esm.js:17:5)
    at SigninPage (webpack-internal:///../../node_modules/@keystone-6/auth/pages/SigninPage/dist/keystone-6-auth-pages-SigninPage.esm.js:34:5)
    at ErrorBoundary (webpack-internal:///../../node_modules/@keystone-6/core/dist/Errors-f59723d8.esm.js:20:5)
    at DrawerProvider (webpack-internal:///../../node_modules/@keystone-ui/modals/dist/keystone-ui-modals.esm.js:54:5)
    at ToastProvider (webpack-internal:///../../node_modules/@keystone-ui/toast/dist/keystone-ui-toast.esm.js:41:5)
    at InternalKeystoneProvider (webpack-internal:///../../node_modules/@keystone-6/core/admin-ui/context/dist/keystone-6-core-admin-ui-context.esm.js:310:5)
    at ApolloProvider (webpack-internal:///../../node_modules/@apollo/client/react/context/ApolloProvider.js:12:21)
    at KeystoneProvider (webpack-internal:///../../node_modules/@keystone-6/core/admin-ui/context/dist/keystone-6-core-admin-ui-context.esm.js:356:14)
    at Core (webpack-internal:///../../node_modules/@keystone-ui/core/dist/keystone-ui-core.esm.js:1304:5)
    at eval (webpack-internal:///../../node_modules/@keystone-6/core/___internal-do-not-use-will-break-in-patch/admin-ui/pages/App/dist/keystone-6-core-___internal-do-not-use-will-break-in-patch-admin-ui-pages-App.esm.js:84:5)
    at PathnameContextProviderAdapter (webpack-internal:///../../node_modules/next/dist/shared/lib/router/adapters.js:62:11)
    at ErrorBoundary (webpack-internal:///../../node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:301:63)
    at ReactDevOverlay (webpack-internal:///../../node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:850:919)
    at Container (webpack-internal:///../../node_modules/next/dist/client/index.js:61:1)
    at AppContainer (webpack-internal:///../../node_modules/next/dist/client/index.js:171:11)
    at Root (webpack-internal:///../../node_modules/next/dist/client/index.js:346:11)
```

**Comment by devmor-j** [comment]
Also similar warning log when discard creating an item (dev env):

```js
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
    at div
    at eval (webpack-internal:///../../node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Dot (webpack-internal:///../../node_modules/@keystone-ui/loading/dist/keystone-ui-loading.esm.js:59:5)
    at div
    at eval (webpack-internal:///../../node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at LoadingDots (webpack-internal:///../../node_modules/@keystone-ui/loading/dist/keystone-ui-loading.esm.js:21:7)
    at p
    at eval (webpack-internal:///../../node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at ResultsSummaryContainer (webpack-internal:///../../node_modules/@keystone-6/core/___internal-do-not-use-will-break-in-patch/admin-ui/pages/ListPage/dist/keystone-6-core-___internal-do-not-use-will-break-in-patch-admin-ui-pages-ListPage.esm.js:1250:5)
    at main
    at eval (webpack-internal:///../../node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Content (webpack-internal:///../../node_modules/@keystone-6/core/dist/PageContainer-60ad26d2.esm.js:347:66)
    at div
    at eval (webpack-internal:///../../node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at PageWrapper
    at PageContainer (webpack-internal:///../../node_modules/@keystone-6/core/dist/PageContainer-60ad26d2.esm.js:364:5)
    at ListPage (webpack-internal:///../../node_modules/@keystone-6/core/___internal-do-not-use-will-break-in-patch/admin-ui/pages/ListPage/dist/keystone-6-core-___internal-do-not-use-will-break-in-patch-admin-ui-pages-ListPage.esm.js:994:5)
    at ErrorBoundary (webpack-internal:///../../node_modules/@keystone-6/core/dist/Errors-f59723d8.esm.js:20:5)
    at DrawerProvider (webpack-internal:///../../node_modules/@keystone-ui/modals/dist/keystone-ui-modals.esm.js:54:5)
    at ToastProvider (webpack-internal:///../../node_modules/@keystone-ui/toast/dist/keystone-ui-toast.esm.js:41:5)
    at InternalKeystoneProvider (webpack-internal:///../../node_modules/@keystone-6/core/admin-ui/context/dist/keystone-6-core-admin-ui-context.esm.js:310:5)
    at ApolloProvider (webpack-internal:///../../node_modules/@apollo/client/react/context/ApolloProvider.js:12:21)
    at KeystoneProvider (webpack-internal:///../../node_modules/@keystone-6/core/admin-ui/context/dist/keystone-6-core-admin-ui-context.esm.js:356:14)
    at Core (webpack-internal:///../../node_modules/@keystone-ui/core/dist/keystone-ui-core.esm.js:1304:5)
    at eval (webpack-internal:///../../node_modules/@keystone-6/core/___internal-do-not-use-will-break-in-patch/admin-ui/pages/App/dist/keystone-6-core-___internal-do-not-use-will-break-in-patch-admin-ui-pages-App.esm.js:84:5)
    at PathnameContextProviderAdapter (webpack-internal:///../../node_modules/next/dist/shared/lib/router/adapters.js:62:11)
    at ErrorBoundary (webpack-internal:///../../node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:301:63)
    at ReactDevOverlay (webpack-internal:///../../node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:850:919)
    at Container (webpack-internal:///../../node_modules/next/dist/client/index.js:61:1)
    at AppContainer (webpack-internal:///../../node_modules/next/dist/client/index.js:171:11)
    at Root (webpack-internal:///../../node_modules/next/dist/client/index.js:346:11)
```

**Comment by borisno2** [comment]
Hi @devmor-j thanks for logging this issue, this will be fixed in our next release.
Thanks,
