### ISSUE TITLE
Upgrade react-apollo

### ISSUE THREAD

**Issue by timleslie** [keystonejs/keystone#839]
# Bug report

## Describe the bug

We want to upgrade `react-apollo`. There are a number of packages that need updating (mainly demos). It would be best to do this in multiple PRs:
1. `demo-projects/blog`
1. `demo-projects/meetup` - This one is done here: https://github.com/Thinkmill/meetup-alternative (can probably just be copied over to the mono-repo folder)
1. `packages/apollo-helpers`
1. `packages/app-admin-ui`
1. `packages/fields`

## Additional context

Attempt to upgrade react-apollo 2.5.x caused cypress tests to fail:

```
 Running: user-filter_spec.js...                                                        (13 of 14) 

․․!

  2 passing (11s)
  1 failing

  1) Filter by company
       Should filter by company:
     CypressError: Timed out retrying: expected '<main>' to contain 'thinkmill'
      at Object.cypressErr (http://localhost:3000/__cypress/runner/cypress_runner.js:65283:11)
      at Object.throwErr (http://localhost:3000/__cypress/runner/cypress_runner.js:65248:18)
      at Object.throwErrByPath (http://localhost:3000/__cypress/runner/cypress_runner.js:65275:17)
      at retry (http://localhost:3000/__cypress/runner/cypress_runner.js:58816:16)
      at http://localhost:3000/__cypress/runner/cypress_runner.js:50924:18
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:127195:23)
      at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:125213:31)
      at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:125270:18)
      at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:125315:10)
      at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:125390:18)
      at Async._drainQueue (http://localhost:3000/__cypress/runner/cypress_runner.js:122119:16)
      at Async._drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:122129:10)
      at Async.drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:122003:14)
      at <anonymous>```

**Comment by timleslie** [comment]
We're now at `3.1.3` 👍
