### ISSUE TITLE
Problem launching new Keystone project due to issue with Next.js version

### ISSUE THREAD

**Issue by unbywyd** [keystonejs/keystone#8553]
**New installation is not working**, there is a problem with Next.js. It is necessary to manually downgrade to version 13.3.4, as the default installation installs the latest version ^13.4 which does not work

1. new installation with npm / npx
2. cd app and npm run dev
3. everything is fine until you try to open a running project in the browser:
<img width="863" alt="image" src="https://user-images.githubusercontent.com/24291513/236559408-26bebfbe-166f-40b4-adb0-3cac35dce45c.png">
<img width="513" alt="image" src="https://user-images.githubusercontent.com/24291513/236559466-7114791f-4952-43e9-afc6-00b0f609f42b.png">

By the way, I've noticed that if you install a version of Next.js lower than 13.3.4, the build process gets stuck, which can cause issues. To fix this, you can try changing the package dependency to a specific version of Next.js, such as "next:": "13.3.4", instead of using the default "^13.3.0". This should help mitigate the problem and allow the build process to complete successfully.

**Comment by molotow11** [comment]
I have the same issue with latest version, checked with default project setup from examples

**Comment by gautamsi** [comment]
use resolution to pin nextjs version to `13.3.4`

**Comment by molotow11** [comment]
@gautamsi 
Thanks, works with resolutions (need to be in top level package.json if monorepo).
```
  "resolutions": {
    "next": "13.3.4"
  }
```

**Comment by mmachatschek** [comment]
I've also bumped into this issue. Pinning to 13.3.4 works for me too

**Comment by MohammadKurjieh** [comment]
Pinning to version 13.3.4 works. @gautamsi Any idea what might have caused this issue?

**Comment by Thinkscape** [comment]
👍 would love to start using 13.4

**Comment by MohammadKurjieh** [comment]
I was able to resolve the issue, it was caused by the appDir being set to true in next v13.4 and above.
Reference on Nextjs: https://github.com/vercel/next.js/issues/49261 and https://github.com/vercel/next.js/discussions/49251

Check the following pull request for more details: #8568

**Comment by beerdedfellow** [comment]
Hello, this fix is not working for me:


```
rhutchison@Ryans-M2M.local:/Users/rhutchison $ mkdir keystone_test
rhutchison@Ryans-M2M.local:/Users/rhutchison $ cd keystone_test 
rhutchison@Ryans-M2M.local:/Users/rhutchison/keystone_test $ npm init keystone-app@latest

✨ You're about to generate a project using Keystone 6 packages.

✔ What directory should create-keystone-app generate your app into? · test

⠋ Installing dependencies with yarn. This may take a few minutes.
⚠ Failed to install with yarn.
✔ Installed dependencies with npm.


🎉  Keystone created a starter project in: test

  To launch your app, run:

  - cd test
  - npm run dev

  Next steps:

  - Read test/README.md for additional getting started details.
  - Edit test/keystone.ts to customize your app.
  - Open the Admin UI
  - Open the Graphql API
  - Read the docs
  - Star Keystone on GitHub

rhutchison@Ryans-M2M.local:/Users/rhutchison/keystone_test $ cd test
rhutchison@Ryans-M2M.local:/Users/rhutchison/keystone_test/test $ cat package.json 
{
  "name": "keystone-app",
  "version": "1.0.2",
  "private": true,
  "scripts": {
    "dev": "keystone dev",
    "start": "keystone start",
    "build": "keystone build",
    "postinstall": "keystone build --no-ui --frozen"
  },
  "dependencies": {
    "@keystone-6/auth": "^7.0.0",
    "@keystone-6/core": "^5.0.0",
    "@keystone-6/fields-document": "^7.0.0",
    "typescript": "^4.9.5"
  }
}
rhutchison@Ryans-M2M.local:/Users/rhutchison/keystone_test/test $ vim package.json 
rhutchison@Ryans-M2M.local:/Users/rhutchison/keystone_test/test $ cat package.json
{
  "name": "keystone-app",
  "version": "1.0.2",
  "private": true,
  "scripts": {
    "dev": "keystone dev",
    "start": "keystone start",
    "build": "keystone build",
    "postinstall": "keystone build --no-ui --frozen"
  },
  "dependencies": {
    "@keystone-6/auth": "^7.0.0",
    "@keystone-6/core": "^5.0.0",
    "@keystone-6/fields-document": "^7.0.0",
    "typescript": "^4.9.5"
  },
  "resolutions": {
      "next": "13.3.4"
  }
}
rhutchison@Ryans-M2M.local:/Users/rhutchison/keystone_test/test $ rm -rf node_modules 
rhutchison@Ryans-M2M.local:/Users/rhutchison/keystone_test/test $ rm package-lock.json 
rm: remove regular file 'package-lock.json'? y
rhutchison@Ryans-M2M.local:/Users/rhutchison/keystone_test/test $ npm i
npm WARN deprecated cuid@2.1.8: Cuid and other k-sortable and non-cryptographic ids (Ulid, ObjectId, KSUID, all UUIDs) are all insecure. Use @paralleldrive/cuid2 instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

> keystone-app@1.0.2 postinstall
> keystone build --no-ui --frozen

✨ GraphQL and Prisma schemas are up to date

added 920 packages, and audited 921 packages in 11s

156 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
rhutchison@Ryans-M2M.local:/Users/rhutchison/keystone_test/test $ npm run dev

> keystone-app@1.0.2 dev
> keystone dev

✨ Starting Keystone
⭐️ Server listening on :3000 (http://localhost:3000/)
⭐️ GraphQL API available at /api/graphql
✨ Generating GraphQL and Prisma schemas
✨ sqlite database "keystone.db" created at file:./keystone.db
✨ Your database is now in sync with your schema. Done in 200ms
✨ Connecting to the database
✨ Creating server
✅ GraphQL API ready
✨ Generating Admin UI code
✨ Preparing Admin UI app
- event compiled client and server successfully in 2.2s (1706 modules)
- wait compiling...
✅ Admin UI ready
- event compiled client and server successfully in 214 ms (1706 modules)
- wait compiling /_error (client and server)...
- event compiled client and server successfully in 140 ms (1707 modules)
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
TypeError: Cannot read properties of null (reading 'useContext')
    at Object.useContext (/Users/rhutchison/keystone_test/test/node_modules/react/cjs/react.development.js:1618:21)
    at useTheme (/Users/rhutchison/keystone_test/test/node_modules/@keystone-ui/core/dist/keystone-ui-core.cjs.dev.js:839:13)
    at BaseCSS (/Users/rhutchison/keystone_test/test/node_modules/@keystone-ui/core/dist/keystone-ui-core.cjs.dev.js:1286:7)
    at renderWithHooks (/Users/rhutchison/keystone_test/test/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8674:16)
```

**Comment by rpmcoding** [comment]
@dcousens could this fix be updated in the yarn create keystone-app package?  Currently I still can't install keystone.

**Comment by dcousens** [comment]
@rpmcoding could you try out our newest `rc` snapshot? https://www.npmjs.com/package/@keystone-6/core?activeTab=versions
If that resolves your problem, we should have that officially released on Monday.

**Comment by Durwinner** [comment]
Keystone requires a higher version of Next.js, specifically version 13.3 or above. If you encounter an error, please make sure to use at least this version. To fix the issue, you can add the following code to your package.json file:
```
"resolutions": {
  "next": "~13.3.0"
}
```
By adding this code, you're specifying a resolution to use Next.js version 13.3.0 or a compatible version. This can help resolve the problem you're facing. Make sure to save the package.json file after making this change.
