### ISSUE TITLE
Failed to load next.config.js, Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './___internal-do-not-use-will-break-in-patch/admin-ui/next-config' is not defined by "exports"

### ISSUE THREAD

**Issue by tommyboylab** [keystonejs/keystone#8639]
- Instantiate a new project
- Upgrade the dependencies
- Add custom admin pages
- Run yarn dev
- View error

- I expect to be able to run the server. I have not created this next.config.js file that this error is being thrown by and when removing it it is auto generated on next `yarn dev` by the server.
 
~~Seems to be coming from an upgrade of the `@keystone-6/fields-document` package~~ Issue is present after upgrading core

```
error Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
[0] Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './___internal-do-not-use-will-break-in-patch/admin-ui/next-config' is not defined by "exports" in /Users/keystone/node_modules/@keystone-6/core/package.json
[0]     at new NodeError (node:internal/errors:400:5)
[0]     at exportsNotFound (node:internal/modules/esm/resolve:361:10)
[0]     at packageExportsResolve (node:internal/modules/esm/resolve:697:9)
[0]     at resolveExports (node:internal/modules/cjs/loader:538:36)
[0]     at Module._findPath (node:internal/modules/cjs/loader:607:31)
[0]     at Module._resolveFilename (node:internal/modules/cjs/loader:1025:27)
[0]     at /Users/keystone/node_modules/next/dist/server/require-hook.js:189:36
[0]     at Module._load (node:internal/modules/cjs/loader:885:27)
[0]     at Module.require (node:internal/modules/cjs/loader:1105:19)
[0]     at require (node:internal/modules/cjs/helpers:103:18) {
[0]   code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
[0] }
```

Node version: 18.13.0

**Comment by tommyboylab** [comment]
Needed to place this within my keystone.ts in order for the page to render correctly. Hopefully this can help someone else struggling with it.

`	ui: {
		basePath: '/admin',
	},
`

**Comment by Francoois** [comment]
@tommyboylab I've got nearly the same (few differences in stacktrace).
```
- error Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './___internal-do-not-use-will-break-in-patch/admin-ui/next-config' is not defined by "exports" in /Users/keystone/monorepo/ksapp/node_modules/@keystone-6/core/package.json
    at new NodeError (node:internal/errors:387:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:464:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:748:3)
    at resolveExports (node:internal/modules/cjs/loader:493:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:533:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:942:27)
    at /Users/francoislouis/lm/repo/lamachinerie.org/apps/cms/node_modules/@keystone-6/core/node_modules/next/dist/server/require-hook.js:189:36
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
``` 
But setting basePath didn't work out.
What helped you realise it was this setting in your case ?

**Comment by Francoois** [comment]
Turned out my issue was caused by keystone-nextjs-auth package
