### ISSUE TITLE
TypeError: /node_modules/keystone/templates/mixins/rows.jade:5

### ISSUE THREAD

**Issue by lab101** [keystonejs/keystone#877]
Hey

Thx for this amazing CMS. 
It's perfect for the project I'm working on!

Today we ran into a strange error.
It happend only once.
I didn't produce the error myself so I don't know what exactly caused it but it seems the user tried to delete a model of the type "Tag" which produced the below error in the row.jade mixin.

OS: Linux Ubuntu
node --version
v0.10.25
keystone   "version": "0.2.33",

Any idea?

        TypeError: /var/www/momucms-prod/node_modules/keystone/templates/mixins/rows.jade:5
            3| mixin row(list, colums, item)
            4|   tr(id=item.id)
          > 5|     if !list.get('nodelete') && item.id !== user.id
            6|       td.control: a(href='/keystone/' + list.path + '?delete=' + item.id + csrf_query).control-delete
            7|     else if !list.get('nodelete')
            8|       td.control

        Cannot read property 'id' of undefined
          at Object.jade_mixins.row (<anonymous>:292:47)
          at eval (<anonymous>:392:19)
          at eval (<anonymous>:394:22)
          at res (/var/www/momucms-prod/node_modules/keystone/node_modules/jade/lib/jade.js:180:38)
          at Object.exports.render (/var/www/momucms-prod/node_modules/keystone/node_modules/jade/lib/jade.js:305:10)
          at Object.exports.renderFile (/var/www/momucms-prod/node_modules/keystone/node_modules/jade/lib/jade.js:341:18)
          at Promise.<anonymous> (/var/www/momucms-prod/node_modules/keystone/routes/api/list.js:254:17)
          at Promise.<anonymous> (/var/www/momucms-prod/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
          at Promise.EventEmitter.emit (events.js:95:17)
          at Promise.emit (/var/www/momucms-prod/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
          at Promise.fulfill (/var/www/momucms-prod/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
          at Promise.resolve (/var/www/momucms-prod/node_modules/keystone/node_modules/mongoose/lib/promise.js:114:23)
          at Promise.<anonymous> (/var/www/momucms-prod/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
          at Promise.EventEmitter.emit (events.js:95:17)
          at Promise.emit (/var/www/momucms-prod/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
          at Promise.fulfill (/var/www/momucms-prod/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
          at /var/www/momucms-prod/node_modules/keystone/node_modules/mongoose/lib/query.js:1052:26
          at model.Document.init (/var/www/momucms-prod/node_modules/keystone/node_modules/mongoose/lib/document.js:250:11)
          at completeMany (/var/www/momucms-prod/node_modules/keystone/node_modules/mongoose/lib/query.js:1050:12)
          at Object.cb (/var/www/momucms-prod/node_modules/keystone/node_modules/mongoose/lib/query.js:1016:11)
          at Object._onImmediate (/var/www/momucms-prod/node_modules/keystone/node_modules/mongoose/node_modules/mquery/lib/utils.js:137:16)
          at processImmediate [as _immediateCallback] (timers.js:330:15)

**Comment by creynders** [comment]
Please update your keystone version, this _should_ be fixed, see #716

**Comment by lab101** [comment]
aha indeed sorry for the duplicated issue

**Comment by JedWatson** [comment]
> Thx for this amazing CMS. 
> It's perfect for the project I'm working on!

It's a pleasure @lab101, glad to hear it :smile:
