### ISSUE TITLE
Production build failing with "unexpected call to getAdminMetaInRelationshipField" error

### ISSUE THREAD

**Issue by ttbarnes** [keystonejs/keystone#8791]
When running `keystone build` via npm scripts, I get the following error:

```shell
Error: unexpected call to getAdminMetaInRelationshipField
    at Object.getAdminMetaForRelationshipField (/Users/tony/project-x/src/api/node_modules/@keystone-6/core/dist/create-admin-meta-5d6c7c4d.cjs.prod.js:152:11)
    at Object.getAdminMeta (/Users/tony/project-x/src/api/node_modules/@keystone-6/core/fields/dist/keystone-6-core-fields.cjs.prod.js:2882:45)
    at Object.createAdminMeta (/Users/tony/project-x/src/api/node_modules/@keystone-6/core/dist/create-admin-meta-d9f6d1a4.cjs.dev.js:141:245)
    at Object.createSystem (/Users/tony/project-x/src/api/node_modules/@keystone-6/core/dist/createSystem-6881942b.cjs.dev.js:2182:37)
    at build (/Users/tony/project-x/src/api/node_modules/@keystone-6/core/scripts/cli/dist/keystone-6-core-scripts-cli.cjs.dev.js:519:20)
```

It also happens when adding the "no ui" flag: `keystone build --no-ui`

**keystone.ts**:

```js
export default withAuth(
  config({
    db: {
      provider: 'mysql',
      url: DB_URL,
    },
    lists,
    session,
  })
);
```

`lists` and `session` are not doing anything out of the ordinary and are following [the examples](https://github.com/keystonejs/keystone/tree/main/examples).

I expect the build to be successful - it has been for quite some time, but it seems that some recent changes (in my codebase) are causing this error. It looks like keystone is failing with some `currentAdminMeta` logic in `create-admin-meta.ts` and not surfacing some more contextual information.

Should it be trying to create admin related things even with `--no-ui`?

I appreciate this is more than likely something in my codebase. Struggling to find what the cause could be. I've removed or simplified a lot of the setup to try and get the build working, but keep getting this error.

How or why would this be happening please?

- Node version `v19.4.0`. Also tried previous versions e.g `v18.16.0`.

**Comment by ttbarnes** [comment]
For anyone who comes across this - for now, setting the NODE_ENV in npm scripts works as per [this comment](https://github.com/keystonejs/keystone/issues/8774#issuecomment-1689154397).

```js
"build": "NODE_ENV=production keystone build"
```

Having it set in a .env file doesn't work and causes the above error RE `getAdminMetaInRelationshipField`.

**Comment by aditya162002** [comment]
can i try to solve it?

**Comment by jmchor** [comment]
Is anybody still working on this, since the issue seems to persist?

**Comment by dcousens** [comment]
@jmchor can you reproduce this issue reliably?

**Comment by jmchor** [comment]
I had several builds fail because I wasn't aware of this - so far, it will reliably run into the error of `getAdminMetaInRelationshipField`when the .env variable NODE_ENV is set to production
