### ISSUE TITLE
Unable to use Content Blocks in Keystone 6.

### ISSUE THREAD

**Issue by vishwa795** [keystonejs/keystone#9077]
Use the keystone boilerplate repository. In the post schema, add a component block exactly as mentioned in the [docs](https://keystonejs.com/docs/guides/document-fields#component-blocks). 

Application should run fine.

<img width="903" alt="Screenshot 2024-03-31 at 12 18 15 AM" src="https://github.com/keystonejs/keystone/assets/54198625/e5cb997e-7dc9-4a63-ac66-d829fa0e0fbf">
<img width="552" alt="Screenshot 2024-03-31 at 12 19 18 AM" src="https://github.com/keystonejs/keystone/assets/54198625/b2294e8a-6bac-411e-8f0e-65b83f2da54f">

```
✨ Starting Keystone
(node:21488) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/declarations/src/component-blocks' is not defined by "exports" in /Users/vishwa/Desktop/work/synapse/node_modules/@keystone-6/fields-document/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:416:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:669:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at /Users/vishwa/Desktop/work/synapse/node_modules/next/dist/server/require-hook.js:54:36
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at Module.mod.require (/Users/vishwa/Desktop/work/synapse/node_modules/next/dist/server/require-hook.js:64:28) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
error Command failed with exit code 1.
```

node version: 17.0.0
Latest keystone version

**Comment by borisno2** [comment]
Hi @vishwa795,
The error suggests you are trying to import something from `@keystone-6/fields-document/dist/declarations/src/component-blocks` but that is not defined in the exports of the package, what are you importing from that location?

**Comment by vishwa795** [comment]
Ah, my bad the import was hapenning from wrong location.

I guess vscode automatically imported from the wrong location.
However, Im getting a diferrent error now.
![image](https://github.com/keystonejs/keystone/assets/54198625/0fcffb7b-edfc-4329-93e6-aec77d5947ff)

This is how i'm using the component blocks ^^

Getting the following error:

```
Module not found: Can't resolve '/Users/vishwa/Desktop/work/curio/apps/component-blocks.tsx'
   8 | import * as view5 from "@keystone-6/core/fields/types/timestamp/views";
   9 | import * as view6 from "@keystone-6/fields-document/views";
> 10 | import * as view7 from "/Users/vishwa/Desktop/work/curio/apps/component-blocks.tsx";
  11 | 
  12 | var adminConfig = {};
  13 | 
```

**Comment by borisno2** [comment]
Your `views: path.resolve("../component-blocks.tsx")` on line 32 is being converted to `/Users/vishwa/Desktop/work/curio/apps/component-blocks.tsx` which can't be found, so your path of `../component-blocks.tsx` is not correct.
