### ISSUE TITLE
Prisma AggregateError when running keystone prisma migrate dev, keystone build, etc.

### ISSUE THREAD

**Issue by yorkeJohn** [keystonejs/keystone#9146]
The following error occurs when running `keystone build` (in the postinstall):
```
> npm install

> cms@1.0.3 postinstall
> keystone build --no-ui --frozen

(node:18708) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)        
✨ GraphQL and Prisma schemas are up to date
AggregateError: 
    GeneratorError: Generator "C://Users//yorke//Documents//Larix//metro-thrift-bus//cms//node_modules//@prisma//client//generator-build//index.js" failed:
    Assertion failed: process_title, file c:/ws/deps/uv/src/win/util.c, line 418  
        at ChildProcess.<anonymous> (C:/Users/yorke/Documents/Larix/metro-thrift-bus/cms/node_modules/@prisma/generator-helper/dist/chunk-XP4JGOVU.js:620:25)       
        at ChildProcess.emit (node:events:520:28)
        at ChildProcess.emit (node:domain:488:12)
        at ChildProcess._handle.onexit (node:internal/child_process:294:12)       
    at next (C:\Users\yorke\Documents\Larix\metro-thrift-bus\cms\node_modules\@prisma\internals\dist\chunk-WTCY7DFZ.js:3159:24)
    at C:\Users\yorke\Documents\Larix\metro-thrift-bus\cms\node_modules\@prisma\internals\dist\chunk-WTCY7DFZ.js:3180:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
```

And the following when running prisma commands such as `keystone prisma migrate dev` and `keystone prisma generate`
```
> npm run migrate-dev                                                                                                                                                                   

> cms@1.0.3 migrate-dev
> keystone prisma migrate dev

(node:8912) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
✨ GraphQL and Prisma schemas are up to date
Assertion failed: process_title, file c:\ws\deps\uv\src\win\util.c, line 418
```

This may be related to node version, as I have recently updated to Node `v22.1.0`
```
> node -v                                                                                                                                                                               
v22.1.0
```

Any help is appreciated.

**Comment by dcousens** [comment]
@yorkeJohn can you provide any additional details about your environment?

**Comment by yorkeJohn** [comment]
Windows 11, NPM 10.7.0

**Comment by mandymozart** [comment]
also running all keystone related stuff on 18.19.1 actually.

**Comment by Villva-vinoth** [comment]
Having the same while installing keystone do 
npm build 
the issuse solve temporarily 
keystone build --no-ui --frozen is not working

**Comment by krzysztof-fijolek** [comment]
I am also facing the same issue. Any update on this?

**Comment by TheRealFlyingCoder** [comment]
Just dropping in and confirming I also had issues when I didn't realise I'd left my Node up at V22.13.1 from another project :)

When trying to run `migrate dev` I got:

`Assertion failed: process_title, file c:\ws\deps\uv\src\win\util.c, line 412`

Quick switch back to 20.14.0 and it worked a charm

**Comment by dcousens** [comment]
I'm seeing a trend of Windows paths in the reports 👀

**Comment by TheRealFlyingCoder** [comment]
>I'm seeing a trend of Windows paths in the reports 👀

Any thoughts on why it might be failing for windows @dcousens?

**Comment by azhaziqgoh** [comment]
We can see this with node v24 in windows.

It happen when I try to run **keystone prisma generate** / **keystone prisma migrate dev**

**keystone dev** seems ok

<img width="668" height="88" alt="Image" src="https://github.com/user-attachments/assets/daf12b69-bc08-4352-a025-9e66af997540" />

**Comment by dcousens** [comment]
This probably needs to be reported to Prisma, what happens if you use `prisma` directly?

**Comment by azhaziqgoh** [comment]
Direct prisma seems don't have the issue. Potentially might be related with this https://github.com/libuv/libuv/pull/4807

**Comment by askoufis** [comment]
There's likely nothing that can be done for now (other than downgrading) given https://github.com/libuv/libuv/pull/4807 hasn't been released yet, meaning Node.js can't update to a version of libuv that fixes the issue. Also https://github.com/nodejs/TSC/issues/1657#issuecomment-3098035831.

**Comment by dcousens** [comment]
This is particularly annoying, but unfortunately out of our control.

Hopefully you can use the [WSL](https://learn.microsoft.com/en-us/windows/wsl/install) to resolve the issue?

**Comment by sfodor** [comment]
If direct prisma don't have this issue, then what is causing this in the Keystone Prisma CLI commands?
Are there any workarounds beside WSL or Node 20?

**Comment by dcousens** [comment]
> If direct prisma don't have this issue, then what is causing this in the Keystone Prisma CLI commands?

Maybe the nature of `node:child_process`'s `spawn` results in this issue? We could try something else? I don't have a readily available environment to test this, but, maybe someone else could play with different options here? 

https://github.com/keystonejs/keystone/blob/16b2b4765a98e5060eec6ebf622546b35ee28eec/packages/core/src/scripts/prisma.ts#L21-L33

**Comment by sfodor** [comment]
Thanks.

It seems adding a `'--title=prisma'` argument solves the problem on my Windows computer with node v22.18.0, e.g.:

 `const p = spawn('node', ['--title=prisma', require.resolve('prisma/build/index.js'), ...commands], { `

Although I'm not sure this is the best approach.


Note that the [packages/core/src/scripts/migrate.ts](https://github.com/keystonejs/keystone/blob/6708cb5293e018ef6b62ee721dd6cff7862b4a06/packages/core/src/scripts/migrate.ts#L40) can have this problem as well.

**Comment by dcousens** [comment]
@sfodor nice!
>   --title=...                                    the process title to use on startup

that's pretty harmless, if it resolves the issue, please, pull request accepted!
