### ISSUE TITLE
Vhost package integration show the following error 

### ISSUE THREAD

**Issue by Niazakhan** [keystonejs/keystone#9214]
Error: vhost package initialization failed due to KeystoneJS incompatibility.

Error Details:
- Module: vhost
- Version: 2.0.1
- Incompatible Module: KeystoneJS
- KeystoneJS Version: 6.1.0
- File: /usr/local/lib/node_modules/vhost/lib/core.js
- Line: 98
- Function: loadConfiguration

Exception Trace:
Error: DependencyConflictError: vhost 2.0.1 is incompatible with KeystoneJS 6.1.0
    at loadConfiguration (/usr/local/lib/node_modules/vhost/lib/core.js:98:15)
    at initialize (/usr/local/lib/node_modules/vhost/lib/core.js:45:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/vhost/index.js:12:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)

Resolution Steps:
1. Verify the compatibility between vhost and KeystoneJS versions.
2. Consider upgrading or downgrading the vhost or KeystoneJS package to a compatible version.
3. Check the vhost and KeystoneJS documentation for compatibility notes and recommended versions.
4. If using a custom configuration, ensure it adheres to the guidelines provided by both vhost and KeystoneJS.
5. Contact support or refer to the community forums for further assistance.

For additional information, please refer to the log files or visit the official documentation of vhost and KeystoneJS.

**Comment by emmatown** [comment]
This appears to be AI slop, `vhost` doesn't even have a `2.0.1` version on npm and it's unclear how this is at all related to Keystone.
