### ISSUE TITLE
Running eslint fails with Could not find "member-delimiter-style"

### ISSUE THREAD

**Issue by iamandrewluca** [keystonejs/keystone#9316]
```
npx eslint .
```

> [!CAUTION]
> This rule has been moved to the [ESLint stylistic plugin](https://eslint.style/). See [#8072](https://github.com/typescript-eslint/typescript-eslint/issues/8072) and [#8074](https://github.com/typescript-eslint/typescript-eslint/issues/8074) for more information.
> – https://typescript-eslint.io/rules/member-delimiter-style/

```
Oops! Something went wrong! :(

ESLint: 9.9.1

TypeError: Key "rules": Key "@typescript-eslint/member-delimiter-style": Could not find "member-delimiter-style" in plugin "@typescript-eslint".
    at throwRuleNotFoundError (/Users/iamandrewluca/Projects/github/fork-keystone/node_modules/.pnpm/eslint@9.9.1/node_modules/eslint/lib/config/rule-validator.js:66:11)
    at RuleValidator.validate (/Users/iamandrewluca/Projects/github/fork-keystone/node_modules/.pnpm/eslint@9.9.1/node_modules/eslint/lib/config/rule-validator.js:147:17)
    at [finalizeConfig] (/Users/iamandrewluca/Projects/github/fork-keystone/node_modules/.pnpm/eslint@9.9.1/node_modules/eslint/lib/config/flat-config-array.js:378:23)
    at FlatConfigArray.getConfigWithStatus (/Users/iamandrewluca/Projects/github/fork-keystone/node_modules/.pnpm/@eslint+config-array@0.18.0/node_modules/@eslint/config-array/dist/cjs/index.cjs:1102:55)
    at FlatConfigArray.getConfig (/Users/iamandrewluca/Projects/github/fork-keystone/node_modules/.pnpm/@eslint+config-array@0.18.0/node_modules/@eslint/config-array/dist/cjs/index.cjs:1120:15)
    at /Users/iamandrewluca/Projects/github/fork-keystone/node_modules/.pnpm/eslint@9.9.1/node_modules/eslint/lib/eslint/eslint-helpers.js:346:56
    at Array.reduce (<anonymous>)
    at /Users/iamandrewluca/Projects/github/fork-keystone/node_modules/.pnpm/eslint@9.9.1/node_modules/eslint/lib/eslint/eslint-helpers.js:333:36
    at /Users/iamandrewluca/Projects/github/fork-keystone/node_modules/.pnpm/eslint@9.9.1/node_modules/eslint/lib/eslint/eslint-helpers.js:296:32
    at Object.isAppliedFilter (/Users/iamandrewluca/Projects/github/fork-keystone/node_modules/.pnpm/@nodelib+fs.walk@1.2.8/node_modules/@nodelib/fs.walk/out/readers/common.js:12:31)
```

**Comment by Deepak-png981** [comment]
@iamandrewluca  what are the steps involved to replicate this Bug?

**Comment by iamandrewluca** [comment]
Oh, forgot to write that. Is by running the ESLint check

```
npx eslint .
```
