### ISSUE TITLE
Relationship Field throws Error if _id has a Non-ObjectID value

### ISSUE THREAD

**Issue by Johnster03** [keystonejs/keystone#932]
CastError: Cast to ObjectId failed for value "horror" at path "genres"
  at ObjectId.cast (/home/mine/Projects/yttw/node_modules/keystone/node_modules/mongoose/lib/schema/objectid.js:116:13)

The thing that I am trying to do is to add multiple genres to a game. Those are the Genre and Games models:

Genre.js - Model:

    var keystone = require('keystone'),
            Types = keystone.Field.Types;
     
    var Genre = new keystone.List('Genre', {
            autokey: { from: 'name', path: '_id', unique: true }
    });
     
    Genre.add({
            name_de: { type: String, required: true, initial: true  },
            name: { type: String, required: true, initial: true  }
    });
     
    Genre.relationship({ ref: 'Game', path: 'genres' });
     
    Genre.defaultColumns = 'name_de, name';
     
    Genre.register();

Game.js - Model

    var keystone = require('keystone'),
            Types = keystone.Field.Types;
     
    var Game= new keystone.List('Game', {
            autokey: { from: 'name', path: '_id', unique: true }
    });
     
    Game.add({
            name_de: { type: String, required: true, initial: true, unique: true },
            name: { type: String, required: true, initial: true, unique: true  },
            intro_de: { type: String, required: true, initial: true  },
            intro_en: { type: String, required: true, initial: true  },
            thumb_sm: { type: Types.Url },
            thumb_lg: { type: Types.Url },
            banner: { type: Types.Url },
            genres: { type: Types.Relationship, ref: 'Genre', many: true }
    });
     
    Game.defaultColumns = 'name_de, name, genres';
    Game.register();

The special thing about those models is that the "_id" value is created by using autokey from the name field, which causes the _id field to be a String and not an ObjectId. Inserting documents via the keystone backend works like a charm and it also creates the "_id" field as intended:

>db.genres.find()
{ "_id" : "survival", "name" : "Survival", "name_de" : "Survival", "__v" : 0 }
{ "_id" : "horror", "name" : "Horror", "name_de" : "Horror", "__v" : 0 }
>db.games.find()
{ "_id" : "the-forest", "intro_en" : "asdfjd;ksf", "intro_de" : "asdjaskd", "name" : "The Forest", "name_de" : "The Forest", "genres" : [ ], "__v" : 0 }

However, once I try to add the genres to the game via the keystone backend, it throws the following error:

CastError: Cast to ObjectId failed for value "horror" at path "genres"
  at ObjectId.cast (/home/mine/Projects/yttw/node_modules/keystone/node_modules/mongoose/lib/schema/objectid.js:116:13)

Full error here: http://pastebin.com/JPsDAc4H

The problem seems to be that Keystone/Mongoose expects an ObjectId field and does not accept non-ObjectId values for the Relationship/_id field.

The interesting thing is that the autocomplete in the keystone backend for the "genres" field in the Games model correctly finds the genres from the Genre collection, however they cannot be added as it results in the error above.

The reason why I want to do have strings as _ids is because of the already unique value of the name field. I also want to create in a later step to allow the game model to have multiple children of its own model as documented here:

http://docs.mongodb.org/manual/tutorial/model-tree-structures-with-child-references/

**Comment by Johnster03** [comment]
I found the cause of the problem.

In the /node_modules/keystone/lib/fieldTypes/relationship.js file, the nativeType (schema type) is defined as ObjectId. Here is the function (from line 17 in the file):

	function relationship(list, path, options) {
	
		this.many = (options.many) ? true : false;
		this.filters = options.filters;
		**this._nativeType = keystone.mongoose.Schema.Types.ObjectId;**
		this._underscoreMethods = ['format'];
	
		relationship.super_.call(this, list, path, options);
	
	}

I changed the nativeType to mixed, which solved the CastError problem described earlier as it now allows any _id field be any type and not only ObjectIds. This is the new function with the mixed schema type:

	function relationship(list, path, options) {
	
		this.many = (options.many) ? true : false;
		this.filters = options.filters;
		this._nativeType = keystone.mongoose.Schema.Types.Mixed;
		this._underscoreMethods = ['format'];
	
		relationship.super_.call(this, list, path, options);
	
	}

I tested CRUD ops and population which all seem to work. However, as the mixed schema type allows basically all kinds of input, this should be further tested whether this is an acceptable solution or whether it may cause any potential issues within keystone or other concerns. 

Maybe a keystone developer can look into this. :)

**Comment by morenoh149** [comment]
Two sides I see to this:
1) Is using the autokey feature (using a unique string as the object identifier) providing a *substantial* improvement in performance? If not I'd keep a redundant column and use the mongo generated `_id` field.
2) If being able to do these mongo data-modeling tweaks is important we may have to use `Mixed` type in relationships because they are the most *open*. Though I'm hesitant because you lose a lot of automatic features such as validation.

See http://mongoosejs.com/docs/schematypes.html#mixed

**Comment by mxstbr** [comment]
Closing due to inactivity, feel free to comment again if this issue persists!
