### ISSUE TITLE
Empty SQLite database when using a custom location 

### ISSUE THREAD

**Issue by cbroome** [keystonejs/keystone#9376]
I'm trying to build a template to reliably create a new Keystone JS instance and setting a custom location database location to more easily store it in a Docker volume.

i.e. in the `keystone.ts` file:

```
    db: {
      provider: 'sqlite',
      url: 'file:./db/keystone.db',
    },
```

A sqlite file will be created at this location but it will be empty. 

The empty database causes errors starting the application: 

```
The table `main.User` does not exist in the current database.
    at Ln.handleRequestError (/Users/cbroome/Workspace/docker-scratchpad/apps/keystone/node_modules/@prisma/client/runtime/library.js:121:7753)
    at Ln.handleAndLogRequestError (/Users/cbroome/Workspace/docker-scratchpad/apps/keystone/node_modules/@prisma/client/runtime/library.js:121:7061)
    at Ln.request (/Users/cbroome/Workspace/docker-scratchpad/apps/keystone/node_modules/@prisma/client/runtime/library.js:121:6745)
    at async Array.$allOperations (/Users/cbroome/Workspace/docker-scratchpad/apps/keystone/node_modules/@keystone-6/core/dist/createSystem-a67f94f3.cjs.dev.js:4515:18)
    at async l (/Users/cbroome/Workspace/docker-scratchpad/apps/keystone/node_modules/@prisma/client/runtime/library.js:130:9633)
    at async count (/Users/cbroome/Workspace/docker-scratchpad/apps/keystone/node_modules/@keystone-6/core/dist/createSystem-a67f94f3.cjs.dev.js:1659:17)
    at async Promise.all (index 0)
    at async Object.count (/Users/cbroome/Workspace/docker-scratchpad/apps/keystone/node_modules/@keystone-6/core/dist/createSystem-a67f94f3.cjs.dev.js:962:20)
    at async hasInitFirstItemConditions (/Users/cbroome/Workspace/docker-scratchpad/apps/keystone/node_modules/@keystone-6/auth/dist/keystone-6-auth.cjs.dev.js:929:19)
    at async isAccessAllowed (/Users/cbroome/Workspace/docker-scratchpad/apps/keystone/node_modules/@keystone-6/auth/dist/keystone-6-auth.cjs.dev.js:1004:15) {
  code: 'P2021',
  clientVersion: '5.19.0',
  meta: { modelName: 'User', table: 'main.User' }
}
```

- Node: v20.11.0
- Keystone: 
```
    "@keystone-6/auth": "^8.0.0",
    "@keystone-6/core": "^6.0.0",
    "@keystone-6/fields-document": "^9.0.0",
```

**Comment by dcousens** [comment]
@cbroome did you resolve this?
