### ISSUE TITLE
S3 file upload bug when same file name re-uploaded

### ISSUE THREAD

**Issue by gautamsi** [keystonejs/keystone#9419]
* configure file upload with S3
* set preserve  flag to false (default)
* set `transformName` to `(filename) => filename.replace(/[^a-zA-Z0-9.]/g, '-')`  - essentially just return original file name
* upload file twice
* notice the file is actually deleted on s3

File should be replaced and not deleted

### Workaround
set `preserver` to true so that file is kept, but that could be unintended consequences.

**Comment by gautamsi** [comment]
possible improvement should be to add config which throws error on same file being uploaded again, silently upload if the flag is false (default)

**Comment by dcousens** [comment]
alternatively, the delete could happen before the upload

**Comment by dcousens** [comment]
> possible improvement should be to add config which throws error on same file being uploaded again, silently upload if the flag is false (default)

that could probably be a validate hook, and left to developers

**Comment by gautamsi** [comment]
if you delete before and the update failed then you are left with nothing :)

I would run delete if the file name was not same

**Comment by dcousens** [comment]
this would introduce a HEAD request for every upload, but I don't think we have any other option

**Comment by gautamsi** [comment]
We can check file name locally from existing record before deleting.

**Comment by willypuzzle** [comment]
Hello, I wish to work in this issue. What's the procedure? Can you assign this task to me?

Thanks!

**Comment by dcousens** [comment]
@willypuzzle pull requests accepted 💛💙 - other than that, if the pull request resolves the problem in a way that reaches consensus, I'll do everything I can to help the pull request land

**Comment by willypuzzle** [comment]
@dcousens according to [this](https://github.com/keystonejs/keystone/blob/main/packages/core/src/types/config/index.ts#L59-L95) `transformName` was removed from s3 config type storage. In fact it doesn't work anymore in my local machine. How can I workaround?

**Comment by dcousens** [comment]
@willypuzzle keep following the type, see `& FileOrName` https://github.com/keystonejs/keystone/blob/main/packages/core/src/types/config/index.ts#L26

**Comment by willypuzzle** [comment]
> [@willypuzzle](https://github.com/willypuzzle) keep following the type, see `& FileOrImage` on the type you referenced.
> 
> https://github.com/keystonejs/keystone/blob/main/packages/core/src/types/config/index.ts#L26

@dcousens yes, you're right. My fault. I reproduced the bug. I'm going to work on it.

**Comment by willypuzzle** [comment]
Hello @dcousens  I tried to run this test on the unmodified codebase of the branch main:

DATABASE_URL=file:./keystone-example.db S3_BUCKET_NAME=keystone-app S3_REGION=eu-west-2 S3_ACCESS_KEY_ID=<omitted> S3_SECRET_ACCESS_KEY=<omitted> jest files

But on S3 tests fail with this output:

 

> The following files share their name; please adjust your hasteImpl:
>     * <rootDir>/examples/graphql-gql.tada/package.json
>     * <rootDir>/examples/graphql-ts-gql/package.json
> 
>  FAIL  tests/api-tests/fields/files.test.ts
>   File - Crud special tests
>     local                                                                                                                                                                           
>       Create - upload                                                                                                                                                               
>         ✓ Upload values should match expected corrected (430 ms)                                                                                                                    
>       After Operation Hook                                                                                                                                                          
>         ✓ with preserve: true (91 ms)                                                                                                                                               
>         ✓ with preserve: false (110 ms)                                                                                                                                             
>     s3                                                                                                                                                                              
>       Create - upload                                                                                                                                                               
>         ✕ Upload values should match expected corrected (423 ms)                                                                                                                    
>       After Operation Hook                                                                                                                                                          
>         ✕ with preserve: true (306 ms)                                                                                                                                              
>         ✕ with preserve: false (326 ms)                                                                                                                                             
>                                                                                                                                                                                     
>   ● File - Crud special tests › s3 › Create - upload › Upload values should match expected corrected                                                                                
> 
>     TypeError: Failed to parse URL from keystone-OaDkHGp4IGqkqXY27Rh5nQ.jpeg
> 
> 
> 
>     Cause:
>     TypeError: Invalid URL
> 
>       92 | describe('File - Crud special tests', () => {
>       93 |   const filename = 'keystone.jpeg'
>     > 94 |   const fileHash = createHash('sha1')
>          |                       ^
>       95 |     .update(fs.readFileSync(path.resolve(fieldPath, 'image/test-files', filename)))
>       96 |     .digest('hex')
>       97 |
> 
>       at getFileHash (tests/api-tests/fields/files.test.ts:94:23)
>       at tests/api-tests/fields/files.test.ts:148:44
>       at Object.<anonymous> (tests/api-tests/test-runner.ts:206:14)
> 
>   ● File - Crud special tests › s3 › After Operation Hook › with preserve: true
> 
>     TypeError: Failed to parse URL from keystone-pXuaRVS76HN83aG3WfOMVQ.jpeg
> 
> 
> 
>     Cause:
>     TypeError: Invalid URL
> 
>        97 |
>        98 |   const createItem = (context: any) =>
>     >  99 |     context.query.Test.createOne({
>           |                                                 ^
>       100 |       data: { secretFile: prepareFile(filename, 'image') },
>       101 |       query: `
>       102 |         id
> 
>       at checkFile (tests/api-tests/fields/files.test.ts:99:49)
>       at tests/api-tests/fields/files.test.ts:163:28
>       at Object.<anonymous> (tests/api-tests/test-runner.ts:206:14)
> 
>   ● File - Crud special tests › s3 › After Operation Hook › with preserve: false
> 
>     TypeError: Failed to parse URL from keystone-83VFQbUdb-rtCBWc9l_9jA.jpeg
> 
> 
> 
>     Cause:
>     TypeError: Invalid URL
> 
>        97 |
>        98 |   const createItem = (context: any) =>
>     >  99 |     context.query.Test.createOne({
>           |                                                 ^
>       100 |       data: { secretFile: prepareFile(filename, 'image') },
>       101 |       query: `
>       102 |         id
> 
>       at checkFile (tests/api-tests/fields/files.test.ts:99:49)
>       at tests/api-tests/fields/files.test.ts:188:26
>       at Object.<anonymous> (tests/api-tests/test-runner.ts:206:14)
> 
> Test Suites: 1 failed, 1 total                                                                                                                                                      
> Tests:       3 failed, 3 passed, 6 total                                                                                                                                            
> Snapshots:   0 total
> Time:        4.98 s
> Ran all test suites matching /files/i.
> 

What am I doing wrong?

Thanks!
